
# Longitudinal Technical Analysis of the CI Pipeline — V1 (MVP)–V4

Este notebook consolida os relatórios técnicos do pipeline das versões V1, V2, V3 e V4 do sistema analisado.
- **V1** - Módulos Contracheque (Empregados) e Cédula C
- **V2** - Módulo SIRH (Cadastro, Pós-Graduação)
- **V3** - Módulos SIRH (Ficha Financeira) e Contracheque (Pensionistas)
- **V4** - Módulo SIRH (Acadêmico)

As versões **V1**, **V2**, e **V3** estão em produção e **V4** encontra-se em fase de homologação.

O objetivo é preservar a **rastreabilidade temporal das evidências**, distinguindo:

1. **configuração** — capacidade declarada em artefato versionado;
2. **orquestração no pipeline** — capacidade explicitamente invocada pelo GitLab CI;
3. **execução efetiva** — capacidade comprovada por histórico de jobs, logs, branches ou Merge Requests.

> **Importante:** a ausência de evidência de execução não deve ser interpretada automaticamente como ausência da prática. Quando necessário, a situação é representada por `?`.


## 1. Scope

Versões analisadas:

- **V1** — `web-1.25.10-1`
- **V2** — `web-1.26.4-1`
- **V3** — `web-1.26.6-1`
- **V4** — `web-1.26.8-beta.1`

Artefatos principais considerados:
- `.gitlab-ci.yml`;
- `Boilerplate4Dev.csproj`;
- `renovate.json`;
- `RENOVATE_SETUP.md`;
- `Dockerfile`;
- `Dockerfile.postgres`;
- `docker-compose.yaml`;
- `Program.cs`;
- `appsettings.json`;
- `.editorconfig`;
- `.env.example`;
- `.env.io.example`;
- `init.sql`;
- `seed.sql`;
- `start-db.ps1`.

A análise apresentada neste notebook corresponde ao recorte técnico já consolidado nos relatórios individuais e longitudinal.

## 2. Analysis Criteria

A análise foi conduzida a partir dos artefatos técnicos versionados associados às entregas V1, V2, V3 e V4, considerando tanto a presença das práticas quanto o nível de evidência disponível para sustentá-las. Para preservar a rastreabilidade entre os artefatos observados e as conclusões apresentadas, foram estabelecidos critérios para a classificação das evidências e para a avaliação da maturidade das práticas de automação do pipeline.

###2.1 Evidence Classification

As evidências foram analisadas considerando três níveis distintos:

Configuração: a capacidade está declarada em um artefato técnico versionado, indicando que foi configurada no projeto;

Orquestração no pipeline: a capacidade é explicitamente invocada ou incorporada à definição do pipeline de CI;

Execução efetiva: além da configuração ou orquestração, existem evidências de runtime que comprovam sua execução, como histórico de jobs, logs, branches ou Merge Requests gerados pela ferramenta.

Essa distinção evita inferir a execução de uma prática exclusivamente a partir da existência de sua configuração. Dessa forma, quando os artefatos analisados demonstram a configuração de uma capacidade, mas não fornecem evidências suficientes de sua execução efetiva, essa condição é explicitamente indicada na análise. Essa abordagem é particularmente relevante para a análise do Renovate, cuja configuração e orquestração podem ser verificadas nos artefatos versionados, enquanto sua execução efetiva depende de evidências adicionais do ambiente de CI.

Para representação das evidências nas matrizes, são utilizados os seguintes símbolos:

- **✓** para capacidade evidenciada ou configurada no artefato analisado;
- **—** para capacidade ausente ou não evidenciada no artefato analisado;
- **?** quando a confirmação depende de evidência adicional de execução.

A ausência de evidência de execução não é interpretada automaticamente como ausência da prática, preservando a distinção entre o que pode ser diretamente observado nos artefatos e aquilo que depende de evidências complementares.

###2.2 Pipeline Maturity Classification

Além da classificação das evidências individuais, foi adotada uma escala ordinal de quatro níveis para sintetizar o estágio de maturidade das práticas de automação do pipeline no recorte analisado.

Nível	Classificação	Critério:

1	`Ausente/Tradicional`	Práticas inexistentes ou totalmente manuais.

Ausência de pipeline versionado ou pipeline sem etapas relevantes de automação; build, testes, análise de qualidade e entrega predominantemente manuais.

2	`Inicial/Ad hoc`	Adoção pontual e não sistematizada.

Pipeline existente, mas com automações pontuais, por exemplo apenas build, análise estática ou alguma tarefa isolada; baixa integração entre etapas.

3	`Parcial/Emergente`	Práticas estruturadas, porém incompletas.

Pipeline versionado com práticas estruturadas de CI, como restore, build, análise de qualidade, gerenciamento automatizado de dependências ou outras etapas recorrentes, mas ainda com lacunas relevantes, como ausência de testes automatizados, deploy, promoção ou rollback.

4	`Avançado/Consolidado`	Práticas institucionalizadas e integradas.

Pipeline integrado cobrindo build, testes automatizados, controles de qualidade efetivamente bloqueantes e mecanismos estruturados de entrega/implantação, promoção e recuperação. A simples presença dos arquivos não basta: são necessárias também evidências de execução e continuidade dessas práticas.

A classificação é realizada a partir do conjunto das evidências observadas nas versões analisadas, considerando a existência e a continuidade das práticas de Integração Contínua, automação de build, análise de qualidade, gerenciamento de dependências, testes automatizados e mecanismos relacionados à entrega e implantação do software.

A escala é aplicada especificamente às práticas de automação do pipeline observadas no recorte temporal analisado. Portanto, o nível resultante não deve ser interpretado isoladamente como uma classificação da maturidade DevOps global do projeto ou da organização. Uma avaliação global exigiria a aplicação de critérios equivalentes às demais dimensões envolvidas na adoção de DevOps.

A classificação final do pipeline é apresentada somente após a análise individual das versões e a análise longitudinal, permitindo que o nível atribuído seja derivado das evidências técnicas apresentadas ao longo do relatório, e não estabelecido previamente como resultado da avaliação.

3. AI-Assisted Interpretation

A Inteligência Artificial é utilizada neste notebook como mecanismo de apoio à interpretação das evidências técnicas extraídas dos artefatos analisados.

A IA não realiza a identificação primária das práticas nem substitui os critérios objetivos definidos para a classificação da maturidade do pipeline. As evidências são previamente extraídas de forma automatizada a partir dos arquivos fornecidos, estruturadas e avaliadas segundo uma rubrica previamente estabelecida.

A partir dessas informações, a IA é utilizada para:

- interpretar o conjunto de evidências identificadas;
- verificar se as evidências sustentam a classificação obtida pelos critérios definidos;
- elaborar uma justificativa técnica e acadêmica para a classificação;
- identificar lacunas e limitações da análise;
- distinguir evidências de configuração, orquestração e execução efetiva;
- evitar inferências sobre práticas que não estejam diretamente sustentadas pelos artefatos analisados.

A interpretação assistida por IA deve ser conservadora e rastreável. A ausência de evidência não deve ser automaticamente interpretada como inexistência da prática, especialmente quando o artefato necessário para sua verificação não estiver disponível.

Assim, o fluxo analítico adotado neste notebook segue a sequência:

** `1`artefatos técnicos → `2`identificação e validação dos arquivos → `3`extração objetiva de evidências → `4`classificação determinística por critérios → `5`estruturação das evidências → `6`interpretação assistida por IA → `7`armazenamento dos resultados por versão → `8`consolidação das evidências → `9`análise longitudinal**

A classificação básica permanece reproduzível independentemente da IA, enquanto o modelo é utilizado como apoio à análise qualitativa e à elaboração da interpretação dos resultados.

In [1]:
# OpenAI API Setup
!pip install -q --upgrade openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.4 MB/s eta 0:00:00

In [2]:
# OpenAI API Client Configuration
from google.colab import userdata
from openai import OpenAI

try:
    api_key = userdata.get("OPENAI_API_KEY")
except Exception:
    api_key = None

if not api_key:
    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada nos Secrets do Colab."
    )

client = OpenAI(api_key=api_key)

print("✓ Cliente de IA configurado com segurança.")

✓ Cliente de IA configurado com segurança.

In [3]:
# Bibliotecas
import re
import json
import os
import glob
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import pandas as pd
import yaml

In [4]:
# Common Utility Functions
def contem(texto, *padroes):
    if texto is None:
        return False

    texto = str(texto).lower()

    return any(
        str(padrao).lower() in texto
        for padrao in padroes
    )


def buscar_regex(texto, padrao):
    if texto is None:
        return None

    return re.search(
        padrao,
        str(texto),
        flags=re.IGNORECASE | re.MULTILINE
    )

In [65]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None


print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [66]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar "
            "o arquivo .csproj:"
        )

        print(
            erro
        )


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = (
            match_sdk.group(1)
        )


    # Pipeline versionado
    evidencias[
        "GitLab CI como código"
    ] = True


    # Restore
    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias[
        "Espera pelo Quality Gate"
    ] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias[
        "Quality Gate bloqueante"
    ] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if dockerfile_postgres:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo
        in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome
        in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# appsettings
if appsettings:

    fontes_banco.append(
        appsettings
    )


# Program.cs
if program_cs:

    fontes_banco.append(
        program_cs
    )


# .csproj
if csproj:

    fontes_banco.append(
        csproj
    )


# Docker Compose
if docker_compose:

    fontes_banco.append(
        docker_compose
    )


# Dockerfile.postgres
if dockerfile_postgres:

    fontes_banco.append(
        dockerfile_postgres
    )


# Dockerfile da aplicação
if dockerfile:

    fontes_banco.append(
        dockerfile
    )


# Scripts
if conteudo_total_scripts:

    fontes_banco.append(
        conteudo_total_scripts
    )


# ---------------------------------------------------------
# 13.1 Consolidação das fontes de banco
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for conteudo
        in fontes_banco
    )


    # -----------------------------------------------------
    # Identificação do PostgreSQL
    # -----------------------------------------------------

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem(
        conteudo_banco,
        "postgresql",
        "postgres",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    conteudo_dotnet_banco = "\n".join(
        [
            program_cs or "",
            csproj or ""
        ]
    )

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = contem(
        conteudo_dotnet_banco,
        "npgsql",
        "usenpgsql",
        "addnpgsql"
    )


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if (
        evidencias[
            "PostgreSQL evidenciado"
        ] is True
    ):

        tecnologia_banco = (
            "PostgreSQL"
        )

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Exemplos reconhecidos:
    #
    # FROM postgres:16
    # FROM postgres:16.4
    # FROM postgres:16-alpine
    # image: postgres:16
    # image: postgres:16.4-alpine
    #
    # A versão encontrada representa a versão configurada
    # no artefato analisado e não comprova a versão
    # efetivamente executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.2 Prioridade 1 — Dockerfile.postgres
    # -----------------------------------------------------

    if dockerfile_postgres:

        match_postgres_dockerfile_postgres = (
            buscar_regex(
                dockerfile_postgres,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile_postgres:

            versao_banco = (
                match_postgres_dockerfile_postgres.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile.postgres"
            )


    # -----------------------------------------------------
    # 13.3 Prioridade 2 — Docker Compose
    # -----------------------------------------------------

    if (
        versao_banco is None
        and docker_compose
    ):

        match_postgres_compose = (
            buscar_regex(
                docker_compose,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_compose:

            versao_banco = (
                match_postgres_compose.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.4 Prioridade 3 — Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and dockerfile
    ):

        match_postgres_dockerfile = (
            buscar_regex(
                dockerfile,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile:

            versao_banco = (
                match_postgres_dockerfile.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile"
            )


    # -----------------------------------------------------
    # 13.5 Prioridade 4 — Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        match_postgres_script = (
            buscar_regex(
                conteudo_total_scripts,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_script:

            versao_banco = (
                match_postgres_script.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia_banco,

    "database_version":
        versao_banco,

    "database_version_source":
        fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None
Banco de dados: None
Versão configurada do banco: None
Fonte da versão do banco: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Dockerfile PostgreSQL presente
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local
? PostgreSQL evidenciado
? Provider PostgreSQL (.NET)
? Versão PostgreSQL identificada

## 3. V1 (MVP) — Pipeline Technical Analysis

### 3.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.25.10-1`**.

### 3.2 Análise dos Artefatos

In [67]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (4)
Saving .env.example to .env (4).example
Saving .env.io.example to .env.io (3).example
Saving appsettings.json to appsettings (4).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (4).csproj
Saving docker-compose.yaml to docker-compose (4).yaml
Saving Dockerfile to Dockerfile (4)
Saving Dockerfile.postgres to Dockerfile (4).postgres
Saving gitlab-ci.yml to gitlab-ci (4).yml
Saving init.sql to init (4).sql
Saving Program.cs to Program (4).cs
Saving start-db.ps1 to start-db (4).ps1

✓ 12 arquivo(s) carregado(s):

  ✓ .editorconfig (4)
  ✓ .env (4).example
  ✓ .env.io (3).example
  ✓ Boilerplate4Dev (4).csproj
  ✓ Dockerfile (4)
  ✓ Dockerfile (4).postgres
  ✓ Program (4).cs
  ✓ appsettings (4).json
  ✓ docker-compose (4).yaml
  ✓ gitlab-ci (4).yml
  ✓ init (4).sql
  ✓ start-db (4).ps1

In [68]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:

    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None

dockerfile_valido = None
dockerfile_postgres_valido = None
docker_compose_valido = None

program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):

    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):

    nome = nome_base(
        nome
    )

    # Remove sufixos adicionados pelo Colab:
    #
    # arquivo (1).json      -> arquivo.json
    # Dockerfile (2)        -> Dockerfile
    # Dockerfile (1).postgres -> Dockerfile.postgres
    #
    # O primeiro padrão trata o sufixo antes da extensão.
    # O segundo trata o sufixo no final do nome.

    nome = re.sub(
        r"\s*\(\d+\)(?=\.)",
        "",
        nome
    )

    nome = re.sub(
        r"\s*\(\d+\)$",
        "",
        nome
    )

    return (
        nome
        .lower()
        .strip()
    )


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):

    if not candidatos:

        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _
                in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(
    conteudo
):

    if conteudo is None:

        return None

    if isinstance(
        conteudo,
        bytes
    ):

        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []

candidatos_dockerfile = []
candidatos_dockerfile_postgres = []
candidatos_docker_compose = []

candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []


extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # -----------------------------------------------------
    # GitLab CI
    # -----------------------------------------------------

    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Projeto .NET
    # -----------------------------------------------------

    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Renovate
    # -----------------------------------------------------

    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile.postgres
    #
    # Deve ser identificado ANTES do Dockerfile genérico.
    # -----------------------------------------------------

    if normalizado == "dockerfile.postgres":

        candidatos_dockerfile_postgres.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile da aplicação
    # -----------------------------------------------------

    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Docker Compose
    # -----------------------------------------------------

    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Program.cs
    # -----------------------------------------------------

    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # appsettings.json
    # -----------------------------------------------------

    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .editorconfig
    # -----------------------------------------------------

    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.io.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Scripts
    # -----------------------------------------------------

    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile da aplicação"
)

dockerfile_postgres, dockerfile_postgres_nome = (
    selecionar_unico(
        candidatos_dockerfile_postgres,
        "Dockerfile.postgres"
    )
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

dockerfile_postgres = como_texto(
    dockerfile_postgres
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):

    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):

            continue

        if "=" not in linha:

            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # Continua utilizável para extração textual.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


def validar_dockerfile(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    possui_from = bool(
        re.search(
            r"^\s*FROM\s+\S+",
            conteudo,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    if possui_from:

        validacao_artefatos.append(
            f"✓ {descricao} estruturalmente válido "
            "(instrução FROM identificada)."
        )

        return True

    validacao_artefatos.append(
        f"✗ {descricao} sem instrução FROM identificada."
    )

    return False


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

dockerfile_valido = validar_dockerfile(
    dockerfile,
    "Dockerfile"
)


# ---------------------------------------------------------
# 6. Dockerfile.postgres
# ---------------------------------------------------------

dockerfile_postgres_valido = validar_dockerfile(
    dockerfile_postgres,
    "Dockerfile.postgres"
)


# ---------------------------------------------------------
# 7. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 8. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador
            in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 9. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 10. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 11. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# 13. Artefatos habilitados para análise
#
# Somente artefatos explicitamente validados podem ser
# utilizados pela etapa de extração determinística.
# ---------------------------------------------------------

artefatos_analisaveis = {

    "pipeline":
        pipeline_valido is True,

    "csproj":
        csproj_valido is True,

    "renovate_json":
        renovate_json_valido is True,

    "renovate_setup":
        renovate_setup_valido is True,

    "dockerfile":
        dockerfile_valido is True,

    "dockerfile_postgres":
        dockerfile_postgres_valido is True,

    "docker_compose":
        docker_compose_valido is True,

    "program_cs":
        program_cs_valido is True,

    "appsettings":
        appsettings_valido is True,

    "editorconfig":
        editorconfig_valido is True,

    "env_example":
        env_example_valido is True,

    "env_io_example":
        env_io_example_valido is True
}


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

artefatos_analisaveis[
    "scripts"
] = any(
    estado is True
    for estado
    in scripts_validos.values()
)


# ---------------------------------------------------------
# Mantém apenas scripts validados para a etapa de análise
# ---------------------------------------------------------

scripts_analisaveis = {

    nome:
        conteudo

    for nome, conteudo
    in scripts.items()

    if scripts_validos.get(
        nome
    ) is True
}


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):

    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Dockerfile.postgres",
    dockerfile_postgres_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):

        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {

    "Pipeline":
        pipeline_valido,

    ".csproj":
        csproj_valido,

    "renovate.json":
        renovate_json_valido,

    "RENOVATE_SETUP.md":
        renovate_setup_valido,

    "Dockerfile":
        dockerfile_valido,

    "Dockerfile.postgres":
        dockerfile_postgres_valido,

    "Docker Compose":
        docker_compose_valido,

    "Program.cs":
        program_cs_valido,

    "appsettings.json":
        appsettings_valido,

    ".editorconfig":
        editorconfig_valido,

    ".env.example":
        env_example_valido,

    ".env.io.example":
        env_io_example_valido
}


for artefato, estado in (
    estados_validacao.items()
):

    if estado is True:

        simbolo = "✓"

    elif estado is False:

        simbolo = "✗"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

if scripts_validos:

    print(
        "\nESTADO DOS SCRIPTS\n"
    )

    for nome in sorted(
        scripts_validos
    ):

        estado = scripts_validos[
            nome
        ]

        simbolo = (
            "✓"
            if estado is True
            else "✗"
        )

        print(
            f"{simbolo} {nome}"
        )


# ---------------------------------------------------------
# Artefatos disponíveis para extração
# ---------------------------------------------------------

print(
    "\nARTEFATOS HABILITADOS PARA EXTRAÇÃO\n"
)

for artefato, habilitado in (
    artefatos_analisaveis.items()
):

    simbolo = (
        "✓"
        if habilitado
        else "—"
    )

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (4).yml
✓ .csproj: Boilerplate4Dev (4).csproj
? renovate.json: não fornecido
? RENOVATE_SETUP.md: não fornecido
✓ Dockerfile: Dockerfile (4)
✓ Dockerfile.postgres: Dockerfile (4).postgres
✓ Docker Compose: docker-compose (4).yaml
✓ Program.cs: Program (4).cs
✓ appsettings.json: appsettings (4).json
✓ .editorconfig: .editorconfig (4)
✓ .env.example: .env (4).example
✓ .env.io.example: .env.io (3).example
✓ Scripts: 2 arquivo(s)
    - init (4).sql
    - start-db (4).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Dockerfile.postgres estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (4).sql: script SQL legível e não vazio.
✓ start-db (4).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
? renovate.json
? RENOVATE_SETUP.md
✓ Dockerfile
✓ Dockerfile.postgres
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

ESTADO DOS SCRIPTS

✓ init (4).sql
✓ start-db (4).ps1

ARTEFATOS HABILITADOS PARA EXTRAÇÃO

✓ pipeline
✓ csproj
— renovate_json
— renovate_setup
✓ dockerfile
✓ dockerfile_postgres
✓ docker_compose
✓ program_cs
✓ appsettings
✓ editorconfig
✓ env_example
✓ env_io_example
✓ scripts

In [69]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# Funções auxiliares específicas desta etapa
# ---------------------------------------------------------

def analisavel(nome_artefato):
    """
    Retorna True somente quando o artefato foi previamente
    identificado e validado pela etapa anterior.
    """
    return (
        isinstance(artefatos_analisaveis, dict)
        and artefatos_analisaveis.get(nome_artefato) is True
    )


def texto_lower(conteudo):
    if conteudo is None:
        return ""
    return str(conteudo).lower()


def contem_todos(conteudo, *termos):
    """
    Retorna True somente se TODOS os termos forem encontrados.
    Útil quando a simples presença de qualquer termo poderia
    produzir falso positivo.
    """
    texto = texto_lower(conteudo)

    return all(
        str(termo).lower() in texto
        for termo in termos
    )


def contem_algum(conteudo, *termos):
    """
    Retorna True se pelo menos um dos termos for encontrado.
    """
    texto = texto_lower(conteudo)

    return any(
        str(termo).lower() in texto
        for termo in termos
    )


def texto_job_gitlab(job):
    """
    Converte o conteúdo relevante de um job GitLab CI em texto
    para permitir análise determinística do próprio job.
    """

    if not isinstance(job, dict):
        return ""

    partes = []

    for chave in (
        "image",
        "stage",
        "before_script",
        "script",
        "after_script",
        "rules",
        "only",
        "except"
    ):

        valor = job.get(chave)

        if valor is None:
            continue

        if isinstance(valor, list):

            partes.extend(
                str(item)
                for item in valor
            )

        elif isinstance(valor, dict):

            partes.append(
                json.dumps(
                    valor,
                    ensure_ascii=False
                )
            )

        else:

            partes.append(
                str(valor)
            )

    return "\n".join(partes)


def localizar_jobs_sonar(pipeline_obj):
    """
    Localiza jobs que apresentam evidência de execução do SonarQube.
    """

    if not isinstance(pipeline_obj, dict):
        return []

    chaves_reservadas = {
        "image",
        "services",
        "variables",
        "stages",
        "workflow",
        "default",
        "include",
        "cache",
        "before_script",
        "after_script"
    }

    jobs = []

    for nome_job, configuracao in pipeline_obj.items():

        if nome_job in chaves_reservadas:
            continue

        if not isinstance(configuracao, dict):
            continue

        texto_job = texto_job_gitlab(
            configuracao
        )

        if contem_algum(
            texto_job,
            "dotnet-sonarscanner",
            "sonarscanner",
            "sonar.host.url",
            "sonar_token",
            "sonar.qualitygate.wait"
        ):

            jobs.append(
                (
                    nome_job,
                    configuracao,
                    texto_job
                )
            )

    return jobs


def extrair_variavel_env(
    conteudo,
    nomes_variaveis
):
    """
    Procura uma variável em arquivo .env no formato CHAVE=VALOR.
    """

    if not conteudo:
        return None, None

    nomes_normalizados = {
        nome.upper()
        for nome in nomes_variaveis
    }

    for linha in conteudo.splitlines():

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
            or "=" not in linha
        ):
            continue

        chave, valor = linha.split(
            "=",
            1
        )

        chave = chave.strip().upper()

        valor = valor.strip().strip(
            "\"'"
        )

        if chave in nomes_normalizados:

            return chave, valor

    return None, None


def extrair_versao_postgres_imagem(
    conteudo
):
    """
    Extrai versão de referências como:

    postgres:16
    postgres:16.4
    postgres:16-alpine
    postgresql:16
    """

    if not conteudo:
        return None

    match = re.search(
        r"\bpostgres(?:ql)?\s*:\s*"
        r"([0-9]+(?:\.[0-9]+){0,2})"
        r"(?:[-._a-zA-Z0-9]*)?",
        str(conteudo),
        flags=re.IGNORECASE
    )

    if match:
        return match.group(1)

    return None


def extrair_versao_postgres_env(
    conteudo
):
    """
    Procura versão PostgreSQL em variáveis de ambiente.
    """

    if not conteudo:
        return None, None

    # Variáveis explicitamente destinadas à versão
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_VERSION",
            "POSTGRESQL_VERSION",
            "PG_VERSION"
        }
    )

    if valor:

        match = re.search(
            r"([0-9]+(?:\.[0-9]+){0,2})",
            valor
        )

        if match:

            return (
                match.group(1),
                chave
            )

    # Variáveis que podem armazenar a imagem completa
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_IMAGE",
            "POSTGRESQL_IMAGE",
            "DATABASE_IMAGE",
            "DB_IMAGE"
        }
    )

    if valor:

        versao = extrair_versao_postgres_imagem(
            valor
        )

        if versao:

            return (
                versao,
                chave
            )

    return None, None


def extrair_versao_postgres_dockerfile(
    conteudo
):
    """
    Extrai a versão configurada do PostgreSQL em Dockerfiles.

    Reconhece, por exemplo:

    FROM postgres:16
    FROM postgres:16.4-alpine

    ARG POSTGRES_VERSION=16
    ENV POSTGRES_VERSION=16
    FROM postgres:${POSTGRES_VERSION}

    A versão identificada é configuracional e não comprova
    a versão efetivamente executada em produção.
    """

    if not conteudo:

        return None, None

    # -----------------------------------------------------
    # 1. Referência literal da imagem
    # -----------------------------------------------------

    versao_literal = extrair_versao_postgres_imagem(
        conteudo
    )

    if versao_literal:

        return (
            versao_literal,
            "imagem PostgreSQL literal"
        )


    # -----------------------------------------------------
    # 2. ARG/ENV com variável de versão
    # -----------------------------------------------------

    nomes_variaveis = (
        "POSTGRES_VERSION",
        "POSTGRESQL_VERSION",
        "PG_VERSION"
    )

    for nome_variavel in nomes_variaveis:

        padrao_variavel = (
            rf"^\s*(?:ARG|ENV)\s+"
            rf"{re.escape(nome_variavel)}"
            rf"\s*(?:=|\s)\s*"
            rf"[\"']?"
            rf"([0-9]+(?:\.[0-9]+){{0,2}})"
        )

        match_variavel = re.search(
            padrao_variavel,
            str(conteudo),
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )

        if not match_variavel:

            continue

        # Exige também uma referência à imagem PostgreSQL,
        # evitando interpretar uma variável isolada como prova
        # de que o Dockerfile usa PostgreSQL.
        if contem_algum(
            conteudo,
            "from postgres:",
            "from postgresql:"
        ):

            return (
                match_variavel.group(1),
                nome_variavel
            )

    return None, None


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if analisavel("csproj"):

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        # Em princípio não deve ocorrer, pois o arquivo já foi
        # validado na etapa anterior.
        print(
            "⚠ Inconsistência: .csproj havia sido validado, "
            "mas não pôde ser interpretado nesta etapa."
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if analisavel("pipeline"):

    # -----------------------------------------------------
    # SDK .NET utilizado no pipeline
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem_algum(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem_algum(
        pipeline,
        "dotnet build"
    )

    possui_release = contem_algum(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem_algum(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    evidencias[
        "Espera pelo Quality Gate"
    ] = contem_algum(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    #
    # Avalia allow_failure no job do SonarQube, e não em
    # qualquer outro job do pipeline.
    # -----------------------------------------------------

    quality_gate_bloqueante = False

    try:

        pipeline_obj = yaml.safe_load(
            pipeline
        )

        jobs_sonar = localizar_jobs_sonar(
            pipeline_obj
        )

        jobs_qg = []

        for (
            nome_job,
            configuracao_job,
            texto_job
        ) in jobs_sonar:

            if contem_algum(
                texto_job,
                "sonar.qualitygate.wait=true"
            ):

                jobs_qg.append(
                    (
                        nome_job,
                        configuracao_job
                    )
                )

        if jobs_qg:

            # Considera bloqueante se existir job com espera de
            # Quality Gate e allow_failure diferente de True.
            quality_gate_bloqueante = any(
                configuracao.get(
                    "allow_failure"
                ) is not True
                for _, configuracao in jobs_qg
            )

        else:

            quality_gate_bloqueante = False

    except Exception:

        # Não utiliza inferência textual genérica como substituto,
        # pois isso poderia associar allow_failure ao job errado.
        quality_gate_bloqueante = False


    evidencias[
        "Quality Gate bloqueante"
    ] = (
        evidencias[
            "Espera pelo Quality Gate"
        ]
        and quality_gate_bloqueante
    )


    # -----------------------------------------------------
    # Cache
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem_algum(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem_algum(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Merge Request
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem_algum(
        pipeline,
        "merge_request_event"
    )


    # -----------------------------------------------------
    # Branch main
    # -----------------------------------------------------

    possui_variavel_branch = contem_algum(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # -----------------------------------------------------
    # Testes automatizados
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem_algum(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy automatizado
    #
    # Dockerfile / Docker Compose de configuração não são
    # considerados prova de deploy automatizado.
    # Aqui são procurados comandos dentro do pipeline.
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem_algum(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção automática
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem_algum(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback automatizado
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem_algum(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if analisavel("renovate_json"):

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # -------------------------------------------------
        # Vulnerability Alerts
        # -------------------------------------------------

        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem_algum(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # -------------------------------------------------
        # Lock File Maintenance
        # -------------------------------------------------

        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem_algum(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        # Em princípio não deverá ocorrer porque o arquivo
        # somente chega aqui se foi validado.
        evidencias[
            "Renovate configurado"
        ] = None

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = None

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = None

        evidencias[
            "Vulnerability Alerts"
        ] = None

        evidencias[
            "Lock File Maintenance"
        ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if analisavel("pipeline"):

    possui_imagem_renovate = contem_algum(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem_algum(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    if evidencias[
        "Job Renovate no pipeline"
    ]:

        evidencias[
            "Regra schedule para Renovate"
        ] = contem_algum(
            pipeline,
            "schedule"
        )

        evidencias[
            "Execução manual do Renovate"
        ] = contem_algum(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )

    else:

        evidencias[
            "Regra schedule para Renovate"
        ] = False

        evidencias[
            "Execução manual do Renovate"
        ] = False

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva.
# Logs, branch Renovate ou MR criado pelo bot seriam
# necessários para estabelecer execução efetiva.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if analisavel("dockerfile"):

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if analisavel("dockerfile_postgres"):

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if analisavel("docker_compose"):

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem_algum(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem_algum(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem_algum(
            docker_compose,
            "external:"
        )
        and contem_algum(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem_algum(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if analisavel("program_cs"):

    evidencias[
        "Sentry integrado em runtime"
    ] = contem_algum(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )


    # -----------------------------------------------------
    # Health Check de banco
    #
    # Exige simultaneamente:
    # - evidência de infraestrutura de Health Check
    # - evidência de integração PostgreSQL/Npgsql
    # -----------------------------------------------------

    possui_healthcheck = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks",
        "healthcheck"
    )

    possui_npgsql_healthcheck = contem_algum(
        program_cs,
        "addnpgsql",
        ".addnpgsql",
        "npgsql"
    )

    evidencias[
        "Health Check de banco"
    ] = (
        possui_healthcheck
        and possui_npgsql_healthcheck
    )


    # -----------------------------------------------------
    # Health Check de API
    # -----------------------------------------------------

    evidencias[
        "Health Check de API"
    ] = (
        contem_algum(
            program_cs,
            "addurlgroup",
            "httpclient"
        )
        and contem_algum(
            program_cs,
            "health"
        )
    )


    # -----------------------------------------------------
    # Logging
    # -----------------------------------------------------

    evidencias[
        "Console Logging"
    ] = contem_algum(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if analisavel("appsettings"):

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem_algum(
        appsettings,
        "sentry",
        "\"dsn\""
    )

    evidencias[
        "Matomo configurado"
    ] = contem_algum(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem_algum(
        appsettings,
        "connectionstrings",
        "environment",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if analisavel("editorconfig"):

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = (
        contem_algum(
            editorconfig,
            "dotnet_diagnostic"
        )
        and contem_algum(
            editorconfig,
            "severity"
        )
    )


    # Não utiliza mais o termo isolado "s",
    # que produzia falsos positivos.
    evidencias[
        "Regras de segurança declaradas"
    ] = contem_algum(
        editorconfig,
        "security",
        "securityrule",
        "securityhotspot",
        "ca2100",
        "ca2119",
        "ca2122",
        "ca2135",
        "ca2300",
        "ca2301",
        "ca2302",
        "ca2305",
        "ca2310",
        "ca2311",
        "ca2312",
        "ca2321",
        "ca2322",
        "ca2326",
        "ca2327",
        "ca2328",
        "ca2329",
        "ca2330",
        "ca3001",
        "ca3002",
        "ca3003",
        "ca3004",
        "ca3005",
        "ca3006",
        "ca3007",
        "ca3008",
        "ca3009",
        "ca3010",
        "ca3011",
        "ca3012",
        "ca3061",
        "ca3075",
        "ca3076",
        "ca3077"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if analisavel("env_example"):

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem_algum(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host",
        "version"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if analisavel("env_io_example"):

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem_algum(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project",
        "host"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if analisavel("scripts"):

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts_analisaveis.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts_analisaveis.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem_algum(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem_algum(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem_algum(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )


    # Atenção: automação de ambiente local não equivale
    # a deploy automatizado da aplicação.
    evidencias[
        "Automação de ambiente local"
    ] = contem_algum(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# ---------------------------------------------------------
# Somente artefatos previamente validados participam da
# identificação da tecnologia de banco.
# ---------------------------------------------------------

if analisavel("appsettings"):

    fontes_banco.append(
        (
            "appsettings.json",
            appsettings
        )
    )


if analisavel("program_cs"):

    fontes_banco.append(
        (
            "Program.cs",
            program_cs
        )
    )


if analisavel("csproj"):

    fontes_banco.append(
        (
            ".csproj",
            csproj
        )
    )


if analisavel("dockerfile_postgres"):

    fontes_banco.append(
        (
            "Dockerfile.postgres",
            dockerfile_postgres
        )
    )


if analisavel("docker_compose"):

    fontes_banco.append(
        (
            "Docker Compose",
            docker_compose
        )
    )


if analisavel("dockerfile"):

    fontes_banco.append(
        (
            "Dockerfile",
            dockerfile
        )
    )


if analisavel("env_example"):

    fontes_banco.append(
        (
            ".env.example",
            env_example
        )
    )


if analisavel("env_io_example"):

    fontes_banco.append(
        (
            ".env.io.example",
            env_io_example
        )
    )


if conteudo_total_scripts:

    fontes_banco.append(
        (
            "Scripts",
            conteudo_total_scripts
        )
    )


# ---------------------------------------------------------
# Identificação do PostgreSQL
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for _, conteudo in fontes_banco
    )

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem_algum(
        conteudo_banco,
        "postgresql",
        "postgres:",
        "postgres_",
        "postgres-",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    fontes_dotnet = []

    if analisavel("program_cs"):

        fontes_dotnet.append(
            program_cs
        )

    if analisavel("csproj"):

        fontes_dotnet.append(
            csproj
        )

    if fontes_dotnet:

        conteudo_dotnet_banco = "\n".join(
            fontes_dotnet
        )

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = contem_algum(
            conteudo_dotnet_banco,
            "npgsql",
            "usenpgsql",
            "addnpgsql"
        )

    else:

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = None


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if evidencias[
        "PostgreSQL evidenciado"
    ] is True:

        tecnologia_banco = "PostgreSQL"

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Ordem de prioridade:
    # 1. Dockerfile.postgres
    # 2. Docker Compose com versão literal
    # 3. .env.example
    # 4. .env.io.example
    # 5. Dockerfile da aplicação
    # 6. Scripts
    #
    # A prioridade do Dockerfile.postgres decorre de ele ser
    # um artefato especificamente destinado à configuração
    # da imagem PostgreSQL.
    #
    # A versão representa evidência configuracional.
    # Não comprova a versão executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.1 Dockerfile.postgres
    # -----------------------------------------------------

    if analisavel("dockerfile_postgres"):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile_postgres
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile.postgres "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile.postgres"
                )


    # -----------------------------------------------------
    # 13.2 Docker Compose — versão literal
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("docker_compose")
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                docker_compose
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.3 .env.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.4 .env.io.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_io_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_io_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.io.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.5 Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("dockerfile")
    ):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile"
                )


    # -----------------------------------------------------
    # 13.6 Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                conteudo_total_scripts
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline,
    "database_technology": tecnologia_banco,
    "database_version": versao_banco,
    "database_version_source": fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
#
# ✓ = evidência identificada
# — = artefato válido analisado, evidência não identificada
# ? = artefato ausente, inválido ou execução não verificável
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net9.0
SDK Pipeline: None
Banco de dados: PostgreSQL
Versão configurada do banco: 17
Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)

✓ GitLab CI como código
— `dotnet restore` no CI
— Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
— Cache NuGet
✓ Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Dockerfile PostgreSQL presente
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
✓ Health Check de banco
✓ Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ Parametrização de ambientes
✓ .env.io.example presente
✓ Scripts presentes
✓ Script de inicialização de banco
— Script de seed
— Dump de banco presente
✓ Automação de ambiente local
✓ PostgreSQL evidenciado
✓ Provider PostgreSQL (.NET)
✓ Versão PostgreSQL identificada

In [70]:
# ---------------------------------------------------------
# PIPELINE AUTOMATION MATURITY CLASSIFICATION
#
# Rubrica determinística específica deste estudo.
#
# A classificação representa a maturidade da automação
# observável no pipeline analisado e não uma avaliação
# abrangente da maturidade DevOps da organização.
#
# Nível 1:
#   Pipeline versionado
#
# Nível 2:
#   Automação básica de CI
#
# Nível 3:
#   CI estruturada com controle de qualidade
#
# Nível 4:
#   Automação de entrega ponta a ponta
#
# None:
#   Evidência insuficiente / pipeline não analisável
# ---------------------------------------------------------


def classificar_maturidade_pipeline(e):

    # -----------------------------------------------------
    # Ausência completa da estrutura de evidências
    # -----------------------------------------------------

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência técnica foi extraída."
            ),
            "lacunas": [],
            "indeterminacoes": [],
            "capacidades_adicionais": []
        }


    # -----------------------------------------------------
    # Evidências centrais do pipeline
    # -----------------------------------------------------

    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidências complementares do pipeline
    # -----------------------------------------------------

    cache_sonar = e.get(
        "Cache Sonar"
    )

    cache_nuget = e.get(
        "Cache NuGet"
    )

    regra_merge_request = e.get(
        "Regra para Merge Request"
    )

    regra_main = e.get(
        "Regra para branch main"
    )

    renovate_configurado = e.get(
        "Renovate configurado"
    )

    renovate_job = e.get(
        "Job Renovate no pipeline"
    )

    renovate_schedule = e.get(
        "Regra schedule para Renovate"
    )

    renovate_manual = e.get(
        "Execução manual do Renovate"
    )


    # -----------------------------------------------------
    # Evidências complementares de infraestrutura
    #
    # Servem apenas para caracterização técnica.
    # Não aumentam isoladamente o nível de maturidade
    # da automação do pipeline.
    # -----------------------------------------------------

    dockerfile_presente = e.get(
        "Dockerfile presente"
    )

    dockerfile_postgres_presente = e.get(
        "Dockerfile PostgreSQL presente"
    )

    docker_compose_presente = e.get(
        "Docker Compose presente"
    )

    postgres_evidenciado = e.get(
        "PostgreSQL evidenciado"
    )

    postgres_provider_dotnet = e.get(
        "Provider PostgreSQL (.NET)"
    )

    postgres_versao_identificada = e.get(
        "Versão PostgreSQL identificada"
    )


    # -----------------------------------------------------
    # Verificação de evidência suficiente
    #
    # Se todas as evidências centrais do pipeline forem None,
    # o artefato está ausente, inválido ou não analisável.
    #
    # Evidências de Docker/PostgreSQL NÃO substituem a
    # disponibilidade do pipeline para aplicação da rubrica.
    # -----------------------------------------------------

    evidencias_centrais = (
        gitlab_ci,
        restore,
        build,
        sonar,
        quality_gate_wait,
        quality_gate_blocking,
        testes,
        deploy,
        promocao,
        rollback
    )

    if all(
        valor is None
        for valor in evidencias_centrais
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível, não pôde ser "
                "validado ou não forneceu evidências suficientes "
                "para aplicação da rubrica."
            ),
            "lacunas": [],
            "indeterminacoes": [],
            "capacidades_adicionais": []
        }


    # -----------------------------------------------------
    # Capacidades fundamentais
    # -----------------------------------------------------

    pipeline_versionado = (
        gitlab_ci is True
    )

    possui_automacao_basica = (
        restore is True
        or build is True
        or sonar is True
        or quality_gate_wait is True
    )

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    controle_qualidade = (
        sonar is True
        or quality_gate_wait is True
    )

    entrega_ponta_a_ponta = (
        ci_estruturada
        and controle_qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    )


    # -----------------------------------------------------
    # Lacunas da automação de entrega
    #
    # Somente False é tratado como ausência evidenciada.
    # None representa evidência indeterminada e é registrado
    # separadamente.
    # -----------------------------------------------------

    lacunas = []
    indeterminacoes = []

    criterios_entrega = {
        "testes automatizados":
            testes,

        "Quality Gate bloqueante":
            quality_gate_blocking,

        "deploy automatizado":
            deploy,

        "promoção automática entre ambientes":
            promocao,

        "rollback automatizado":
            rollback
    }

    for descricao, valor in (
        criterios_entrega.items()
    ):

        if valor is False:

            lacunas.append(
                descricao
            )

        elif valor is None:

            indeterminacoes.append(
                descricao
            )


    # -----------------------------------------------------
    # Capacidades adicionais
    #
    # Essas capacidades enriquecem a caracterização da
    # versão, mas NÃO aumentam isoladamente o nível da
    # automação do pipeline.
    # -----------------------------------------------------

    capacidades_adicionais = []


    # -----------------------------------------------------
    # CI / qualidade
    # -----------------------------------------------------

    if cache_sonar is True:

        capacidades_adicionais.append(
            "cache do Sonar"
        )


    if cache_nuget is True:

        capacidades_adicionais.append(
            "cache de dependências NuGet"
        )


    if regra_merge_request is True:

        capacidades_adicionais.append(
            "execução associada a Merge Request"
        )


    if regra_main is True:

        capacidades_adicionais.append(
            "regra associada à branch main"
        )


    # -----------------------------------------------------
    # Renovate
    # -----------------------------------------------------

    if renovate_configurado is True:

        capacidades_adicionais.append(
            "Renovate configurado"
        )


    if renovate_job is True:

        capacidades_adicionais.append(
            "Renovate orquestrado no pipeline"
        )


    if renovate_schedule is True:

        capacidades_adicionais.append(
            "execução agendada do Renovate configurada"
        )


    if renovate_manual is True:

        capacidades_adicionais.append(
            "execução manual do Renovate configurada"
        )


    # -----------------------------------------------------
    # Containerização
    # -----------------------------------------------------

    if dockerfile_presente is True:

        capacidades_adicionais.append(
            "Dockerfile da aplicação presente"
        )


    if dockerfile_postgres_presente is True:

        capacidades_adicionais.append(
            "Dockerfile específico do PostgreSQL presente"
        )


    if docker_compose_presente is True:

        capacidades_adicionais.append(
            "Docker Compose presente"
        )


    # -----------------------------------------------------
    # Banco de dados
    #
    # Caracterização tecnológica, não critério de elevação
    # do nível da automação do pipeline.
    # -----------------------------------------------------

    if postgres_evidenciado is True:

        capacidades_adicionais.append(
            "PostgreSQL evidenciado nos artefatos"
        )


    if postgres_provider_dotnet is True:

        capacidades_adicionais.append(
            "provider PostgreSQL integrado ao .NET"
        )


    if postgres_versao_identificada is True:

        capacidades_adicionais.append(
            "versão configurada do PostgreSQL identificada"
        )


    # -----------------------------------------------------
    # Nível 4
    #
    # Automação de entrega ponta a ponta
    # -----------------------------------------------------

    if entrega_ponta_a_ponta:

        return {
            "nivel": 4,
            "classificacao": (
                "Automação de entrega ponta a ponta"
            ),
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada, controle de qualidade, testes "
                "automatizados, Quality Gate bloqueante, deploy, "
                "promoção entre ambientes e rollback automatizados."
            ),
            "lacunas": lacunas,
            "indeterminacoes": indeterminacoes,
            "capacidades_adicionais": capacidades_adicionais
        }


    # -----------------------------------------------------
    # Nível 3
    #
    # CI estruturada com controle de qualidade
    # -----------------------------------------------------

    if (
        ci_estruturada
        and controle_qualidade
    ):

        motivo = (
            "O pipeline apresenta integração contínua estruturada "
            "com restore, build e controle automatizado de qualidade."
        )

        if lacunas:

            motivo += (
                " A automação de entrega permanece incompleta, "
                "com ausência evidenciada de: "
                + ", ".join(lacunas)
                + "."
            )

        if indeterminacoes:

            motivo += (
                " Não foi possível determinar, a partir dos "
                "artefatos analisados, a presença de: "
                + ", ".join(indeterminacoes)
                + "."
            )

        return {
            "nivel": 3,
            "classificacao": (
                "CI estruturada com controle de qualidade"
            ),
            "motivo": motivo,
            "lacunas": lacunas,
            "indeterminacoes": indeterminacoes,
            "capacidades_adicionais": capacidades_adicionais
        }


    # -----------------------------------------------------
    # Nível 2
    #
    # Automação básica de CI
    # -----------------------------------------------------

    if (
        pipeline_versionado
        and possui_automacao_basica
    ):

        capacidades_basicas = []


        if restore is True:

            capacidades_basicas.append(
                "restore automatizado"
            )


        if build is True:

            capacidades_basicas.append(
                "build automatizado"
            )


        if sonar is True:

            capacidades_basicas.append(
                "análise SonarQube"
            )


        if quality_gate_wait is True:

            capacidades_basicas.append(
                "espera pelo Quality Gate"
            )


        if capacidades_basicas:

            descricao_capacidades = (
                ", ".join(
                    capacidades_basicas
                )
            )

            motivo = (
                "Existe pipeline versionado com automações básicas "
                f"de integração contínua: {descricao_capacidades}. "
                "Os critérios para CI estruturada completa ainda "
                "não foram integralmente atendidos."
            )

        else:

            motivo = (
                "Existe pipeline versionado com alguma automação "
                "de integração contínua, mas sem atendimento "
                "completo aos critérios de CI estruturada."
            )


        return {
            "nivel": 2,
            "classificacao": (
                "Inicial / Adhoc"
            ),
            "motivo": motivo,
            "lacunas": lacunas,
            "indeterminacoes": indeterminacoes,
            "capacidades_adicionais": capacidades_adicionais
        }


    # -----------------------------------------------------
    # Nível 1
    #
    # Pipeline versionado
    # -----------------------------------------------------

    if pipeline_versionado:

        return {
            "nivel": 1,
            "classificacao": (
                "Pipeline versionado"
            ),
            "motivo": (
                "Foi identificado pipeline GitLab CI versionado, "
                "mas não foram evidenciadas automações suficientes "
                "para classificá-lo nos níveis superiores da rubrica."
            ),
            "lacunas": lacunas,
            "indeterminacoes": indeterminacoes,
            "capacidades_adicionais": capacidades_adicionais
        }


    # -----------------------------------------------------
    # Caso residual
    # -----------------------------------------------------

    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis não permitem aplicar "
            "de forma segura os níveis definidos pela rubrica."
        ),
        "lacunas": lacunas,
        "indeterminacoes": indeterminacoes,
        "capacidades_adicionais": capacidades_adicionais
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = (
    classificar_maturidade_pipeline(
        evidencias
    )
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print(
    "CLASSIFICAÇÃO DA MATURIDADE "
    "DA AUTOMAÇÃO DO PIPELINE\n"
)


print(
    "Nível:",
    resultado_maturidade[
        "nivel"
    ]
)


print(
    "Classificação:",
    resultado_maturidade[
        "classificacao"
    ]
)


print(
    "Motivo:",
    resultado_maturidade[
        "motivo"
    ]
)


# ---------------------------------------------------------
# Lacunas
# ---------------------------------------------------------

lacunas_resultado = (
    resultado_maturidade.get(
        "lacunas",
        []
    )
)


print(
    "\nLacunas evidenciadas:"
)


if lacunas_resultado:

    for lacuna in lacunas_resultado:

        print(
            f"— {lacuna}"
        )

else:

    print(
        "Nenhuma lacuna explicitamente evidenciada "
        "para os critérios avaliados."
    )


# ---------------------------------------------------------
# Evidências indeterminadas
# ---------------------------------------------------------

indeterminacoes_resultado = (
    resultado_maturidade.get(
        "indeterminacoes",
        []
    )
)


print(
    "\nCritérios indeterminados:"
)


if indeterminacoes_resultado:

    for item in indeterminacoes_resultado:

        print(
            f"? {item}"
        )

else:

    print(
        "Nenhum critério indeterminado."
    )


# ---------------------------------------------------------
# Capacidades adicionais
# ---------------------------------------------------------

capacidades_resultado = (
    resultado_maturidade.get(
        "capacidades_adicionais",
        []
    )
)


print(
    "\nCapacidades adicionais observadas:"
)


if capacidades_resultado:

    for capacidade in capacidades_resultado:

        print(
            f"✓ {capacidade}"
        )

else:

    print(
        "Nenhuma capacidade adicional identificada."
    )

CLASSIFICAÇÃO DA MATURIDADE DA AUTOMAÇÃO DO PIPELINE

Nível: 2
Classificação: Inicial / Adhoc
Motivo: Existe pipeline versionado com automações básicas de integração contínua: análise SonarQube, espera pelo Quality Gate. Os critérios para CI estruturada completa ainda não foram integralmente atendidos.

Lacunas evidenciadas:
— testes automatizados
— Quality Gate bloqueante
— deploy automatizado
— promoção automática entre ambientes
— rollback automatizado

Critérios indeterminados:
Nenhum critério indeterminado.

Capacidades adicionais observadas:
✓ cache do Sonar
✓ execução associada a Merge Request
✓ regra associada à branch main
✓ Dockerfile da aplicação presente
✓ Dockerfile específico do PostgreSQL presente
✓ Docker Compose presente
✓ PostgreSQL evidenciado nos artefatos
✓ provider PostgreSQL integrado ao .NET
✓ versão configurada do PostgreSQL identificada

In [71]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
#
# Esta etapa não altera nem reclassifica as evidências.
# Ela apenas organiza os resultados determinísticos em um
# pacote estruturado para interpretação qualitativa pela IA.
# ---------------------------------------------------------


# ---------------------------------------------------------
# Verificações preliminares
# ---------------------------------------------------------

if not evidencias:

    raise ValueError(
        "Nenhuma evidência foi extraída."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


if not isinstance(
    artefatos_analisaveis,
    dict
):

    raise ValueError(
        "A estrutura de artefatos analisáveis não está disponível. "
        "Execute primeiro a etapa de identificação e validação."
    )


# ---------------------------------------------------------
# Função auxiliar
# ---------------------------------------------------------

def nome_se_analisavel(
    chave,
    nome
):
    """
    Retorna o nome do artefato somente se ele tiver sido
    previamente validado e habilitado para análise.

    Caso contrário, retorna None.
    """

    if artefatos_analisaveis.get(
        chave
    ) is True:

        return nome

    return None


# ---------------------------------------------------------
# Scripts efetivamente utilizados na análise
# ---------------------------------------------------------

scripts_analisados = sorted(
    scripts_analisaveis.keys()
) if isinstance(
    scripts_analisaveis,
    dict
) else []


# ---------------------------------------------------------
# Estado dos artefatos
#
# Permite que a interpretação assistida por IA diferencie:
#
# True  = artefato validado e analisado
# False = artefato encontrado, mas não habilitado
# ---------------------------------------------------------

estado_artefatos = {
    chave: bool(valor)
    for chave, valor in artefatos_analisaveis.items()
}


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    # -----------------------------------------------------
    # 1. Metadados da análise
    # -----------------------------------------------------

    "metadados_analise": {

        "tipo_analise":
            "extração determinística de evidências técnicas",

        "objetivo":
            (
                "Preparar evidências técnicas para interpretação "
                "qualitativa assistida por IA, sem alterar a "
                "classificação determinística."
            ),

        "semantica_tri_state": {

            "true":
                "Evidência diretamente identificada no artefato válido.",

            "false":
                (
                    "Artefato válido analisado, mas a evidência "
                    "não foi identificada."
                ),

            "null":
                (
                    "Evidência indeterminada devido à ausência, "
                    "invalidade ou insuficiência do artefato."
                )
        }
    },


    # -----------------------------------------------------
    # 2. Artefatos analisados
    # -----------------------------------------------------

    "artefatos_analisados": {

        "pipeline":
            nome_se_analisavel(
                "pipeline",
                pipeline_nome
            ),

        "csproj":
            nome_se_analisavel(
                "csproj",
                csproj_nome
            ),

        "renovate_json":
            nome_se_analisavel(
                "renovate_json",
                renovate_json_nome
            ),

        "renovate_setup":
            nome_se_analisavel(
                "renovate_setup",
                renovate_setup_nome
            ),

        "dockerfile":
            nome_se_analisavel(
                "dockerfile",
                dockerfile_nome
            ),

        "dockerfile_postgres":
            nome_se_analisavel(
                "dockerfile_postgres",
                dockerfile_postgres_nome
            ),

        "docker_compose":
            nome_se_analisavel(
                "docker_compose",
                docker_compose_nome
            ),

        "program_cs":
            nome_se_analisavel(
                "program_cs",
                program_cs_nome
            ),

        "appsettings":
            nome_se_analisavel(
                "appsettings",
                appsettings_nome
            ),

        "editorconfig":
            nome_se_analisavel(
                "editorconfig",
                editorconfig_nome
            ),

        "env_example":
            nome_se_analisavel(
                "env_example",
                env_example_nome
            ),

        "env_io_example":
            nome_se_analisavel(
                "env_io_example",
                env_io_example_nome
            ),

        "scripts":
            scripts_analisados
    },


    # -----------------------------------------------------
    # 3. Estado dos artefatos
    # -----------------------------------------------------

    "estado_artefatos": {

        "pipeline":
            estado_artefatos.get(
                "pipeline",
                False
            ),

        "csproj":
            estado_artefatos.get(
                "csproj",
                False
            ),

        "renovate_json":
            estado_artefatos.get(
                "renovate_json",
                False
            ),

        "renovate_setup":
            estado_artefatos.get(
                "renovate_setup",
                False
            ),

        "dockerfile":
            estado_artefatos.get(
                "dockerfile",
                False
            ),

        "dockerfile_postgres":
            estado_artefatos.get(
                "dockerfile_postgres",
                False
            ),

        "docker_compose":
            estado_artefatos.get(
                "docker_compose",
                False
            ),

        "program_cs":
            estado_artefatos.get(
                "program_cs",
                False
            ),

        "appsettings":
            estado_artefatos.get(
                "appsettings",
                False
            ),

        "editorconfig":
            estado_artefatos.get(
                "editorconfig",
                False
            ),

        "env_example":
            estado_artefatos.get(
                "env_example",
                False
            ),

        "env_io_example":
            estado_artefatos.get(
                "env_io_example",
                False
            ),

        "scripts":
            estado_artefatos.get(
                "scripts",
                False
            )
    },


    # -----------------------------------------------------
    # 4. Caracterização tecnológica
    # -----------------------------------------------------

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline,

        "database_technology":
            tecnologia.get(
                "database_technology"
            ),

        "database_version":
            tecnologia.get(
                "database_version"
            ),

        "database_version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "postgresql_dockerfile_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "postgresql_dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "postgresql_version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            )
    },


    # -----------------------------------------------------
    # 5. Integração contínua
    # -----------------------------------------------------

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },


    # -----------------------------------------------------
    # 6. Gerenciamento de dependências
    # -----------------------------------------------------

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },


    # -----------------------------------------------------
    # 7. Containerização
    # -----------------------------------------------------

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },


    # -----------------------------------------------------
    # 8. Observabilidade
    # -----------------------------------------------------

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },


    # -----------------------------------------------------
    # 9. Configuração e ambiente
    # -----------------------------------------------------

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },


    # -----------------------------------------------------
    # 10. Banco de dados
    #
    # Separado da configuração de ambiente porque representa
    # caracterização tecnológica própria.
    # -----------------------------------------------------

    "banco_de_dados": {

        "technology":
            tecnologia.get(
                "database_technology"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            ),

        "configured_version":
            tecnologia.get(
                "database_version"
            ),

        "version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "interpretation_constraint":
            (
                "A versão identificada representa a versão "
                "configurada nos artefatos analisados e não "
                "comprova a versão efetivamente executada "
                "no ambiente de produção."
            )
    },


    # -----------------------------------------------------
    # 11. Qualidade estática
    # -----------------------------------------------------

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },


    # -----------------------------------------------------
    # 12. Automação local
    # -----------------------------------------------------

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            ),

        "interpretation_constraint":
            (
                "Automação de ambiente local não constitui "
                "evidência de deploy automatizado da aplicação."
            )
    },


    # -----------------------------------------------------
    # 13. Entrega e recuperação
    # -----------------------------------------------------

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },


    # -----------------------------------------------------
    # 14. Classificação determinística
    #
    # A IA recebe a classificação pronta e não deve
    # recalculá-la.
    # -----------------------------------------------------

    "classificacao_deterministica": {

        "scope":
            (
                "maturidade da automação do pipeline "
                "segundo rubrica específica do estudo"
            ),

        "nivel":
            resultado_maturidade.get(
                "nivel"
            ),

        "classificacao":
            resultado_maturidade.get(
                "classificacao"
            ),

        "motivo":
            resultado_maturidade.get(
                "motivo"
            ),

        "lacunas":
            resultado_maturidade.get(
                "lacunas",
                []
            ),

        "indeterminacoes":
            resultado_maturidade.get(
                "indeterminacoes",
                []
            ),

        "capacidades_adicionais":
            resultado_maturidade.get(
                "capacidades_adicionais",
                []
            )
    },


    # -----------------------------------------------------
    # 15. Restrições interpretativas
    # -----------------------------------------------------

    "restricoes_interpretativas": [

        (
            "A interpretação assistida por IA deve partir "
            "exclusivamente das evidências estruturadas fornecidas."
        ),

        (
            "A IA não deve transformar ausência de evidência "
            "em evidência de ausência quando o valor for null."
        ),

        (
            "Valores false representam ausência da característica "
            "somente no escopo do artefato válido analisado."
        ),

        (
            "A presença de Dockerfile, Dockerfile.postgres ou "
            "Docker Compose não constitui, por si só, evidência "
            "de deploy automatizado."
        ),

        (
            "A presença de renovate.json comprova configuração "
            "do Renovate, mas não comprova sua execução efetiva."
        ),

        (
            "Um job Renovate no pipeline comprova orquestração "
            "configurada, mas não comprova execução efetiva."
        ),

        (
            "A configuração de espera pelo Quality Gate não "
            "implica Quality Gate bloqueante quando o job permite "
            "falha."
        ),

        (
            "Scripts de inicialização ou automação local não "
            "devem ser interpretados como automação de deployment."
        ),

        (
            "A versão PostgreSQL identificada representa "
            "configuração observada nos artefatos e não a versão "
            "necessariamente executada em produção."
        ),

        (
            "Dockerfile.postgres evidencia configuração de uma "
            "imagem/container PostgreSQL quando validado, mas não "
            "comprova a versão efetivamente executada em produção "
            "nem automação de deployment."
        ),

        (
            "A classificação determinística representa somente "
            "a maturidade da automação observável no pipeline e "
            "não a maturidade DevOps global da organização."
        )
    ]
}


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)


print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "metadados_analise": {
    "tipo_analise": "extração determinística de evidências técnicas",
    "objetivo": "Preparar evidências técnicas para interpretação qualitativa assistida por IA, sem alterar a classificação determinística.",
    "semantica_tri_state": {
      "true": "Evidência diretamente identificada no artefato válido.",
      "false": "Artefato válido analisado, mas a evidência não foi identificada.",
      "null": "Evidência indeterminada devido à ausência, invalidade ou insuficiência do artefato."
    }
  },
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (4).yml",
    "csproj": "Boilerplate4Dev (4).csproj",
    "renovate_json": null,
    "renovate_setup": null,
    "dockerfile": "Dockerfile (4)",
    "dockerfile_postgres": "Dockerfile (4).postgres",
    "docker_compose": "docker-compose (4).yaml",
    "program_cs": "Program (4).cs",
    "appsettings": "appsettings (4).json",
    "editorconfig": ".editorconfig (4)",
    "env_example": ".env (4).example",
    "env_io_example": ".env.io (3).example",
    "scripts": [
      "init (4).sql",
      "start-db (4).ps1"
    ]
  },
  "estado_artefatos": {
    "pipeline": true,
    "csproj": true,
    "renovate_json": false,
    "renovate_setup": false,
    "dockerfile": true,
    "dockerfile_postgres": true,
    "docker_compose": true,
    "program_cs": true,
    "appsettings": true,
    "editorconfig": true,
    "env_example": true,
    "env_io_example": true,
    "scripts": true
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net9.0",
    "sdk_pipeline": null,
    "database_technology": "PostgreSQL",
    "database_version": "17",
    "database_version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "postgresql_evidenced": true,
    "postgresql_dockerfile_present": true,
    "postgresql_dotnet_provider": true,
    "postgresql_version_identified": true
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": false,
    "build_release": false,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": false,
    "merge_request_rule": true,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": null,
    "nuget_manager": null,
    "dockerfile_manager": null,
    "vulnerability_alerts": null,
    "lock_file_maintenance": null,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "dockerfile_postgres_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": true,
    "api_health_check": true,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "environment_parameterization": true
  },
  "banco_de_dados": {
    "technology": "PostgreSQL",
    "postgresql_evidenced": true,
    "dockerfile_postgres_present": true,
    "dotnet_provider": true,
    "version_identified": true,
    "configured_version": "17",
    "version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "interpretation_constraint": "A versão identificada representa a versão configurada nos artefatos analisados e não comprova a versão efetivamente executada no ambiente de produção."
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": false,
    "database_dump_present": false,
    "local_environment_automation": true,
    "interpretation_constraint": "Automação de ambiente local não constitui evidência de deploy automatizado da aplicação."
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "scope": "maturidade da automação do pipeline segundo rubrica específica do estudo",
    "nivel": 2,
    "classificacao": "Inicial / Adhoc",
    "motivo": "Existe pipeline versionado com automações básicas de integração contínua: análise SonarQube, espera pelo Quality Gate. Os critérios para CI estruturada completa ainda não foram integralmente atendidos.",
    "lacunas": [
      "testes automatizados",
      "Quality Gate bloqueante",
      "deploy automatizado",
      "promoção automática entre ambientes",
      "rollback automatizado"
    ],
    "indeterminacoes": [],
    "capacidades_adicionais": [
      "cache do Sonar",
      "execução associada a Merge Request",
      "regra associada à branch main",
      "Dockerfile da aplicação presente",
      "Dockerfile específico do PostgreSQL presente",
      "Docker Compose presente",
      "PostgreSQL evidenciado nos artefatos",
      "provider PostgreSQL integrado ao .NET",
      "versão configurada do PostgreSQL identificada"
    ]
  },
  "restricoes_interpretativas": [
    "A interpretação assistida por IA deve partir exclusivamente das evidências estruturadas fornecidas.",
    "A IA não deve transformar ausência de evidência em evidência de ausência quando o valor for null.",
    "Valores false representam ausência da característica somente no escopo do artefato válido analisado.",
    "A presença de Dockerfile, Dockerfile.postgres ou Docker Compose não constitui, por si só, evidência de deploy automatizado.",
    "A presença de renovate.json comprova configuração do Renovate, mas não comprova sua execução efetiva.",
    "Um job Renovate no pipeline comprova orquestração configurada, mas não comprova execução efetiva.",
    "A configuração de espera pelo Quality Gate não implica Quality Gate bloqueante quando o job permite falha.",
    "Scripts de inicialização ou automação local não devem ser interpretados como automação de deployment.",
    "A versão PostgreSQL identificada representa configuração observada nos artefatos e não a versão necessariamente executada em produção.",
    "Dockerfile.postgres evidencia configuração de uma imagem/container PostgreSQL quando validado, mas não comprova a versão efetivamente executada em produção nem automação de deployment.",
    "A classificação determinística representa somente a maturidade da automação observável no pipeline e não a maturidade DevOps global da organização."
  ]
}

In [72]:
# ---------------------------------------------------------
# PIPELINE AUTOMATION MATURITY CRITERIA
#
# Rubrica determinística específica deste estudo.
#
# Esta escala representa somente a maturidade da automação
# observável no pipeline analisado. Ela não representa um
# modelo geral de maturidade DevOps da organização.
# ---------------------------------------------------------

criterios_maturidade = """
Rubrica de maturidade da automação do pipeline utilizada neste estudo:

Nível 1 — Pipeline versionado
Existe um pipeline de integração contínua versionado, mas não foram
identificadas automações suficientes para caracterizar níveis superiores.

Nível 2 — Automação básica de CI
Existe pipeline versionado com automações pontuais de integração contínua,
como restore, build ou análise automatizada de qualidade, mas sem atendimento
integral aos critérios de uma CI estruturada.

Nível 3 — CI estruturada com controle de qualidade
Existe pipeline versionado com restore automatizado, build automatizado
e controle automatizado de qualidade, como SonarQube ou espera pelo
Quality Gate. Ainda podem permanecer lacunas relativas a testes
automatizados, bloqueio do Quality Gate, deploy, promoção entre ambientes
e rollback.

Nível 4 — Automação de entrega ponta a ponta
Além da integração contínua estruturada e dos controles de qualidade,
existem evidências de testes automatizados, Quality Gate bloqueante,
deploy automatizado, promoção automática entre ambientes e rollback
automatizado.

A classificação é baseada exclusivamente nas evidências técnicas
extraídas dos artefatos válidos analisados.

A presença de arquivos de configuração, isoladamente, não comprova
execução efetiva das práticas.

A rubrica é específica deste estudo e não deve ser interpretada como
classificação abrangente de maturidade DevOps da organização.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica e conservadora das evidências
relacionadas à automação do pipeline apresentadas abaixo.

A classificação da maturidade da automação do pipeline já foi calculada
deterministicamente pelo notebook.

Sua função NÃO é criar uma nova classificação independente.

Sua função é:

1. interpretar tecnicamente as evidências;
2. verificar se elas sustentam a classificação determinística;
3. identificar lacunas, limitações e evidências indeterminadas;
4. contextualizar capacidades adicionais observadas;
5. evitar inferências que ultrapassem os artefatos analisados.

A classificação avaliada refere-se exclusivamente à maturidade da
automação observável no pipeline segundo a rubrica específica deste estudo.

Ela NÃO representa a maturidade DevOps global do projeto, da equipe
ou da organização.


{criterios_maturidade}


EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}


REGRAS DA INTERPRETAÇÃO:

1. Utilize exclusivamente as evidências fornecidas.

2. Não presuma práticas, ferramentas, execuções ou resultados
   que não estejam evidenciados.

3. Não avalie a maturidade DevOps global do projeto ou da organização.

4. Avalie especificamente se as evidências sustentam a classificação
   determinística da maturidade da automação do pipeline.

5. Respeite rigorosamente a semântica tri-state:

   true
   = evidência positiva identificada em artefato válido;

   false
   = artefato válido analisado e característica não identificada;

   null
   = evidência indeterminada por ausência, invalidade ou insuficiência
     do artefato.

6. Null não significa ausência da prática.

7. False deve ser interpretado somente no escopo dos artefatos
   válidos efetivamente analisados.

8. Não transforme ausência de evidência em evidência de ausência
   quando o valor for null.

9. Quality Gate configurado ou aguardado não significa necessariamente
   Quality Gate bloqueante.

10. Se o job responsável pelo Quality Gate estiver configurado com
    allow_failure:true, o Quality Gate não deve ser interpretado como
    bloqueante.

11. SonarQube e Quality Gate caracterizam controle automatizado
    de qualidade, mas não comprovam testes automatizados.

12. A ausência de comandos de testes automatizados nos pipelines
    analisados deve ser interpretada somente no escopo desses pipelines.

13. A ausência de comandos de deploy no pipeline não prova que
    nenhum deployment seja realizado por processos externos ou manuais.

14. O mesmo princípio se aplica à promoção entre ambientes
    e ao rollback.

15. Dockerfile da aplicação demonstra definição automatizada de construção
    e empacotamento de imagem, mas não comprova deployment automatizado.

16. Dockerfile.postgres evidencia configuração de uma imagem/container
    PostgreSQL quando validado. Sua presença não comprova deployment
    automatizado, execução do banco em produção nem a versão efetivamente
    executada no ambiente de produção.

17. Docker Compose demonstra configuração de serviços, execução
    e integração de contêineres, mas sua presença não constitui
    evidência de deploy automatizado em pipeline.

18. Scripts locais, scripts de inicialização de banco, scripts de seed
    ou comandos de ambiente local não devem ser interpretados
    como deploy automatizado da aplicação.

19. A presença de renovate.json comprova configuração da ferramenta,
    mas não comprova sua execução efetiva.

20. Um job Renovate no pipeline comprova que existe orquestração
    configurada para a ferramenta, mas não comprova execução
    efetiva ou bem-sucedida.

21. Regras de schedule ou execução manual do Renovate representam
    possibilidades configuradas de execução e não histórico
    comprovado de execução.

22. Execução efetiva do Renovate exige evidências de runtime,
    como histórico de pipeline, logs, branches renovate/*,
    commits ou merge requests criados pela ferramenta.

23. A ausência de um job Renovate em determinada versão não deve
    ser interpretada automaticamente como ausência completa
    do Renovate caso sua configuração permaneça presente.

24. Sentry configurado em appsettings representa evidência
    configuracional.

25. Sentry identificado em Program.cs representa evidência mais forte
    de integração em runtime da aplicação.

26. Logging, health checks, Sentry e Matomo caracterizam capacidades
    relacionadas à observabilidade, monitoramento ou telemetria.

27. Essas capacidades de observabilidade não devem ser usadas,
    isoladamente, para aumentar o nível de maturidade da automação
    do pipeline.

28. A presença de regras no .editorconfig representa regras
    declaradas de análise estática.

29. Regras declaradas no .editorconfig não comprovam, isoladamente,
    que tenham sido aplicadas ou bloqueado o pipeline.

30. Evidências de PostgreSQL caracterizam a tecnologia de banco
    identificada nos artefatos analisados.

31. A identificação de Npgsql, UseNpgsql ou AddNpgsql pode sustentar
    a interpretação de utilização do provider PostgreSQL no .NET.

32. A versão PostgreSQL identificada em Dockerfile.postgres,
    Docker Compose, Dockerfile da aplicação, scripts ou arquivos
    de ambiente representa versão configurada nos artefatos.

33. A versão PostgreSQL configurada não comprova a versão efetivamente
    executada no servidor de produção. Ao interpretar a versão, preserve
    também database_version_source para indicar de qual artefato válido
    a configuração foi extraída.

34. A presença de PostgreSQL nos artefatos modernos não comprova,
    isoladamente, a execução de uma migração de Ingres para PostgreSQL.

35. Não inferir Continuous Delivery apenas pela existência
    de integração contínua, Docker ou scripts.

36. Não inferir Continuous Deployment sem evidência de deployment
    automatizado no pipeline.

37. Não utilizar capacidades adicionais, como cache, Renovate,
    observabilidade ou containerização, para elevar arbitrariamente
    o nível da rubrica.

38. Capacidades adicionais devem ser tratadas como elementos
    complementares da caracterização técnica da versão.

39. Compare explicitamente as evidências observadas com os critérios
    do nível atribuído pela classificação determinística.

40. Se as evidências forem compatíveis com a classificação,
    declare que a classificação é sustentada.

41. Se apenas parte das evidências necessárias puder ser confirmada,
    declare que a classificação é parcialmente sustentada.

42. Se houver contradição objetiva entre a classificação determinística
    e as evidências fornecidas, declare que a classificação
    não é sustentada.

43. Caso identifique inconsistência, descreva-a explicitamente,
    mas não substitua arbitrariamente a classificação calculada.

44. Diferencie claramente:
    - evidências positivas;
    - lacunas evidenciadas;
    - evidências indeterminadas;
    - capacidades adicionais.

45. Não atribua causalidade a partir da simples coexistência
    de ferramentas ou configurações.

46. Não trate evolução temporal como necessariamente monotônica.
    Uma versão posterior pode preservar, retirar ou alterar
    determinada automação sem que isso represente evolução
    linear de maturidade.

47. Utilize linguagem técnica, conservadora, rastreável
    e adequada a um trabalho acadêmico.

48. Evite expressões promocionais ou conclusões amplas como:
    "pipeline DevOps completo",
    "DevOps maduro",
    "automação total",
    "CI/CD plenamente implementado",
    quando essas afirmações não forem diretamente sustentadas
    pelas evidências.

49. Não apresente a rubrica do notebook como modelo universal
    de maturidade DevOps. Ela é uma operacionalização específica
    deste estudo.


PRODUZA A RESPOSTA EXATAMENTE COM A SEGUINTE ESTRUTURA:


### Avaliação da classificação

Classificação determinística:
[reproduza o nível e a classificação recebidos]

Avaliação:
[Sustentada / Parcialmente sustentada / Não sustentada]

Justificativa:
[explique de forma objetiva a relação entre as evidências
e os critérios do nível atribuído]


### Evidências que sustentam a avaliação

Apresente as principais evidências positivas que sustentam
a classificação, priorizando aquelas diretamente relacionadas
à rubrica.


### Lacunas identificadas

Apresente somente lacunas que estejam efetivamente evidenciadas
como false nos artefatos analisados.

Não inclua valores null como ausência.


### Evidências indeterminadas

Apresente os itens relevantes cujo valor seja null e explique,
quando necessário, que eles não podem ser classificados
como presentes nem ausentes.


### Capacidades adicionais observadas

Apresente capacidades tecnicamente relevantes, como cache,
Renovate, containerização, observabilidade, configuração
externalizada ou banco de dados, sem utilizá-las para elevar
arbitrariamente o nível da classificação.


### Limitações da interpretação

Explique as principais limitações decorrentes do escopo
dos artefatos analisados.

Destaque quando a configuração não comprovar execução efetiva.


### Síntese

Produza uma síntese curta, acadêmica e conservadora,
indicando se a classificação determinística é sustentada
pelas evidências disponíveis.
"""


# ---------------------------------------------------------
# RESULTADO
# ---------------------------------------------------------

print(
    "✓ Prompt de interpretação preparado."
)

print(
    "✓ Rubrica de maturidade alinhada "
    "à classificação determinística."
)

print(
    "✓ Restrições de interpretação incorporadas."
)

✓ Prompt de interpretação preparado.
✓ Rubrica de maturidade alinhada à classificação determinística.
✓ Restrições de interpretação incorporadas.

In [75]:
# ---------------------------------------------------------
# VERSION ANALYSIS STORAGE
#
# Reinicia a estrutura longitudinal antes de uma nova
# execução completa V1 → V4.
# ---------------------------------------------------------

resultados_versoes = {}

print(
    "✓ Estrutura longitudinal reinicializada."
)

print(
    "✓ Versões armazenadas:",
    sorted(
        resultados_versoes.keys()
    )
)

✓ Estrutura longitudinal reinicializada.
✓ Versões armazenadas: []

In [76]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
#
# A IA atua exclusivamente como apoio à interpretação
# qualitativa das evidências previamente extraídas e
# classificadas de forma determinística.
#
# A IA não altera:
# - as evidências extraídas;
# - os estados tri-state;
# - o nível calculado;
# - a classificação determinística.
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Configuração da interpretação
# ---------------------------------------------------------

MODELO_IA = "gpt-5.6-terra"
ESFORCO_RACIOCINIO = "medium"


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

interpretacao_ia = None

metadados_interpretacao_ia = {
    "executada": False,
    "modelo_solicitado": MODELO_IA,
    "modelo_retornado": None,
    "esforco_raciocinio": ESFORCO_RACIOCINIO,
    "classificacao_deterministica_preservada": True,
    "response_id": None,
    "input_tokens": None,
    "output_tokens": None,
    "total_tokens": None,
    "erro": None
}


# ---------------------------------------------------------
# 3. Recupera a chave da API
#
# A chave deve permanecer nos Secrets do Google Colab.
# Ela não deve ser inserida diretamente no notebook,
# impressa ou armazenada nos resultados da pesquisa.
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception:

    api_key = None

    metadados_interpretacao_ia[
        "erro"
    ] = (
        "Não foi possível acessar os Secrets "
        "do Google Colab."
    )


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 4. Validação das entradas
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or evidencias_para_ia is None
):

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not isinstance(
    evidencias_para_ia,
    dict
):

    raise TypeError(
        "evidencias_para_ia deve ser um dicionário."
    )


if (
    "prompt" not in globals()
    or not isinstance(
        prompt,
        str
    )
    or not prompt.strip()
):

    raise ValueError(
        "O prompt de interpretação ainda não foi criado "
        "ou está vazio."
    )


if (
    "resultado_maturidade" not in globals()
    or resultado_maturidade is None
):

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


if not isinstance(
    resultado_maturidade,
    dict
):

    raise TypeError(
        "resultado_maturidade deve ser um dicionário."
    )


# ---------------------------------------------------------
# 5. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 6. Instruções de sistema da interpretação
# ---------------------------------------------------------

instrucoes_interpretacao = """
Atue como avaliador técnico de evidências relacionadas à
automação de pipelines de software.

A análise integra um estudo acadêmico longitudinal sobre
modernização de software legado.

Sua interpretação deve ser:

- técnica;
- conservadora;
- rastreável;
- baseada exclusivamente nas evidências fornecidas;
- coerente com a semântica tri-state apresentada;
- limitada ao escopo dos artefatos analisados.

Não realize uma nova classificação independente.

Não altere o nível de maturidade calculado deterministicamente
pelo notebook.

Avalie se as evidências fornecidas sustentam a classificação
determinística.

Diferencie explicitamente:

- evidência positiva;
- ausência evidenciada;
- evidência indeterminada;
- configuração;
- orquestração;
- execução efetiva.

Não interprete ausência de evidência como evidência de ausência
quando o valor recebido for null.

Não avalie a maturidade DevOps global da organização.

A classificação fornecida representa exclusivamente a maturidade
da automação observável no pipeline segundo a rubrica específica
definida neste estudo.

Não atribua causalidade ou evolução de maturidade apenas pela
presença de ferramentas.

Não presuma evolução temporal monotônica.

A presença de Dockerfile.postgres deve ser interpretada como
evidência configuracional relacionada à containerização do
PostgreSQL quando essa evidência estiver explicitamente presente.

Dockerfile.postgres não comprova, isoladamente:

- deployment automatizado;
- execução efetiva do banco em produção;
- versão efetivamente executada em produção;
- Continuous Delivery;
- Continuous Deployment;
- migração efetiva de banco de dados.

Quando uma versão PostgreSQL configurada estiver presente,
considere também a respectiva fonte registrada em
database_version_source.

Utilize linguagem adequada a um trabalho acadêmico.
"""


# ---------------------------------------------------------
# 7. Interpretação assistida por IA
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model=MODELO_IA,

        reasoning={
            "effort": ESFORCO_RACIOCINIO
        },

        instructions=(
            instrucoes_interpretacao
        ),

        input=prompt,

        store=False
    )


    # -----------------------------------------------------
    # 8. Recupera a interpretação textual
    # -----------------------------------------------------

    interpretacao_ia = (
        response.output_text.strip()
        if response.output_text
        else None
    )


    if not interpretacao_ia:

        raise ValueError(
            "A API respondeu, mas não retornou "
            "interpretação textual."
        )


    # -----------------------------------------------------
    # 9. Metadados da execução
    #
    # Não armazenamos API key nem outros segredos.
    # -----------------------------------------------------

    metadados_interpretacao_ia[
        "executada"
    ] = True

    metadados_interpretacao_ia[
        "modelo_retornado"
    ] = getattr(
        response,
        "model",
        None
    )

    metadados_interpretacao_ia[
        "response_id"
    ] = getattr(
        response,
        "id",
        None
    )


    # -----------------------------------------------------
    # 10. Uso de tokens, quando disponibilizado pela API
    # -----------------------------------------------------

    usage = getattr(
        response,
        "usage",
        None
    )


    if usage is not None:

        metadados_interpretacao_ia[
            "input_tokens"
        ] = getattr(
            usage,
            "input_tokens",
            None
        )

        metadados_interpretacao_ia[
            "output_tokens"
        ] = getattr(
            usage,
            "output_tokens",
            None
        )

        metadados_interpretacao_ia[
            "total_tokens"
        ] = getattr(
            usage,
            "total_tokens",
            None
        )


    # -----------------------------------------------------
    # 11. Resultado
    # -----------------------------------------------------

    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


    print(
        "\n"
        "-----------------------------------------"
    )

    print(
        "Modelo solicitado:",
        metadados_interpretacao_ia[
            "modelo_solicitado"
        ]
    )

    print(
        "Modelo retornado:",
        metadados_interpretacao_ia[
            "modelo_retornado"
        ]
    )

    print(
        "Esforço de raciocínio:",
        metadados_interpretacao_ia[
            "esforco_raciocinio"
        ]
    )

    print(
        "Execução:",
        "concluída"
    )


# ---------------------------------------------------------
# 12. Tratamento de erro
# ---------------------------------------------------------

except Exception as erro:

    interpretacao_ia = None

    metadados_interpretacao_ia[
        "executada"
    ] = False

    metadados_interpretacao_ia[
        "erro"
    ] = str(
        erro
    )


    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação

Classificação determinística:
Nível 2 — Inicial / Adhoc.

Avaliação:
Sustentada.

Justificativa:
As evidências sustentam a classificação no Nível 2 da rubrica específica do estudo. Há evidência positiva de pipeline GitLab CI versionado (`gitlab_ci: true`) e de automação pontual de integração contínua relacionada ao controle de qualidade, por meio de SonarQube (`sonarqube: true`) e espera pelo Quality Gate (`quality_gate_wait: true`).

Contudo, os critérios de CI estruturada do Nível 3 não estão integralmente evidenciados: `dotnet_restore` e `build_release` possuem valor `false` nos artefatos válidos analisados. Embora exista análise de qualidade e espera pelo Quality Gate, este não é bloqueante (`quality_gate_blocking: false`). Portanto, as evidências não sustentam a caracterização de CI estruturada com controle de qualidade nos termos completos da rubrica.

Também não há evidência, no escopo do pipeline analisado, de testes automatizados, deploy automatizado, promoção entre ambientes ou rollback automatizado. Essas lacunas são coerentes com a não caracterização do Nível 4. A classificação é, assim, compatível com a presença de automação básica de CI, sem comprovação dos controles e mecanismos exigidos para níveis superiores.

### Evidências que sustentam a avaliação

- Existe evidência positiva de pipeline GitLab CI versionado (`gitlab_ci: true`).
- O pipeline contém integração com SonarQube (`sonarqube: true`), caracterizando automação de análise de qualidade.
- Há configuração de espera pelo Quality Gate (`quality_gate_wait: true`), o que demonstra orquestração de uma verificação de qualidade no pipeline.
- Foram identificadas regras associadas a Merge Requests (`merge_request_rule: true`) e à branch `main` (`main_branch_rule: true`), indicando condições configuradas para acionamento ou aplicação do pipeline nesses contextos.
- Há cache do Sonar configurado (`sonar_cache: true`), como capacidade complementar de eficiência da execução configurada.
- A presença de SonarQube e da espera pelo Quality Gate é suficiente para sustentar a identificação de automação pontual de CI requerida pelo Nível 2, sem implicar, isoladamente, CI estruturada completa.

### Lacunas identificadas

As seguintes lacunas foram evidenciadas com valor `false` no escopo dos artefatos válidos analisados:

- Não foi identificado restore .NET no pipeline (`dotnet_restore: false`).
- Não foi identificado build em configuração Release no pipeline (`build_release: false`).
- O Quality Gate não é bloqueante (`quality_gate_blocking: false`); portanto, a espera pelo resultado do Quality Gate não comprova interrupção obrigatória do pipeline em caso de reprovação.
- Não foram identificados testes automatizados no pipeline analisado (`automated_tests: false`).
- Não foi identificado deploy automatizado (`automated_deploy: false`).
- Não foi identificada promoção automática entre ambientes (`automated_promotion: false`).
- Não foi identificado rollback automatizado (`automated_rollback: false`).
- Não foi identificado cache NuGet (`nuget_cache: false`), embora essa ausência não seja, por si só, determinante para o nível da rubrica.
- Não foram identificados job, agendamento ou acionamento manual de Renovate no pipeline analisado (`renovate_job`, `renovate_schedule` e `renovate_manual`: `false`). Isso se limita aos mecanismos observados e não comprova ausência completa da ferramenta em processos externos ao escopo analisado.

### Evidências indeterminadas

Os seguintes itens possuem valor `null` e, portanto, não podem ser interpretados como presença ou ausência da prática:

- O SDK utilizado no pipeline é indeterminado (`sdk_pipeline: null`).
- A configuração do Renovate é indeterminada (`renovate_configured: null`), pois não foram disponibilizados artefatos válidos de `renovate.json` ou de configuração equivalente.
- A identificação de gerenciadores Renovate para dependências NuGet e Dockerfile é indeterminada (`nuget_manager: null` e `dockerfile_manager: null`).
- A existência de alertas de vulnerabilidade relacionados ao gerenciamento de dependências é indeterminada (`vulnerability_alerts: null`).
- A manutenção de arquivos de lock é indeterminada (`lock_file_maintenance: null`).
- A execução efetiva do Renovate é indeterminada (`renovate_effective_execution: null`). Não foram fornecidas evidências de runtime, tais como logs, histórico de pipelines, branches, commits ou Merge Requests produzidos pela ferramenta.

Esses valores `null` não devem ser convertidos em evidência de ausência de Renovate, de gerenciamento automatizado de dependências ou de execução efetiva dessas práticas.

### Capacidades adicionais observadas

- Há Dockerfile da aplicação (`dockerfile_present: true`) com construção multiestágio (`multi_stage_build: true`), restore (`docker_restore: true`), build (`docker_build: true`) e publish (`docker_publish: true`) configurados. Essas evidências caracterizam automação de construção e empacotamento de imagem, não deploy automatizado.
- Há Dockerfile específico para PostgreSQL (`dockerfile_postgres_present: true`). Isso constitui evidência configuracional de uma imagem ou contêiner PostgreSQL.
- A versão PostgreSQL configurada é `17`, com fonte registrada como `Dockerfile.postgres (imagem PostgreSQL literal)`. Essa informação representa a versão configurada no artefato analisado, não a versão comprovadamente executada em produção.
- PostgreSQL está evidenciado como tecnologia de banco de dados, com provider .NET identificado (`postgresql_dotnet_provider: true`).
- Há Docker Compose (`docker_compose_present: true`), com build configurado, política de reinício, rede externa e proxy reverso. Tais elementos descrevem configuração e orquestração de serviços em contêineres, mas não comprovam deployment por pipeline nem execução efetiva em ambiente produtivo.
- Foram identificados scripts de automação local, incluindo script de inicialização de banco (`database_initialization_script: true`) e automação de ambiente local (`local_environment_automation: true`). Essas capacidades não constituem evidência de deploy automatizado da aplicação.
- Há configuração externalizada e parametrização por ambiente (`externalized_configuration: true`, `environment_parameterization: true`), com arquivos de exemplo `.env` e `.env.io`.
- Foram identificadas regras declaradas no `.editorconfig`, incluindo regras de análise estática e segurança. Essas regras representam configuração de qualidade estática, sem comprovar sua aplicação efetiva ou bloqueio do pipeline.
- Há capacidades de observabilidade e telemetria: Sentry configurado e integrado em runtime da aplicação, health checks de API e banco de dados, logging em console e configuração Matomo. Essas capacidades são tecnicamente relevantes, mas não elevam, isoladamente, a maturidade da automação do pipeline segundo a rubrica.

### Limitações da interpretação

A interpretação está limitada aos artefatos estruturados fornecidos e à semântica tri-state da extração determinística. Valores `false` indicam que determinada característica não foi identificada nos artefatos válidos analisados, sem demonstrar que ela inexista em processos manuais, serviços externos ou outros repositórios.

A presença de SonarQube e da espera pelo Quality Gate demonstra configuração e orquestração de controle de qualidade, mas não comprova resultado de execução, aprovação do gate ou bloqueio do pipeline. Neste caso, a evidência explícita de `quality_gate_blocking: false` impede interpretar o Quality Gate como bloqueante.

De modo semelhante, Dockerfile, Dockerfile.postgres, Docker Compose, scripts locais e configurações de ambiente demonstram definições técnicas e capacidades configuracionais. Esses elementos não comprovam execução efetiva em produção, deploy automatizado, Continuous Delivery, Continuous Deployment, promoção automática ou rollback.

A integração de Sentry em `Program.cs` constitui evidência mais forte de integração no runtime da aplicação do que mera configuração em arquivo, mas ainda não comprova telemetria efetivamente enviada ou monitoramento operacional ativo. Igualmente, a versão PostgreSQL `17`, extraída de `Dockerfile.postgres`, é uma versão configurada nos artefatos analisados e não comprova a versão efetivamente executada em produção.

### Síntese

A classificação determinística Nível 2 — Inicial / Adhoc é sustentada pelas evidências disponíveis. O pipeline GitLab CI versionado contém automação pontual de qualidade com SonarQube e espera pelo Quality Gate, mas não apresenta restore e build Release identificados, nem Quality Gate bloqueante, testes automatizados, deploy, promoção ou rollback automatizados no escopo analisado. As capacidades de containerização, observabilidade, configuração de ambiente e PostgreSQL complementam a caracterização técnica, sem alterar o nível de maturidade de automação do pipeline definido pela rubrica.

-----------------------------------------
Modelo solicitado: gpt-5.6-terra
Modelo retornado: gpt-5.6-terra
Esforço de raciocínio: medium
Execução: concluída

In [77]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS
#
# Armazena uma cópia independente dos resultados da versão
# atualmente analisada para posterior análise longitudinal.
#
# A mesma célula pode ser reutilizada para V1, V2, V3 e V4.
# Basta definir:
#
# versao_atual
# snapshot_atual
#
# antes da execução.
# ---------------------------------------------------------

import copy

versao_atual = "V1"
snapshot_atual = "web-1.25.10-1"

if (
    "versao_atual" not in globals()
    or not isinstance(
        versao_atual,
        str
    )
    or not versao_atual.strip()
):

    raise ValueError(
        "A variável versao_atual não foi definida."
    )


versao_atual = versao_atual.strip().upper()


if (
    "snapshot_atual" not in globals()
    or not isinstance(
        snapshot_atual,
        str
    )
    or not snapshot_atual.strip()
):

    raise ValueError(
        f"O snapshot da {versao_atual} não foi definido "
        "na variável snapshot_atual."
    )


snapshot_atual = snapshot_atual.strip()


# ---------------------------------------------------------
# 2. Validação da estrutura longitudinal
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes não foi inicializada."
    )


# ---------------------------------------------------------
# 3. Validação das evidências
# ---------------------------------------------------------

if (
    "evidencias" not in globals()
    or not isinstance(
        evidencias,
        dict
    )
    or not evidencias
):

    raise ValueError(
        f"As evidências da {versao_atual} "
        "não estão disponíveis."
    )


# ---------------------------------------------------------
# 4. Validação da classificação determinística
# ---------------------------------------------------------

if (
    "resultado_maturidade" not in globals()
    or not isinstance(
        resultado_maturidade,
        dict
    )
):

    raise ValueError(
        f"A classificação determinística da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 5. Validação do pacote preparado para a IA
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or not isinstance(
        evidencias_para_ia,
        dict
    )
):

    raise ValueError(
        f"O pacote estruturado de evidências da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 6. Validação da caracterização tecnológica
# ---------------------------------------------------------

if (
    "tecnologia" not in globals()
    or not isinstance(
        tecnologia,
        dict
    )
):

    raise ValueError(
        f"A caracterização tecnológica da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 7. Validação dos artefatos analisáveis
# ---------------------------------------------------------

if (
    "artefatos_analisaveis" not in globals()
    or not isinstance(
        artefatos_analisaveis,
        dict
    )
):

    raise ValueError(
        f"A estrutura de artefatos analisáveis da "
        f"{versao_atual} não está disponível."
    )


# ---------------------------------------------------------
# 8. Captura segura da interpretação assistida por IA
# ---------------------------------------------------------

interpretacao_atual = (
    interpretacao_ia
    if (
        "interpretacao_ia" in globals()
        and interpretacao_ia is not None
    )
    else None
)


# ---------------------------------------------------------
# 9. Metadados da execução da IA
# ---------------------------------------------------------

metadados_ia_atual = (
    copy.deepcopy(
        metadados_interpretacao_ia
    )
    if (
        "metadados_interpretacao_ia" in globals()
        and isinstance(
            metadados_interpretacao_ia,
            dict
        )
    )
    else {
        "executada": False,
        "modelo_solicitado": None,
        "modelo_retornado": None,
        "esforco_raciocinio": None,
        "classificacao_deterministica_preservada": True,
        "response_id": None,
        "input_tokens": None,
        "output_tokens": None,
        "total_tokens": None,
        "erro": (
            "Metadados da interpretação assistida "
            "por IA não disponíveis."
        )
    }
)


# ---------------------------------------------------------
# 10. Scripts efetivamente analisados
# ---------------------------------------------------------

scripts_analisados_atual = (
    sorted(
        scripts_analisaveis.keys()
    )
    if (
        "scripts_analisaveis" in globals()
        and isinstance(
            scripts_analisaveis,
            dict
        )
    )
    else []
)


# ---------------------------------------------------------
# 11. Artefatos efetivamente analisados
# ---------------------------------------------------------

artefatos_analisados_atual = {

    "pipeline":
        pipeline_nome
        if artefatos_analisaveis.get(
            "pipeline"
        ) is True
        else None,

    "csproj":
        csproj_nome
        if artefatos_analisaveis.get(
            "csproj"
        ) is True
        else None,

    "renovate_json":
        renovate_json_nome
        if artefatos_analisaveis.get(
            "renovate_json"
        ) is True
        else None,

    "renovate_setup":
        renovate_setup_nome
        if artefatos_analisaveis.get(
            "renovate_setup"
        ) is True
        else None,

    "dockerfile":
        dockerfile_nome
        if artefatos_analisaveis.get(
            "dockerfile"
        ) is True
        else None,

    "dockerfile_postgres":
        dockerfile_postgres_nome
        if artefatos_analisaveis.get(
            "dockerfile_postgres"
        ) is True
        else None,

    "docker_compose":
        docker_compose_nome
        if artefatos_analisaveis.get(
            "docker_compose"
        ) is True
        else None,

    "program_cs":
        program_cs_nome
        if artefatos_analisaveis.get(
            "program_cs"
        ) is True
        else None,

    "appsettings":
        appsettings_nome
        if artefatos_analisaveis.get(
            "appsettings"
        ) is True
        else None,

    "editorconfig":
        editorconfig_nome
        if artefatos_analisaveis.get(
            "editorconfig"
        ) is True
        else None,

    "env_example":
        env_example_nome
        if artefatos_analisaveis.get(
            "env_example"
        ) is True
        else None,

    "env_io_example":
        env_io_example_nome
        if artefatos_analisaveis.get(
            "env_io_example"
        ) is True
        else None,

    "scripts":
        scripts_analisados_atual
}


# ---------------------------------------------------------
# 12. Estado dos artefatos
# ---------------------------------------------------------

estado_artefatos_atual = copy.deepcopy(
    artefatos_analisaveis
)


# ---------------------------------------------------------
# 13. Caracterização tecnológica
# ---------------------------------------------------------

caracterizacao_tecnologica_atual = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia.get(
            "database_technology"
        ),

    "database_version":
        tecnologia.get(
            "database_version"
        ),

    "database_version_source":
        tecnologia.get(
            "database_version_source"
        ),

    "postgresql_evidenced":
        evidencias.get(
            "PostgreSQL evidenciado"
        ),

    "postgresql_dockerfile_present":
        evidencias.get(
            "Dockerfile PostgreSQL presente"
        ),

    "postgresql_dotnet_provider":
        evidencias.get(
            "Provider PostgreSQL (.NET)"
        ),

    "postgresql_version_identified":
        evidencias.get(
            "Versão PostgreSQL identificada"
        )
}


# ---------------------------------------------------------
# 14. Registro consolidado da versão atual
# ---------------------------------------------------------

registro_atual = {

    "versao":
        versao_atual,

    "snapshot":
        snapshot_atual,

    "artefatos_analisados":
        copy.deepcopy(
            artefatos_analisados_atual
        ),

    "estado_artefatos":
        copy.deepcopy(
            estado_artefatos_atual
        ),

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "caracterizacao_tecnologica":
        copy.deepcopy(
            caracterizacao_tecnologica_atual
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_atual,

    "metadados_interpretacao_ia":
        copy.deepcopy(
            metadados_ia_atual
        )
}


# ---------------------------------------------------------
# 15. Verifica se a versão já estava armazenada
# ---------------------------------------------------------

versao_ja_existia = (
    versao_atual
    in resultados_versoes
)


# ---------------------------------------------------------
# 16. Armazena a versão atual
# ---------------------------------------------------------

resultados_versoes[
    versao_atual
] = copy.deepcopy(
    registro_atual
)


# ---------------------------------------------------------
# 17. Resultado
# ---------------------------------------------------------

if versao_ja_existia:

    print(
        f"✓ Resultados da {versao_atual} atualizados "
        "para a análise longitudinal."
    )

else:

    print(
        f"✓ Resultados da {versao_atual} armazenados "
        "para a análise longitudinal."
    )


registro_salvo = resultados_versoes[
    versao_atual
]


print(
    "✓ Snapshot:",
    registro_salvo[
        "snapshot"
    ]
)


print(
    "✓ Nível:",
    registro_salvo[
        "classificacao"
    ].get(
        "nivel"
    )
)


print(
    "✓ Classificação:",
    registro_salvo[
        "classificacao"
    ].get(
        "classificacao"
    )
)


print(
    "✓ Banco de dados:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_technology"
    )
)


print(
    "✓ Versão configurada do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version"
    )
)


print(
    "✓ Fonte da versão do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version_source"
    )
)


print(
    "✓ Dockerfile PostgreSQL:",
    (
        "analisado"
        if registro_salvo[
            "estado_artefatos"
        ].get(
            "dockerfile_postgres"
        ) is True
        else "não analisado"
    )
)


print(
    "✓ Interpretação assistida por IA:",
    (
        "disponível"
        if registro_salvo[
            "interpretacao_ia"
        ]
        else "não disponível"
    )
)


print(
    "✓ Versões atualmente armazenadas:",
    ", ".join(
        sorted(
            resultados_versoes.keys()
        )
    )
)

✓ Resultados da V1 armazenados para a análise longitudinal.
✓ Snapshot: web-1.25.10-1
✓ Nível: 2
✓ Classificação: Inicial / Adhoc
✓ Banco de dados: PostgreSQL
✓ Versão configurada do banco: 17
✓ Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)
✓ Dockerfile PostgreSQL: analisado
✓ Interpretação assistida por IA: disponível
✓ Versões atualmente armazenadas: V1

## 4. V2 — Pipeline Technical Analysis

### 4.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.4-1`**.

### 4.2 Análise dos Artefatos

In [78]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None


print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [79]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar "
            "o arquivo .csproj:"
        )

        print(
            erro
        )


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = (
            match_sdk.group(1)
        )


    # Pipeline versionado
    evidencias[
        "GitLab CI como código"
    ] = True


    # Restore
    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias[
        "Espera pelo Quality Gate"
    ] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias[
        "Quality Gate bloqueante"
    ] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if dockerfile_postgres:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo
        in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome
        in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# appsettings
if appsettings:

    fontes_banco.append(
        appsettings
    )


# Program.cs
if program_cs:

    fontes_banco.append(
        program_cs
    )


# .csproj
if csproj:

    fontes_banco.append(
        csproj
    )


# Docker Compose
if docker_compose:

    fontes_banco.append(
        docker_compose
    )


# Dockerfile.postgres
if dockerfile_postgres:

    fontes_banco.append(
        dockerfile_postgres
    )


# Dockerfile da aplicação
if dockerfile:

    fontes_banco.append(
        dockerfile
    )


# Scripts
if conteudo_total_scripts:

    fontes_banco.append(
        conteudo_total_scripts
    )


# ---------------------------------------------------------
# 13.1 Consolidação das fontes de banco
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for conteudo
        in fontes_banco
    )


    # -----------------------------------------------------
    # Identificação do PostgreSQL
    # -----------------------------------------------------

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem(
        conteudo_banco,
        "postgresql",
        "postgres",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    conteudo_dotnet_banco = "\n".join(
        [
            program_cs or "",
            csproj or ""
        ]
    )

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = contem(
        conteudo_dotnet_banco,
        "npgsql",
        "usenpgsql",
        "addnpgsql"
    )


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if (
        evidencias[
            "PostgreSQL evidenciado"
        ] is True
    ):

        tecnologia_banco = (
            "PostgreSQL"
        )

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Exemplos reconhecidos:
    #
    # FROM postgres:16
    # FROM postgres:16.4
    # FROM postgres:16-alpine
    # image: postgres:16
    # image: postgres:16.4-alpine
    #
    # A versão encontrada representa a versão configurada
    # no artefato analisado e não comprova a versão
    # efetivamente executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.2 Prioridade 1 — Dockerfile.postgres
    # -----------------------------------------------------

    if dockerfile_postgres:

        match_postgres_dockerfile_postgres = (
            buscar_regex(
                dockerfile_postgres,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile_postgres:

            versao_banco = (
                match_postgres_dockerfile_postgres.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile.postgres"
            )


    # -----------------------------------------------------
    # 13.3 Prioridade 2 — Docker Compose
    # -----------------------------------------------------

    if (
        versao_banco is None
        and docker_compose
    ):

        match_postgres_compose = (
            buscar_regex(
                docker_compose,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_compose:

            versao_banco = (
                match_postgres_compose.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.4 Prioridade 3 — Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and dockerfile
    ):

        match_postgres_dockerfile = (
            buscar_regex(
                dockerfile,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile:

            versao_banco = (
                match_postgres_dockerfile.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile"
            )


    # -----------------------------------------------------
    # 13.5 Prioridade 4 — Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        match_postgres_script = (
            buscar_regex(
                conteudo_total_scripts,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_script:

            versao_banco = (
                match_postgres_script.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia_banco,

    "database_version":
        versao_banco,

    "database_version_source":
        fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None
Banco de dados: None
Versão configurada do banco: None
Fonte da versão do banco: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Dockerfile PostgreSQL presente
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local
? PostgreSQL evidenciado
? Provider PostgreSQL (.NET)
? Versão PostgreSQL identificada

In [80]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (5)
Saving .env.example to .env (5).example
Saving appsettings.json to appsettings (5).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (5).csproj
Saving docker-compose.yaml to docker-compose (5).yaml
Saving Dockerfile to Dockerfile (5)
Saving Dockerfile.postgres to Dockerfile (5).postgres
Saving env.io.example to env.io (1).example
Saving gitlab-ci.yml to gitlab-ci (5).yml
Saving init.sql to init (5).sql
Saving Program.cs to Program (5).cs
Saving renovate.json to renovate (3).json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP (3).md
Saving seed.sql to seed (3).sql
Saving start-db.ps1 to start-db (5).ps1

✓ 15 arquivo(s) carregado(s):

  ✓ .editorconfig (5)
  ✓ .env (5).example
  ✓ Boilerplate4Dev (5).csproj
  ✓ Dockerfile (5)
  ✓ Dockerfile (5).postgres
  ✓ Program (5).cs
  ✓ RENOVATE_SETUP (3).md
  ✓ appsettings (5).json
  ✓ docker-compose (5).yaml
  ✓ env.io (1).example
  ✓ gitlab-ci (5).yml
  ✓ init (5).sql
  ✓ renovate (3).json
  ✓ seed (3).sql
  ✓ start-db (5).ps1

In [81]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:

    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None

dockerfile_valido = None
dockerfile_postgres_valido = None
docker_compose_valido = None

program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):

    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):

    nome = nome_base(
        nome
    )

    # Remove sufixos adicionados pelo Colab:
    #
    # arquivo (1).json      -> arquivo.json
    # Dockerfile (2)        -> Dockerfile
    # Dockerfile (1).postgres -> Dockerfile.postgres
    #
    # O primeiro padrão trata o sufixo antes da extensão.
    # O segundo trata o sufixo no final do nome.

    nome = re.sub(
        r"\s*\(\d+\)(?=\.)",
        "",
        nome
    )

    nome = re.sub(
        r"\s*\(\d+\)$",
        "",
        nome
    )

    return (
        nome
        .lower()
        .strip()
    )


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):

    if not candidatos:

        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _
                in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(
    conteudo
):

    if conteudo is None:

        return None

    if isinstance(
        conteudo,
        bytes
    ):

        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []

candidatos_dockerfile = []
candidatos_dockerfile_postgres = []
candidatos_docker_compose = []

candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []


extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # -----------------------------------------------------
    # GitLab CI
    # -----------------------------------------------------

    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Projeto .NET
    # -----------------------------------------------------

    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Renovate
    # -----------------------------------------------------

    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile.postgres
    #
    # Deve ser identificado ANTES do Dockerfile genérico.
    # -----------------------------------------------------

    if normalizado == "dockerfile.postgres":

        candidatos_dockerfile_postgres.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile da aplicação
    # -----------------------------------------------------

    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Docker Compose
    # -----------------------------------------------------

    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Program.cs
    # -----------------------------------------------------

    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # appsettings.json
    # -----------------------------------------------------

    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .editorconfig
    # -----------------------------------------------------

    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.io.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Scripts
    # -----------------------------------------------------

    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile da aplicação"
)

dockerfile_postgres, dockerfile_postgres_nome = (
    selecionar_unico(
        candidatos_dockerfile_postgres,
        "Dockerfile.postgres"
    )
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

dockerfile_postgres = como_texto(
    dockerfile_postgres
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):

    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):

            continue

        if "=" not in linha:

            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # Continua utilizável para extração textual.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


def validar_dockerfile(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    possui_from = bool(
        re.search(
            r"^\s*FROM\s+\S+",
            conteudo,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    if possui_from:

        validacao_artefatos.append(
            f"✓ {descricao} estruturalmente válido "
            "(instrução FROM identificada)."
        )

        return True

    validacao_artefatos.append(
        f"✗ {descricao} sem instrução FROM identificada."
    )

    return False


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

dockerfile_valido = validar_dockerfile(
    dockerfile,
    "Dockerfile"
)


# ---------------------------------------------------------
# 6. Dockerfile.postgres
# ---------------------------------------------------------

dockerfile_postgres_valido = validar_dockerfile(
    dockerfile_postgres,
    "Dockerfile.postgres"
)


# ---------------------------------------------------------
# 7. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 8. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador
            in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 9. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 10. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 11. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# 13. Artefatos habilitados para análise
#
# Somente artefatos explicitamente validados podem ser
# utilizados pela etapa de extração determinística.
# ---------------------------------------------------------

artefatos_analisaveis = {

    "pipeline":
        pipeline_valido is True,

    "csproj":
        csproj_valido is True,

    "renovate_json":
        renovate_json_valido is True,

    "renovate_setup":
        renovate_setup_valido is True,

    "dockerfile":
        dockerfile_valido is True,

    "dockerfile_postgres":
        dockerfile_postgres_valido is True,

    "docker_compose":
        docker_compose_valido is True,

    "program_cs":
        program_cs_valido is True,

    "appsettings":
        appsettings_valido is True,

    "editorconfig":
        editorconfig_valido is True,

    "env_example":
        env_example_valido is True,

    "env_io_example":
        env_io_example_valido is True
}


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

artefatos_analisaveis[
    "scripts"
] = any(
    estado is True
    for estado
    in scripts_validos.values()
)


# ---------------------------------------------------------
# Mantém apenas scripts validados para a etapa de análise
# ---------------------------------------------------------

scripts_analisaveis = {

    nome:
        conteudo

    for nome, conteudo
    in scripts.items()

    if scripts_validos.get(
        nome
    ) is True
}


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):

    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Dockerfile.postgres",
    dockerfile_postgres_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):

        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {

    "Pipeline":
        pipeline_valido,

    ".csproj":
        csproj_valido,

    "renovate.json":
        renovate_json_valido,

    "RENOVATE_SETUP.md":
        renovate_setup_valido,

    "Dockerfile":
        dockerfile_valido,

    "Dockerfile.postgres":
        dockerfile_postgres_valido,

    "Docker Compose":
        docker_compose_valido,

    "Program.cs":
        program_cs_valido,

    "appsettings.json":
        appsettings_valido,

    ".editorconfig":
        editorconfig_valido,

    ".env.example":
        env_example_valido,

    ".env.io.example":
        env_io_example_valido
}


for artefato, estado in (
    estados_validacao.items()
):

    if estado is True:

        simbolo = "✓"

    elif estado is False:

        simbolo = "✗"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

if scripts_validos:

    print(
        "\nESTADO DOS SCRIPTS\n"
    )

    for nome in sorted(
        scripts_validos
    ):

        estado = scripts_validos[
            nome
        ]

        simbolo = (
            "✓"
            if estado is True
            else "✗"
        )

        print(
            f"{simbolo} {nome}"
        )


# ---------------------------------------------------------
# Artefatos disponíveis para extração
# ---------------------------------------------------------

print(
    "\nARTEFATOS HABILITADOS PARA EXTRAÇÃO\n"
)

for artefato, habilitado in (
    artefatos_analisaveis.items()
):

    simbolo = (
        "✓"
        if habilitado
        else "—"
    )

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (5).yml
✓ .csproj: Boilerplate4Dev (5).csproj
✓ renovate.json: renovate (3).json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP (3).md
✓ Dockerfile: Dockerfile (5)
✓ Dockerfile.postgres: Dockerfile (5).postgres
✓ Docker Compose: docker-compose (5).yaml
✓ Program.cs: Program (5).cs
✓ appsettings.json: appsettings (5).json
✓ .editorconfig: .editorconfig (5)
✓ .env.example: .env (5).example
✓ .env.io.example: env.io (1).example
✓ Scripts: 3 arquivo(s)
    - init (5).sql
    - seed (3).sql
    - start-db (5).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Dockerfile.postgres estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (5).sql: script SQL legível e não vazio.
✓ seed (3).sql: script SQL legível e não vazio.
✓ start-db (5).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Dockerfile.postgres
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

ESTADO DOS SCRIPTS

✓ init (5).sql
✓ seed (3).sql
✓ start-db (5).ps1

ARTEFATOS HABILITADOS PARA EXTRAÇÃO

✓ pipeline
✓ csproj
✓ renovate_json
✓ renovate_setup
✓ dockerfile
✓ dockerfile_postgres
✓ docker_compose
✓ program_cs
✓ appsettings
✓ editorconfig
✓ env_example
✓ env_io_example
✓ scripts

In [82]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# Funções auxiliares específicas desta etapa
# ---------------------------------------------------------

def analisavel(nome_artefato):
    """
    Retorna True somente quando o artefato foi previamente
    identificado e validado pela etapa anterior.
    """
    return (
        isinstance(artefatos_analisaveis, dict)
        and artefatos_analisaveis.get(nome_artefato) is True
    )


def texto_lower(conteudo):
    if conteudo is None:
        return ""
    return str(conteudo).lower()


def contem_todos(conteudo, *termos):
    """
    Retorna True somente se TODOS os termos forem encontrados.
    Útil quando a simples presença de qualquer termo poderia
    produzir falso positivo.
    """
    texto = texto_lower(conteudo)

    return all(
        str(termo).lower() in texto
        for termo in termos
    )


def contem_algum(conteudo, *termos):
    """
    Retorna True se pelo menos um dos termos for encontrado.
    """
    texto = texto_lower(conteudo)

    return any(
        str(termo).lower() in texto
        for termo in termos
    )


def texto_job_gitlab(job):
    """
    Converte o conteúdo relevante de um job GitLab CI em texto
    para permitir análise determinística do próprio job.
    """

    if not isinstance(job, dict):
        return ""

    partes = []

    for chave in (
        "image",
        "stage",
        "before_script",
        "script",
        "after_script",
        "rules",
        "only",
        "except"
    ):

        valor = job.get(chave)

        if valor is None:
            continue

        if isinstance(valor, list):

            partes.extend(
                str(item)
                for item in valor
            )

        elif isinstance(valor, dict):

            partes.append(
                json.dumps(
                    valor,
                    ensure_ascii=False
                )
            )

        else:

            partes.append(
                str(valor)
            )

    return "\n".join(partes)


def localizar_jobs_sonar(pipeline_obj):
    """
    Localiza jobs que apresentam evidência de execução do SonarQube.
    """

    if not isinstance(pipeline_obj, dict):
        return []

    chaves_reservadas = {
        "image",
        "services",
        "variables",
        "stages",
        "workflow",
        "default",
        "include",
        "cache",
        "before_script",
        "after_script"
    }

    jobs = []

    for nome_job, configuracao in pipeline_obj.items():

        if nome_job in chaves_reservadas:
            continue

        if not isinstance(configuracao, dict):
            continue

        texto_job = texto_job_gitlab(
            configuracao
        )

        if contem_algum(
            texto_job,
            "dotnet-sonarscanner",
            "sonarscanner",
            "sonar.host.url",
            "sonar_token",
            "sonar.qualitygate.wait"
        ):

            jobs.append(
                (
                    nome_job,
                    configuracao,
                    texto_job
                )
            )

    return jobs


def extrair_variavel_env(
    conteudo,
    nomes_variaveis
):
    """
    Procura uma variável em arquivo .env no formato CHAVE=VALOR.
    """

    if not conteudo:
        return None, None

    nomes_normalizados = {
        nome.upper()
        for nome in nomes_variaveis
    }

    for linha in conteudo.splitlines():

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
            or "=" not in linha
        ):
            continue

        chave, valor = linha.split(
            "=",
            1
        )

        chave = chave.strip().upper()

        valor = valor.strip().strip(
            "\"'"
        )

        if chave in nomes_normalizados:

            return chave, valor

    return None, None


def extrair_versao_postgres_imagem(
    conteudo
):
    """
    Extrai versão de referências como:

    postgres:16
    postgres:16.4
    postgres:16-alpine
    postgresql:16
    """

    if not conteudo:
        return None

    match = re.search(
        r"\bpostgres(?:ql)?\s*:\s*"
        r"([0-9]+(?:\.[0-9]+){0,2})"
        r"(?:[-._a-zA-Z0-9]*)?",
        str(conteudo),
        flags=re.IGNORECASE
    )

    if match:
        return match.group(1)

    return None


def extrair_versao_postgres_env(
    conteudo
):
    """
    Procura versão PostgreSQL em variáveis de ambiente.
    """

    if not conteudo:
        return None, None

    # Variáveis explicitamente destinadas à versão
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_VERSION",
            "POSTGRESQL_VERSION",
            "PG_VERSION"
        }
    )

    if valor:

        match = re.search(
            r"([0-9]+(?:\.[0-9]+){0,2})",
            valor
        )

        if match:

            return (
                match.group(1),
                chave
            )

    # Variáveis que podem armazenar a imagem completa
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_IMAGE",
            "POSTGRESQL_IMAGE",
            "DATABASE_IMAGE",
            "DB_IMAGE"
        }
    )

    if valor:

        versao = extrair_versao_postgres_imagem(
            valor
        )

        if versao:

            return (
                versao,
                chave
            )

    return None, None


def extrair_versao_postgres_dockerfile(
    conteudo
):
    """
    Extrai a versão configurada do PostgreSQL em Dockerfiles.

    Reconhece, por exemplo:

    FROM postgres:16
    FROM postgres:16.4-alpine

    ARG POSTGRES_VERSION=16
    ENV POSTGRES_VERSION=16
    FROM postgres:${POSTGRES_VERSION}

    A versão identificada é configuracional e não comprova
    a versão efetivamente executada em produção.
    """

    if not conteudo:

        return None, None

    # -----------------------------------------------------
    # 1. Referência literal da imagem
    # -----------------------------------------------------

    versao_literal = extrair_versao_postgres_imagem(
        conteudo
    )

    if versao_literal:

        return (
            versao_literal,
            "imagem PostgreSQL literal"
        )


    # -----------------------------------------------------
    # 2. ARG/ENV com variável de versão
    # -----------------------------------------------------

    nomes_variaveis = (
        "POSTGRES_VERSION",
        "POSTGRESQL_VERSION",
        "PG_VERSION"
    )

    for nome_variavel in nomes_variaveis:

        padrao_variavel = (
            rf"^\s*(?:ARG|ENV)\s+"
            rf"{re.escape(nome_variavel)}"
            rf"\s*(?:=|\s)\s*"
            rf"[\"']?"
            rf"([0-9]+(?:\.[0-9]+){{0,2}})"
        )

        match_variavel = re.search(
            padrao_variavel,
            str(conteudo),
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )

        if not match_variavel:

            continue

        # Exige também uma referência à imagem PostgreSQL,
        # evitando interpretar uma variável isolada como prova
        # de que o Dockerfile usa PostgreSQL.
        if contem_algum(
            conteudo,
            "from postgres:",
            "from postgresql:"
        ):

            return (
                match_variavel.group(1),
                nome_variavel
            )

    return None, None


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if analisavel("csproj"):

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        # Em princípio não deve ocorrer, pois o arquivo já foi
        # validado na etapa anterior.
        print(
            "⚠ Inconsistência: .csproj havia sido validado, "
            "mas não pôde ser interpretado nesta etapa."
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if analisavel("pipeline"):

    # -----------------------------------------------------
    # SDK .NET utilizado no pipeline
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem_algum(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem_algum(
        pipeline,
        "dotnet build"
    )

    possui_release = contem_algum(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem_algum(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    evidencias[
        "Espera pelo Quality Gate"
    ] = contem_algum(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    #
    # Avalia allow_failure no job do SonarQube, e não em
    # qualquer outro job do pipeline.
    # -----------------------------------------------------

    quality_gate_bloqueante = False

    try:

        pipeline_obj = yaml.safe_load(
            pipeline
        )

        jobs_sonar = localizar_jobs_sonar(
            pipeline_obj
        )

        jobs_qg = []

        for (
            nome_job,
            configuracao_job,
            texto_job
        ) in jobs_sonar:

            if contem_algum(
                texto_job,
                "sonar.qualitygate.wait=true"
            ):

                jobs_qg.append(
                    (
                        nome_job,
                        configuracao_job
                    )
                )

        if jobs_qg:

            # Considera bloqueante se existir job com espera de
            # Quality Gate e allow_failure diferente de True.
            quality_gate_bloqueante = any(
                configuracao.get(
                    "allow_failure"
                ) is not True
                for _, configuracao in jobs_qg
            )

        else:

            quality_gate_bloqueante = False

    except Exception:

        # Não utiliza inferência textual genérica como substituto,
        # pois isso poderia associar allow_failure ao job errado.
        quality_gate_bloqueante = False


    evidencias[
        "Quality Gate bloqueante"
    ] = (
        evidencias[
            "Espera pelo Quality Gate"
        ]
        and quality_gate_bloqueante
    )


    # -----------------------------------------------------
    # Cache
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem_algum(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem_algum(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Merge Request
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem_algum(
        pipeline,
        "merge_request_event"
    )


    # -----------------------------------------------------
    # Branch main
    # -----------------------------------------------------

    possui_variavel_branch = contem_algum(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # -----------------------------------------------------
    # Testes automatizados
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem_algum(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy automatizado
    #
    # Dockerfile / Docker Compose de configuração não são
    # considerados prova de deploy automatizado.
    # Aqui são procurados comandos dentro do pipeline.
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem_algum(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção automática
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem_algum(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback automatizado
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem_algum(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if analisavel("renovate_json"):

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # -------------------------------------------------
        # Vulnerability Alerts
        # -------------------------------------------------

        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem_algum(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # -------------------------------------------------
        # Lock File Maintenance
        # -------------------------------------------------

        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem_algum(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        # Em princípio não deverá ocorrer porque o arquivo
        # somente chega aqui se foi validado.
        evidencias[
            "Renovate configurado"
        ] = None

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = None

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = None

        evidencias[
            "Vulnerability Alerts"
        ] = None

        evidencias[
            "Lock File Maintenance"
        ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if analisavel("pipeline"):

    possui_imagem_renovate = contem_algum(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem_algum(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    if evidencias[
        "Job Renovate no pipeline"
    ]:

        evidencias[
            "Regra schedule para Renovate"
        ] = contem_algum(
            pipeline,
            "schedule"
        )

        evidencias[
            "Execução manual do Renovate"
        ] = contem_algum(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )

    else:

        evidencias[
            "Regra schedule para Renovate"
        ] = False

        evidencias[
            "Execução manual do Renovate"
        ] = False

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva.
# Logs, branch Renovate ou MR criado pelo bot seriam
# necessários para estabelecer execução efetiva.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if analisavel("dockerfile"):

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if analisavel("dockerfile_postgres"):

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if analisavel("docker_compose"):

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem_algum(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem_algum(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem_algum(
            docker_compose,
            "external:"
        )
        and contem_algum(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem_algum(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if analisavel("program_cs"):

    evidencias[
        "Sentry integrado em runtime"
    ] = contem_algum(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )


    # -----------------------------------------------------
    # Health Check de banco
    #
    # Exige simultaneamente:
    # - evidência de infraestrutura de Health Check
    # - evidência de integração PostgreSQL/Npgsql
    # -----------------------------------------------------

    possui_healthcheck = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks",
        "healthcheck"
    )

    possui_npgsql_healthcheck = contem_algum(
        program_cs,
        "addnpgsql",
        ".addnpgsql",
        "npgsql"
    )

    evidencias[
        "Health Check de banco"
    ] = (
        possui_healthcheck
        and possui_npgsql_healthcheck
    )


    # -----------------------------------------------------
    # Health Check de API
    # -----------------------------------------------------

    evidencias[
        "Health Check de API"
    ] = (
        contem_algum(
            program_cs,
            "addurlgroup",
            "httpclient"
        )
        and contem_algum(
            program_cs,
            "health"
        )
    )


    # -----------------------------------------------------
    # Logging
    # -----------------------------------------------------

    evidencias[
        "Console Logging"
    ] = contem_algum(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if analisavel("appsettings"):

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem_algum(
        appsettings,
        "sentry",
        "\"dsn\""
    )

    evidencias[
        "Matomo configurado"
    ] = contem_algum(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem_algum(
        appsettings,
        "connectionstrings",
        "environment",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if analisavel("editorconfig"):

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = (
        contem_algum(
            editorconfig,
            "dotnet_diagnostic"
        )
        and contem_algum(
            editorconfig,
            "severity"
        )
    )


    # Não utiliza mais o termo isolado "s",
    # que produzia falsos positivos.
    evidencias[
        "Regras de segurança declaradas"
    ] = contem_algum(
        editorconfig,
        "security",
        "securityrule",
        "securityhotspot",
        "ca2100",
        "ca2119",
        "ca2122",
        "ca2135",
        "ca2300",
        "ca2301",
        "ca2302",
        "ca2305",
        "ca2310",
        "ca2311",
        "ca2312",
        "ca2321",
        "ca2322",
        "ca2326",
        "ca2327",
        "ca2328",
        "ca2329",
        "ca2330",
        "ca3001",
        "ca3002",
        "ca3003",
        "ca3004",
        "ca3005",
        "ca3006",
        "ca3007",
        "ca3008",
        "ca3009",
        "ca3010",
        "ca3011",
        "ca3012",
        "ca3061",
        "ca3075",
        "ca3076",
        "ca3077"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if analisavel("env_example"):

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem_algum(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host",
        "version"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if analisavel("env_io_example"):

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem_algum(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project",
        "host"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if analisavel("scripts"):

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts_analisaveis.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts_analisaveis.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem_algum(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem_algum(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem_algum(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )


    # Atenção: automação de ambiente local não equivale
    # a deploy automatizado da aplicação.
    evidencias[
        "Automação de ambiente local"
    ] = contem_algum(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# ---------------------------------------------------------
# Somente artefatos previamente validados participam da
# identificação da tecnologia de banco.
# ---------------------------------------------------------

if analisavel("appsettings"):

    fontes_banco.append(
        (
            "appsettings.json",
            appsettings
        )
    )


if analisavel("program_cs"):

    fontes_banco.append(
        (
            "Program.cs",
            program_cs
        )
    )


if analisavel("csproj"):

    fontes_banco.append(
        (
            ".csproj",
            csproj
        )
    )


if analisavel("dockerfile_postgres"):

    fontes_banco.append(
        (
            "Dockerfile.postgres",
            dockerfile_postgres
        )
    )


if analisavel("docker_compose"):

    fontes_banco.append(
        (
            "Docker Compose",
            docker_compose
        )
    )


if analisavel("dockerfile"):

    fontes_banco.append(
        (
            "Dockerfile",
            dockerfile
        )
    )


if analisavel("env_example"):

    fontes_banco.append(
        (
            ".env.example",
            env_example
        )
    )


if analisavel("env_io_example"):

    fontes_banco.append(
        (
            ".env.io.example",
            env_io_example
        )
    )


if conteudo_total_scripts:

    fontes_banco.append(
        (
            "Scripts",
            conteudo_total_scripts
        )
    )


# ---------------------------------------------------------
# Identificação do PostgreSQL
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for _, conteudo in fontes_banco
    )

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem_algum(
        conteudo_banco,
        "postgresql",
        "postgres:",
        "postgres_",
        "postgres-",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    fontes_dotnet = []

    if analisavel("program_cs"):

        fontes_dotnet.append(
            program_cs
        )

    if analisavel("csproj"):

        fontes_dotnet.append(
            csproj
        )

    if fontes_dotnet:

        conteudo_dotnet_banco = "\n".join(
            fontes_dotnet
        )

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = contem_algum(
            conteudo_dotnet_banco,
            "npgsql",
            "usenpgsql",
            "addnpgsql"
        )

    else:

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = None


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if evidencias[
        "PostgreSQL evidenciado"
    ] is True:

        tecnologia_banco = "PostgreSQL"

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Ordem de prioridade:
    # 1. Dockerfile.postgres
    # 2. Docker Compose com versão literal
    # 3. .env.example
    # 4. .env.io.example
    # 5. Dockerfile da aplicação
    # 6. Scripts
    #
    # A prioridade do Dockerfile.postgres decorre de ele ser
    # um artefato especificamente destinado à configuração
    # da imagem PostgreSQL.
    #
    # A versão representa evidência configuracional.
    # Não comprova a versão executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.1 Dockerfile.postgres
    # -----------------------------------------------------

    if analisavel("dockerfile_postgres"):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile_postgres
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile.postgres "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile.postgres"
                )


    # -----------------------------------------------------
    # 13.2 Docker Compose — versão literal
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("docker_compose")
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                docker_compose
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.3 .env.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.4 .env.io.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_io_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_io_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.io.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.5 Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("dockerfile")
    ):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile"
                )


    # -----------------------------------------------------
    # 13.6 Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                conteudo_total_scripts
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline,
    "database_technology": tecnologia_banco,
    "database_version": versao_banco,
    "database_version_source": fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
#
# ✓ = evidência identificada
# — = artefato válido analisado, evidência não identificada
# ? = artefato ausente, inválido ou execução não verificável
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0
Banco de dados: PostgreSQL
Versão configurada do banco: 18
Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
✓ Job Renovate no pipeline
✓ Regra schedule para Renovate
✓ Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Dockerfile PostgreSQL presente
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
✓ Health Check de banco
✓ Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ Parametrização de ambientes
✓ .env.io.example presente
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local
✓ PostgreSQL evidenciado
✓ Provider PostgreSQL (.NET)
✓ Versão PostgreSQL identificada

In [83]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [84]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
#
# Esta etapa não altera nem reclassifica as evidências.
# Ela apenas organiza os resultados determinísticos em um
# pacote estruturado para interpretação qualitativa pela IA.
# ---------------------------------------------------------


# ---------------------------------------------------------
# Verificações preliminares
# ---------------------------------------------------------

if not evidencias:

    raise ValueError(
        "Nenhuma evidência foi extraída."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


if not isinstance(
    artefatos_analisaveis,
    dict
):

    raise ValueError(
        "A estrutura de artefatos analisáveis não está disponível. "
        "Execute primeiro a etapa de identificação e validação."
    )


# ---------------------------------------------------------
# Função auxiliar
# ---------------------------------------------------------

def nome_se_analisavel(
    chave,
    nome
):
    """
    Retorna o nome do artefato somente se ele tiver sido
    previamente validado e habilitado para análise.

    Caso contrário, retorna None.
    """

    if artefatos_analisaveis.get(
        chave
    ) is True:

        return nome

    return None


# ---------------------------------------------------------
# Scripts efetivamente utilizados na análise
# ---------------------------------------------------------

scripts_analisados = sorted(
    scripts_analisaveis.keys()
) if isinstance(
    scripts_analisaveis,
    dict
) else []


# ---------------------------------------------------------
# Estado dos artefatos
#
# Permite que a interpretação assistida por IA diferencie:
#
# True  = artefato validado e analisado
# False = artefato encontrado, mas não habilitado
# ---------------------------------------------------------

estado_artefatos = {
    chave: bool(valor)
    for chave, valor in artefatos_analisaveis.items()
}


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    # -----------------------------------------------------
    # 1. Metadados da análise
    # -----------------------------------------------------

    "metadados_analise": {

        "tipo_analise":
            "extração determinística de evidências técnicas",

        "objetivo":
            (
                "Preparar evidências técnicas para interpretação "
                "qualitativa assistida por IA, sem alterar a "
                "classificação determinística."
            ),

        "semantica_tri_state": {

            "true":
                "Evidência diretamente identificada no artefato válido.",

            "false":
                (
                    "Artefato válido analisado, mas a evidência "
                    "não foi identificada."
                ),

            "null":
                (
                    "Evidência indeterminada devido à ausência, "
                    "invalidade ou insuficiência do artefato."
                )
        }
    },


    # -----------------------------------------------------
    # 2. Artefatos analisados
    # -----------------------------------------------------

    "artefatos_analisados": {

        "pipeline":
            nome_se_analisavel(
                "pipeline",
                pipeline_nome
            ),

        "csproj":
            nome_se_analisavel(
                "csproj",
                csproj_nome
            ),

        "renovate_json":
            nome_se_analisavel(
                "renovate_json",
                renovate_json_nome
            ),

        "renovate_setup":
            nome_se_analisavel(
                "renovate_setup",
                renovate_setup_nome
            ),

        "dockerfile":
            nome_se_analisavel(
                "dockerfile",
                dockerfile_nome
            ),

        "dockerfile_postgres":
            nome_se_analisavel(
                "dockerfile_postgres",
                dockerfile_postgres_nome
            ),

        "docker_compose":
            nome_se_analisavel(
                "docker_compose",
                docker_compose_nome
            ),

        "program_cs":
            nome_se_analisavel(
                "program_cs",
                program_cs_nome
            ),

        "appsettings":
            nome_se_analisavel(
                "appsettings",
                appsettings_nome
            ),

        "editorconfig":
            nome_se_analisavel(
                "editorconfig",
                editorconfig_nome
            ),

        "env_example":
            nome_se_analisavel(
                "env_example",
                env_example_nome
            ),

        "env_io_example":
            nome_se_analisavel(
                "env_io_example",
                env_io_example_nome
            ),

        "scripts":
            scripts_analisados
    },


    # -----------------------------------------------------
    # 3. Estado dos artefatos
    # -----------------------------------------------------

    "estado_artefatos": {

        "pipeline":
            estado_artefatos.get(
                "pipeline",
                False
            ),

        "csproj":
            estado_artefatos.get(
                "csproj",
                False
            ),

        "renovate_json":
            estado_artefatos.get(
                "renovate_json",
                False
            ),

        "renovate_setup":
            estado_artefatos.get(
                "renovate_setup",
                False
            ),

        "dockerfile":
            estado_artefatos.get(
                "dockerfile",
                False
            ),

        "dockerfile_postgres":
            estado_artefatos.get(
                "dockerfile_postgres",
                False
            ),

        "docker_compose":
            estado_artefatos.get(
                "docker_compose",
                False
            ),

        "program_cs":
            estado_artefatos.get(
                "program_cs",
                False
            ),

        "appsettings":
            estado_artefatos.get(
                "appsettings",
                False
            ),

        "editorconfig":
            estado_artefatos.get(
                "editorconfig",
                False
            ),

        "env_example":
            estado_artefatos.get(
                "env_example",
                False
            ),

        "env_io_example":
            estado_artefatos.get(
                "env_io_example",
                False
            ),

        "scripts":
            estado_artefatos.get(
                "scripts",
                False
            )
    },


    # -----------------------------------------------------
    # 4. Caracterização tecnológica
    # -----------------------------------------------------

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline,

        "database_technology":
            tecnologia.get(
                "database_technology"
            ),

        "database_version":
            tecnologia.get(
                "database_version"
            ),

        "database_version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "postgresql_dockerfile_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "postgresql_dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "postgresql_version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            )
    },


    # -----------------------------------------------------
    # 5. Integração contínua
    # -----------------------------------------------------

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },


    # -----------------------------------------------------
    # 6. Gerenciamento de dependências
    # -----------------------------------------------------

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },


    # -----------------------------------------------------
    # 7. Containerização
    # -----------------------------------------------------

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },


    # -----------------------------------------------------
    # 8. Observabilidade
    # -----------------------------------------------------

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },


    # -----------------------------------------------------
    # 9. Configuração e ambiente
    # -----------------------------------------------------

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },


    # -----------------------------------------------------
    # 10. Banco de dados
    #
    # Separado da configuração de ambiente porque representa
    # caracterização tecnológica própria.
    # -----------------------------------------------------

    "banco_de_dados": {

        "technology":
            tecnologia.get(
                "database_technology"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            ),

        "configured_version":
            tecnologia.get(
                "database_version"
            ),

        "version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "interpretation_constraint":
            (
                "A versão identificada representa a versão "
                "configurada nos artefatos analisados e não "
                "comprova a versão efetivamente executada "
                "no ambiente de produção."
            )
    },


    # -----------------------------------------------------
    # 11. Qualidade estática
    # -----------------------------------------------------

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },


    # -----------------------------------------------------
    # 12. Automação local
    # -----------------------------------------------------

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            ),

        "interpretation_constraint":
            (
                "Automação de ambiente local não constitui "
                "evidência de deploy automatizado da aplicação."
            )
    },


    # -----------------------------------------------------
    # 13. Entrega e recuperação
    # -----------------------------------------------------

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },


    # -----------------------------------------------------
    # 14. Classificação determinística
    #
    # A IA recebe a classificação pronta e não deve
    # recalculá-la.
    # -----------------------------------------------------

    "classificacao_deterministica": {

        "scope":
            (
                "maturidade da automação do pipeline "
                "segundo rubrica específica do estudo"
            ),

        "nivel":
            resultado_maturidade.get(
                "nivel"
            ),

        "classificacao":
            resultado_maturidade.get(
                "classificacao"
            ),

        "motivo":
            resultado_maturidade.get(
                "motivo"
            ),

        "lacunas":
            resultado_maturidade.get(
                "lacunas",
                []
            ),

        "indeterminacoes":
            resultado_maturidade.get(
                "indeterminacoes",
                []
            ),

        "capacidades_adicionais":
            resultado_maturidade.get(
                "capacidades_adicionais",
                []
            )
    },


    # -----------------------------------------------------
    # 15. Restrições interpretativas
    # -----------------------------------------------------

    "restricoes_interpretativas": [

        (
            "A interpretação assistida por IA deve partir "
            "exclusivamente das evidências estruturadas fornecidas."
        ),

        (
            "A IA não deve transformar ausência de evidência "
            "em evidência de ausência quando o valor for null."
        ),

        (
            "Valores false representam ausência da característica "
            "somente no escopo do artefato válido analisado."
        ),

        (
            "A presença de Dockerfile, Dockerfile.postgres ou "
            "Docker Compose não constitui, por si só, evidência "
            "de deploy automatizado."
        ),

        (
            "A presença de renovate.json comprova configuração "
            "do Renovate, mas não comprova sua execução efetiva."
        ),

        (
            "Um job Renovate no pipeline comprova orquestração "
            "configurada, mas não comprova execução efetiva."
        ),

        (
            "A configuração de espera pelo Quality Gate não "
            "implica Quality Gate bloqueante quando o job permite "
            "falha."
        ),

        (
            "Scripts de inicialização ou automação local não "
            "devem ser interpretados como automação de deployment."
        ),

        (
            "A versão PostgreSQL identificada representa "
            "configuração observada nos artefatos e não a versão "
            "necessariamente executada em produção."
        ),

        (
            "Dockerfile.postgres evidencia configuração de uma "
            "imagem/container PostgreSQL quando validado, mas não "
            "comprova a versão efetivamente executada em produção "
            "nem automação de deployment."
        ),

        (
            "A classificação determinística representa somente "
            "a maturidade da automação observável no pipeline e "
            "não a maturidade DevOps global da organização."
        )
    ]
}


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)


print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "metadados_analise": {
    "tipo_analise": "extração determinística de evidências técnicas",
    "objetivo": "Preparar evidências técnicas para interpretação qualitativa assistida por IA, sem alterar a classificação determinística.",
    "semantica_tri_state": {
      "true": "Evidência diretamente identificada no artefato válido.",
      "false": "Artefato válido analisado, mas a evidência não foi identificada.",
      "null": "Evidência indeterminada devido à ausência, invalidade ou insuficiência do artefato."
    }
  },
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (5).yml",
    "csproj": "Boilerplate4Dev (5).csproj",
    "renovate_json": "renovate (3).json",
    "renovate_setup": "RENOVATE_SETUP (3).md",
    "dockerfile": "Dockerfile (5)",
    "dockerfile_postgres": "Dockerfile (5).postgres",
    "docker_compose": "docker-compose (5).yaml",
    "program_cs": "Program (5).cs",
    "appsettings": "appsettings (5).json",
    "editorconfig": ".editorconfig (5)",
    "env_example": ".env (5).example",
    "env_io_example": "env.io (1).example",
    "scripts": [
      "init (5).sql",
      "seed (3).sql",
      "start-db (5).ps1"
    ]
  },
  "estado_artefatos": {
    "pipeline": true,
    "csproj": true,
    "renovate_json": true,
    "renovate_setup": true,
    "dockerfile": true,
    "dockerfile_postgres": true,
    "docker_compose": true,
    "program_cs": true,
    "appsettings": true,
    "editorconfig": true,
    "env_example": true,
    "env_io_example": true,
    "scripts": true
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0",
    "database_technology": "PostgreSQL",
    "database_version": "18",
    "database_version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "postgresql_evidenced": true,
    "postgresql_dockerfile_present": true,
    "postgresql_dotnet_provider": true,
    "postgresql_version_identified": true
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": true,
    "renovate_schedule": true,
    "renovate_manual": true,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "dockerfile_postgres_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": true,
    "api_health_check": true,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "environment_parameterization": true
  },
  "banco_de_dados": {
    "technology": "PostgreSQL",
    "postgresql_evidenced": true,
    "dockerfile_postgres_present": true,
    "dotnet_provider": true,
    "version_identified": true,
    "configured_version": "18",
    "version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "interpretation_constraint": "A versão identificada representa a versão configurada nos artefatos analisados e não comprova a versão efetivamente executada no ambiente de produção."
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true,
    "interpretation_constraint": "Automação de ambiente local não constitui evidência de deploy automatizado da aplicação."
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "scope": "maturidade da automação do pipeline segundo rubrica específica do estudo",
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.",
    "lacunas": [],
    "indeterminacoes": [],
    "capacidades_adicionais": []
  },
  "restricoes_interpretativas": [
    "A interpretação assistida por IA deve partir exclusivamente das evidências estruturadas fornecidas.",
    "A IA não deve transformar ausência de evidência em evidência de ausência quando o valor for null.",
    "Valores false representam ausência da característica somente no escopo do artefato válido analisado.",
    "A presença de Dockerfile, Dockerfile.postgres ou Docker Compose não constitui, por si só, evidência de deploy automatizado.",
    "A presença de renovate.json comprova configuração do Renovate, mas não comprova sua execução efetiva.",
    "Um job Renovate no pipeline comprova orquestração configurada, mas não comprova execução efetiva.",
    "A configuração de espera pelo Quality Gate não implica Quality Gate bloqueante quando o job permite falha.",
    "Scripts de inicialização ou automação local não devem ser interpretados como automação de deployment.",
    "A versão PostgreSQL identificada representa configuração observada nos artefatos e não a versão necessariamente executada em produção.",
    "Dockerfile.postgres evidencia configuração de uma imagem/container PostgreSQL quando validado, mas não comprova a versão efetivamente executada em produção nem automação de deployment.",
    "A classificação determinística representa somente a maturidade da automação observável no pipeline e não a maturidade DevOps global da organização."
  ]
}

In [85]:
# ---------------------------------------------------------
# PIPELINE AUTOMATION MATURITY CRITERIA
#
# Rubrica determinística específica deste estudo.
#
# Esta escala representa somente a maturidade da automação
# observável no pipeline analisado. Ela não representa um
# modelo geral de maturidade DevOps da organização.
# ---------------------------------------------------------

criterios_maturidade = """
Rubrica de maturidade da automação do pipeline utilizada neste estudo:

Nível 1 — Pipeline versionado
Existe um pipeline de integração contínua versionado, mas não foram
identificadas automações suficientes para caracterizar níveis superiores.

Nível 2 — Automação básica de CI
Existe pipeline versionado com automações pontuais de integração contínua,
como restore, build ou análise automatizada de qualidade, mas sem atendimento
integral aos critérios de uma CI estruturada.

Nível 3 — CI estruturada com controle de qualidade
Existe pipeline versionado com restore automatizado, build automatizado
e controle automatizado de qualidade, como SonarQube ou espera pelo
Quality Gate. Ainda podem permanecer lacunas relativas a testes
automatizados, bloqueio do Quality Gate, deploy, promoção entre ambientes
e rollback.

Nível 4 — Automação de entrega ponta a ponta
Além da integração contínua estruturada e dos controles de qualidade,
existem evidências de testes automatizados, Quality Gate bloqueante,
deploy automatizado, promoção automática entre ambientes e rollback
automatizado.

A classificação é baseada exclusivamente nas evidências técnicas
extraídas dos artefatos válidos analisados.

A presença de arquivos de configuração, isoladamente, não comprova
execução efetiva das práticas.

A rubrica é específica deste estudo e não deve ser interpretada como
classificação abrangente de maturidade DevOps da organização.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica e conservadora das evidências
relacionadas à automação do pipeline apresentadas abaixo.

A classificação da maturidade da automação do pipeline já foi calculada
deterministicamente pelo notebook.

Sua função NÃO é criar uma nova classificação independente.

Sua função é:

1. interpretar tecnicamente as evidências;
2. verificar se elas sustentam a classificação determinística;
3. identificar lacunas, limitações e evidências indeterminadas;
4. contextualizar capacidades adicionais observadas;
5. evitar inferências que ultrapassem os artefatos analisados.

A classificação avaliada refere-se exclusivamente à maturidade da
automação observável no pipeline segundo a rubrica específica deste estudo.

Ela NÃO representa a maturidade DevOps global do projeto, da equipe
ou da organização.


{criterios_maturidade}


EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}


REGRAS DA INTERPRETAÇÃO:

1. Utilize exclusivamente as evidências fornecidas.

2. Não presuma práticas, ferramentas, execuções ou resultados
   que não estejam evidenciados.

3. Não avalie a maturidade DevOps global do projeto ou da organização.

4. Avalie especificamente se as evidências sustentam a classificação
   determinística da maturidade da automação do pipeline.

5. Respeite rigorosamente a semântica tri-state:

   true
   = evidência positiva identificada em artefato válido;

   false
   = artefato válido analisado e característica não identificada;

   null
   = evidência indeterminada por ausência, invalidade ou insuficiência
     do artefato.

6. Null não significa ausência da prática.

7. False deve ser interpretado somente no escopo dos artefatos
   válidos efetivamente analisados.

8. Não transforme ausência de evidência em evidência de ausência
   quando o valor for null.

9. Quality Gate configurado ou aguardado não significa necessariamente
   Quality Gate bloqueante.

10. Se o job responsável pelo Quality Gate estiver configurado com
    allow_failure:true, o Quality Gate não deve ser interpretado como
    bloqueante.

11. SonarQube e Quality Gate caracterizam controle automatizado
    de qualidade, mas não comprovam testes automatizados.

12. A ausência de comandos de testes automatizados nos pipelines
    analisados deve ser interpretada somente no escopo desses pipelines.

13. A ausência de comandos de deploy no pipeline não prova que
    nenhum deployment seja realizado por processos externos ou manuais.

14. O mesmo princípio se aplica à promoção entre ambientes
    e ao rollback.

15. Dockerfile da aplicação demonstra definição automatizada de construção
    e empacotamento de imagem, mas não comprova deployment automatizado.

16. Dockerfile.postgres evidencia configuração de uma imagem/container
    PostgreSQL quando validado. Sua presença não comprova deployment
    automatizado, execução do banco em produção nem a versão efetivamente
    executada no ambiente de produção.

17. Docker Compose demonstra configuração de serviços, execução
    e integração de contêineres, mas sua presença não constitui
    evidência de deploy automatizado em pipeline.

18. Scripts locais, scripts de inicialização de banco, scripts de seed
    ou comandos de ambiente local não devem ser interpretados
    como deploy automatizado da aplicação.

19. A presença de renovate.json comprova configuração da ferramenta,
    mas não comprova sua execução efetiva.

20. Um job Renovate no pipeline comprova que existe orquestração
    configurada para a ferramenta, mas não comprova execução
    efetiva ou bem-sucedida.

21. Regras de schedule ou execução manual do Renovate representam
    possibilidades configuradas de execução e não histórico
    comprovado de execução.

22. Execução efetiva do Renovate exige evidências de runtime,
    como histórico de pipeline, logs, branches renovate/*,
    commits ou merge requests criados pela ferramenta.

23. A ausência de um job Renovate em determinada versão não deve
    ser interpretada automaticamente como ausência completa
    do Renovate caso sua configuração permaneça presente.

24. Sentry configurado em appsettings representa evidência
    configuracional.

25. Sentry identificado em Program.cs representa evidência mais forte
    de integração em runtime da aplicação.

26. Logging, health checks, Sentry e Matomo caracterizam capacidades
    relacionadas à observabilidade, monitoramento ou telemetria.

27. Essas capacidades de observabilidade não devem ser usadas,
    isoladamente, para aumentar o nível de maturidade da automação
    do pipeline.

28. A presença de regras no .editorconfig representa regras
    declaradas de análise estática.

29. Regras declaradas no .editorconfig não comprovam, isoladamente,
    que tenham sido aplicadas ou bloqueado o pipeline.

30. Evidências de PostgreSQL caracterizam a tecnologia de banco
    identificada nos artefatos analisados.

31. A identificação de Npgsql, UseNpgsql ou AddNpgsql pode sustentar
    a interpretação de utilização do provider PostgreSQL no .NET.

32. A versão PostgreSQL identificada em Dockerfile.postgres,
    Docker Compose, Dockerfile da aplicação, scripts ou arquivos
    de ambiente representa versão configurada nos artefatos.

33. A versão PostgreSQL configurada não comprova a versão efetivamente
    executada no servidor de produção. Ao interpretar a versão, preserve
    também database_version_source para indicar de qual artefato válido
    a configuração foi extraída.

34. A presença de PostgreSQL nos artefatos modernos não comprova,
    isoladamente, a execução de uma migração de Ingres para PostgreSQL.

35. Não inferir Continuous Delivery apenas pela existência
    de integração contínua, Docker ou scripts.

36. Não inferir Continuous Deployment sem evidência de deployment
    automatizado no pipeline.

37. Não utilizar capacidades adicionais, como cache, Renovate,
    observabilidade ou containerização, para elevar arbitrariamente
    o nível da rubrica.

38. Capacidades adicionais devem ser tratadas como elementos
    complementares da caracterização técnica da versão.

39. Compare explicitamente as evidências observadas com os critérios
    do nível atribuído pela classificação determinística.

40. Se as evidências forem compatíveis com a classificação,
    declare que a classificação é sustentada.

41. Se apenas parte das evidências necessárias puder ser confirmada,
    declare que a classificação é parcialmente sustentada.

42. Se houver contradição objetiva entre a classificação determinística
    e as evidências fornecidas, declare que a classificação
    não é sustentada.

43. Caso identifique inconsistência, descreva-a explicitamente,
    mas não substitua arbitrariamente a classificação calculada.

44. Diferencie claramente:
    - evidências positivas;
    - lacunas evidenciadas;
    - evidências indeterminadas;
    - capacidades adicionais.

45. Não atribua causalidade a partir da simples coexistência
    de ferramentas ou configurações.

46. Não trate evolução temporal como necessariamente monotônica.
    Uma versão posterior pode preservar, retirar ou alterar
    determinada automação sem que isso represente evolução
    linear de maturidade.

47. Utilize linguagem técnica, conservadora, rastreável
    e adequada a um trabalho acadêmico.

48. Evite expressões promocionais ou conclusões amplas como:
    "pipeline DevOps completo",
    "DevOps maduro",
    "automação total",
    "CI/CD plenamente implementado",
    quando essas afirmações não forem diretamente sustentadas
    pelas evidências.

49. Não apresente a rubrica do notebook como modelo universal
    de maturidade DevOps. Ela é uma operacionalização específica
    deste estudo.


PRODUZA A RESPOSTA EXATAMENTE COM A SEGUINTE ESTRUTURA:


### Avaliação da classificação

Classificação determinística:
[reproduza o nível e a classificação recebidos]

Avaliação:
[Sustentada / Parcialmente sustentada / Não sustentada]

Justificativa:
[explique de forma objetiva a relação entre as evidências
e os critérios do nível atribuído]


### Evidências que sustentam a avaliação

Apresente as principais evidências positivas que sustentam
a classificação, priorizando aquelas diretamente relacionadas
à rubrica.


### Lacunas identificadas

Apresente somente lacunas que estejam efetivamente evidenciadas
como false nos artefatos analisados.

Não inclua valores null como ausência.


### Evidências indeterminadas

Apresente os itens relevantes cujo valor seja null e explique,
quando necessário, que eles não podem ser classificados
como presentes nem ausentes.


### Capacidades adicionais observadas

Apresente capacidades tecnicamente relevantes, como cache,
Renovate, containerização, observabilidade, configuração
externalizada ou banco de dados, sem utilizá-las para elevar
arbitrariamente o nível da classificação.


### Limitações da interpretação

Explique as principais limitações decorrentes do escopo
dos artefatos analisados.

Destaque quando a configuração não comprovar execução efetiva.


### Síntese

Produza uma síntese curta, acadêmica e conservadora,
indicando se a classificação determinística é sustentada
pelas evidências disponíveis.
"""


# ---------------------------------------------------------
# RESULTADO
# ---------------------------------------------------------

print(
    "✓ Prompt de interpretação preparado."
)

print(
    "✓ Rubrica de maturidade alinhada "
    "à classificação determinística."
)

print(
    "✓ Restrições de interpretação incorporadas."
)

✓ Prompt de interpretação preparado.
✓ Rubrica de maturidade alinhada à classificação determinística.
✓ Restrições de interpretação incorporadas.

In [86]:
# ---------------------------------------------------------
# VERSION ANALYSIS STORAGE — CONTINUIDADE
#
# Reutiliza a estrutura longitudinal já inicializada na V1.
# Não reinicializa resultados_versoes, preservando as versões
# anteriormente armazenadas.
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):
    raise ValueError(
        "A estrutura resultados_versoes não está disponível. "
        "A V1 deve ter sido executada anteriormente na mesma sessão."
    )


print(
    "✓ Estrutura longitudinal existente."
)


if resultados_versoes:

    print(
        "✓ Versões já armazenadas:",
        ", ".join(
            sorted(
                resultados_versoes.keys()
            )
        )
    )

else:

    print(
        "⚠ A estrutura existe, mas ainda não possui versões armazenadas."
    )

✓ Estrutura longitudinal existente.
✓ Versões já armazenadas: V1

In [87]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
#
# A IA atua exclusivamente como apoio à interpretação
# qualitativa das evidências previamente extraídas e
# classificadas de forma determinística.
#
# A IA não altera:
# - as evidências extraídas;
# - os estados tri-state;
# - o nível calculado;
# - a classificação determinística.
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Configuração da interpretação
# ---------------------------------------------------------

MODELO_IA = "gpt-5.6-terra"
ESFORCO_RACIOCINIO = "medium"


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

interpretacao_ia = None

metadados_interpretacao_ia = {
    "executada": False,
    "modelo": MODELO_IA,
    "esforco_raciocinio": ESFORCO_RACIOCINIO,
    "erro": None
}


# ---------------------------------------------------------
# 3. Recupera a chave da API
#
# A chave deve permanecer nos Secrets do Google Colab.
# Ela não deve ser inserida diretamente no notebook,
# impressa ou armazenada nos resultados da pesquisa.
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception as erro_chave:

    api_key = None

    metadados_interpretacao_ia[
        "erro"
    ] = (
        "Não foi possível acessar os Secrets "
        "do Google Colab."
    )


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 4. Validação das entradas
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or evidencias_para_ia is None
):

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not isinstance(
    evidencias_para_ia,
    dict
):

    raise TypeError(
        "evidencias_para_ia deve ser um dicionário."
    )


if (
    "prompt" not in globals()
    or not isinstance(
        prompt,
        str
    )
    or not prompt.strip()
):

    raise ValueError(
        "O prompt de interpretação ainda não foi criado "
        "ou está vazio."
    )


if (
    "resultado_maturidade" not in globals()
    or resultado_maturidade is None
):

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


if not isinstance(
    resultado_maturidade,
    dict
):

    raise TypeError(
        "resultado_maturidade deve ser um dicionário."
    )


# ---------------------------------------------------------
# 5. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 6. Instruções de sistema da interpretação
# ---------------------------------------------------------

instrucoes_interpretacao = """
Atue como avaliador técnico de evidências relacionadas à
automação de pipelines de software.

A análise integra um estudo acadêmico longitudinal sobre
modernização de software legado.

Sua interpretação deve ser:

- técnica;
- conservadora;
- rastreável;
- baseada exclusivamente nas evidências fornecidas;
- coerente com a semântica tri-state apresentada;
- limitada ao escopo dos artefatos analisados.

Não realize uma nova classificação independente.

Não altere o nível de maturidade calculado deterministicamente
pelo notebook.

Avalie se as evidências fornecidas sustentam a classificação
determinística.

Diferencie explicitamente:

- evidência positiva;
- ausência evidenciada;
- evidência indeterminada;
- configuração;
- orquestração;
- execução efetiva.

Não interprete ausência de evidência como evidência de ausência
quando o valor recebido for null.

Não avalie a maturidade DevOps global da organização.

A classificação fornecida representa exclusivamente a maturidade
da automação observável no pipeline segundo a rubrica específica
definida neste estudo.

Não atribua causalidade ou evolução de maturidade apenas pela
presença de ferramentas.

Não presuma evolução temporal monotônica.

Utilize linguagem adequada a um trabalho acadêmico.
"""


# ---------------------------------------------------------
# 7. Interpretação assistida por IA
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model=MODELO_IA,

        reasoning={
            "effort": ESFORCO_RACIOCINIO
        },

        instructions=(
            instrucoes_interpretacao
        ),

        input=prompt,

        store=False
    )


    # -----------------------------------------------------
    # 8. Recupera a interpretação textual
    # -----------------------------------------------------

    interpretacao_ia = (
        response.output_text.strip()
        if response.output_text
        else None
    )


    if not interpretacao_ia:

        raise ValueError(
            "A API respondeu, mas não retornou "
            "interpretação textual."
        )


    # -----------------------------------------------------
    # 9. Metadados da execução
    #
    # Não armazenamos API key nem outros segredos.
    # -----------------------------------------------------

    metadados_interpretacao_ia[
        "executada"
    ] = True

    metadados_interpretacao_ia[
        "modelo"
    ] = getattr(
        response,
        "model",
        MODELO_IA
    )

    metadados_interpretacao_ia[
        "response_id"
    ] = getattr(
        response,
        "id",
        None
    )


    # -----------------------------------------------------
    # 10. Uso de tokens, quando disponibilizado pela API
    # -----------------------------------------------------

    usage = getattr(
        response,
        "usage",
        None
    )


    if usage is not None:

        metadados_interpretacao_ia[
            "input_tokens"
        ] = getattr(
            usage,
            "input_tokens",
            None
        )

        metadados_interpretacao_ia[
            "output_tokens"
        ] = getattr(
            usage,
            "output_tokens",
            None
        )

        metadados_interpretacao_ia[
            "total_tokens"
        ] = getattr(
            usage,
            "total_tokens",
            None
        )


    # -----------------------------------------------------
    # 11. Resultado
    # -----------------------------------------------------

    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


    print(
        "\n"
        "-----------------------------------------"
    )

    print(
        "Modelo:",
        metadados_interpretacao_ia[
            "modelo"
        ]
    )

    print(
        "Esforço de raciocínio:",
        metadados_interpretacao_ia[
            "esforco_raciocinio"
        ]
    )

    print(
        "Execução:",
        "concluída"
    )


# ---------------------------------------------------------
# 12. Tratamento de erro
# ---------------------------------------------------------

except Exception as erro:

    interpretacao_ia = None

    metadados_interpretacao_ia[
        "executada"
    ] = False

    metadados_interpretacao_ia[
        "erro"
    ] = str(
        erro
    )


    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação

Classificação determinística:
Nível 3 — CI estruturada com controle de qualidade; classificação: **Parcial/Emergente**.

Avaliação:
**Sustentada**

Justificativa:
As evidências fornecidas atendem aos critérios centrais do Nível 3 da rubrica específica do estudo: há pipeline GitLab CI versionado, restore automatizado de dependências .NET, build em modo Release e controle automatizado de qualidade por SonarQube, incluindo configuração de espera pelo Quality Gate. Esses elementos caracterizam uma integração contínua estruturada com controle de qualidade automatizado.

A classificação como Parcial/Emergente também é coerente com as lacunas evidenciadas no escopo dos artefatos válidos: não foram identificados testes automatizados no pipeline, Quality Gate bloqueante, deploy automatizado, promoção automatizada entre ambientes ou rollback automatizado. Portanto, não há evidência suficiente para caracterizar o Nível 4, que exige automação de entrega ponta a ponta. A ausência de bloqueio do Quality Gate é particularmente relevante: a espera pelo resultado do gate constitui controle de qualidade, mas `quality_gate_blocking: false` impede interpretá-lo como mecanismo bloqueante.

---

### Evidências que sustentam a avaliação

As evidências positivas diretamente relacionadas à rubrica são:

- **Pipeline GitLab CI identificado** (`gitlab_ci: true`), em artefato de pipeline válido, sustentando a existência de automação versionada de integração contínua.
- **Restore automatizado de dependências .NET** (`dotnet_restore: true`), compatível com o critério de restore automatizado requerido para CI estruturada.
- **Build automatizado em modo Release** (`build_release: true`), evidenciando automação de compilação no pipeline.
- **Integração com SonarQube** (`sonarqube: true`), caracterizando controle automatizado de qualidade.
- **Espera pelo Quality Gate** (`quality_gate_wait: true`), indicando que o pipeline está configurado para aguardar o resultado do controle de qualidade.
- **Regra associada à branch principal** (`main_branch_rule: true`), evidenciando que há ao menos uma condição configurada de execução relacionada à branch principal; essa evidência é complementar e não altera isoladamente o nível atribuído.

Em conjunto, restore, build e análise automatizada de qualidade sustentam tecnicamente a interpretação de CI estruturada prevista no Nível 3. A evidência de SonarQube e de espera pelo Quality Gate representa controle automatizado de qualidade, mas não deve ser interpretada como comprovação de testes automatizados nem de bloqueio obrigatório do pipeline.

---

### Lacunas identificadas

As seguintes lacunas estão explicitamente evidenciadas como `false` no escopo dos artefatos válidos analisados:

- **Testes automatizados não identificados no pipeline analisado** (`automated_tests: false`). Essa constatação é limitada aos pipelines e artefatos válidos examinados; não demonstra inexistência de testes executados externamente, manualmente ou em outros repositórios/pipelines não analisados.
- **Quality Gate não bloqueante** (`quality_gate_blocking: false`). Embora exista espera pelo Quality Gate, não há evidência de que sua reprovação interrompa obrigatoriamente o pipeline.
- **Ausência de regra identificada para merge requests** (`merge_request_rule: false`) no pipeline analisado. Essa lacuna não impede o Nível 3, mas limita a caracterização de gatilhos de CI no escopo observado.
- **Deploy automatizado não identificado** (`automated_deploy: false`).
- **Promoção automatizada entre ambientes não identificada** (`automated_promotion: false`).
- **Rollback automatizado não identificado** (`automated_rollback: false`).
- **Database dump não identificado nos scripts analisados** (`database_dump_present: false`). Trata-se de uma lacuna de automação local/de banco de dados e não constitui, por si, critério determinante da rubrica de maturidade do pipeline.

As lacunas de testes, bloqueio de Quality Gate, deploy, promoção e rollback são compatíveis com a conclusão de que não há evidência, no escopo analisado, dos requisitos adicionais necessários para o Nível 4.

---

### Evidências indeterminadas

- **Execução efetiva do Renovate** (`renovate_effective_execution: null`): a evidência é indeterminada. Há configuração do Renovate, job no pipeline, agendamento e possibilidade de execução manual, mas tais elementos demonstram configuração e orquestração potencial, não execução efetiva ou bem-sucedida. Não foram fornecidos logs de execução, histórico de pipelines, branches `renovate/*`, commits ou merge requests atribuíveis à ferramenta.

Esse valor `null` não pode ser interpretado nem como ausência de execução do Renovate nem como comprovação de que a ferramenta tenha sido executada.

---

### Capacidades adicionais observadas

Foram observadas capacidades complementares tecnicamente relevantes, que caracterizam o ambiente e a implementação analisados, mas não elevam, isoladamente, o nível da rubrica:

- **Cache de dependências e análise**: cache do SonarQube (`sonar_cache: true`) e cache NuGet (`nuget_cache: true`). Essas configurações podem favorecer eficiência operacional do pipeline, mas não comprovam execução efetiva nem ampliam os critérios formais do Nível 3.
- **Gerenciamento de dependências configurado**: Renovate configurado para NuGet e Dockerfiles, com alertas de vulnerabilidade e manutenção de lock files. Também há job, agendamento e possibilidade de acionamento manual. Isso evidencia configuração e orquestração potencial da ferramenta, não seu histórico de execução.
- **Containerização**: Dockerfile da aplicação, Dockerfile específico para PostgreSQL e Docker Compose estão presentes. Há evidências de build multiestágio, restore, build e publish na imagem, além de composição de serviços, política de reinício, rede externa e proxy reverso. Esses elementos demonstram configuração de construção, empacotamento e integração de contêineres, mas não comprovam deploy automatizado pelo pipeline.
- **Observabilidade e monitoramento**: Sentry está configurado e possui integração em runtime, além de health checks de aplicação e banco de dados, logging em console e configuração do Matomo. Tais evidências caracterizam capacidades de observabilidade, telemetria e monitoramento da aplicação, sem demonstrar maior automação de entrega.
- **Configuração externalizada e parametrização de ambiente**: há `appsettings`, arquivos de exemplo de variáveis de ambiente e parametrização de ambiente. Esses artefatos demonstram capacidade configuracional, mas não comprovam promoção ou deployment automatizado.
- **Automação local e banco de dados**: scripts de inicialização e seed do banco, bem como automação de ambiente local, foram identificados. Eles não constituem evidência de deploy automatizado.
- **PostgreSQL configurado**: PostgreSQL é evidenciado por Dockerfile específico, provider .NET e configuração associada. A versão configurada é `18`, extraída de `Dockerfile.postgres (imagem PostgreSQL literal)`. Essa informação representa configuração observada nos artefatos e não comprova a versão efetivamente executada em produção.
- **Regras de análise estática declaradas**: `.editorconfig` com regras de analisadores e de segurança. Essas regras são configuração declarada e, isoladamente, não comprovam aplicação efetiva nem bloqueio do pipeline.

---

### Limitações da interpretação

A interpretação está restrita aos artefatos válidos listados e às evidências estruturadas fornecidas. Consequentemente:

- A presença do pipeline, de comandos de restore, build e integração com SonarQube comprova configuração observável no artefato analisado, mas não fornece histórico de execuções, resultados de builds ou aprovação/reprovação de Quality Gates.
- A espera pelo Quality Gate não equivale a bloqueio, pois `quality_gate_blocking: false` evidencia que o resultado não é bloqueante no escopo avaliado.
- A ausência identificada de testes automatizados, deploy, promoção e rollback aplica-se somente aos artefatos válidos analisados. Ela não permite concluir que tais práticas inexistam em processos manuais, infraestrutura externa, pipelines distintos ou repositórios não incluídos.
- A configuração do Renovate, seu job, agendamento e acionamento manual demonstram possibilidade de orquestração, mas não execução efetiva. A execução permanece indeterminada (`null`) por ausência de evidências de runtime.
- Dockerfiles, Docker Compose, scripts locais e scripts de banco demonstram configuração de build, ambiente e serviços, mas não comprovam deployment automatizado.
- Sentry configurado em `appsettings` é evidência configuracional; sua integração em `Program.cs` é evidência mais forte de integração de runtime. Ainda assim, essas capacidades não demonstram automação de entrega.
- A versão PostgreSQL `18` é uma versão configurada no `Dockerfile.postgres`; não é evidência da versão executada em produção.
- A análise não permite inferir maturidade DevOps global, eficácia operacional, frequência de execução, confiabilidade dos pipelines, adoção organizacional ou evolução temporal da automação.

---

### Síntese

A classificação determinística de **Nível 3 — CI estruturada com controle de qualidade, Parcial/Emergente** é sustentada pelas evidências disponíveis. O pipeline analisado apresenta restore, build Release e controle automatizado de qualidade com SonarQube e espera pelo Quality Gate. Contudo, permanecem lacunas evidenciadas quanto a testes automatizados, bloqueio do Quality Gate, deploy, promoção entre ambientes e rollback, o que impede caracterizar automação de entrega ponta a ponta no escopo da rubrica e dos artefatos analisados.

-----------------------------------------
Modelo: gpt-5.6-terra
Esforço de raciocínio: medium
Execução: concluída

In [88]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS
#
# Armazena uma cópia independente dos resultados da versão
# atualmente analisada para posterior análise longitudinal.
#
# A mesma célula pode ser reutilizada para V1, V2, V3 e V4.
# Basta definir:
#
# versao_atual
# snapshot_atual
#
# antes da execução.
# ---------------------------------------------------------

import copy

versao_atual = "V2"
snapshot_atual = "web-1.26.4-1"

if (
    "versao_atual" not in globals()
    or not isinstance(
        versao_atual,
        str
    )
    or not versao_atual.strip()
):

    raise ValueError(
        "A variável versao_atual não foi definida."
    )


versao_atual = versao_atual.strip().upper()


if (
    "snapshot_atual" not in globals()
    or not isinstance(
        snapshot_atual,
        str
    )
    or not snapshot_atual.strip()
):

    raise ValueError(
        f"O snapshot da {versao_atual} não foi definido "
        "na variável snapshot_atual."
    )


snapshot_atual = snapshot_atual.strip()


# ---------------------------------------------------------
# 2. Validação da estrutura longitudinal
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes não foi inicializada."
    )


# ---------------------------------------------------------
# 3. Validação das evidências
# ---------------------------------------------------------

if (
    "evidencias" not in globals()
    or not isinstance(
        evidencias,
        dict
    )
    or not evidencias
):

    raise ValueError(
        f"As evidências da {versao_atual} "
        "não estão disponíveis."
    )


# ---------------------------------------------------------
# 4. Validação da classificação determinística
# ---------------------------------------------------------

if (
    "resultado_maturidade" not in globals()
    or not isinstance(
        resultado_maturidade,
        dict
    )
):

    raise ValueError(
        f"A classificação determinística da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 5. Validação do pacote preparado para a IA
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or not isinstance(
        evidencias_para_ia,
        dict
    )
):

    raise ValueError(
        f"O pacote estruturado de evidências da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 6. Validação da caracterização tecnológica
# ---------------------------------------------------------

if (
    "tecnologia" not in globals()
    or not isinstance(
        tecnologia,
        dict
    )
):

    raise ValueError(
        f"A caracterização tecnológica da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 7. Validação dos artefatos analisáveis
# ---------------------------------------------------------

if (
    "artefatos_analisaveis" not in globals()
    or not isinstance(
        artefatos_analisaveis,
        dict
    )
):

    raise ValueError(
        f"A estrutura de artefatos analisáveis da "
        f"{versao_atual} não está disponível."
    )


# ---------------------------------------------------------
# 8. Captura segura da interpretação assistida por IA
# ---------------------------------------------------------

interpretacao_atual = (
    interpretacao_ia
    if (
        "interpretacao_ia" in globals()
        and interpretacao_ia is not None
    )
    else None
)


# ---------------------------------------------------------
# 9. Metadados da execução da IA
# ---------------------------------------------------------

metadados_ia_atual = (
    copy.deepcopy(
        metadados_interpretacao_ia
    )
    if (
        "metadados_interpretacao_ia" in globals()
        and isinstance(
            metadados_interpretacao_ia,
            dict
        )
    )
    else {
        "executada": False,
        "modelo_solicitado": None,
        "modelo_retornado": None,
        "esforco_raciocinio": None,
        "classificacao_deterministica_preservada": True,
        "response_id": None,
        "input_tokens": None,
        "output_tokens": None,
        "total_tokens": None,
        "erro": (
            "Metadados da interpretação assistida "
            "por IA não disponíveis."
        )
    }
)


# ---------------------------------------------------------
# 10. Scripts efetivamente analisados
# ---------------------------------------------------------

scripts_analisados_atual = (
    sorted(
        scripts_analisaveis.keys()
    )
    if (
        "scripts_analisaveis" in globals()
        and isinstance(
            scripts_analisaveis,
            dict
        )
    )
    else []
)


# ---------------------------------------------------------
# 11. Artefatos efetivamente analisados
# ---------------------------------------------------------

artefatos_analisados_atual = {

    "pipeline":
        pipeline_nome
        if artefatos_analisaveis.get(
            "pipeline"
        ) is True
        else None,

    "csproj":
        csproj_nome
        if artefatos_analisaveis.get(
            "csproj"
        ) is True
        else None,

    "renovate_json":
        renovate_json_nome
        if artefatos_analisaveis.get(
            "renovate_json"
        ) is True
        else None,

    "renovate_setup":
        renovate_setup_nome
        if artefatos_analisaveis.get(
            "renovate_setup"
        ) is True
        else None,

    "dockerfile":
        dockerfile_nome
        if artefatos_analisaveis.get(
            "dockerfile"
        ) is True
        else None,

    "dockerfile_postgres":
        dockerfile_postgres_nome
        if artefatos_analisaveis.get(
            "dockerfile_postgres"
        ) is True
        else None,

    "docker_compose":
        docker_compose_nome
        if artefatos_analisaveis.get(
            "docker_compose"
        ) is True
        else None,

    "program_cs":
        program_cs_nome
        if artefatos_analisaveis.get(
            "program_cs"
        ) is True
        else None,

    "appsettings":
        appsettings_nome
        if artefatos_analisaveis.get(
            "appsettings"
        ) is True
        else None,

    "editorconfig":
        editorconfig_nome
        if artefatos_analisaveis.get(
            "editorconfig"
        ) is True
        else None,

    "env_example":
        env_example_nome
        if artefatos_analisaveis.get(
            "env_example"
        ) is True
        else None,

    "env_io_example":
        env_io_example_nome
        if artefatos_analisaveis.get(
            "env_io_example"
        ) is True
        else None,

    "scripts":
        scripts_analisados_atual
}


# ---------------------------------------------------------
# 12. Estado dos artefatos
# ---------------------------------------------------------

estado_artefatos_atual = copy.deepcopy(
    artefatos_analisaveis
)


# ---------------------------------------------------------
# 13. Caracterização tecnológica
# ---------------------------------------------------------

caracterizacao_tecnologica_atual = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia.get(
            "database_technology"
        ),

    "database_version":
        tecnologia.get(
            "database_version"
        ),

    "database_version_source":
        tecnologia.get(
            "database_version_source"
        ),

    "postgresql_evidenced":
        evidencias.get(
            "PostgreSQL evidenciado"
        ),

    "postgresql_dockerfile_present":
        evidencias.get(
            "Dockerfile PostgreSQL presente"
        ),

    "postgresql_dotnet_provider":
        evidencias.get(
            "Provider PostgreSQL (.NET)"
        ),

    "postgresql_version_identified":
        evidencias.get(
            "Versão PostgreSQL identificada"
        )
}


# ---------------------------------------------------------
# 14. Registro consolidado da versão atual
# ---------------------------------------------------------

registro_atual = {

    "versao":
        versao_atual,

    "snapshot":
        snapshot_atual,

    "artefatos_analisados":
        copy.deepcopy(
            artefatos_analisados_atual
        ),

    "estado_artefatos":
        copy.deepcopy(
            estado_artefatos_atual
        ),

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "caracterizacao_tecnologica":
        copy.deepcopy(
            caracterizacao_tecnologica_atual
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_atual,

    "metadados_interpretacao_ia":
        copy.deepcopy(
            metadados_ia_atual
        )
}


# ---------------------------------------------------------
# 15. Verifica se a versão já estava armazenada
# ---------------------------------------------------------

versao_ja_existia = (
    versao_atual
    in resultados_versoes
)


# ---------------------------------------------------------
# 16. Armazena a versão atual
# ---------------------------------------------------------

resultados_versoes[
    versao_atual
] = copy.deepcopy(
    registro_atual
)


# ---------------------------------------------------------
# 17. Resultado
# ---------------------------------------------------------

if versao_ja_existia:

    print(
        f"✓ Resultados da {versao_atual} atualizados "
        "para a análise longitudinal."
    )

else:

    print(
        f"✓ Resultados da {versao_atual} armazenados "
        "para a análise longitudinal."
    )


registro_salvo = resultados_versoes[
    versao_atual
]


print(
    "✓ Snapshot:",
    registro_salvo[
        "snapshot"
    ]
)


print(
    "✓ Nível:",
    registro_salvo[
        "classificacao"
    ].get(
        "nivel"
    )
)


print(
    "✓ Classificação:",
    registro_salvo[
        "classificacao"
    ].get(
        "classificacao"
    )
)


print(
    "✓ Banco de dados:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_technology"
    )
)


print(
    "✓ Versão configurada do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version"
    )
)


print(
    "✓ Fonte da versão do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version_source"
    )
)


print(
    "✓ Dockerfile PostgreSQL:",
    (
        "analisado"
        if registro_salvo[
            "estado_artefatos"
        ].get(
            "dockerfile_postgres"
        ) is True
        else "não analisado"
    )
)


print(
    "✓ Interpretação assistida por IA:",
    (
        "disponível"
        if registro_salvo[
            "interpretacao_ia"
        ]
        else "não disponível"
    )
)


print(
    "✓ Versões atualmente armazenadas:",
    ", ".join(
        sorted(
            resultados_versoes.keys()
        )
    )
)

✓ Resultados da V2 armazenados para a análise longitudinal.
✓ Snapshot: web-1.26.4-1
✓ Nível: 3
✓ Classificação: Parcial/Emergente
✓ Banco de dados: PostgreSQL
✓ Versão configurada do banco: 18
✓ Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)
✓ Dockerfile PostgreSQL: analisado
✓ Interpretação assistida por IA: disponível
✓ Versões atualmente armazenadas: V1, V2

## 5. V3 — Pipeline Technical Analysis

### 5.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.6-1`**.

### 5.2 Análise dos Artefatos

In [89]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None


print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [90]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar "
            "o arquivo .csproj:"
        )

        print(
            erro
        )


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = (
            match_sdk.group(1)
        )


    # Pipeline versionado
    evidencias[
        "GitLab CI como código"
    ] = True


    # Restore
    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias[
        "Espera pelo Quality Gate"
    ] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias[
        "Quality Gate bloqueante"
    ] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if dockerfile_postgres:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo
        in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome
        in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# appsettings
if appsettings:

    fontes_banco.append(
        appsettings
    )


# Program.cs
if program_cs:

    fontes_banco.append(
        program_cs
    )


# .csproj
if csproj:

    fontes_banco.append(
        csproj
    )


# Docker Compose
if docker_compose:

    fontes_banco.append(
        docker_compose
    )


# Dockerfile.postgres
if dockerfile_postgres:

    fontes_banco.append(
        dockerfile_postgres
    )


# Dockerfile da aplicação
if dockerfile:

    fontes_banco.append(
        dockerfile
    )


# Scripts
if conteudo_total_scripts:

    fontes_banco.append(
        conteudo_total_scripts
    )


# ---------------------------------------------------------
# 13.1 Consolidação das fontes de banco
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for conteudo
        in fontes_banco
    )


    # -----------------------------------------------------
    # Identificação do PostgreSQL
    # -----------------------------------------------------

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem(
        conteudo_banco,
        "postgresql",
        "postgres",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    conteudo_dotnet_banco = "\n".join(
        [
            program_cs or "",
            csproj or ""
        ]
    )

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = contem(
        conteudo_dotnet_banco,
        "npgsql",
        "usenpgsql",
        "addnpgsql"
    )


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if (
        evidencias[
            "PostgreSQL evidenciado"
        ] is True
    ):

        tecnologia_banco = (
            "PostgreSQL"
        )

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Exemplos reconhecidos:
    #
    # FROM postgres:16
    # FROM postgres:16.4
    # FROM postgres:16-alpine
    # image: postgres:16
    # image: postgres:16.4-alpine
    #
    # A versão encontrada representa a versão configurada
    # no artefato analisado e não comprova a versão
    # efetivamente executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.2 Prioridade 1 — Dockerfile.postgres
    # -----------------------------------------------------

    if dockerfile_postgres:

        match_postgres_dockerfile_postgres = (
            buscar_regex(
                dockerfile_postgres,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile_postgres:

            versao_banco = (
                match_postgres_dockerfile_postgres.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile.postgres"
            )


    # -----------------------------------------------------
    # 13.3 Prioridade 2 — Docker Compose
    # -----------------------------------------------------

    if (
        versao_banco is None
        and docker_compose
    ):

        match_postgres_compose = (
            buscar_regex(
                docker_compose,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_compose:

            versao_banco = (
                match_postgres_compose.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.4 Prioridade 3 — Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and dockerfile
    ):

        match_postgres_dockerfile = (
            buscar_regex(
                dockerfile,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile:

            versao_banco = (
                match_postgres_dockerfile.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile"
            )


    # -----------------------------------------------------
    # 13.5 Prioridade 4 — Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        match_postgres_script = (
            buscar_regex(
                conteudo_total_scripts,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_script:

            versao_banco = (
                match_postgres_script.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia_banco,

    "database_version":
        versao_banco,

    "database_version_source":
        fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None
Banco de dados: None
Versão configurada do banco: None
Fonte da versão do banco: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Dockerfile PostgreSQL presente
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local
? PostgreSQL evidenciado
? Provider PostgreSQL (.NET)
? Versão PostgreSQL identificada

In [91]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (6)
Saving .env.example to .env (6).example
Saving .env.io.example to .env.io (4).example
Saving appsettings.json to appsettings (6).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (6).csproj
Saving docker-compose.yaml to docker-compose (6).yaml
Saving Dockerfile to Dockerfile (6)
Saving Dockerfile.postgres to Dockerfile (6).postgres
Saving gitlab-ci.yml to gitlab-ci (6).yml
Saving init.sql to init (6).sql
Saving Program.cs to Program (6).cs
Saving renovate.json to renovate (4).json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP (4).md
Saving seed.sql to seed (4).sql
Saving start-db.ps1 to start-db (6).ps1

✓ 15 arquivo(s) carregado(s):

  ✓ .editorconfig (6)
  ✓ .env (6).example
  ✓ .env.io (4).example
  ✓ Boilerplate4Dev (6).csproj
  ✓ Dockerfile (6)
  ✓ Dockerfile (6).postgres
  ✓ Program (6).cs
  ✓ RENOVATE_SETUP (4).md
  ✓ appsettings (6).json
  ✓ docker-compose (6).yaml
  ✓ gitlab-ci (6).yml
  ✓ init (6).sql
  ✓ renovate (4).json
  ✓ seed (4).sql
  ✓ start-db (6).ps1

In [92]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:

    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None

dockerfile_valido = None
dockerfile_postgres_valido = None
docker_compose_valido = None

program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):

    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):

    nome = nome_base(
        nome
    )

    # Remove sufixos adicionados pelo Colab:
    #
    # arquivo (1).json      -> arquivo.json
    # Dockerfile (2)        -> Dockerfile
    # Dockerfile (1).postgres -> Dockerfile.postgres
    #
    # O primeiro padrão trata o sufixo antes da extensão.
    # O segundo trata o sufixo no final do nome.

    nome = re.sub(
        r"\s*\(\d+\)(?=\.)",
        "",
        nome
    )

    nome = re.sub(
        r"\s*\(\d+\)$",
        "",
        nome
    )

    return (
        nome
        .lower()
        .strip()
    )


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):

    if not candidatos:

        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _
                in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(
    conteudo
):

    if conteudo is None:

        return None

    if isinstance(
        conteudo,
        bytes
    ):

        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []

candidatos_dockerfile = []
candidatos_dockerfile_postgres = []
candidatos_docker_compose = []

candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []


extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # -----------------------------------------------------
    # GitLab CI
    # -----------------------------------------------------

    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Projeto .NET
    # -----------------------------------------------------

    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Renovate
    # -----------------------------------------------------

    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile.postgres
    #
    # Deve ser identificado ANTES do Dockerfile genérico.
    # -----------------------------------------------------

    if normalizado == "dockerfile.postgres":

        candidatos_dockerfile_postgres.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile da aplicação
    # -----------------------------------------------------

    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Docker Compose
    # -----------------------------------------------------

    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Program.cs
    # -----------------------------------------------------

    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # appsettings.json
    # -----------------------------------------------------

    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .editorconfig
    # -----------------------------------------------------

    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.io.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Scripts
    # -----------------------------------------------------

    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile da aplicação"
)

dockerfile_postgres, dockerfile_postgres_nome = (
    selecionar_unico(
        candidatos_dockerfile_postgres,
        "Dockerfile.postgres"
    )
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

dockerfile_postgres = como_texto(
    dockerfile_postgres
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):

    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):

            continue

        if "=" not in linha:

            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # Continua utilizável para extração textual.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


def validar_dockerfile(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    possui_from = bool(
        re.search(
            r"^\s*FROM\s+\S+",
            conteudo,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    if possui_from:

        validacao_artefatos.append(
            f"✓ {descricao} estruturalmente válido "
            "(instrução FROM identificada)."
        )

        return True

    validacao_artefatos.append(
        f"✗ {descricao} sem instrução FROM identificada."
    )

    return False


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

dockerfile_valido = validar_dockerfile(
    dockerfile,
    "Dockerfile"
)


# ---------------------------------------------------------
# 6. Dockerfile.postgres
# ---------------------------------------------------------

dockerfile_postgres_valido = validar_dockerfile(
    dockerfile_postgres,
    "Dockerfile.postgres"
)


# ---------------------------------------------------------
# 7. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 8. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador
            in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 9. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 10. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 11. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# 13. Artefatos habilitados para análise
#
# Somente artefatos explicitamente validados podem ser
# utilizados pela etapa de extração determinística.
# ---------------------------------------------------------

artefatos_analisaveis = {

    "pipeline":
        pipeline_valido is True,

    "csproj":
        csproj_valido is True,

    "renovate_json":
        renovate_json_valido is True,

    "renovate_setup":
        renovate_setup_valido is True,

    "dockerfile":
        dockerfile_valido is True,

    "dockerfile_postgres":
        dockerfile_postgres_valido is True,

    "docker_compose":
        docker_compose_valido is True,

    "program_cs":
        program_cs_valido is True,

    "appsettings":
        appsettings_valido is True,

    "editorconfig":
        editorconfig_valido is True,

    "env_example":
        env_example_valido is True,

    "env_io_example":
        env_io_example_valido is True
}


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

artefatos_analisaveis[
    "scripts"
] = any(
    estado is True
    for estado
    in scripts_validos.values()
)


# ---------------------------------------------------------
# Mantém apenas scripts validados para a etapa de análise
# ---------------------------------------------------------

scripts_analisaveis = {

    nome:
        conteudo

    for nome, conteudo
    in scripts.items()

    if scripts_validos.get(
        nome
    ) is True
}


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):

    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Dockerfile.postgres",
    dockerfile_postgres_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):

        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {

    "Pipeline":
        pipeline_valido,

    ".csproj":
        csproj_valido,

    "renovate.json":
        renovate_json_valido,

    "RENOVATE_SETUP.md":
        renovate_setup_valido,

    "Dockerfile":
        dockerfile_valido,

    "Dockerfile.postgres":
        dockerfile_postgres_valido,

    "Docker Compose":
        docker_compose_valido,

    "Program.cs":
        program_cs_valido,

    "appsettings.json":
        appsettings_valido,

    ".editorconfig":
        editorconfig_valido,

    ".env.example":
        env_example_valido,

    ".env.io.example":
        env_io_example_valido
}


for artefato, estado in (
    estados_validacao.items()
):

    if estado is True:

        simbolo = "✓"

    elif estado is False:

        simbolo = "✗"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

if scripts_validos:

    print(
        "\nESTADO DOS SCRIPTS\n"
    )

    for nome in sorted(
        scripts_validos
    ):

        estado = scripts_validos[
            nome
        ]

        simbolo = (
            "✓"
            if estado is True
            else "✗"
        )

        print(
            f"{simbolo} {nome}"
        )


# ---------------------------------------------------------
# Artefatos disponíveis para extração
# ---------------------------------------------------------

print(
    "\nARTEFATOS HABILITADOS PARA EXTRAÇÃO\n"
)

for artefato, habilitado in (
    artefatos_analisaveis.items()
):

    simbolo = (
        "✓"
        if habilitado
        else "—"
    )

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (6).yml
✓ .csproj: Boilerplate4Dev (6).csproj
✓ renovate.json: renovate (4).json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP (4).md
✓ Dockerfile: Dockerfile (6)
✓ Dockerfile.postgres: Dockerfile (6).postgres
✓ Docker Compose: docker-compose (6).yaml
✓ Program.cs: Program (6).cs
✓ appsettings.json: appsettings (6).json
✓ .editorconfig: .editorconfig (6)
✓ .env.example: .env (6).example
✓ .env.io.example: .env.io (4).example
✓ Scripts: 3 arquivo(s)
    - init (6).sql
    - seed (4).sql
    - start-db (6).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Dockerfile.postgres estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (6).sql: script SQL legível e não vazio.
✓ seed (4).sql: script SQL legível e não vazio.
✓ start-db (6).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Dockerfile.postgres
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

ESTADO DOS SCRIPTS

✓ init (6).sql
✓ seed (4).sql
✓ start-db (6).ps1

ARTEFATOS HABILITADOS PARA EXTRAÇÃO

✓ pipeline
✓ csproj
✓ renovate_json
✓ renovate_setup
✓ dockerfile
✓ dockerfile_postgres
✓ docker_compose
✓ program_cs
✓ appsettings
✓ editorconfig
✓ env_example
✓ env_io_example
✓ scripts

In [93]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# Funções auxiliares específicas desta etapa
# ---------------------------------------------------------

def analisavel(nome_artefato):
    """
    Retorna True somente quando o artefato foi previamente
    identificado e validado pela etapa anterior.
    """
    return (
        isinstance(artefatos_analisaveis, dict)
        and artefatos_analisaveis.get(nome_artefato) is True
    )


def texto_lower(conteudo):
    if conteudo is None:
        return ""
    return str(conteudo).lower()


def contem_todos(conteudo, *termos):
    """
    Retorna True somente se TODOS os termos forem encontrados.
    Útil quando a simples presença de qualquer termo poderia
    produzir falso positivo.
    """
    texto = texto_lower(conteudo)

    return all(
        str(termo).lower() in texto
        for termo in termos
    )


def contem_algum(conteudo, *termos):
    """
    Retorna True se pelo menos um dos termos for encontrado.
    """
    texto = texto_lower(conteudo)

    return any(
        str(termo).lower() in texto
        for termo in termos
    )


def texto_job_gitlab(job):
    """
    Converte o conteúdo relevante de um job GitLab CI em texto
    para permitir análise determinística do próprio job.
    """

    if not isinstance(job, dict):
        return ""

    partes = []

    for chave in (
        "image",
        "stage",
        "before_script",
        "script",
        "after_script",
        "rules",
        "only",
        "except"
    ):

        valor = job.get(chave)

        if valor is None:
            continue

        if isinstance(valor, list):

            partes.extend(
                str(item)
                for item in valor
            )

        elif isinstance(valor, dict):

            partes.append(
                json.dumps(
                    valor,
                    ensure_ascii=False
                )
            )

        else:

            partes.append(
                str(valor)
            )

    return "\n".join(partes)


def localizar_jobs_sonar(pipeline_obj):
    """
    Localiza jobs que apresentam evidência de execução do SonarQube.
    """

    if not isinstance(pipeline_obj, dict):
        return []

    chaves_reservadas = {
        "image",
        "services",
        "variables",
        "stages",
        "workflow",
        "default",
        "include",
        "cache",
        "before_script",
        "after_script"
    }

    jobs = []

    for nome_job, configuracao in pipeline_obj.items():

        if nome_job in chaves_reservadas:
            continue

        if not isinstance(configuracao, dict):
            continue

        texto_job = texto_job_gitlab(
            configuracao
        )

        if contem_algum(
            texto_job,
            "dotnet-sonarscanner",
            "sonarscanner",
            "sonar.host.url",
            "sonar_token",
            "sonar.qualitygate.wait"
        ):

            jobs.append(
                (
                    nome_job,
                    configuracao,
                    texto_job
                )
            )

    return jobs


def extrair_variavel_env(
    conteudo,
    nomes_variaveis
):
    """
    Procura uma variável em arquivo .env no formato CHAVE=VALOR.
    """

    if not conteudo:
        return None, None

    nomes_normalizados = {
        nome.upper()
        for nome in nomes_variaveis
    }

    for linha in conteudo.splitlines():

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
            or "=" not in linha
        ):
            continue

        chave, valor = linha.split(
            "=",
            1
        )

        chave = chave.strip().upper()

        valor = valor.strip().strip(
            "\"'"
        )

        if chave in nomes_normalizados:

            return chave, valor

    return None, None


def extrair_versao_postgres_imagem(
    conteudo
):
    """
    Extrai versão de referências como:

    postgres:16
    postgres:16.4
    postgres:16-alpine
    postgresql:16
    """

    if not conteudo:
        return None

    match = re.search(
        r"\bpostgres(?:ql)?\s*:\s*"
        r"([0-9]+(?:\.[0-9]+){0,2})"
        r"(?:[-._a-zA-Z0-9]*)?",
        str(conteudo),
        flags=re.IGNORECASE
    )

    if match:
        return match.group(1)

    return None


def extrair_versao_postgres_env(
    conteudo
):
    """
    Procura versão PostgreSQL em variáveis de ambiente.
    """

    if not conteudo:
        return None, None

    # Variáveis explicitamente destinadas à versão
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_VERSION",
            "POSTGRESQL_VERSION",
            "PG_VERSION"
        }
    )

    if valor:

        match = re.search(
            r"([0-9]+(?:\.[0-9]+){0,2})",
            valor
        )

        if match:

            return (
                match.group(1),
                chave
            )

    # Variáveis que podem armazenar a imagem completa
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_IMAGE",
            "POSTGRESQL_IMAGE",
            "DATABASE_IMAGE",
            "DB_IMAGE"
        }
    )

    if valor:

        versao = extrair_versao_postgres_imagem(
            valor
        )

        if versao:

            return (
                versao,
                chave
            )

    return None, None


def extrair_versao_postgres_dockerfile(
    conteudo
):
    """
    Extrai a versão configurada do PostgreSQL em Dockerfiles.

    Reconhece, por exemplo:

    FROM postgres:16
    FROM postgres:16.4-alpine

    ARG POSTGRES_VERSION=16
    ENV POSTGRES_VERSION=16
    FROM postgres:${POSTGRES_VERSION}

    A versão identificada é configuracional e não comprova
    a versão efetivamente executada em produção.
    """

    if not conteudo:

        return None, None

    # -----------------------------------------------------
    # 1. Referência literal da imagem
    # -----------------------------------------------------

    versao_literal = extrair_versao_postgres_imagem(
        conteudo
    )

    if versao_literal:

        return (
            versao_literal,
            "imagem PostgreSQL literal"
        )


    # -----------------------------------------------------
    # 2. ARG/ENV com variável de versão
    # -----------------------------------------------------

    nomes_variaveis = (
        "POSTGRES_VERSION",
        "POSTGRESQL_VERSION",
        "PG_VERSION"
    )

    for nome_variavel in nomes_variaveis:

        padrao_variavel = (
            rf"^\s*(?:ARG|ENV)\s+"
            rf"{re.escape(nome_variavel)}"
            rf"\s*(?:=|\s)\s*"
            rf"[\"']?"
            rf"([0-9]+(?:\.[0-9]+){{0,2}})"
        )

        match_variavel = re.search(
            padrao_variavel,
            str(conteudo),
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )

        if not match_variavel:

            continue

        # Exige também uma referência à imagem PostgreSQL,
        # evitando interpretar uma variável isolada como prova
        # de que o Dockerfile usa PostgreSQL.
        if contem_algum(
            conteudo,
            "from postgres:",
            "from postgresql:"
        ):

            return (
                match_variavel.group(1),
                nome_variavel
            )

    return None, None


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if analisavel("csproj"):

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        # Em princípio não deve ocorrer, pois o arquivo já foi
        # validado na etapa anterior.
        print(
            "⚠ Inconsistência: .csproj havia sido validado, "
            "mas não pôde ser interpretado nesta etapa."
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if analisavel("pipeline"):

    # -----------------------------------------------------
    # SDK .NET utilizado no pipeline
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem_algum(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem_algum(
        pipeline,
        "dotnet build"
    )

    possui_release = contem_algum(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem_algum(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    evidencias[
        "Espera pelo Quality Gate"
    ] = contem_algum(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    #
    # Avalia allow_failure no job do SonarQube, e não em
    # qualquer outro job do pipeline.
    # -----------------------------------------------------

    quality_gate_bloqueante = False

    try:

        pipeline_obj = yaml.safe_load(
            pipeline
        )

        jobs_sonar = localizar_jobs_sonar(
            pipeline_obj
        )

        jobs_qg = []

        for (
            nome_job,
            configuracao_job,
            texto_job
        ) in jobs_sonar:

            if contem_algum(
                texto_job,
                "sonar.qualitygate.wait=true"
            ):

                jobs_qg.append(
                    (
                        nome_job,
                        configuracao_job
                    )
                )

        if jobs_qg:

            # Considera bloqueante se existir job com espera de
            # Quality Gate e allow_failure diferente de True.
            quality_gate_bloqueante = any(
                configuracao.get(
                    "allow_failure"
                ) is not True
                for _, configuracao in jobs_qg
            )

        else:

            quality_gate_bloqueante = False

    except Exception:

        # Não utiliza inferência textual genérica como substituto,
        # pois isso poderia associar allow_failure ao job errado.
        quality_gate_bloqueante = False


    evidencias[
        "Quality Gate bloqueante"
    ] = (
        evidencias[
            "Espera pelo Quality Gate"
        ]
        and quality_gate_bloqueante
    )


    # -----------------------------------------------------
    # Cache
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem_algum(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem_algum(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Merge Request
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem_algum(
        pipeline,
        "merge_request_event"
    )


    # -----------------------------------------------------
    # Branch main
    # -----------------------------------------------------

    possui_variavel_branch = contem_algum(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # -----------------------------------------------------
    # Testes automatizados
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem_algum(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy automatizado
    #
    # Dockerfile / Docker Compose de configuração não são
    # considerados prova de deploy automatizado.
    # Aqui são procurados comandos dentro do pipeline.
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem_algum(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção automática
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem_algum(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback automatizado
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem_algum(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if analisavel("renovate_json"):

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # -------------------------------------------------
        # Vulnerability Alerts
        # -------------------------------------------------

        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem_algum(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # -------------------------------------------------
        # Lock File Maintenance
        # -------------------------------------------------

        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem_algum(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        # Em princípio não deverá ocorrer porque o arquivo
        # somente chega aqui se foi validado.
        evidencias[
            "Renovate configurado"
        ] = None

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = None

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = None

        evidencias[
            "Vulnerability Alerts"
        ] = None

        evidencias[
            "Lock File Maintenance"
        ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if analisavel("pipeline"):

    possui_imagem_renovate = contem_algum(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem_algum(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    if evidencias[
        "Job Renovate no pipeline"
    ]:

        evidencias[
            "Regra schedule para Renovate"
        ] = contem_algum(
            pipeline,
            "schedule"
        )

        evidencias[
            "Execução manual do Renovate"
        ] = contem_algum(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )

    else:

        evidencias[
            "Regra schedule para Renovate"
        ] = False

        evidencias[
            "Execução manual do Renovate"
        ] = False

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva.
# Logs, branch Renovate ou MR criado pelo bot seriam
# necessários para estabelecer execução efetiva.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if analisavel("dockerfile"):

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if analisavel("dockerfile_postgres"):

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if analisavel("docker_compose"):

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem_algum(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem_algum(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem_algum(
            docker_compose,
            "external:"
        )
        and contem_algum(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem_algum(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if analisavel("program_cs"):

    evidencias[
        "Sentry integrado em runtime"
    ] = contem_algum(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )


    # -----------------------------------------------------
    # Health Check de banco
    #
    # Exige simultaneamente:
    # - evidência de infraestrutura de Health Check
    # - evidência de integração PostgreSQL/Npgsql
    # -----------------------------------------------------

    possui_healthcheck = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks",
        "healthcheck"
    )

    possui_npgsql_healthcheck = contem_algum(
        program_cs,
        "addnpgsql",
        ".addnpgsql",
        "npgsql"
    )

    evidencias[
        "Health Check de banco"
    ] = (
        possui_healthcheck
        and possui_npgsql_healthcheck
    )


    # -----------------------------------------------------
    # Health Check de API
    # -----------------------------------------------------

    evidencias[
        "Health Check de API"
    ] = (
        contem_algum(
            program_cs,
            "addurlgroup",
            "httpclient"
        )
        and contem_algum(
            program_cs,
            "health"
        )
    )


    # -----------------------------------------------------
    # Logging
    # -----------------------------------------------------

    evidencias[
        "Console Logging"
    ] = contem_algum(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if analisavel("appsettings"):

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem_algum(
        appsettings,
        "sentry",
        "\"dsn\""
    )

    evidencias[
        "Matomo configurado"
    ] = contem_algum(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem_algum(
        appsettings,
        "connectionstrings",
        "environment",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if analisavel("editorconfig"):

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = (
        contem_algum(
            editorconfig,
            "dotnet_diagnostic"
        )
        and contem_algum(
            editorconfig,
            "severity"
        )
    )


    # Não utiliza mais o termo isolado "s",
    # que produzia falsos positivos.
    evidencias[
        "Regras de segurança declaradas"
    ] = contem_algum(
        editorconfig,
        "security",
        "securityrule",
        "securityhotspot",
        "ca2100",
        "ca2119",
        "ca2122",
        "ca2135",
        "ca2300",
        "ca2301",
        "ca2302",
        "ca2305",
        "ca2310",
        "ca2311",
        "ca2312",
        "ca2321",
        "ca2322",
        "ca2326",
        "ca2327",
        "ca2328",
        "ca2329",
        "ca2330",
        "ca3001",
        "ca3002",
        "ca3003",
        "ca3004",
        "ca3005",
        "ca3006",
        "ca3007",
        "ca3008",
        "ca3009",
        "ca3010",
        "ca3011",
        "ca3012",
        "ca3061",
        "ca3075",
        "ca3076",
        "ca3077"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if analisavel("env_example"):

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem_algum(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host",
        "version"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if analisavel("env_io_example"):

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem_algum(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project",
        "host"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if analisavel("scripts"):

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts_analisaveis.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts_analisaveis.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem_algum(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem_algum(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem_algum(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )


    # Atenção: automação de ambiente local não equivale
    # a deploy automatizado da aplicação.
    evidencias[
        "Automação de ambiente local"
    ] = contem_algum(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# ---------------------------------------------------------
# Somente artefatos previamente validados participam da
# identificação da tecnologia de banco.
# ---------------------------------------------------------

if analisavel("appsettings"):

    fontes_banco.append(
        (
            "appsettings.json",
            appsettings
        )
    )


if analisavel("program_cs"):

    fontes_banco.append(
        (
            "Program.cs",
            program_cs
        )
    )


if analisavel("csproj"):

    fontes_banco.append(
        (
            ".csproj",
            csproj
        )
    )


if analisavel("dockerfile_postgres"):

    fontes_banco.append(
        (
            "Dockerfile.postgres",
            dockerfile_postgres
        )
    )


if analisavel("docker_compose"):

    fontes_banco.append(
        (
            "Docker Compose",
            docker_compose
        )
    )


if analisavel("dockerfile"):

    fontes_banco.append(
        (
            "Dockerfile",
            dockerfile
        )
    )


if analisavel("env_example"):

    fontes_banco.append(
        (
            ".env.example",
            env_example
        )
    )


if analisavel("env_io_example"):

    fontes_banco.append(
        (
            ".env.io.example",
            env_io_example
        )
    )


if conteudo_total_scripts:

    fontes_banco.append(
        (
            "Scripts",
            conteudo_total_scripts
        )
    )


# ---------------------------------------------------------
# Identificação do PostgreSQL
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for _, conteudo in fontes_banco
    )

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem_algum(
        conteudo_banco,
        "postgresql",
        "postgres:",
        "postgres_",
        "postgres-",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    fontes_dotnet = []

    if analisavel("program_cs"):

        fontes_dotnet.append(
            program_cs
        )

    if analisavel("csproj"):

        fontes_dotnet.append(
            csproj
        )

    if fontes_dotnet:

        conteudo_dotnet_banco = "\n".join(
            fontes_dotnet
        )

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = contem_algum(
            conteudo_dotnet_banco,
            "npgsql",
            "usenpgsql",
            "addnpgsql"
        )

    else:

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = None


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if evidencias[
        "PostgreSQL evidenciado"
    ] is True:

        tecnologia_banco = "PostgreSQL"

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Ordem de prioridade:
    # 1. Dockerfile.postgres
    # 2. Docker Compose com versão literal
    # 3. .env.example
    # 4. .env.io.example
    # 5. Dockerfile da aplicação
    # 6. Scripts
    #
    # A prioridade do Dockerfile.postgres decorre de ele ser
    # um artefato especificamente destinado à configuração
    # da imagem PostgreSQL.
    #
    # A versão representa evidência configuracional.
    # Não comprova a versão executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.1 Dockerfile.postgres
    # -----------------------------------------------------

    if analisavel("dockerfile_postgres"):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile_postgres
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile.postgres "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile.postgres"
                )


    # -----------------------------------------------------
    # 13.2 Docker Compose — versão literal
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("docker_compose")
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                docker_compose
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.3 .env.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.4 .env.io.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_io_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_io_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.io.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.5 Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("dockerfile")
    ):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile"
                )


    # -----------------------------------------------------
    # 13.6 Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                conteudo_total_scripts
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline,
    "database_technology": tecnologia_banco,
    "database_version": versao_banco,
    "database_version_source": fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
#
# ✓ = evidência identificada
# — = artefato válido analisado, evidência não identificada
# ? = artefato ausente, inválido ou execução não verificável
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0
Banco de dados: PostgreSQL
Versão configurada do banco: 18
Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Dockerfile PostgreSQL presente
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
✓ Health Check de banco
✓ Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ Parametrização de ambientes
✓ .env.io.example presente
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local
✓ PostgreSQL evidenciado
✓ Provider PostgreSQL (.NET)
✓ Versão PostgreSQL identificada

In [94]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [95]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
#
# Esta etapa não altera nem reclassifica as evidências.
# Ela apenas organiza os resultados determinísticos em um
# pacote estruturado para interpretação qualitativa pela IA.
# ---------------------------------------------------------


# ---------------------------------------------------------
# Verificações preliminares
# ---------------------------------------------------------

if not evidencias:

    raise ValueError(
        "Nenhuma evidência foi extraída."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


if not isinstance(
    artefatos_analisaveis,
    dict
):

    raise ValueError(
        "A estrutura de artefatos analisáveis não está disponível. "
        "Execute primeiro a etapa de identificação e validação."
    )


# ---------------------------------------------------------
# Função auxiliar
# ---------------------------------------------------------

def nome_se_analisavel(
    chave,
    nome
):
    """
    Retorna o nome do artefato somente se ele tiver sido
    previamente validado e habilitado para análise.

    Caso contrário, retorna None.
    """

    if artefatos_analisaveis.get(
        chave
    ) is True:

        return nome

    return None


# ---------------------------------------------------------
# Scripts efetivamente utilizados na análise
# ---------------------------------------------------------

scripts_analisados = sorted(
    scripts_analisaveis.keys()
) if isinstance(
    scripts_analisaveis,
    dict
) else []


# ---------------------------------------------------------
# Estado dos artefatos
#
# Permite que a interpretação assistida por IA diferencie:
#
# True  = artefato validado e analisado
# False = artefato encontrado, mas não habilitado
# ---------------------------------------------------------

estado_artefatos = {
    chave: bool(valor)
    for chave, valor in artefatos_analisaveis.items()
}


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    # -----------------------------------------------------
    # 1. Metadados da análise
    # -----------------------------------------------------

    "metadados_analise": {

        "tipo_analise":
            "extração determinística de evidências técnicas",

        "objetivo":
            (
                "Preparar evidências técnicas para interpretação "
                "qualitativa assistida por IA, sem alterar a "
                "classificação determinística."
            ),

        "semantica_tri_state": {

            "true":
                "Evidência diretamente identificada no artefato válido.",

            "false":
                (
                    "Artefato válido analisado, mas a evidência "
                    "não foi identificada."
                ),

            "null":
                (
                    "Evidência indeterminada devido à ausência, "
                    "invalidade ou insuficiência do artefato."
                )
        }
    },


    # -----------------------------------------------------
    # 2. Artefatos analisados
    # -----------------------------------------------------

    "artefatos_analisados": {

        "pipeline":
            nome_se_analisavel(
                "pipeline",
                pipeline_nome
            ),

        "csproj":
            nome_se_analisavel(
                "csproj",
                csproj_nome
            ),

        "renovate_json":
            nome_se_analisavel(
                "renovate_json",
                renovate_json_nome
            ),

        "renovate_setup":
            nome_se_analisavel(
                "renovate_setup",
                renovate_setup_nome
            ),

        "dockerfile":
            nome_se_analisavel(
                "dockerfile",
                dockerfile_nome
            ),

        "dockerfile_postgres":
            nome_se_analisavel(
                "dockerfile_postgres",
                dockerfile_postgres_nome
            ),

        "docker_compose":
            nome_se_analisavel(
                "docker_compose",
                docker_compose_nome
            ),

        "program_cs":
            nome_se_analisavel(
                "program_cs",
                program_cs_nome
            ),

        "appsettings":
            nome_se_analisavel(
                "appsettings",
                appsettings_nome
            ),

        "editorconfig":
            nome_se_analisavel(
                "editorconfig",
                editorconfig_nome
            ),

        "env_example":
            nome_se_analisavel(
                "env_example",
                env_example_nome
            ),

        "env_io_example":
            nome_se_analisavel(
                "env_io_example",
                env_io_example_nome
            ),

        "scripts":
            scripts_analisados
    },


    # -----------------------------------------------------
    # 3. Estado dos artefatos
    # -----------------------------------------------------

    "estado_artefatos": {

        "pipeline":
            estado_artefatos.get(
                "pipeline",
                False
            ),

        "csproj":
            estado_artefatos.get(
                "csproj",
                False
            ),

        "renovate_json":
            estado_artefatos.get(
                "renovate_json",
                False
            ),

        "renovate_setup":
            estado_artefatos.get(
                "renovate_setup",
                False
            ),

        "dockerfile":
            estado_artefatos.get(
                "dockerfile",
                False
            ),

        "dockerfile_postgres":
            estado_artefatos.get(
                "dockerfile_postgres",
                False
            ),

        "docker_compose":
            estado_artefatos.get(
                "docker_compose",
                False
            ),

        "program_cs":
            estado_artefatos.get(
                "program_cs",
                False
            ),

        "appsettings":
            estado_artefatos.get(
                "appsettings",
                False
            ),

        "editorconfig":
            estado_artefatos.get(
                "editorconfig",
                False
            ),

        "env_example":
            estado_artefatos.get(
                "env_example",
                False
            ),

        "env_io_example":
            estado_artefatos.get(
                "env_io_example",
                False
            ),

        "scripts":
            estado_artefatos.get(
                "scripts",
                False
            )
    },


    # -----------------------------------------------------
    # 4. Caracterização tecnológica
    # -----------------------------------------------------

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline,

        "database_technology":
            tecnologia.get(
                "database_technology"
            ),

        "database_version":
            tecnologia.get(
                "database_version"
            ),

        "database_version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "postgresql_dockerfile_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "postgresql_dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "postgresql_version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            )
    },


    # -----------------------------------------------------
    # 5. Integração contínua
    # -----------------------------------------------------

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },


    # -----------------------------------------------------
    # 6. Gerenciamento de dependências
    # -----------------------------------------------------

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },


    # -----------------------------------------------------
    # 7. Containerização
    # -----------------------------------------------------

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },


    # -----------------------------------------------------
    # 8. Observabilidade
    # -----------------------------------------------------

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },


    # -----------------------------------------------------
    # 9. Configuração e ambiente
    # -----------------------------------------------------

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },


    # -----------------------------------------------------
    # 10. Banco de dados
    #
    # Separado da configuração de ambiente porque representa
    # caracterização tecnológica própria.
    # -----------------------------------------------------

    "banco_de_dados": {

        "technology":
            tecnologia.get(
                "database_technology"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            ),

        "configured_version":
            tecnologia.get(
                "database_version"
            ),

        "version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "interpretation_constraint":
            (
                "A versão identificada representa a versão "
                "configurada nos artefatos analisados e não "
                "comprova a versão efetivamente executada "
                "no ambiente de produção."
            )
    },


    # -----------------------------------------------------
    # 11. Qualidade estática
    # -----------------------------------------------------

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },


    # -----------------------------------------------------
    # 12. Automação local
    # -----------------------------------------------------

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            ),

        "interpretation_constraint":
            (
                "Automação de ambiente local não constitui "
                "evidência de deploy automatizado da aplicação."
            )
    },


    # -----------------------------------------------------
    # 13. Entrega e recuperação
    # -----------------------------------------------------

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },


    # -----------------------------------------------------
    # 14. Classificação determinística
    #
    # A IA recebe a classificação pronta e não deve
    # recalculá-la.
    # -----------------------------------------------------

    "classificacao_deterministica": {

        "scope":
            (
                "maturidade da automação do pipeline "
                "segundo rubrica específica do estudo"
            ),

        "nivel":
            resultado_maturidade.get(
                "nivel"
            ),

        "classificacao":
            resultado_maturidade.get(
                "classificacao"
            ),

        "motivo":
            resultado_maturidade.get(
                "motivo"
            ),

        "lacunas":
            resultado_maturidade.get(
                "lacunas",
                []
            ),

        "indeterminacoes":
            resultado_maturidade.get(
                "indeterminacoes",
                []
            ),

        "capacidades_adicionais":
            resultado_maturidade.get(
                "capacidades_adicionais",
                []
            )
    },


    # -----------------------------------------------------
    # 15. Restrições interpretativas
    # -----------------------------------------------------

    "restricoes_interpretativas": [

        (
            "A interpretação assistida por IA deve partir "
            "exclusivamente das evidências estruturadas fornecidas."
        ),

        (
            "A IA não deve transformar ausência de evidência "
            "em evidência de ausência quando o valor for null."
        ),

        (
            "Valores false representam ausência da característica "
            "somente no escopo do artefato válido analisado."
        ),

        (
            "A presença de Dockerfile, Dockerfile.postgres ou "
            "Docker Compose não constitui, por si só, evidência "
            "de deploy automatizado."
        ),

        (
            "A presença de renovate.json comprova configuração "
            "do Renovate, mas não comprova sua execução efetiva."
        ),

        (
            "Um job Renovate no pipeline comprova orquestração "
            "configurada, mas não comprova execução efetiva."
        ),

        (
            "A configuração de espera pelo Quality Gate não "
            "implica Quality Gate bloqueante quando o job permite "
            "falha."
        ),

        (
            "Scripts de inicialização ou automação local não "
            "devem ser interpretados como automação de deployment."
        ),

        (
            "A versão PostgreSQL identificada representa "
            "configuração observada nos artefatos e não a versão "
            "necessariamente executada em produção."
        ),

        (
            "Dockerfile.postgres evidencia configuração de uma "
            "imagem/container PostgreSQL quando validado, mas não "
            "comprova a versão efetivamente executada em produção "
            "nem automação de deployment."
        ),

        (
            "A classificação determinística representa somente "
            "a maturidade da automação observável no pipeline e "
            "não a maturidade DevOps global da organização."
        )
    ]
}


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)


print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "metadados_analise": {
    "tipo_analise": "extração determinística de evidências técnicas",
    "objetivo": "Preparar evidências técnicas para interpretação qualitativa assistida por IA, sem alterar a classificação determinística.",
    "semantica_tri_state": {
      "true": "Evidência diretamente identificada no artefato válido.",
      "false": "Artefato válido analisado, mas a evidência não foi identificada.",
      "null": "Evidência indeterminada devido à ausência, invalidade ou insuficiência do artefato."
    }
  },
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (6).yml",
    "csproj": "Boilerplate4Dev (6).csproj",
    "renovate_json": "renovate (4).json",
    "renovate_setup": "RENOVATE_SETUP (4).md",
    "dockerfile": "Dockerfile (6)",
    "dockerfile_postgres": "Dockerfile (6).postgres",
    "docker_compose": "docker-compose (6).yaml",
    "program_cs": "Program (6).cs",
    "appsettings": "appsettings (6).json",
    "editorconfig": ".editorconfig (6)",
    "env_example": ".env (6).example",
    "env_io_example": ".env.io (4).example",
    "scripts": [
      "init (6).sql",
      "seed (4).sql",
      "start-db (6).ps1"
    ]
  },
  "estado_artefatos": {
    "pipeline": true,
    "csproj": true,
    "renovate_json": true,
    "renovate_setup": true,
    "dockerfile": true,
    "dockerfile_postgres": true,
    "docker_compose": true,
    "program_cs": true,
    "appsettings": true,
    "editorconfig": true,
    "env_example": true,
    "env_io_example": true,
    "scripts": true
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0",
    "database_technology": "PostgreSQL",
    "database_version": "18",
    "database_version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "postgresql_evidenced": true,
    "postgresql_dockerfile_present": true,
    "postgresql_dotnet_provider": true,
    "postgresql_version_identified": true
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "dockerfile_postgres_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": true,
    "api_health_check": true,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "environment_parameterization": true
  },
  "banco_de_dados": {
    "technology": "PostgreSQL",
    "postgresql_evidenced": true,
    "dockerfile_postgres_present": true,
    "dotnet_provider": true,
    "version_identified": true,
    "configured_version": "18",
    "version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "interpretation_constraint": "A versão identificada representa a versão configurada nos artefatos analisados e não comprova a versão efetivamente executada no ambiente de produção."
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true,
    "interpretation_constraint": "Automação de ambiente local não constitui evidência de deploy automatizado da aplicação."
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "scope": "maturidade da automação do pipeline segundo rubrica específica do estudo",
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.",
    "lacunas": [],
    "indeterminacoes": [],
    "capacidades_adicionais": []
  },
  "restricoes_interpretativas": [
    "A interpretação assistida por IA deve partir exclusivamente das evidências estruturadas fornecidas.",
    "A IA não deve transformar ausência de evidência em evidência de ausência quando o valor for null.",
    "Valores false representam ausência da característica somente no escopo do artefato válido analisado.",
    "A presença de Dockerfile, Dockerfile.postgres ou Docker Compose não constitui, por si só, evidência de deploy automatizado.",
    "A presença de renovate.json comprova configuração do Renovate, mas não comprova sua execução efetiva.",
    "Um job Renovate no pipeline comprova orquestração configurada, mas não comprova execução efetiva.",
    "A configuração de espera pelo Quality Gate não implica Quality Gate bloqueante quando o job permite falha.",
    "Scripts de inicialização ou automação local não devem ser interpretados como automação de deployment.",
    "A versão PostgreSQL identificada representa configuração observada nos artefatos e não a versão necessariamente executada em produção.",
    "Dockerfile.postgres evidencia configuração de uma imagem/container PostgreSQL quando validado, mas não comprova a versão efetivamente executada em produção nem automação de deployment.",
    "A classificação determinística representa somente a maturidade da automação observável no pipeline e não a maturidade DevOps global da organização."
  ]
}

In [96]:
# ---------------------------------------------------------
# PIPELINE AUTOMATION MATURITY CRITERIA
#
# Rubrica determinística específica deste estudo.
#
# Esta escala representa somente a maturidade da automação
# observável no pipeline analisado. Ela não representa um
# modelo geral de maturidade DevOps da organização.
# ---------------------------------------------------------

criterios_maturidade = """
Rubrica de maturidade da automação do pipeline utilizada neste estudo:

Nível 1 — Pipeline versionado
Existe um pipeline de integração contínua versionado, mas não foram
identificadas automações suficientes para caracterizar níveis superiores.

Nível 2 — Automação básica de CI
Existe pipeline versionado com automações pontuais de integração contínua,
como restore, build ou análise automatizada de qualidade, mas sem atendimento
integral aos critérios de uma CI estruturada.

Nível 3 — CI estruturada com controle de qualidade
Existe pipeline versionado com restore automatizado, build automatizado
e controle automatizado de qualidade, como SonarQube ou espera pelo
Quality Gate. Ainda podem permanecer lacunas relativas a testes
automatizados, bloqueio do Quality Gate, deploy, promoção entre ambientes
e rollback.

Nível 4 — Automação de entrega ponta a ponta
Além da integração contínua estruturada e dos controles de qualidade,
existem evidências de testes automatizados, Quality Gate bloqueante,
deploy automatizado, promoção automática entre ambientes e rollback
automatizado.

A classificação é baseada exclusivamente nas evidências técnicas
extraídas dos artefatos válidos analisados.

A presença de arquivos de configuração, isoladamente, não comprova
execução efetiva das práticas.

A rubrica é específica deste estudo e não deve ser interpretada como
classificação abrangente de maturidade DevOps da organização.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica e conservadora das evidências
relacionadas à automação do pipeline apresentadas abaixo.

A classificação da maturidade da automação do pipeline já foi calculada
deterministicamente pelo notebook.

Sua função NÃO é criar uma nova classificação independente.

Sua função é:

1. interpretar tecnicamente as evidências;
2. verificar se elas sustentam a classificação determinística;
3. identificar lacunas, limitações e evidências indeterminadas;
4. contextualizar capacidades adicionais observadas;
5. evitar inferências que ultrapassem os artefatos analisados.

A classificação avaliada refere-se exclusivamente à maturidade da
automação observável no pipeline segundo a rubrica específica deste estudo.

Ela NÃO representa a maturidade DevOps global do projeto, da equipe
ou da organização.


{criterios_maturidade}


EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}


REGRAS DA INTERPRETAÇÃO:

1. Utilize exclusivamente as evidências fornecidas.

2. Não presuma práticas, ferramentas, execuções ou resultados
   que não estejam evidenciados.

3. Não avalie a maturidade DevOps global do projeto ou da organização.

4. Avalie especificamente se as evidências sustentam a classificação
   determinística da maturidade da automação do pipeline.

5. Respeite rigorosamente a semântica tri-state:

   true
   = evidência positiva identificada em artefato válido;

   false
   = artefato válido analisado e característica não identificada;

   null
   = evidência indeterminada por ausência, invalidade ou insuficiência
     do artefato.

6. Null não significa ausência da prática.

7. False deve ser interpretado somente no escopo dos artefatos
   válidos efetivamente analisados.

8. Não transforme ausência de evidência em evidência de ausência
   quando o valor for null.

9. Quality Gate configurado ou aguardado não significa necessariamente
   Quality Gate bloqueante.

10. Se o job responsável pelo Quality Gate estiver configurado com
    allow_failure:true, o Quality Gate não deve ser interpretado como
    bloqueante.

11. SonarQube e Quality Gate caracterizam controle automatizado
    de qualidade, mas não comprovam testes automatizados.

12. A ausência de comandos de testes automatizados nos pipelines
    analisados deve ser interpretada somente no escopo desses pipelines.

13. A ausência de comandos de deploy no pipeline não prova que
    nenhum deployment seja realizado por processos externos ou manuais.

14. O mesmo princípio se aplica à promoção entre ambientes
    e ao rollback.

15. Dockerfile da aplicação demonstra definição automatizada de construção
    e empacotamento de imagem, mas não comprova deployment automatizado.

16. Dockerfile.postgres evidencia configuração de uma imagem/container
    PostgreSQL quando validado. Sua presença não comprova deployment
    automatizado, execução do banco em produção nem a versão efetivamente
    executada no ambiente de produção.

17. Docker Compose demonstra configuração de serviços, execução
    e integração de contêineres, mas sua presença não constitui
    evidência de deploy automatizado em pipeline.

18. Scripts locais, scripts de inicialização de banco, scripts de seed
    ou comandos de ambiente local não devem ser interpretados
    como deploy automatizado da aplicação.

19. A presença de renovate.json comprova configuração da ferramenta,
    mas não comprova sua execução efetiva.

20. Um job Renovate no pipeline comprova que existe orquestração
    configurada para a ferramenta, mas não comprova execução
    efetiva ou bem-sucedida.

21. Regras de schedule ou execução manual do Renovate representam
    possibilidades configuradas de execução e não histórico
    comprovado de execução.

22. Execução efetiva do Renovate exige evidências de runtime,
    como histórico de pipeline, logs, branches renovate/*,
    commits ou merge requests criados pela ferramenta.

23. A ausência de um job Renovate em determinada versão não deve
    ser interpretada automaticamente como ausência completa
    do Renovate caso sua configuração permaneça presente.

24. Sentry configurado em appsettings representa evidência
    configuracional.

25. Sentry identificado em Program.cs representa evidência mais forte
    de integração em runtime da aplicação.

26. Logging, health checks, Sentry e Matomo caracterizam capacidades
    relacionadas à observabilidade, monitoramento ou telemetria.

27. Essas capacidades de observabilidade não devem ser usadas,
    isoladamente, para aumentar o nível de maturidade da automação
    do pipeline.

28. A presença de regras no .editorconfig representa regras
    declaradas de análise estática.

29. Regras declaradas no .editorconfig não comprovam, isoladamente,
    que tenham sido aplicadas ou bloqueado o pipeline.

30. Evidências de PostgreSQL caracterizam a tecnologia de banco
    identificada nos artefatos analisados.

31. A identificação de Npgsql, UseNpgsql ou AddNpgsql pode sustentar
    a interpretação de utilização do provider PostgreSQL no .NET.

32. A versão PostgreSQL identificada em Dockerfile.postgres,
    Docker Compose, Dockerfile da aplicação, scripts ou arquivos
    de ambiente representa versão configurada nos artefatos.

33. A versão PostgreSQL configurada não comprova a versão efetivamente
    executada no servidor de produção. Ao interpretar a versão, preserve
    também database_version_source para indicar de qual artefato válido
    a configuração foi extraída.

34. A presença de PostgreSQL nos artefatos modernos não comprova,
    isoladamente, a execução de uma migração de Ingres para PostgreSQL.

35. Não inferir Continuous Delivery apenas pela existência
    de integração contínua, Docker ou scripts.

36. Não inferir Continuous Deployment sem evidência de deployment
    automatizado no pipeline.

37. Não utilizar capacidades adicionais, como cache, Renovate,
    observabilidade ou containerização, para elevar arbitrariamente
    o nível da rubrica.

38. Capacidades adicionais devem ser tratadas como elementos
    complementares da caracterização técnica da versão.

39. Compare explicitamente as evidências observadas com os critérios
    do nível atribuído pela classificação determinística.

40. Se as evidências forem compatíveis com a classificação,
    declare que a classificação é sustentada.

41. Se apenas parte das evidências necessárias puder ser confirmada,
    declare que a classificação é parcialmente sustentada.

42. Se houver contradição objetiva entre a classificação determinística
    e as evidências fornecidas, declare que a classificação
    não é sustentada.

43. Caso identifique inconsistência, descreva-a explicitamente,
    mas não substitua arbitrariamente a classificação calculada.

44. Diferencie claramente:
    - evidências positivas;
    - lacunas evidenciadas;
    - evidências indeterminadas;
    - capacidades adicionais.

45. Não atribua causalidade a partir da simples coexistência
    de ferramentas ou configurações.

46. Não trate evolução temporal como necessariamente monotônica.
    Uma versão posterior pode preservar, retirar ou alterar
    determinada automação sem que isso represente evolução
    linear de maturidade.

47. Utilize linguagem técnica, conservadora, rastreável
    e adequada a um trabalho acadêmico.

48. Evite expressões promocionais ou conclusões amplas como:
    "pipeline DevOps completo",
    "DevOps maduro",
    "automação total",
    "CI/CD plenamente implementado",
    quando essas afirmações não forem diretamente sustentadas
    pelas evidências.

49. Não apresente a rubrica do notebook como modelo universal
    de maturidade DevOps. Ela é uma operacionalização específica
    deste estudo.


PRODUZA A RESPOSTA EXATAMENTE COM A SEGUINTE ESTRUTURA:


### Avaliação da classificação

Classificação determinística:
[reproduza o nível e a classificação recebidos]

Avaliação:
[Sustentada / Parcialmente sustentada / Não sustentada]

Justificativa:
[explique de forma objetiva a relação entre as evidências
e os critérios do nível atribuído]


### Evidências que sustentam a avaliação

Apresente as principais evidências positivas que sustentam
a classificação, priorizando aquelas diretamente relacionadas
à rubrica.


### Lacunas identificadas

Apresente somente lacunas que estejam efetivamente evidenciadas
como false nos artefatos analisados.

Não inclua valores null como ausência.


### Evidências indeterminadas

Apresente os itens relevantes cujo valor seja null e explique,
quando necessário, que eles não podem ser classificados
como presentes nem ausentes.


### Capacidades adicionais observadas

Apresente capacidades tecnicamente relevantes, como cache,
Renovate, containerização, observabilidade, configuração
externalizada ou banco de dados, sem utilizá-las para elevar
arbitrariamente o nível da classificação.


### Limitações da interpretação

Explique as principais limitações decorrentes do escopo
dos artefatos analisados.

Destaque quando a configuração não comprovar execução efetiva.


### Síntese

Produza uma síntese curta, acadêmica e conservadora,
indicando se a classificação determinística é sustentada
pelas evidências disponíveis.
"""


# ---------------------------------------------------------
# RESULTADO
# ---------------------------------------------------------

print(
    "✓ Prompt de interpretação preparado."
)

print(
    "✓ Rubrica de maturidade alinhada "
    "à classificação determinística."
)

print(
    "✓ Restrições de interpretação incorporadas."
)

✓ Prompt de interpretação preparado.
✓ Rubrica de maturidade alinhada à classificação determinística.
✓ Restrições de interpretação incorporadas.

In [97]:
# ---------------------------------------------------------
# VERSION ANALYSIS STORAGE — CONTINUIDADE
#
# Reutiliza a estrutura longitudinal já inicializada na V1.
# Não reinicializa resultados_versoes, preservando as versões
# anteriormente armazenadas.
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):
    raise ValueError(
        "A estrutura resultados_versoes não está disponível. "
        "A V1 deve ter sido executada anteriormente na mesma sessão."
    )


print(
    "✓ Estrutura longitudinal existente."
)


if resultados_versoes:

    print(
        "✓ Versões já armazenadas:",
        ", ".join(
            sorted(
                resultados_versoes.keys()
            )
        )
    )

else:

    print(
        "⚠ A estrutura existe, mas ainda não possui versões armazenadas."
    )

✓ Estrutura longitudinal existente.
✓ Versões já armazenadas: V1, V2

In [98]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
#
# A IA atua exclusivamente como apoio à interpretação
# qualitativa das evidências previamente extraídas e
# classificadas de forma determinística.
#
# A IA não altera:
# - as evidências extraídas;
# - os estados tri-state;
# - o nível calculado;
# - a classificação determinística.
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Configuração da interpretação
# ---------------------------------------------------------

MODELO_IA = "gpt-5.6-terra"
ESFORCO_RACIOCINIO = "medium"


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

interpretacao_ia = None

metadados_interpretacao_ia = {
    "executada": False,
    "modelo": MODELO_IA,
    "esforco_raciocinio": ESFORCO_RACIOCINIO,
    "erro": None
}


# ---------------------------------------------------------
# 3. Recupera a chave da API
#
# A chave deve permanecer nos Secrets do Google Colab.
# Ela não deve ser inserida diretamente no notebook,
# impressa ou armazenada nos resultados da pesquisa.
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception as erro_chave:

    api_key = None

    metadados_interpretacao_ia[
        "erro"
    ] = (
        "Não foi possível acessar os Secrets "
        "do Google Colab."
    )


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 4. Validação das entradas
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or evidencias_para_ia is None
):

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not isinstance(
    evidencias_para_ia,
    dict
):

    raise TypeError(
        "evidencias_para_ia deve ser um dicionário."
    )


if (
    "prompt" not in globals()
    or not isinstance(
        prompt,
        str
    )
    or not prompt.strip()
):

    raise ValueError(
        "O prompt de interpretação ainda não foi criado "
        "ou está vazio."
    )


if (
    "resultado_maturidade" not in globals()
    or resultado_maturidade is None
):

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


if not isinstance(
    resultado_maturidade,
    dict
):

    raise TypeError(
        "resultado_maturidade deve ser um dicionário."
    )


# ---------------------------------------------------------
# 5. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 6. Instruções de sistema da interpretação
# ---------------------------------------------------------

instrucoes_interpretacao = """
Atue como avaliador técnico de evidências relacionadas à
automação de pipelines de software.

A análise integra um estudo acadêmico longitudinal sobre
modernização de software legado.

Sua interpretação deve ser:

- técnica;
- conservadora;
- rastreável;
- baseada exclusivamente nas evidências fornecidas;
- coerente com a semântica tri-state apresentada;
- limitada ao escopo dos artefatos analisados.

Não realize uma nova classificação independente.

Não altere o nível de maturidade calculado deterministicamente
pelo notebook.

Avalie se as evidências fornecidas sustentam a classificação
determinística.

Diferencie explicitamente:

- evidência positiva;
- ausência evidenciada;
- evidência indeterminada;
- configuração;
- orquestração;
- execução efetiva.

Não interprete ausência de evidência como evidência de ausência
quando o valor recebido for null.

Não avalie a maturidade DevOps global da organização.

A classificação fornecida representa exclusivamente a maturidade
da automação observável no pipeline segundo a rubrica específica
definida neste estudo.

Não atribua causalidade ou evolução de maturidade apenas pela
presença de ferramentas.

Não presuma evolução temporal monotônica.

Utilize linguagem adequada a um trabalho acadêmico.
"""


# ---------------------------------------------------------
# 7. Interpretação assistida por IA
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model=MODELO_IA,

        reasoning={
            "effort": ESFORCO_RACIOCINIO
        },

        instructions=(
            instrucoes_interpretacao
        ),

        input=prompt,

        store=False
    )


    # -----------------------------------------------------
    # 8. Recupera a interpretação textual
    # -----------------------------------------------------

    interpretacao_ia = (
        response.output_text.strip()
        if response.output_text
        else None
    )


    if not interpretacao_ia:

        raise ValueError(
            "A API respondeu, mas não retornou "
            "interpretação textual."
        )


    # -----------------------------------------------------
    # 9. Metadados da execução
    #
    # Não armazenamos API key nem outros segredos.
    # -----------------------------------------------------

    metadados_interpretacao_ia[
        "executada"
    ] = True

    metadados_interpretacao_ia[
        "modelo"
    ] = getattr(
        response,
        "model",
        MODELO_IA
    )

    metadados_interpretacao_ia[
        "response_id"
    ] = getattr(
        response,
        "id",
        None
    )


    # -----------------------------------------------------
    # 10. Uso de tokens, quando disponibilizado pela API
    # -----------------------------------------------------

    usage = getattr(
        response,
        "usage",
        None
    )


    if usage is not None:

        metadados_interpretacao_ia[
            "input_tokens"
        ] = getattr(
            usage,
            "input_tokens",
            None
        )

        metadados_interpretacao_ia[
            "output_tokens"
        ] = getattr(
            usage,
            "output_tokens",
            None
        )

        metadados_interpretacao_ia[
            "total_tokens"
        ] = getattr(
            usage,
            "total_tokens",
            None
        )


    # -----------------------------------------------------
    # 11. Resultado
    # -----------------------------------------------------

    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


    print(
        "\n"
        "-----------------------------------------"
    )

    print(
        "Modelo:",
        metadados_interpretacao_ia[
            "modelo"
        ]
    )

    print(
        "Esforço de raciocínio:",
        metadados_interpretacao_ia[
            "esforco_raciocinio"
        ]
    )

    print(
        "Execução:",
        "concluída"
    )


# ---------------------------------------------------------
# 12. Tratamento de erro
# ---------------------------------------------------------

except Exception as erro:

    interpretacao_ia = None

    metadados_interpretacao_ia[
        "executada"
    ] = False

    metadados_interpretacao_ia[
        "erro"
    ] = str(
        erro
    )


    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação

Classificação determinística:
Nível 3 — CI estruturada com controle de qualidade; classificação: Parcial/Emergente.

Avaliação:
Sustentada.

Justificativa:
As evidências disponíveis sustentam os critérios centrais do Nível 3 da rubrica específica do estudo: há evidência positiva de pipeline GitLab CI, restore automatizado de dependências .NET, build em modo Release e controle automatizado de qualidade por SonarQube, incluindo configuração de espera pelo Quality Gate. Essas práticas caracterizam uma integração contínua estruturada com controle de qualidade automatizado.

As lacunas identificadas são compatíveis com a classificação em Nível 3, pois não há evidência de testes automatizados no pipeline analisado, o Quality Gate não é bloqueante e não foram identificadas automações de deploy, promoção entre ambientes ou rollback. Portanto, as evidências não sustentam os requisitos adicionais previstos para o Nível 4. A classificação refere-se somente à automação observável nos artefatos analisados e não permite inferências sobre a maturidade DevOps global do projeto, equipe ou organização.

### Evidências que sustentam a avaliação

- **Pipeline de CI identificado:** `gitlab_ci: true` evidencia a presença de um pipeline GitLab CI no artefato válido analisado.
- **Restore automatizado:** `dotnet_restore: true` sustenta a automação de restauração de dependências no pipeline.
- **Build automatizado:** `build_release: true` evidencia compilação automatizada em configuração Release.
- **Controle automatizado de qualidade:** `sonarqube: true` identifica integração do pipeline com SonarQube.
- **Espera pelo Quality Gate:** `quality_gate_wait: true` indica que o pipeline possui configuração para aguardar o resultado do Quality Gate, caracterizando controle de qualidade integrado à orquestração de CI.
- **Regra para branch principal:** `main_branch_rule: true` indica uma regra configurada para a branch principal no escopo do pipeline analisado.
- **Regras estáticas declaradas:** `.editorconfig` está presente, com regras de analisadores e de segurança declaradas. Essa evidência é complementar ao controle de qualidade, embora a declaração isolada dessas regras não comprove sua aplicação ou bloqueio do pipeline.

### Lacunas identificadas

As seguintes lacunas foram identificadas como `false` no escopo dos artefatos válidos analisados:

- **Quality Gate não bloqueante:** `quality_gate_blocking: false`. Embora exista espera pelo Quality Gate, não há bloqueio efetivo do pipeline por seu resultado. Portanto, a configuração de qualidade não deve ser interpretada como gate bloqueante.
- **Testes automatizados não identificados no pipeline:** `automated_tests: false`. Não foram identificados comandos ou evidências de testes automatizados no pipeline analisado. Essa constatação é limitada aos artefatos de pipeline examinados.
- **Ausência de regra identificada para merge requests:** `merge_request_rule: false`. Não foi identificada regra específica para merge requests no pipeline analisado.
- **Deploy automatizado não identificado:** `automated_deploy: false`. Não foram identificados comandos ou mecanismos de deployment automatizado no escopo do pipeline analisado.
- **Promoção automatizada entre ambientes não identificada:** `automated_promotion: false`.
- **Rollback automatizado não identificado:** `automated_rollback: false`.
- **Orquestração do Renovate não identificada no pipeline:** `renovate_job: false`, `renovate_schedule: false` e `renovate_manual: false`. Não foram identificados job, agendamento ou acionamento manual do Renovate no pipeline analisado. Isso não invalida a configuração da ferramenta em arquivo próprio.

### Evidências indeterminadas

- **Execução efetiva do Renovate:** `renovate_effective_execution: null`. A configuração do Renovate está evidenciada, mas não há informação suficiente para afirmar ou negar sua execução efetiva. Não foram fornecidas evidências de runtime, como histórico de pipelines, logs, branches `renovate/*`, commits ou merge requests criados pela ferramenta.

Esse valor `null` deve ser tratado como indeterminação, e não como ausência da prática de atualização automatizada de dependências.

### Capacidades adicionais observadas

- **Gerenciamento de dependências configurado:** há evidência de configuração do Renovate (`renovate_configured: true`), incluindo gerenciadores para NuGet e Dockerfile, alertas de vulnerabilidade e manutenção de lock files. Trata-se de evidência de configuração; não há comprovação de orquestração no pipeline nem de execução efetiva.
- **Caches no pipeline:** `sonar_cache: true` e `nuget_cache: true` indicam mecanismos de cache configurados para análise SonarQube e dependências NuGet. Essas capacidades podem reduzir custos de execução, mas não alteram isoladamente o nível da rubrica.
- **Containerização:** há Dockerfile da aplicação, Dockerfile específico para PostgreSQL, build multiestágio, restore, build e publish no processo de imagem, além de Docker Compose com build, política de reinício, rede externa e proxy reverso. Essas evidências caracterizam configuração de construção, empacotamento e composição de contêineres; não comprovam deployment automatizado.
- **Configuração externalizada e parametrização de ambiente:** `appsettings`, arquivos de exemplo `.env` e `.env.io`, bem como `environment_parameterization: true`, indicam mecanismos configurados de parametrização de ambiente.
- **Observabilidade e monitoramento:** foram identificados Sentry configurado e integrado ao runtime, health checks de API e banco de dados, logging em console e configuração de Matomo. Essas capacidades são relevantes para observabilidade da aplicação, mas não devem elevar, por si só, a maturidade da automação do pipeline.
- **Banco de dados PostgreSQL:** PostgreSQL está evidenciado por Dockerfile específico, provider .NET e configuração de versão `18`, cuja fonte é o `Dockerfile.postgres`. A versão representa configuração observada no artefato, sem comprovar a versão efetivamente executada em produção.
- **Automação local:** scripts de inicialização e seed de banco, além de automação de ambiente local, foram identificados. Esses scripts caracterizam suporte ao ambiente local e não evidenciam deployment automatizado da aplicação.

### Limitações da interpretação

A interpretação está limitada aos artefatos válidos analisados e aos valores estruturados fornecidos. Não foram disponibilizados históricos de execução de pipelines, logs de jobs, resultados de SonarQube, resultados de testes, registros de deployment, evidências de promoção entre ambientes ou procedimentos de rollback executados.

A presença de configuração não comprova execução efetiva. Em particular:

- a configuração do Renovate não comprova que a ferramenta tenha sido executada;
- a presença de Dockerfiles e Docker Compose não comprova deployment automatizado;
- a espera pelo Quality Gate não comprova bloqueio do pipeline, pois `quality_gate_blocking` é `false`;
- regras declaradas no `.editorconfig` não comprovam, isoladamente, aplicação efetiva ou bloqueio por análise estática;
- a integração de Sentry em configuração e código indica capacidade de observabilidade, mas não comprova telemetria efetivamente recebida em ambiente operacional;
- a versão PostgreSQL configurada nos artefatos não comprova a versão efetivamente executada em produção.

Adicionalmente, a ausência de testes, deploy, promoção e rollback deve ser interpretada exclusivamente no escopo dos artefatos válidos examinados. Essas evidências não permitem concluir que tais práticas inexistam em processos externos, manuais ou em artefatos não analisados.

### Síntese

A classificação determinística em **Nível 3 — CI estruturada com controle de qualidade, Parcial/Emergente** é sustentada pelas evidências de pipeline GitLab CI, restore, build Release, SonarQube e espera pelo Quality Gate. As lacunas explicitamente identificadas — testes automatizados, Quality Gate bloqueante, deploy, promoção e rollback — são compatíveis com a não caracterização do Nível 4. As capacidades adicionais observadas complementam a caracterização técnica, mas não modificam a classificação da automação do pipeline segundo esta rubrica específica.

-----------------------------------------
Modelo: gpt-5.6-terra
Esforço de raciocínio: medium
Execução: concluída

In [99]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS
#
# Armazena uma cópia independente dos resultados da versão
# atualmente analisada para posterior análise longitudinal.
#
# A mesma célula pode ser reutilizada para V1, V2, V3 e V4.
# Basta definir:
#
# versao_atual
# snapshot_atual
#
# antes da execução.
# ---------------------------------------------------------

import copy

versao_atual = "V3"
snapshot_atual = "web-1.26.6-1"

if (
    "versao_atual" not in globals()
    or not isinstance(
        versao_atual,
        str
    )
    or not versao_atual.strip()
):

    raise ValueError(
        "A variável versao_atual não foi definida."
    )


versao_atual = versao_atual.strip().upper()


if (
    "snapshot_atual" not in globals()
    or not isinstance(
        snapshot_atual,
        str
    )
    or not snapshot_atual.strip()
):

    raise ValueError(
        f"O snapshot da {versao_atual} não foi definido "
        "na variável snapshot_atual."
    )


snapshot_atual = snapshot_atual.strip()


# ---------------------------------------------------------
# 2. Validação da estrutura longitudinal
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes não foi inicializada."
    )


# ---------------------------------------------------------
# 3. Validação das evidências
# ---------------------------------------------------------

if (
    "evidencias" not in globals()
    or not isinstance(
        evidencias,
        dict
    )
    or not evidencias
):

    raise ValueError(
        f"As evidências da {versao_atual} "
        "não estão disponíveis."
    )


# ---------------------------------------------------------
# 4. Validação da classificação determinística
# ---------------------------------------------------------

if (
    "resultado_maturidade" not in globals()
    or not isinstance(
        resultado_maturidade,
        dict
    )
):

    raise ValueError(
        f"A classificação determinística da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 5. Validação do pacote preparado para a IA
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or not isinstance(
        evidencias_para_ia,
        dict
    )
):

    raise ValueError(
        f"O pacote estruturado de evidências da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 6. Validação da caracterização tecnológica
# ---------------------------------------------------------

if (
    "tecnologia" not in globals()
    or not isinstance(
        tecnologia,
        dict
    )
):

    raise ValueError(
        f"A caracterização tecnológica da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 7. Validação dos artefatos analisáveis
# ---------------------------------------------------------

if (
    "artefatos_analisaveis" not in globals()
    or not isinstance(
        artefatos_analisaveis,
        dict
    )
):

    raise ValueError(
        f"A estrutura de artefatos analisáveis da "
        f"{versao_atual} não está disponível."
    )


# ---------------------------------------------------------
# 8. Captura segura da interpretação assistida por IA
# ---------------------------------------------------------

interpretacao_atual = (
    interpretacao_ia
    if (
        "interpretacao_ia" in globals()
        and interpretacao_ia is not None
    )
    else None
)


# ---------------------------------------------------------
# 9. Metadados da execução da IA
# ---------------------------------------------------------

metadados_ia_atual = (
    copy.deepcopy(
        metadados_interpretacao_ia
    )
    if (
        "metadados_interpretacao_ia" in globals()
        and isinstance(
            metadados_interpretacao_ia,
            dict
        )
    )
    else {
        "executada": False,
        "modelo_solicitado": None,
        "modelo_retornado": None,
        "esforco_raciocinio": None,
        "classificacao_deterministica_preservada": True,
        "response_id": None,
        "input_tokens": None,
        "output_tokens": None,
        "total_tokens": None,
        "erro": (
            "Metadados da interpretação assistida "
            "por IA não disponíveis."
        )
    }
)


# ---------------------------------------------------------
# 10. Scripts efetivamente analisados
# ---------------------------------------------------------

scripts_analisados_atual = (
    sorted(
        scripts_analisaveis.keys()
    )
    if (
        "scripts_analisaveis" in globals()
        and isinstance(
            scripts_analisaveis,
            dict
        )
    )
    else []
)


# ---------------------------------------------------------
# 11. Artefatos efetivamente analisados
# ---------------------------------------------------------

artefatos_analisados_atual = {

    "pipeline":
        pipeline_nome
        if artefatos_analisaveis.get(
            "pipeline"
        ) is True
        else None,

    "csproj":
        csproj_nome
        if artefatos_analisaveis.get(
            "csproj"
        ) is True
        else None,

    "renovate_json":
        renovate_json_nome
        if artefatos_analisaveis.get(
            "renovate_json"
        ) is True
        else None,

    "renovate_setup":
        renovate_setup_nome
        if artefatos_analisaveis.get(
            "renovate_setup"
        ) is True
        else None,

    "dockerfile":
        dockerfile_nome
        if artefatos_analisaveis.get(
            "dockerfile"
        ) is True
        else None,

    "dockerfile_postgres":
        dockerfile_postgres_nome
        if artefatos_analisaveis.get(
            "dockerfile_postgres"
        ) is True
        else None,

    "docker_compose":
        docker_compose_nome
        if artefatos_analisaveis.get(
            "docker_compose"
        ) is True
        else None,

    "program_cs":
        program_cs_nome
        if artefatos_analisaveis.get(
            "program_cs"
        ) is True
        else None,

    "appsettings":
        appsettings_nome
        if artefatos_analisaveis.get(
            "appsettings"
        ) is True
        else None,

    "editorconfig":
        editorconfig_nome
        if artefatos_analisaveis.get(
            "editorconfig"
        ) is True
        else None,

    "env_example":
        env_example_nome
        if artefatos_analisaveis.get(
            "env_example"
        ) is True
        else None,

    "env_io_example":
        env_io_example_nome
        if artefatos_analisaveis.get(
            "env_io_example"
        ) is True
        else None,

    "scripts":
        scripts_analisados_atual
}


# ---------------------------------------------------------
# 12. Estado dos artefatos
# ---------------------------------------------------------

estado_artefatos_atual = copy.deepcopy(
    artefatos_analisaveis
)


# ---------------------------------------------------------
# 13. Caracterização tecnológica
# ---------------------------------------------------------

caracterizacao_tecnologica_atual = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia.get(
            "database_technology"
        ),

    "database_version":
        tecnologia.get(
            "database_version"
        ),

    "database_version_source":
        tecnologia.get(
            "database_version_source"
        ),

    "postgresql_evidenced":
        evidencias.get(
            "PostgreSQL evidenciado"
        ),

    "postgresql_dockerfile_present":
        evidencias.get(
            "Dockerfile PostgreSQL presente"
        ),

    "postgresql_dotnet_provider":
        evidencias.get(
            "Provider PostgreSQL (.NET)"
        ),

    "postgresql_version_identified":
        evidencias.get(
            "Versão PostgreSQL identificada"
        )
}


# ---------------------------------------------------------
# 14. Registro consolidado da versão atual
# ---------------------------------------------------------

registro_atual = {

    "versao":
        versao_atual,

    "snapshot":
        snapshot_atual,

    "artefatos_analisados":
        copy.deepcopy(
            artefatos_analisados_atual
        ),

    "estado_artefatos":
        copy.deepcopy(
            estado_artefatos_atual
        ),

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "caracterizacao_tecnologica":
        copy.deepcopy(
            caracterizacao_tecnologica_atual
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_atual,

    "metadados_interpretacao_ia":
        copy.deepcopy(
            metadados_ia_atual
        )
}


# ---------------------------------------------------------
# 15. Verifica se a versão já estava armazenada
# ---------------------------------------------------------

versao_ja_existia = (
    versao_atual
    in resultados_versoes
)


# ---------------------------------------------------------
# 16. Armazena a versão atual
# ---------------------------------------------------------

resultados_versoes[
    versao_atual
] = copy.deepcopy(
    registro_atual
)


# ---------------------------------------------------------
# 17. Resultado
# ---------------------------------------------------------

if versao_ja_existia:

    print(
        f"✓ Resultados da {versao_atual} atualizados "
        "para a análise longitudinal."
    )

else:

    print(
        f"✓ Resultados da {versao_atual} armazenados "
        "para a análise longitudinal."
    )


registro_salvo = resultados_versoes[
    versao_atual
]


print(
    "✓ Snapshot:",
    registro_salvo[
        "snapshot"
    ]
)


print(
    "✓ Nível:",
    registro_salvo[
        "classificacao"
    ].get(
        "nivel"
    )
)


print(
    "✓ Classificação:",
    registro_salvo[
        "classificacao"
    ].get(
        "classificacao"
    )
)


print(
    "✓ Banco de dados:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_technology"
    )
)


print(
    "✓ Versão configurada do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version"
    )
)


print(
    "✓ Fonte da versão do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version_source"
    )
)


print(
    "✓ Dockerfile PostgreSQL:",
    (
        "analisado"
        if registro_salvo[
            "estado_artefatos"
        ].get(
            "dockerfile_postgres"
        ) is True
        else "não analisado"
    )
)


print(
    "✓ Interpretação assistida por IA:",
    (
        "disponível"
        if registro_salvo[
            "interpretacao_ia"
        ]
        else "não disponível"
    )
)


print(
    "✓ Versões atualmente armazenadas:",
    ", ".join(
        sorted(
            resultados_versoes.keys()
        )
    )
)

✓ Resultados da V3 armazenados para a análise longitudinal.
✓ Snapshot: web-1.26.6-1
✓ Nível: 3
✓ Classificação: Parcial/Emergente
✓ Banco de dados: PostgreSQL
✓ Versão configurada do banco: 18
✓ Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)
✓ Dockerfile PostgreSQL: analisado
✓ Interpretação assistida por IA: disponível
✓ Versões atualmente armazenadas: V1, V2, V3

## 6. V4 — Pipeline Technical Analysis

### 6.2 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.8-beta.1`**.

### 6.2 Análise dos Artefatos

In [100]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None


print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [101]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar "
            "o arquivo .csproj:"
        )

        print(
            erro
        )


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = (
            match_sdk.group(1)
        )


    # Pipeline versionado
    evidencias[
        "GitLab CI como código"
    ] = True


    # Restore
    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias[
        "Espera pelo Quality Gate"
    ] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias[
        "Quality Gate bloqueante"
    ] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if dockerfile_postgres:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = (
            evidencia_parametrizacao
        )

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo
        in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome
        in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# appsettings
if appsettings:

    fontes_banco.append(
        appsettings
    )


# Program.cs
if program_cs:

    fontes_banco.append(
        program_cs
    )


# .csproj
if csproj:

    fontes_banco.append(
        csproj
    )


# Docker Compose
if docker_compose:

    fontes_banco.append(
        docker_compose
    )


# Dockerfile.postgres
if dockerfile_postgres:

    fontes_banco.append(
        dockerfile_postgres
    )


# Dockerfile da aplicação
if dockerfile:

    fontes_banco.append(
        dockerfile
    )


# Scripts
if conteudo_total_scripts:

    fontes_banco.append(
        conteudo_total_scripts
    )


# ---------------------------------------------------------
# 13.1 Consolidação das fontes de banco
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for conteudo
        in fontes_banco
    )


    # -----------------------------------------------------
    # Identificação do PostgreSQL
    # -----------------------------------------------------

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem(
        conteudo_banco,
        "postgresql",
        "postgres",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    conteudo_dotnet_banco = "\n".join(
        [
            program_cs or "",
            csproj or ""
        ]
    )

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = contem(
        conteudo_dotnet_banco,
        "npgsql",
        "usenpgsql",
        "addnpgsql"
    )


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if (
        evidencias[
            "PostgreSQL evidenciado"
        ] is True
    ):

        tecnologia_banco = (
            "PostgreSQL"
        )

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Exemplos reconhecidos:
    #
    # FROM postgres:16
    # FROM postgres:16.4
    # FROM postgres:16-alpine
    # image: postgres:16
    # image: postgres:16.4-alpine
    #
    # A versão encontrada representa a versão configurada
    # no artefato analisado e não comprova a versão
    # efetivamente executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.2 Prioridade 1 — Dockerfile.postgres
    # -----------------------------------------------------

    if dockerfile_postgres:

        match_postgres_dockerfile_postgres = (
            buscar_regex(
                dockerfile_postgres,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile_postgres:

            versao_banco = (
                match_postgres_dockerfile_postgres.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile.postgres"
            )


    # -----------------------------------------------------
    # 13.3 Prioridade 2 — Docker Compose
    # -----------------------------------------------------

    if (
        versao_banco is None
        and docker_compose
    ):

        match_postgres_compose = (
            buscar_regex(
                docker_compose,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_compose:

            versao_banco = (
                match_postgres_compose.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.4 Prioridade 3 — Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and dockerfile
    ):

        match_postgres_dockerfile = (
            buscar_regex(
                dockerfile,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_dockerfile:

            versao_banco = (
                match_postgres_dockerfile.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Dockerfile"
            )


    # -----------------------------------------------------
    # 13.5 Prioridade 4 — Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        match_postgres_script = (
            buscar_regex(
                conteudo_total_scripts,
                r"\bpostgres(?:ql)?\s*:\s*"
                r"([0-9]+(?:\.[0-9]+){0,2})"
                r"(?:[-._a-z0-9]*)?"
            )
        )

        if match_postgres_script:

            versao_banco = (
                match_postgres_script.group(
                    1
                )
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia_banco,

    "database_version":
        versao_banco,

    "database_version_source":
        fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None
Banco de dados: None
Versão configurada do banco: None
Fonte da versão do banco: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Dockerfile PostgreSQL presente
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local
? PostgreSQL evidenciado
? Provider PostgreSQL (.NET)
? Versão PostgreSQL identificada

In [102]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (7)
Saving .env.example to .env (7).example
Saving .env.io.example to .env.io (5).example
Saving appsettings.json to appsettings (7).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (7).csproj
Saving docker-compose.yaml to docker-compose (7).yaml
Saving Dockerfile to Dockerfile (7)
Saving Dockerfile.postgres to Dockerfile (7).postgres
Saving gitlab-ci.yml to gitlab-ci (7).yml
Saving init.sql to init (7).sql
Saving Program.cs to Program (7).cs
Saving renovate.json to renovate (5).json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP (5).md
Saving seed.sql to seed (5).sql
Saving start-db.ps1 to start-db (7).ps1

✓ 15 arquivo(s) carregado(s):

  ✓ .editorconfig (7)
  ✓ .env (7).example
  ✓ .env.io (5).example
  ✓ Boilerplate4Dev (7).csproj
  ✓ Dockerfile (7)
  ✓ Dockerfile (7).postgres
  ✓ Program (7).cs
  ✓ RENOVATE_SETUP (5).md
  ✓ appsettings (7).json
  ✓ docker-compose (7).yaml
  ✓ gitlab-ci (7).yml
  ✓ init (7).sql
  ✓ renovate (5).json
  ✓ seed (5).sql
  ✓ start-db (7).ps1

In [103]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:

    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

dockerfile_postgres = None
dockerfile_postgres_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None

dockerfile_valido = None
dockerfile_postgres_valido = None
docker_compose_valido = None

program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):

    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):

    nome = nome_base(
        nome
    )

    # Remove sufixos adicionados pelo Colab:
    #
    # arquivo (1).json      -> arquivo.json
    # Dockerfile (2)        -> Dockerfile
    # Dockerfile (1).postgres -> Dockerfile.postgres
    #
    # O primeiro padrão trata o sufixo antes da extensão.
    # O segundo trata o sufixo no final do nome.

    nome = re.sub(
        r"\s*\(\d+\)(?=\.)",
        "",
        nome
    )

    nome = re.sub(
        r"\s*\(\d+\)$",
        "",
        nome
    )

    return (
        nome
        .lower()
        .strip()
    )


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):

    if not candidatos:

        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _
                in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(
    conteudo
):

    if conteudo is None:

        return None

    if isinstance(
        conteudo,
        bytes
    ):

        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []

candidatos_dockerfile = []
candidatos_dockerfile_postgres = []
candidatos_docker_compose = []

candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []


extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # -----------------------------------------------------
    # GitLab CI
    # -----------------------------------------------------

    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Projeto .NET
    # -----------------------------------------------------

    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Renovate
    # -----------------------------------------------------

    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile.postgres
    #
    # Deve ser identificado ANTES do Dockerfile genérico.
    # -----------------------------------------------------

    if normalizado == "dockerfile.postgres":

        candidatos_dockerfile_postgres.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Dockerfile da aplicação
    # -----------------------------------------------------

    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Docker Compose
    # -----------------------------------------------------

    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Program.cs
    # -----------------------------------------------------

    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # appsettings.json
    # -----------------------------------------------------

    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .editorconfig
    # -----------------------------------------------------

    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.io.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # .env.example
    # -----------------------------------------------------

    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # -----------------------------------------------------
    # Scripts
    # -----------------------------------------------------

    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile da aplicação"
)

dockerfile_postgres, dockerfile_postgres_nome = (
    selecionar_unico(
        candidatos_dockerfile_postgres,
        "Dockerfile.postgres"
    )
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

dockerfile_postgres = como_texto(
    dockerfile_postgres
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):

    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):

            continue

        if "=" not in linha:

            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # Continua utilizável para extração textual.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


def validar_dockerfile(
    conteudo,
    descricao
):

    if conteudo is None:

        return None

    if not arquivo_nao_vazio(
        conteudo
    ):

        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    possui_from = bool(
        re.search(
            r"^\s*FROM\s+\S+",
            conteudo,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    if possui_from:

        validacao_artefatos.append(
            f"✓ {descricao} estruturalmente válido "
            "(instrução FROM identificada)."
        )

        return True

    validacao_artefatos.append(
        f"✗ {descricao} sem instrução FROM identificada."
    )

    return False


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile da aplicação
# ---------------------------------------------------------

dockerfile_valido = validar_dockerfile(
    dockerfile,
    "Dockerfile"
)


# ---------------------------------------------------------
# 6. Dockerfile.postgres
# ---------------------------------------------------------

dockerfile_postgres_valido = validar_dockerfile(
    dockerfile_postgres,
    "Dockerfile.postgres"
)


# ---------------------------------------------------------
# 7. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):

                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 8. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador
            in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 9. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):

                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 10. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 11. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# 13. Artefatos habilitados para análise
#
# Somente artefatos explicitamente validados podem ser
# utilizados pela etapa de extração determinística.
# ---------------------------------------------------------

artefatos_analisaveis = {

    "pipeline":
        pipeline_valido is True,

    "csproj":
        csproj_valido is True,

    "renovate_json":
        renovate_json_valido is True,

    "renovate_setup":
        renovate_setup_valido is True,

    "dockerfile":
        dockerfile_valido is True,

    "dockerfile_postgres":
        dockerfile_postgres_valido is True,

    "docker_compose":
        docker_compose_valido is True,

    "program_cs":
        program_cs_valido is True,

    "appsettings":
        appsettings_valido is True,

    "editorconfig":
        editorconfig_valido is True,

    "env_example":
        env_example_valido is True,

    "env_io_example":
        env_io_example_valido is True
}


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

artefatos_analisaveis[
    "scripts"
] = any(
    estado is True
    for estado
    in scripts_validos.values()
)


# ---------------------------------------------------------
# Mantém apenas scripts validados para a etapa de análise
# ---------------------------------------------------------

scripts_analisaveis = {

    nome:
        conteudo

    for nome, conteudo
    in scripts.items()

    if scripts_validos.get(
        nome
    ) is True
}


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):

    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Dockerfile.postgres",
    dockerfile_postgres_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):

        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {

    "Pipeline":
        pipeline_valido,

    ".csproj":
        csproj_valido,

    "renovate.json":
        renovate_json_valido,

    "RENOVATE_SETUP.md":
        renovate_setup_valido,

    "Dockerfile":
        dockerfile_valido,

    "Dockerfile.postgres":
        dockerfile_postgres_valido,

    "Docker Compose":
        docker_compose_valido,

    "Program.cs":
        program_cs_valido,

    "appsettings.json":
        appsettings_valido,

    ".editorconfig":
        editorconfig_valido,

    ".env.example":
        env_example_valido,

    ".env.io.example":
        env_io_example_valido
}


for artefato, estado in (
    estados_validacao.items()
):

    if estado is True:

        simbolo = "✓"

    elif estado is False:

        simbolo = "✗"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )


# ---------------------------------------------------------
# Estado dos scripts
# ---------------------------------------------------------

if scripts_validos:

    print(
        "\nESTADO DOS SCRIPTS\n"
    )

    for nome in sorted(
        scripts_validos
    ):

        estado = scripts_validos[
            nome
        ]

        simbolo = (
            "✓"
            if estado is True
            else "✗"
        )

        print(
            f"{simbolo} {nome}"
        )


# ---------------------------------------------------------
# Artefatos disponíveis para extração
# ---------------------------------------------------------

print(
    "\nARTEFATOS HABILITADOS PARA EXTRAÇÃO\n"
)

for artefato, habilitado in (
    artefatos_analisaveis.items()
):

    simbolo = (
        "✓"
        if habilitado
        else "—"
    )

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (7).yml
✓ .csproj: Boilerplate4Dev (7).csproj
✓ renovate.json: renovate (5).json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP (5).md
✓ Dockerfile: Dockerfile (7)
✓ Dockerfile.postgres: Dockerfile (7).postgres
✓ Docker Compose: docker-compose (7).yaml
✓ Program.cs: Program (7).cs
✓ appsettings.json: appsettings (7).json
✓ .editorconfig: .editorconfig (7)
✓ .env.example: .env (7).example
✓ .env.io.example: .env.io (5).example
✓ Scripts: 3 arquivo(s)
    - init (7).sql
    - seed (5).sql
    - start-db (7).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Dockerfile.postgres estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (7).sql: script SQL legível e não vazio.
✓ seed (5).sql: script SQL legível e não vazio.
✓ start-db (7).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Dockerfile.postgres
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

ESTADO DOS SCRIPTS

✓ init (7).sql
✓ seed (5).sql
✓ start-db (7).ps1

ARTEFATOS HABILITADOS PARA EXTRAÇÃO

✓ pipeline
✓ csproj
✓ renovate_json
✓ renovate_setup
✓ dockerfile
✓ dockerfile_postgres
✓ docker_compose
✓ program_cs
✓ appsettings
✓ editorconfig
✓ env_example
✓ env_io_example
✓ scripts

In [104]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

tecnologia_banco = None
versao_banco = None
fonte_versao_banco = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# Funções auxiliares específicas desta etapa
# ---------------------------------------------------------

def analisavel(nome_artefato):
    """
    Retorna True somente quando o artefato foi previamente
    identificado e validado pela etapa anterior.
    """
    return (
        isinstance(artefatos_analisaveis, dict)
        and artefatos_analisaveis.get(nome_artefato) is True
    )


def texto_lower(conteudo):
    if conteudo is None:
        return ""
    return str(conteudo).lower()


def contem_todos(conteudo, *termos):
    """
    Retorna True somente se TODOS os termos forem encontrados.
    Útil quando a simples presença de qualquer termo poderia
    produzir falso positivo.
    """
    texto = texto_lower(conteudo)

    return all(
        str(termo).lower() in texto
        for termo in termos
    )


def contem_algum(conteudo, *termos):
    """
    Retorna True se pelo menos um dos termos for encontrado.
    """
    texto = texto_lower(conteudo)

    return any(
        str(termo).lower() in texto
        for termo in termos
    )


def texto_job_gitlab(job):
    """
    Converte o conteúdo relevante de um job GitLab CI em texto
    para permitir análise determinística do próprio job.
    """

    if not isinstance(job, dict):
        return ""

    partes = []

    for chave in (
        "image",
        "stage",
        "before_script",
        "script",
        "after_script",
        "rules",
        "only",
        "except"
    ):

        valor = job.get(chave)

        if valor is None:
            continue

        if isinstance(valor, list):

            partes.extend(
                str(item)
                for item in valor
            )

        elif isinstance(valor, dict):

            partes.append(
                json.dumps(
                    valor,
                    ensure_ascii=False
                )
            )

        else:

            partes.append(
                str(valor)
            )

    return "\n".join(partes)


def localizar_jobs_sonar(pipeline_obj):
    """
    Localiza jobs que apresentam evidência de execução do SonarQube.
    """

    if not isinstance(pipeline_obj, dict):
        return []

    chaves_reservadas = {
        "image",
        "services",
        "variables",
        "stages",
        "workflow",
        "default",
        "include",
        "cache",
        "before_script",
        "after_script"
    }

    jobs = []

    for nome_job, configuracao in pipeline_obj.items():

        if nome_job in chaves_reservadas:
            continue

        if not isinstance(configuracao, dict):
            continue

        texto_job = texto_job_gitlab(
            configuracao
        )

        if contem_algum(
            texto_job,
            "dotnet-sonarscanner",
            "sonarscanner",
            "sonar.host.url",
            "sonar_token",
            "sonar.qualitygate.wait"
        ):

            jobs.append(
                (
                    nome_job,
                    configuracao,
                    texto_job
                )
            )

    return jobs


def extrair_variavel_env(
    conteudo,
    nomes_variaveis
):
    """
    Procura uma variável em arquivo .env no formato CHAVE=VALOR.
    """

    if not conteudo:
        return None, None

    nomes_normalizados = {
        nome.upper()
        for nome in nomes_variaveis
    }

    for linha in conteudo.splitlines():

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
            or "=" not in linha
        ):
            continue

        chave, valor = linha.split(
            "=",
            1
        )

        chave = chave.strip().upper()

        valor = valor.strip().strip(
            "\"'"
        )

        if chave in nomes_normalizados:

            return chave, valor

    return None, None


def extrair_versao_postgres_imagem(
    conteudo
):
    """
    Extrai versão de referências como:

    postgres:16
    postgres:16.4
    postgres:16-alpine
    postgresql:16
    """

    if not conteudo:
        return None

    match = re.search(
        r"\bpostgres(?:ql)?\s*:\s*"
        r"([0-9]+(?:\.[0-9]+){0,2})"
        r"(?:[-._a-zA-Z0-9]*)?",
        str(conteudo),
        flags=re.IGNORECASE
    )

    if match:
        return match.group(1)

    return None


def extrair_versao_postgres_env(
    conteudo
):
    """
    Procura versão PostgreSQL em variáveis de ambiente.
    """

    if not conteudo:
        return None, None

    # Variáveis explicitamente destinadas à versão
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_VERSION",
            "POSTGRESQL_VERSION",
            "PG_VERSION"
        }
    )

    if valor:

        match = re.search(
            r"([0-9]+(?:\.[0-9]+){0,2})",
            valor
        )

        if match:

            return (
                match.group(1),
                chave
            )

    # Variáveis que podem armazenar a imagem completa
    chave, valor = extrair_variavel_env(
        conteudo,
        {
            "POSTGRES_IMAGE",
            "POSTGRESQL_IMAGE",
            "DATABASE_IMAGE",
            "DB_IMAGE"
        }
    )

    if valor:

        versao = extrair_versao_postgres_imagem(
            valor
        )

        if versao:

            return (
                versao,
                chave
            )

    return None, None


def extrair_versao_postgres_dockerfile(
    conteudo
):
    """
    Extrai a versão configurada do PostgreSQL em Dockerfiles.

    Reconhece, por exemplo:

    FROM postgres:16
    FROM postgres:16.4-alpine

    ARG POSTGRES_VERSION=16
    ENV POSTGRES_VERSION=16
    FROM postgres:${POSTGRES_VERSION}

    A versão identificada é configuracional e não comprova
    a versão efetivamente executada em produção.
    """

    if not conteudo:

        return None, None

    # -----------------------------------------------------
    # 1. Referência literal da imagem
    # -----------------------------------------------------

    versao_literal = extrair_versao_postgres_imagem(
        conteudo
    )

    if versao_literal:

        return (
            versao_literal,
            "imagem PostgreSQL literal"
        )


    # -----------------------------------------------------
    # 2. ARG/ENV com variável de versão
    # -----------------------------------------------------

    nomes_variaveis = (
        "POSTGRES_VERSION",
        "POSTGRESQL_VERSION",
        "PG_VERSION"
    )

    for nome_variavel in nomes_variaveis:

        padrao_variavel = (
            rf"^\s*(?:ARG|ENV)\s+"
            rf"{re.escape(nome_variavel)}"
            rf"\s*(?:=|\s)\s*"
            rf"[\"']?"
            rf"([0-9]+(?:\.[0-9]+){{0,2}})"
        )

        match_variavel = re.search(
            padrao_variavel,
            str(conteudo),
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )

        if not match_variavel:

            continue

        # Exige também uma referência à imagem PostgreSQL,
        # evitando interpretar uma variável isolada como prova
        # de que o Dockerfile usa PostgreSQL.
        if contem_algum(
            conteudo,
            "from postgres:",
            "from postgresql:"
        ):

            return (
                match_variavel.group(1),
                nome_variavel
            )

    return None, None


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if analisavel("csproj"):

    try:

        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        # Em princípio não deve ocorrer, pois o arquivo já foi
        # validado na etapa anterior.
        print(
            "⚠ Inconsistência: .csproj havia sido validado, "
            "mas não pôde ser interpretado nesta etapa."
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if analisavel("pipeline"):

    # -----------------------------------------------------
    # SDK .NET utilizado no pipeline
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:

        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem_algum(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem_algum(
        pipeline,
        "dotnet build"
    )

    possui_release = contem_algum(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem_algum(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    evidencias[
        "Espera pelo Quality Gate"
    ] = contem_algum(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    #
    # Avalia allow_failure no job do SonarQube, e não em
    # qualquer outro job do pipeline.
    # -----------------------------------------------------

    quality_gate_bloqueante = False

    try:

        pipeline_obj = yaml.safe_load(
            pipeline
        )

        jobs_sonar = localizar_jobs_sonar(
            pipeline_obj
        )

        jobs_qg = []

        for (
            nome_job,
            configuracao_job,
            texto_job
        ) in jobs_sonar:

            if contem_algum(
                texto_job,
                "sonar.qualitygate.wait=true"
            ):

                jobs_qg.append(
                    (
                        nome_job,
                        configuracao_job
                    )
                )

        if jobs_qg:

            # Considera bloqueante se existir job com espera de
            # Quality Gate e allow_failure diferente de True.
            quality_gate_bloqueante = any(
                configuracao.get(
                    "allow_failure"
                ) is not True
                for _, configuracao in jobs_qg
            )

        else:

            quality_gate_bloqueante = False

    except Exception:

        # Não utiliza inferência textual genérica como substituto,
        # pois isso poderia associar allow_failure ao job errado.
        quality_gate_bloqueante = False


    evidencias[
        "Quality Gate bloqueante"
    ] = (
        evidencias[
            "Espera pelo Quality Gate"
        ]
        and quality_gate_bloqueante
    )


    # -----------------------------------------------------
    # Cache
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem_algum(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem_algum(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Merge Request
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem_algum(
        pipeline,
        "merge_request_event"
    )


    # -----------------------------------------------------
    # Branch main
    # -----------------------------------------------------

    possui_variavel_branch = contem_algum(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias[
        "Regra para branch main"
    ] = (
        possui_variavel_branch
        and possui_main
    )


    # -----------------------------------------------------
    # Testes automatizados
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem_algum(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy automatizado
    #
    # Dockerfile / Docker Compose de configuração não são
    # considerados prova de deploy automatizado.
    # Aqui são procurados comandos dentro do pipeline.
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem_algum(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção automática
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem_algum(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback automatizado
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem_algum(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias[
        "GitLab CI como código"
    ] = None

    evidencias[
        "`dotnet restore` no CI"
    ] = None

    evidencias[
        "Build Release no CI"
    ] = None

    evidencias[
        "SonarQube"
    ] = None

    evidencias[
        "Espera pelo Quality Gate"
    ] = None

    evidencias[
        "Quality Gate bloqueante"
    ] = None

    evidencias[
        "Cache Sonar"
    ] = None

    evidencias[
        "Cache NuGet"
    ] = None

    evidencias[
        "Regra para Merge Request"
    ] = None

    evidencias[
        "Regra para branch main"
    ] = None

    evidencias[
        "Testes automatizados"
    ] = None

    evidencias[
        "Deploy automatizado"
    ] = None

    evidencias[
        "Promoção automática"
    ] = None

    evidencias[
        "Rollback automatizado"
    ] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if analisavel("renovate_json"):

    evidencias[
        "Renovate configurado"
    ] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # -------------------------------------------------
        # Vulnerability Alerts
        # -------------------------------------------------

        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem_algum(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # -------------------------------------------------
        # Lock File Maintenance
        # -------------------------------------------------

        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem_algum(
                renovate_json,
                "lockfilemaintenance"
            )

    except json.JSONDecodeError:

        # Em princípio não deverá ocorrer porque o arquivo
        # somente chega aqui se foi validado.
        evidencias[
            "Renovate configurado"
        ] = None

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = None

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = None

        evidencias[
            "Vulnerability Alerts"
        ] = None

        evidencias[
            "Lock File Maintenance"
        ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if analisavel("pipeline"):

    possui_imagem_renovate = contem_algum(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem_algum(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    if evidencias[
        "Job Renovate no pipeline"
    ]:

        evidencias[
            "Regra schedule para Renovate"
        ] = contem_algum(
            pipeline,
            "schedule"
        )

        evidencias[
            "Execução manual do Renovate"
        ] = contem_algum(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )

    else:

        evidencias[
            "Regra schedule para Renovate"
        ] = False

        evidencias[
            "Execução manual do Renovate"
        ] = False

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva.
# Logs, branch Renovate ou MR criado pelo bot seriam
# necessários para estabelecer execução efetiva.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if analisavel("dockerfile"):

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem_algum(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 5.1 Dockerfile.postgres
# ---------------------------------------------------------

if analisavel("dockerfile_postgres"):

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = True

else:

    evidencias[
        "Dockerfile PostgreSQL presente"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if analisavel("docker_compose"):

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem_algum(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem_algum(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem_algum(
            docker_compose,
            "external:"
        )
        and contem_algum(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem_algum(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if analisavel("program_cs"):

    evidencias[
        "Sentry integrado em runtime"
    ] = contem_algum(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )


    # -----------------------------------------------------
    # Health Check de banco
    #
    # Exige simultaneamente:
    # - evidência de infraestrutura de Health Check
    # - evidência de integração PostgreSQL/Npgsql
    # -----------------------------------------------------

    possui_healthcheck = contem_algum(
        program_cs,
        "addhealthchecks",
        "maphealthchecks",
        "healthcheck"
    )

    possui_npgsql_healthcheck = contem_algum(
        program_cs,
        "addnpgsql",
        ".addnpgsql",
        "npgsql"
    )

    evidencias[
        "Health Check de banco"
    ] = (
        possui_healthcheck
        and possui_npgsql_healthcheck
    )


    # -----------------------------------------------------
    # Health Check de API
    # -----------------------------------------------------

    evidencias[
        "Health Check de API"
    ] = (
        contem_algum(
            program_cs,
            "addurlgroup",
            "httpclient"
        )
        and contem_algum(
            program_cs,
            "health"
        )
    )


    # -----------------------------------------------------
    # Logging
    # -----------------------------------------------------

    evidencias[
        "Console Logging"
    ] = contem_algum(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if analisavel("appsettings"):

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem_algum(
        appsettings,
        "sentry",
        "\"dsn\""
    )

    evidencias[
        "Matomo configurado"
    ] = contem_algum(
        appsettings,
        "matomo"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem_algum(
        appsettings,
        "connectionstrings",
        "environment",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if analisavel("editorconfig"):

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = (
        contem_algum(
            editorconfig,
            "dotnet_diagnostic"
        )
        and contem_algum(
            editorconfig,
            "severity"
        )
    )


    # Não utiliza mais o termo isolado "s",
    # que produzia falsos positivos.
    evidencias[
        "Regras de segurança declaradas"
    ] = contem_algum(
        editorconfig,
        "security",
        "securityrule",
        "securityhotspot",
        "ca2100",
        "ca2119",
        "ca2122",
        "ca2135",
        "ca2300",
        "ca2301",
        "ca2302",
        "ca2305",
        "ca2310",
        "ca2311",
        "ca2312",
        "ca2321",
        "ca2322",
        "ca2326",
        "ca2327",
        "ca2328",
        "ca2329",
        "ca2330",
        "ca3001",
        "ca3002",
        "ca3003",
        "ca3004",
        "ca3005",
        "ca3006",
        "ca3007",
        "ca3008",
        "ca3009",
        "ca3010",
        "ca3011",
        "ca3012",
        "ca3061",
        "ca3075",
        "ca3076",
        "ca3077"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if analisavel("env_example"):

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem_algum(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host",
        "version"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if analisavel("env_io_example"):

    evidencias[
        ".env.io.example presente"
    ] = True

    evidencia_parametrizacao = contem_algum(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project",
        "host"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:

        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:

        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

conteudo_total_scripts = ""

if analisavel("scripts"):

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts_analisaveis.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts_analisaveis.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem_algum(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem_algum(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem_algum(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )


    # Atenção: automação de ambiente local não equivale
    # a deploy automatizado da aplicação.
    evidencias[
        "Automação de ambiente local"
    ] = contem_algum(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Tecnologia de banco de dados
# ---------------------------------------------------------

fontes_banco = []


# ---------------------------------------------------------
# Somente artefatos previamente validados participam da
# identificação da tecnologia de banco.
# ---------------------------------------------------------

if analisavel("appsettings"):

    fontes_banco.append(
        (
            "appsettings.json",
            appsettings
        )
    )


if analisavel("program_cs"):

    fontes_banco.append(
        (
            "Program.cs",
            program_cs
        )
    )


if analisavel("csproj"):

    fontes_banco.append(
        (
            ".csproj",
            csproj
        )
    )


if analisavel("dockerfile_postgres"):

    fontes_banco.append(
        (
            "Dockerfile.postgres",
            dockerfile_postgres
        )
    )


if analisavel("docker_compose"):

    fontes_banco.append(
        (
            "Docker Compose",
            docker_compose
        )
    )


if analisavel("dockerfile"):

    fontes_banco.append(
        (
            "Dockerfile",
            dockerfile
        )
    )


if analisavel("env_example"):

    fontes_banco.append(
        (
            ".env.example",
            env_example
        )
    )


if analisavel("env_io_example"):

    fontes_banco.append(
        (
            ".env.io.example",
            env_io_example
        )
    )


if conteudo_total_scripts:

    fontes_banco.append(
        (
            "Scripts",
            conteudo_total_scripts
        )
    )


# ---------------------------------------------------------
# Identificação do PostgreSQL
# ---------------------------------------------------------

if fontes_banco:

    conteudo_banco = "\n".join(
        str(conteudo)
        for _, conteudo in fontes_banco
    )

    evidencias[
        "PostgreSQL evidenciado"
    ] = contem_algum(
        conteudo_banco,
        "postgresql",
        "postgres:",
        "postgres_",
        "postgres-",
        "npgsql",
        "usenpgsql",
        "addnpgsql",
        "pg_dump"
    )


    # -----------------------------------------------------
    # Provider PostgreSQL utilizado pelo .NET
    # -----------------------------------------------------

    fontes_dotnet = []

    if analisavel("program_cs"):

        fontes_dotnet.append(
            program_cs
        )

    if analisavel("csproj"):

        fontes_dotnet.append(
            csproj
        )

    if fontes_dotnet:

        conteudo_dotnet_banco = "\n".join(
            fontes_dotnet
        )

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = contem_algum(
            conteudo_dotnet_banco,
            "npgsql",
            "usenpgsql",
            "addnpgsql"
        )

    else:

        evidencias[
            "Provider PostgreSQL (.NET)"
        ] = None


    # -----------------------------------------------------
    # Tecnologia de banco identificada
    # -----------------------------------------------------

    if evidencias[
        "PostgreSQL evidenciado"
    ] is True:

        tecnologia_banco = "PostgreSQL"

    else:

        tecnologia_banco = None


    # -----------------------------------------------------
    # Identificação da versão configurada do PostgreSQL
    #
    # Ordem de prioridade:
    # 1. Dockerfile.postgres
    # 2. Docker Compose com versão literal
    # 3. .env.example
    # 4. .env.io.example
    # 5. Dockerfile da aplicação
    # 6. Scripts
    #
    # A prioridade do Dockerfile.postgres decorre de ele ser
    # um artefato especificamente destinado à configuração
    # da imagem PostgreSQL.
    #
    # A versão representa evidência configuracional.
    # Não comprova a versão executada em produção.
    # -----------------------------------------------------

    versao_banco = None
    fonte_versao_banco = None


    # -----------------------------------------------------
    # 13.1 Dockerfile.postgres
    # -----------------------------------------------------

    if analisavel("dockerfile_postgres"):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile_postgres
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile.postgres "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile.postgres"
                )


    # -----------------------------------------------------
    # 13.2 Docker Compose — versão literal
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("docker_compose")
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                docker_compose
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Docker Compose"
            )


    # -----------------------------------------------------
    # 13.3 .env.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.4 .env.io.example
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("env_io_example")
    ):

        (
            versao_detectada,
            variavel_detectada
        ) = extrair_versao_postgres_env(
            env_io_example
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                f".env.io.example "
                f"({variavel_detectada})"
            )


    # -----------------------------------------------------
    # 13.5 Dockerfile da aplicação
    # -----------------------------------------------------

    if (
        versao_banco is None
        and analisavel("dockerfile")
    ):

        (
            versao_detectada,
            detalhe_versao
        ) = extrair_versao_postgres_dockerfile(
            dockerfile
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            if detalhe_versao:

                fonte_versao_banco = (
                    f"Dockerfile "
                    f"({detalhe_versao})"
                )

            else:

                fonte_versao_banco = (
                    "Dockerfile"
                )


    # -----------------------------------------------------
    # 13.6 Scripts
    # -----------------------------------------------------

    if (
        versao_banco is None
        and conteudo_total_scripts
    ):

        versao_detectada = (
            extrair_versao_postgres_imagem(
                conteudo_total_scripts
            )
        )

        if versao_detectada:

            versao_banco = (
                versao_detectada
            )

            fonte_versao_banco = (
                "Scripts"
            )


    # -----------------------------------------------------
    # Evidência da versão
    # -----------------------------------------------------

    evidencias[
        "Versão PostgreSQL identificada"
    ] = (
        versao_banco is not None
    )

else:

    evidencias[
        "PostgreSQL evidenciado"
    ] = None

    evidencias[
        "Provider PostgreSQL (.NET)"
    ] = None

    evidencias[
        "Versão PostgreSQL identificada"
    ] = None

    tecnologia_banco = None
    versao_banco = None
    fonte_versao_banco = None


# ---------------------------------------------------------
# 14. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline,
    "database_technology": tecnologia_banco,
    "database_version": versao_banco,
    "database_version_source": fonte_versao_banco
}


# ---------------------------------------------------------
# 15. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print(
    "Banco de dados:",
    tecnologia_banco
)

print(
    "Versão configurada do banco:",
    versao_banco
)

print(
    "Fonte da versão do banco:",
    fonte_versao_banco
)

print()


# ---------------------------------------------------------
# 16. Exibição tri-state
#
# ✓ = evidência identificada
# — = artefato válido analisado, evidência não identificada
# ? = artefato ausente, inválido ou execução não verificável
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:

        simbolo = "✓"

    elif valor is False:

        simbolo = "—"

    else:

        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0
Banco de dados: PostgreSQL
Versão configurada do banco: 18
Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Dockerfile PostgreSQL presente
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
✓ Health Check de banco
✓ Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ Parametrização de ambientes
✓ .env.io.example presente
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local
✓ PostgreSQL evidenciado
✓ Provider PostgreSQL (.NET)
✓ Versão PostgreSQL identificada

In [105]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [106]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
#
# Esta etapa não altera nem reclassifica as evidências.
# Ela apenas organiza os resultados determinísticos em um
# pacote estruturado para interpretação qualitativa pela IA.
# ---------------------------------------------------------


# ---------------------------------------------------------
# Verificações preliminares
# ---------------------------------------------------------

if not evidencias:

    raise ValueError(
        "Nenhuma evidência foi extraída."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


if not isinstance(
    artefatos_analisaveis,
    dict
):

    raise ValueError(
        "A estrutura de artefatos analisáveis não está disponível. "
        "Execute primeiro a etapa de identificação e validação."
    )


# ---------------------------------------------------------
# Função auxiliar
# ---------------------------------------------------------

def nome_se_analisavel(
    chave,
    nome
):
    """
    Retorna o nome do artefato somente se ele tiver sido
    previamente validado e habilitado para análise.

    Caso contrário, retorna None.
    """

    if artefatos_analisaveis.get(
        chave
    ) is True:

        return nome

    return None


# ---------------------------------------------------------
# Scripts efetivamente utilizados na análise
# ---------------------------------------------------------

scripts_analisados = sorted(
    scripts_analisaveis.keys()
) if isinstance(
    scripts_analisaveis,
    dict
) else []


# ---------------------------------------------------------
# Estado dos artefatos
#
# Permite que a interpretação assistida por IA diferencie:
#
# True  = artefato validado e analisado
# False = artefato encontrado, mas não habilitado
# ---------------------------------------------------------

estado_artefatos = {
    chave: bool(valor)
    for chave, valor in artefatos_analisaveis.items()
}


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    # -----------------------------------------------------
    # 1. Metadados da análise
    # -----------------------------------------------------

    "metadados_analise": {

        "tipo_analise":
            "extração determinística de evidências técnicas",

        "objetivo":
            (
                "Preparar evidências técnicas para interpretação "
                "qualitativa assistida por IA, sem alterar a "
                "classificação determinística."
            ),

        "semantica_tri_state": {

            "true":
                "Evidência diretamente identificada no artefato válido.",

            "false":
                (
                    "Artefato válido analisado, mas a evidência "
                    "não foi identificada."
                ),

            "null":
                (
                    "Evidência indeterminada devido à ausência, "
                    "invalidade ou insuficiência do artefato."
                )
        }
    },


    # -----------------------------------------------------
    # 2. Artefatos analisados
    # -----------------------------------------------------

    "artefatos_analisados": {

        "pipeline":
            nome_se_analisavel(
                "pipeline",
                pipeline_nome
            ),

        "csproj":
            nome_se_analisavel(
                "csproj",
                csproj_nome
            ),

        "renovate_json":
            nome_se_analisavel(
                "renovate_json",
                renovate_json_nome
            ),

        "renovate_setup":
            nome_se_analisavel(
                "renovate_setup",
                renovate_setup_nome
            ),

        "dockerfile":
            nome_se_analisavel(
                "dockerfile",
                dockerfile_nome
            ),

        "dockerfile_postgres":
            nome_se_analisavel(
                "dockerfile_postgres",
                dockerfile_postgres_nome
            ),

        "docker_compose":
            nome_se_analisavel(
                "docker_compose",
                docker_compose_nome
            ),

        "program_cs":
            nome_se_analisavel(
                "program_cs",
                program_cs_nome
            ),

        "appsettings":
            nome_se_analisavel(
                "appsettings",
                appsettings_nome
            ),

        "editorconfig":
            nome_se_analisavel(
                "editorconfig",
                editorconfig_nome
            ),

        "env_example":
            nome_se_analisavel(
                "env_example",
                env_example_nome
            ),

        "env_io_example":
            nome_se_analisavel(
                "env_io_example",
                env_io_example_nome
            ),

        "scripts":
            scripts_analisados
    },


    # -----------------------------------------------------
    # 3. Estado dos artefatos
    # -----------------------------------------------------

    "estado_artefatos": {

        "pipeline":
            estado_artefatos.get(
                "pipeline",
                False
            ),

        "csproj":
            estado_artefatos.get(
                "csproj",
                False
            ),

        "renovate_json":
            estado_artefatos.get(
                "renovate_json",
                False
            ),

        "renovate_setup":
            estado_artefatos.get(
                "renovate_setup",
                False
            ),

        "dockerfile":
            estado_artefatos.get(
                "dockerfile",
                False
            ),

        "dockerfile_postgres":
            estado_artefatos.get(
                "dockerfile_postgres",
                False
            ),

        "docker_compose":
            estado_artefatos.get(
                "docker_compose",
                False
            ),

        "program_cs":
            estado_artefatos.get(
                "program_cs",
                False
            ),

        "appsettings":
            estado_artefatos.get(
                "appsettings",
                False
            ),

        "editorconfig":
            estado_artefatos.get(
                "editorconfig",
                False
            ),

        "env_example":
            estado_artefatos.get(
                "env_example",
                False
            ),

        "env_io_example":
            estado_artefatos.get(
                "env_io_example",
                False
            ),

        "scripts":
            estado_artefatos.get(
                "scripts",
                False
            )
    },


    # -----------------------------------------------------
    # 4. Caracterização tecnológica
    # -----------------------------------------------------

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline,

        "database_technology":
            tecnologia.get(
                "database_technology"
            ),

        "database_version":
            tecnologia.get(
                "database_version"
            ),

        "database_version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "postgresql_dockerfile_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "postgresql_dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "postgresql_version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            )
    },


    # -----------------------------------------------------
    # 5. Integração contínua
    # -----------------------------------------------------

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },


    # -----------------------------------------------------
    # 6. Gerenciamento de dependências
    # -----------------------------------------------------

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },


    # -----------------------------------------------------
    # 7. Containerização
    # -----------------------------------------------------

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },


    # -----------------------------------------------------
    # 8. Observabilidade
    # -----------------------------------------------------

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },


    # -----------------------------------------------------
    # 9. Configuração e ambiente
    # -----------------------------------------------------

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },


    # -----------------------------------------------------
    # 10. Banco de dados
    #
    # Separado da configuração de ambiente porque representa
    # caracterização tecnológica própria.
    # -----------------------------------------------------

    "banco_de_dados": {

        "technology":
            tecnologia.get(
                "database_technology"
            ),

        "postgresql_evidenced":
            evidencias.get(
                "PostgreSQL evidenciado"
            ),

        "dockerfile_postgres_present":
            evidencias.get(
                "Dockerfile PostgreSQL presente"
            ),

        "dotnet_provider":
            evidencias.get(
                "Provider PostgreSQL (.NET)"
            ),

        "version_identified":
            evidencias.get(
                "Versão PostgreSQL identificada"
            ),

        "configured_version":
            tecnologia.get(
                "database_version"
            ),

        "version_source":
            tecnologia.get(
                "database_version_source"
            ),

        "interpretation_constraint":
            (
                "A versão identificada representa a versão "
                "configurada nos artefatos analisados e não "
                "comprova a versão efetivamente executada "
                "no ambiente de produção."
            )
    },


    # -----------------------------------------------------
    # 11. Qualidade estática
    # -----------------------------------------------------

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },


    # -----------------------------------------------------
    # 12. Automação local
    # -----------------------------------------------------

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            ),

        "interpretation_constraint":
            (
                "Automação de ambiente local não constitui "
                "evidência de deploy automatizado da aplicação."
            )
    },


    # -----------------------------------------------------
    # 13. Entrega e recuperação
    # -----------------------------------------------------

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },


    # -----------------------------------------------------
    # 14. Classificação determinística
    #
    # A IA recebe a classificação pronta e não deve
    # recalculá-la.
    # -----------------------------------------------------

    "classificacao_deterministica": {

        "scope":
            (
                "maturidade da automação do pipeline "
                "segundo rubrica específica do estudo"
            ),

        "nivel":
            resultado_maturidade.get(
                "nivel"
            ),

        "classificacao":
            resultado_maturidade.get(
                "classificacao"
            ),

        "motivo":
            resultado_maturidade.get(
                "motivo"
            ),

        "lacunas":
            resultado_maturidade.get(
                "lacunas",
                []
            ),

        "indeterminacoes":
            resultado_maturidade.get(
                "indeterminacoes",
                []
            ),

        "capacidades_adicionais":
            resultado_maturidade.get(
                "capacidades_adicionais",
                []
            )
    },


    # -----------------------------------------------------
    # 15. Restrições interpretativas
    # -----------------------------------------------------

    "restricoes_interpretativas": [

        (
            "A interpretação assistida por IA deve partir "
            "exclusivamente das evidências estruturadas fornecidas."
        ),

        (
            "A IA não deve transformar ausência de evidência "
            "em evidência de ausência quando o valor for null."
        ),

        (
            "Valores false representam ausência da característica "
            "somente no escopo do artefato válido analisado."
        ),

        (
            "A presença de Dockerfile, Dockerfile.postgres ou "
            "Docker Compose não constitui, por si só, evidência "
            "de deploy automatizado."
        ),

        (
            "A presença de renovate.json comprova configuração "
            "do Renovate, mas não comprova sua execução efetiva."
        ),

        (
            "Um job Renovate no pipeline comprova orquestração "
            "configurada, mas não comprova execução efetiva."
        ),

        (
            "A configuração de espera pelo Quality Gate não "
            "implica Quality Gate bloqueante quando o job permite "
            "falha."
        ),

        (
            "Scripts de inicialização ou automação local não "
            "devem ser interpretados como automação de deployment."
        ),

        (
            "A versão PostgreSQL identificada representa "
            "configuração observada nos artefatos e não a versão "
            "necessariamente executada em produção."
        ),

        (
            "Dockerfile.postgres evidencia configuração de uma "
            "imagem/container PostgreSQL quando validado, mas não "
            "comprova a versão efetivamente executada em produção "
            "nem automação de deployment."
        ),

        (
            "A classificação determinística representa somente "
            "a maturidade da automação observável no pipeline e "
            "não a maturidade DevOps global da organização."
        )
    ]
}


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)


print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "metadados_analise": {
    "tipo_analise": "extração determinística de evidências técnicas",
    "objetivo": "Preparar evidências técnicas para interpretação qualitativa assistida por IA, sem alterar a classificação determinística.",
    "semantica_tri_state": {
      "true": "Evidência diretamente identificada no artefato válido.",
      "false": "Artefato válido analisado, mas a evidência não foi identificada.",
      "null": "Evidência indeterminada devido à ausência, invalidade ou insuficiência do artefato."
    }
  },
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (7).yml",
    "csproj": "Boilerplate4Dev (7).csproj",
    "renovate_json": "renovate (5).json",
    "renovate_setup": "RENOVATE_SETUP (5).md",
    "dockerfile": "Dockerfile (7)",
    "dockerfile_postgres": "Dockerfile (7).postgres",
    "docker_compose": "docker-compose (7).yaml",
    "program_cs": "Program (7).cs",
    "appsettings": "appsettings (7).json",
    "editorconfig": ".editorconfig (7)",
    "env_example": ".env (7).example",
    "env_io_example": ".env.io (5).example",
    "scripts": [
      "init (7).sql",
      "seed (5).sql",
      "start-db (7).ps1"
    ]
  },
  "estado_artefatos": {
    "pipeline": true,
    "csproj": true,
    "renovate_json": true,
    "renovate_setup": true,
    "dockerfile": true,
    "dockerfile_postgres": true,
    "docker_compose": true,
    "program_cs": true,
    "appsettings": true,
    "editorconfig": true,
    "env_example": true,
    "env_io_example": true,
    "scripts": true
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0",
    "database_technology": "PostgreSQL",
    "database_version": "18",
    "database_version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "postgresql_evidenced": true,
    "postgresql_dockerfile_present": true,
    "postgresql_dotnet_provider": true,
    "postgresql_version_identified": true
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "dockerfile_postgres_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": true,
    "api_health_check": true,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "environment_parameterization": true
  },
  "banco_de_dados": {
    "technology": "PostgreSQL",
    "postgresql_evidenced": true,
    "dockerfile_postgres_present": true,
    "dotnet_provider": true,
    "version_identified": true,
    "configured_version": "18",
    "version_source": "Dockerfile.postgres (imagem PostgreSQL literal)",
    "interpretation_constraint": "A versão identificada representa a versão configurada nos artefatos analisados e não comprova a versão efetivamente executada no ambiente de produção."
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true,
    "interpretation_constraint": "Automação de ambiente local não constitui evidência de deploy automatizado da aplicação."
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "scope": "maturidade da automação do pipeline segundo rubrica específica do estudo",
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.",
    "lacunas": [],
    "indeterminacoes": [],
    "capacidades_adicionais": []
  },
  "restricoes_interpretativas": [
    "A interpretação assistida por IA deve partir exclusivamente das evidências estruturadas fornecidas.",
    "A IA não deve transformar ausência de evidência em evidência de ausência quando o valor for null.",
    "Valores false representam ausência da característica somente no escopo do artefato válido analisado.",
    "A presença de Dockerfile, Dockerfile.postgres ou Docker Compose não constitui, por si só, evidência de deploy automatizado.",
    "A presença de renovate.json comprova configuração do Renovate, mas não comprova sua execução efetiva.",
    "Um job Renovate no pipeline comprova orquestração configurada, mas não comprova execução efetiva.",
    "A configuração de espera pelo Quality Gate não implica Quality Gate bloqueante quando o job permite falha.",
    "Scripts de inicialização ou automação local não devem ser interpretados como automação de deployment.",
    "A versão PostgreSQL identificada representa configuração observada nos artefatos e não a versão necessariamente executada em produção.",
    "Dockerfile.postgres evidencia configuração de uma imagem/container PostgreSQL quando validado, mas não comprova a versão efetivamente executada em produção nem automação de deployment.",
    "A classificação determinística representa somente a maturidade da automação observável no pipeline e não a maturidade DevOps global da organização."
  ]
}

In [107]:
# ---------------------------------------------------------
# PIPELINE AUTOMATION MATURITY CRITERIA
#
# Rubrica determinística específica deste estudo.
#
# Esta escala representa somente a maturidade da automação
# observável no pipeline analisado. Ela não representa um
# modelo geral de maturidade DevOps da organização.
# ---------------------------------------------------------

criterios_maturidade = """
Rubrica de maturidade da automação do pipeline utilizada neste estudo:

Nível 1 — Pipeline versionado
Existe um pipeline de integração contínua versionado, mas não foram
identificadas automações suficientes para caracterizar níveis superiores.

Nível 2 — Automação básica de CI
Existe pipeline versionado com automações pontuais de integração contínua,
como restore, build ou análise automatizada de qualidade, mas sem atendimento
integral aos critérios de uma CI estruturada.

Nível 3 — CI estruturada com controle de qualidade
Existe pipeline versionado com restore automatizado, build automatizado
e controle automatizado de qualidade, como SonarQube ou espera pelo
Quality Gate. Ainda podem permanecer lacunas relativas a testes
automatizados, bloqueio do Quality Gate, deploy, promoção entre ambientes
e rollback.

Nível 4 — Automação de entrega ponta a ponta
Além da integração contínua estruturada e dos controles de qualidade,
existem evidências de testes automatizados, Quality Gate bloqueante,
deploy automatizado, promoção automática entre ambientes e rollback
automatizado.

A classificação é baseada exclusivamente nas evidências técnicas
extraídas dos artefatos válidos analisados.

A presença de arquivos de configuração, isoladamente, não comprova
execução efetiva das práticas.

A rubrica é específica deste estudo e não deve ser interpretada como
classificação abrangente de maturidade DevOps da organização.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica e conservadora das evidências
relacionadas à automação do pipeline apresentadas abaixo.

A classificação da maturidade da automação do pipeline já foi calculada
deterministicamente pelo notebook.

Sua função NÃO é criar uma nova classificação independente.

Sua função é:

1. interpretar tecnicamente as evidências;
2. verificar se elas sustentam a classificação determinística;
3. identificar lacunas, limitações e evidências indeterminadas;
4. contextualizar capacidades adicionais observadas;
5. evitar inferências que ultrapassem os artefatos analisados.

A classificação avaliada refere-se exclusivamente à maturidade da
automação observável no pipeline segundo a rubrica específica deste estudo.

Ela NÃO representa a maturidade DevOps global do projeto, da equipe
ou da organização.


{criterios_maturidade}


EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}


REGRAS DA INTERPRETAÇÃO:

1. Utilize exclusivamente as evidências fornecidas.

2. Não presuma práticas, ferramentas, execuções ou resultados
   que não estejam evidenciados.

3. Não avalie a maturidade DevOps global do projeto ou da organização.

4. Avalie especificamente se as evidências sustentam a classificação
   determinística da maturidade da automação do pipeline.

5. Respeite rigorosamente a semântica tri-state:

   true
   = evidência positiva identificada em artefato válido;

   false
   = artefato válido analisado e característica não identificada;

   null
   = evidência indeterminada por ausência, invalidade ou insuficiência
     do artefato.

6. Null não significa ausência da prática.

7. False deve ser interpretado somente no escopo dos artefatos
   válidos efetivamente analisados.

8. Não transforme ausência de evidência em evidência de ausência
   quando o valor for null.

9. Quality Gate configurado ou aguardado não significa necessariamente
   Quality Gate bloqueante.

10. Se o job responsável pelo Quality Gate estiver configurado com
    allow_failure:true, o Quality Gate não deve ser interpretado como
    bloqueante.

11. SonarQube e Quality Gate caracterizam controle automatizado
    de qualidade, mas não comprovam testes automatizados.

12. A ausência de comandos de testes automatizados nos pipelines
    analisados deve ser interpretada somente no escopo desses pipelines.

13. A ausência de comandos de deploy no pipeline não prova que
    nenhum deployment seja realizado por processos externos ou manuais.

14. O mesmo princípio se aplica à promoção entre ambientes
    e ao rollback.

15. Dockerfile da aplicação demonstra definição automatizada de construção
    e empacotamento de imagem, mas não comprova deployment automatizado.

16. Dockerfile.postgres evidencia configuração de uma imagem/container
    PostgreSQL quando validado. Sua presença não comprova deployment
    automatizado, execução do banco em produção nem a versão efetivamente
    executada no ambiente de produção.

17. Docker Compose demonstra configuração de serviços, execução
    e integração de contêineres, mas sua presença não constitui
    evidência de deploy automatizado em pipeline.

18. Scripts locais, scripts de inicialização de banco, scripts de seed
    ou comandos de ambiente local não devem ser interpretados
    como deploy automatizado da aplicação.

19. A presença de renovate.json comprova configuração da ferramenta,
    mas não comprova sua execução efetiva.

20. Um job Renovate no pipeline comprova que existe orquestração
    configurada para a ferramenta, mas não comprova execução
    efetiva ou bem-sucedida.

21. Regras de schedule ou execução manual do Renovate representam
    possibilidades configuradas de execução e não histórico
    comprovado de execução.

22. Execução efetiva do Renovate exige evidências de runtime,
    como histórico de pipeline, logs, branches renovate/*,
    commits ou merge requests criados pela ferramenta.

23. A ausência de um job Renovate em determinada versão não deve
    ser interpretada automaticamente como ausência completa
    do Renovate caso sua configuração permaneça presente.

24. Sentry configurado em appsettings representa evidência
    configuracional.

25. Sentry identificado em Program.cs representa evidência mais forte
    de integração em runtime da aplicação.

26. Logging, health checks, Sentry e Matomo caracterizam capacidades
    relacionadas à observabilidade, monitoramento ou telemetria.

27. Essas capacidades de observabilidade não devem ser usadas,
    isoladamente, para aumentar o nível de maturidade da automação
    do pipeline.

28. A presença de regras no .editorconfig representa regras
    declaradas de análise estática.

29. Regras declaradas no .editorconfig não comprovam, isoladamente,
    que tenham sido aplicadas ou bloqueado o pipeline.

30. Evidências de PostgreSQL caracterizam a tecnologia de banco
    identificada nos artefatos analisados.

31. A identificação de Npgsql, UseNpgsql ou AddNpgsql pode sustentar
    a interpretação de utilização do provider PostgreSQL no .NET.

32. A versão PostgreSQL identificada em Dockerfile.postgres,
    Docker Compose, Dockerfile da aplicação, scripts ou arquivos
    de ambiente representa versão configurada nos artefatos.

33. A versão PostgreSQL configurada não comprova a versão efetivamente
    executada no servidor de produção. Ao interpretar a versão, preserve
    também database_version_source para indicar de qual artefato válido
    a configuração foi extraída.

34. A presença de PostgreSQL nos artefatos modernos não comprova,
    isoladamente, a execução de uma migração de Ingres para PostgreSQL.

35. Não inferir Continuous Delivery apenas pela existência
    de integração contínua, Docker ou scripts.

36. Não inferir Continuous Deployment sem evidência de deployment
    automatizado no pipeline.

37. Não utilizar capacidades adicionais, como cache, Renovate,
    observabilidade ou containerização, para elevar arbitrariamente
    o nível da rubrica.

38. Capacidades adicionais devem ser tratadas como elementos
    complementares da caracterização técnica da versão.

39. Compare explicitamente as evidências observadas com os critérios
    do nível atribuído pela classificação determinística.

40. Se as evidências forem compatíveis com a classificação,
    declare que a classificação é sustentada.

41. Se apenas parte das evidências necessárias puder ser confirmada,
    declare que a classificação é parcialmente sustentada.

42. Se houver contradição objetiva entre a classificação determinística
    e as evidências fornecidas, declare que a classificação
    não é sustentada.

43. Caso identifique inconsistência, descreva-a explicitamente,
    mas não substitua arbitrariamente a classificação calculada.

44. Diferencie claramente:
    - evidências positivas;
    - lacunas evidenciadas;
    - evidências indeterminadas;
    - capacidades adicionais.

45. Não atribua causalidade a partir da simples coexistência
    de ferramentas ou configurações.

46. Não trate evolução temporal como necessariamente monotônica.
    Uma versão posterior pode preservar, retirar ou alterar
    determinada automação sem que isso represente evolução
    linear de maturidade.

47. Utilize linguagem técnica, conservadora, rastreável
    e adequada a um trabalho acadêmico.

48. Evite expressões promocionais ou conclusões amplas como:
    "pipeline DevOps completo",
    "DevOps maduro",
    "automação total",
    "CI/CD plenamente implementado",
    quando essas afirmações não forem diretamente sustentadas
    pelas evidências.

49. Não apresente a rubrica do notebook como modelo universal
    de maturidade DevOps. Ela é uma operacionalização específica
    deste estudo.


PRODUZA A RESPOSTA EXATAMENTE COM A SEGUINTE ESTRUTURA:


### Avaliação da classificação

Classificação determinística:
[reproduza o nível e a classificação recebidos]

Avaliação:
[Sustentada / Parcialmente sustentada / Não sustentada]

Justificativa:
[explique de forma objetiva a relação entre as evidências
e os critérios do nível atribuído]


### Evidências que sustentam a avaliação

Apresente as principais evidências positivas que sustentam
a classificação, priorizando aquelas diretamente relacionadas
à rubrica.


### Lacunas identificadas

Apresente somente lacunas que estejam efetivamente evidenciadas
como false nos artefatos analisados.

Não inclua valores null como ausência.


### Evidências indeterminadas

Apresente os itens relevantes cujo valor seja null e explique,
quando necessário, que eles não podem ser classificados
como presentes nem ausentes.


### Capacidades adicionais observadas

Apresente capacidades tecnicamente relevantes, como cache,
Renovate, containerização, observabilidade, configuração
externalizada ou banco de dados, sem utilizá-las para elevar
arbitrariamente o nível da classificação.


### Limitações da interpretação

Explique as principais limitações decorrentes do escopo
dos artefatos analisados.

Destaque quando a configuração não comprovar execução efetiva.


### Síntese

Produza uma síntese curta, acadêmica e conservadora,
indicando se a classificação determinística é sustentada
pelas evidências disponíveis.
"""


# ---------------------------------------------------------
# RESULTADO
# ---------------------------------------------------------

print(
    "✓ Prompt de interpretação preparado."
)

print(
    "✓ Rubrica de maturidade alinhada "
    "à classificação determinística."
)

print(
    "✓ Restrições de interpretação incorporadas."
)

✓ Prompt de interpretação preparado.
✓ Rubrica de maturidade alinhada à classificação determinística.
✓ Restrições de interpretação incorporadas.

In [108]:
# ---------------------------------------------------------
# VERSION ANALYSIS STORAGE — CONTINUIDADE
#
# Reutiliza a estrutura longitudinal já inicializada na V1.
# Não reinicializa resultados_versoes, preservando as versões
# anteriormente armazenadas.
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):
    raise ValueError(
        "A estrutura resultados_versoes não está disponível. "
        "A V1 deve ter sido executada anteriormente na mesma sessão."
    )


print(
    "✓ Estrutura longitudinal existente."
)


if resultados_versoes:

    print(
        "✓ Versões já armazenadas:",
        ", ".join(
            sorted(
                resultados_versoes.keys()
            )
        )
    )

else:

    print(
        "⚠ A estrutura existe, mas ainda não possui versões armazenadas."
    )

✓ Estrutura longitudinal existente.
✓ Versões já armazenadas: V1, V2, V3

In [109]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
#
# A IA atua exclusivamente como apoio à interpretação
# qualitativa das evidências previamente extraídas e
# classificadas de forma determinística.
#
# A IA não altera:
# - as evidências extraídas;
# - os estados tri-state;
# - o nível calculado;
# - a classificação determinística.
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Configuração da interpretação
# ---------------------------------------------------------

MODELO_IA = "gpt-5.6-terra"
ESFORCO_RACIOCINIO = "medium"


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

interpretacao_ia = None

metadados_interpretacao_ia = {
    "executada": False,
    "modelo": MODELO_IA,
    "esforco_raciocinio": ESFORCO_RACIOCINIO,
    "erro": None
}


# ---------------------------------------------------------
# 3. Recupera a chave da API
#
# A chave deve permanecer nos Secrets do Google Colab.
# Ela não deve ser inserida diretamente no notebook,
# impressa ou armazenada nos resultados da pesquisa.
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception as erro_chave:

    api_key = None

    metadados_interpretacao_ia[
        "erro"
    ] = (
        "Não foi possível acessar os Secrets "
        "do Google Colab."
    )


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 4. Validação das entradas
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or evidencias_para_ia is None
):

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not isinstance(
    evidencias_para_ia,
    dict
):

    raise TypeError(
        "evidencias_para_ia deve ser um dicionário."
    )


if (
    "prompt" not in globals()
    or not isinstance(
        prompt,
        str
    )
    or not prompt.strip()
):

    raise ValueError(
        "O prompt de interpretação ainda não foi criado "
        "ou está vazio."
    )


if (
    "resultado_maturidade" not in globals()
    or resultado_maturidade is None
):

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


if not isinstance(
    resultado_maturidade,
    dict
):

    raise TypeError(
        "resultado_maturidade deve ser um dicionário."
    )


# ---------------------------------------------------------
# 5. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 6. Instruções de sistema da interpretação
# ---------------------------------------------------------

instrucoes_interpretacao = """
Atue como avaliador técnico de evidências relacionadas à
automação de pipelines de software.

A análise integra um estudo acadêmico longitudinal sobre
modernização de software legado.

Sua interpretação deve ser:

- técnica;
- conservadora;
- rastreável;
- baseada exclusivamente nas evidências fornecidas;
- coerente com a semântica tri-state apresentada;
- limitada ao escopo dos artefatos analisados.

Não realize uma nova classificação independente.

Não altere o nível de maturidade calculado deterministicamente
pelo notebook.

Avalie se as evidências fornecidas sustentam a classificação
determinística.

Diferencie explicitamente:

- evidência positiva;
- ausência evidenciada;
- evidência indeterminada;
- configuração;
- orquestração;
- execução efetiva.

Não interprete ausência de evidência como evidência de ausência
quando o valor recebido for null.

Não avalie a maturidade DevOps global da organização.

A classificação fornecida representa exclusivamente a maturidade
da automação observável no pipeline segundo a rubrica específica
definida neste estudo.

Não atribua causalidade ou evolução de maturidade apenas pela
presença de ferramentas.

Não presuma evolução temporal monotônica.

Utilize linguagem adequada a um trabalho acadêmico.
"""


# ---------------------------------------------------------
# 7. Interpretação assistida por IA
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model=MODELO_IA,

        reasoning={
            "effort": ESFORCO_RACIOCINIO
        },

        instructions=(
            instrucoes_interpretacao
        ),

        input=prompt,

        store=False
    )


    # -----------------------------------------------------
    # 8. Recupera a interpretação textual
    # -----------------------------------------------------

    interpretacao_ia = (
        response.output_text.strip()
        if response.output_text
        else None
    )


    if not interpretacao_ia:

        raise ValueError(
            "A API respondeu, mas não retornou "
            "interpretação textual."
        )


    # -----------------------------------------------------
    # 9. Metadados da execução
    #
    # Não armazenamos API key nem outros segredos.
    # -----------------------------------------------------

    metadados_interpretacao_ia[
        "executada"
    ] = True

    metadados_interpretacao_ia[
        "modelo"
    ] = getattr(
        response,
        "model",
        MODELO_IA
    )

    metadados_interpretacao_ia[
        "response_id"
    ] = getattr(
        response,
        "id",
        None
    )


    # -----------------------------------------------------
    # 10. Uso de tokens, quando disponibilizado pela API
    # -----------------------------------------------------

    usage = getattr(
        response,
        "usage",
        None
    )


    if usage is not None:

        metadados_interpretacao_ia[
            "input_tokens"
        ] = getattr(
            usage,
            "input_tokens",
            None
        )

        metadados_interpretacao_ia[
            "output_tokens"
        ] = getattr(
            usage,
            "output_tokens",
            None
        )

        metadados_interpretacao_ia[
            "total_tokens"
        ] = getattr(
            usage,
            "total_tokens",
            None
        )


    # -----------------------------------------------------
    # 11. Resultado
    # -----------------------------------------------------

    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


    print(
        "\n"
        "-----------------------------------------"
    )

    print(
        "Modelo:",
        metadados_interpretacao_ia[
            "modelo"
        ]
    )

    print(
        "Esforço de raciocínio:",
        metadados_interpretacao_ia[
            "esforco_raciocinio"
        ]
    )

    print(
        "Execução:",
        "concluída"
    )


# ---------------------------------------------------------
# 12. Tratamento de erro
# ---------------------------------------------------------

except Exception as erro:

    interpretacao_ia = None

    metadados_interpretacao_ia[
        "executada"
    ] = False

    metadados_interpretacao_ia[
        "erro"
    ] = str(
        erro
    )


    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação

Classificação determinística:
Nível 3 — CI estruturada com controle de qualidade; classificação: **Parcial/Emergente**.

Avaliação:
**Sustentada**

Justificativa:
As evidências positivas identificadas nos artefatos válidos sustentam os critérios centrais do Nível 3 da rubrica: há pipeline GitLab CI versionado (`gitlab_ci: true`), execução automatizada de restore de dependências .NET (`dotnet_restore: true`), build em configuração Release (`build_release: true`) e integração com SonarQube (`sonarqube: true`), incluindo espera pelo Quality Gate (`quality_gate_wait: true`).

A classificação como Parcial/Emergente é compatível com as lacunas evidenciadas no escopo analisado. Em particular, não foram identificados testes automatizados, Quality Gate bloqueante, deploy automatizado, promoção automatizada entre ambientes ou rollback automatizado. Portanto, os critérios adicionais exigidos para o Nível 4 não estão demonstrados pelos artefatos válidos analisados.

A espera pelo Quality Gate caracteriza controle automatizado de qualidade, mas não deve ser interpretada como bloqueio efetivo do pipeline, pois `quality_gate_blocking` é `false`.

### Evidências que sustentam a avaliação

- **Pipeline versionado e orquestração de CI:** foi identificada configuração GitLab CI válida (`gitlab_ci: true`) no artefato de pipeline analisado.
- **Restore automatizado:** há evidência direta de execução de restore de dependências .NET no pipeline (`dotnet_restore: true`).
- **Build automatizado:** o pipeline contém evidência de build em configuração Release (`build_release: true`).
- **Controle automatizado de qualidade:** foram identificadas integração com SonarQube (`sonarqube: true`) e configuração de espera pelo Quality Gate (`quality_gate_wait: true`).
- **Regras de qualidade estática declaradas:** o `.editorconfig` está presente, com regras de analisadores e regras de segurança declaradas (`analyzer_rules_declared: true`; `security_rules_declared: true`). Essas regras complementam a caracterização de qualidade estática, embora sua presença isolada não demonstre bloqueio do pipeline.
- **Regra de execução para a branch principal:** foi identificada regra relacionada à branch principal (`main_branch_rule: true`), constituindo evidência de configuração de escopo de execução do pipeline.

Esses elementos atendem ao conjunto de evidências requerido pela rubrica para caracterizar CI estruturada com restore, build e controle automatizado de qualidade.

### Lacunas identificadas

As seguintes lacunas estão evidenciadas como `false` nos artefatos válidos analisados:

- **Testes automatizados no pipeline:** não foram identificados comandos ou mecanismos de testes automatizados (`automated_tests: false`). Essa ausência é limitada ao escopo do pipeline analisado e não permite concluir que testes não existam em processos externos ou em outros artefatos não analisados.
- **Quality Gate bloqueante:** embora exista espera pelo Quality Gate, não foi identificado comportamento bloqueante (`quality_gate_blocking: false`). Assim, o controle de qualidade não é evidenciado como impeditivo para a progressão do pipeline.
- **Deploy automatizado:** não foram identificadas evidências de deployment automatizado (`automated_deploy: false`).
- **Promoção automatizada entre ambientes:** não foram identificadas evidências de promoção automatizada (`automated_promotion: false`).
- **Rollback automatizado:** não foram identificadas evidências de rollback automatizado (`automated_rollback: false`).
- **Regra específica para merge requests:** não foi identificada regra de pipeline para merge requests (`merge_request_rule: false`).
- **Orquestração do Renovate no pipeline:** não foi identificado job Renovate (`renovate_job: false`), nem configuração de execução agendada (`renovate_schedule: false`) ou manual (`renovate_manual: false`) nos artefatos analisados.

As lacunas relativas a testes, bloqueio de Quality Gate, deploy, promoção e rollback são diretamente compatíveis com a não caracterização do Nível 4 pela rubrica aplicada.

### Evidências indeterminadas

- **Execução efetiva do Renovate:** `renovate_effective_execution` possui valor `null`. Portanto, não há base para classificar a execução da ferramenta como presente ou ausente. A configuração do Renovate está evidenciada, mas não foram fornecidos artefatos de runtime, como histórico de pipelines, logs, branches `renovate/*`, commits ou merge requests atribuíveis à ferramenta, que comprovassem execução efetiva.

Esse valor `null` não deve ser interpretado como ausência de uso do Renovate; ele representa indeterminação decorrente da insuficiência das evidências disponíveis para confirmar execução em runtime.

### Capacidades adicionais observadas

- **Cache no pipeline:** foram identificados cache do Sonar (`sonar_cache: true`) e cache do NuGet (`nuget_cache: true`). Essas configurações podem caracterizar otimização operacional do pipeline, mas não alteram, isoladamente, o nível da rubrica.
- **Gerenciamento de dependências configurado:** há configuração válida do Renovate (`renovate_configured: true`), com gerenciadores para NuGet e Dockerfile, além de configurações relacionadas a alertas de vulnerabilidade e manutenção de lock files. Trata-se de evidência de configuração, não de execução efetiva.
- **Containerização da aplicação:** há Dockerfile, Dockerfile específico para PostgreSQL e Docker Compose válidos. Foram identificados build multiestágio, restore, build e publish no Dockerfile da aplicação, além de configuração de build no Docker Compose.
- **Configuração de serviços em contêineres:** o Docker Compose contém evidências de política de reinício, rede externa e proxy reverso. Esses elementos caracterizam configuração de execução e integração de contêineres, mas não comprovam deploy automatizado pelo pipeline.
- **Automação local:** foram identificados scripts de inicialização e seed de banco de dados, além de automação de ambiente local. Tais recursos não constituem evidência de deployment automatizado da aplicação.
- **Observabilidade e telemetria:** há configuração de Sentry e evidência de integração em runtime da aplicação, health checks de API e banco de dados, logging em console e configuração de Matomo. Essas capacidades caracterizam observabilidade, monitoramento ou telemetria e não elevam, por si sós, a maturidade da automação do pipeline.
- **Configuração externalizada:** estão presentes `appsettings`, arquivos de exemplo de variáveis de ambiente e parametrização de ambiente. Isso evidencia práticas de configuração, sem demonstrar execução em ambientes específicos.
- **Banco de dados PostgreSQL:** PostgreSQL está evidenciado por Dockerfile específico, provider .NET e configuração de versão `18`. A versão foi extraída do `Dockerfile.postgres` e representa a versão configurada no artefato, não a versão necessariamente executada em produção.

### Limitações da interpretação

A interpretação está restrita aos artefatos válidos listados na extração determinística. Não foram fornecidos históricos de execução de pipelines, logs de jobs, resultados de análise do SonarQube, resultados de Quality Gate, registros de testes, evidências de publicação de imagens, ambientes de destino, registros de deploy ou eventos de rollback.

A presença do pipeline configura **orquestração** de etapas de CI, e as evidências de restore, build, SonarQube e espera pelo Quality Gate demonstram práticas declaradas no pipeline analisado. Contudo, os artefatos fornecidos não comprovam, por si só, a **execução efetiva e bem-sucedida** dessas etapas em runtime.

De modo semelhante:

- a configuração do Renovate comprova configuração da ferramenta, mas não sua execução efetiva;
- Dockerfile e Docker Compose comprovam configuração de construção, empacotamento e composição de serviços, mas não deployment automatizado;
- scripts locais de banco de dados comprovam automação local, não promoção ou publicação da aplicação;
- Sentry em `appsettings` constitui evidência configuracional, enquanto sua identificação em `Program.cs` fornece evidência mais forte de integração em runtime da aplicação, sem demonstrar operação efetiva em produção;
- a versão PostgreSQL `18` é uma configuração observada no `Dockerfile.postgres`, não uma confirmação da versão em execução em ambiente produtivo.

Além disso, as lacunas identificadas como `false` aplicam-se exclusivamente aos artefatos válidos analisados. Elas não permitem concluir que práticas equivalentes inexistam em ferramentas externas, processos manuais, outros repositórios ou pipelines não incluídos no escopo.

### Síntese

A classificação determinística de **Nível 3 — CI estruturada com controle de qualidade, Parcial/Emergente** é sustentada pelas evidências disponíveis. O pipeline analisado apresenta restore, build e controle automatizado de qualidade com SonarQube e espera pelo Quality Gate. Contudo, a ausência evidenciada de testes automatizados, Quality Gate bloqueante, deploy, promoção entre ambientes e rollback impede a caracterização de automação de entrega ponta a ponta no escopo da rubrica adotada.

-----------------------------------------
Modelo: gpt-5.6-terra
Esforço de raciocínio: medium
Execução: concluída

In [110]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS
#
# Armazena uma cópia independente dos resultados da versão
# atualmente analisada para posterior análise longitudinal.
#
# A mesma célula pode ser reutilizada para V1, V2, V3 e V4.
# Basta definir:
#
# versao_atual
# snapshot_atual
#
# antes da execução.
# ---------------------------------------------------------

import copy

versao_atual = "V4"
snapshot_atual = "web-1.26.8-beta.1"

if (
    "versao_atual" not in globals()
    or not isinstance(
        versao_atual,
        str
    )
    or not versao_atual.strip()
):

    raise ValueError(
        "A variável versao_atual não foi definida."
    )


versao_atual = versao_atual.strip().upper()


if (
    "snapshot_atual" not in globals()
    or not isinstance(
        snapshot_atual,
        str
    )
    or not snapshot_atual.strip()
):

    raise ValueError(
        f"O snapshot da {versao_atual} não foi definido "
        "na variável snapshot_atual."
    )


snapshot_atual = snapshot_atual.strip()


# ---------------------------------------------------------
# 2. Validação da estrutura longitudinal
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes não foi inicializada."
    )


# ---------------------------------------------------------
# 3. Validação das evidências
# ---------------------------------------------------------

if (
    "evidencias" not in globals()
    or not isinstance(
        evidencias,
        dict
    )
    or not evidencias
):

    raise ValueError(
        f"As evidências da {versao_atual} "
        "não estão disponíveis."
    )


# ---------------------------------------------------------
# 4. Validação da classificação determinística
# ---------------------------------------------------------

if (
    "resultado_maturidade" not in globals()
    or not isinstance(
        resultado_maturidade,
        dict
    )
):

    raise ValueError(
        f"A classificação determinística da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 5. Validação do pacote preparado para a IA
# ---------------------------------------------------------

if (
    "evidencias_para_ia" not in globals()
    or not isinstance(
        evidencias_para_ia,
        dict
    )
):

    raise ValueError(
        f"O pacote estruturado de evidências da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 6. Validação da caracterização tecnológica
# ---------------------------------------------------------

if (
    "tecnologia" not in globals()
    or not isinstance(
        tecnologia,
        dict
    )
):

    raise ValueError(
        f"A caracterização tecnológica da {versao_atual} "
        "não está disponível."
    )


# ---------------------------------------------------------
# 7. Validação dos artefatos analisáveis
# ---------------------------------------------------------

if (
    "artefatos_analisaveis" not in globals()
    or not isinstance(
        artefatos_analisaveis,
        dict
    )
):

    raise ValueError(
        f"A estrutura de artefatos analisáveis da "
        f"{versao_atual} não está disponível."
    )


# ---------------------------------------------------------
# 8. Captura segura da interpretação assistida por IA
# ---------------------------------------------------------

interpretacao_atual = (
    interpretacao_ia
    if (
        "interpretacao_ia" in globals()
        and interpretacao_ia is not None
    )
    else None
)


# ---------------------------------------------------------
# 9. Metadados da execução da IA
# ---------------------------------------------------------

metadados_ia_atual = (
    copy.deepcopy(
        metadados_interpretacao_ia
    )
    if (
        "metadados_interpretacao_ia" in globals()
        and isinstance(
            metadados_interpretacao_ia,
            dict
        )
    )
    else {
        "executada": False,
        "modelo_solicitado": None,
        "modelo_retornado": None,
        "esforco_raciocinio": None,
        "classificacao_deterministica_preservada": True,
        "response_id": None,
        "input_tokens": None,
        "output_tokens": None,
        "total_tokens": None,
        "erro": (
            "Metadados da interpretação assistida "
            "por IA não disponíveis."
        )
    }
)


# ---------------------------------------------------------
# 10. Scripts efetivamente analisados
# ---------------------------------------------------------

scripts_analisados_atual = (
    sorted(
        scripts_analisaveis.keys()
    )
    if (
        "scripts_analisaveis" in globals()
        and isinstance(
            scripts_analisaveis,
            dict
        )
    )
    else []
)


# ---------------------------------------------------------
# 11. Artefatos efetivamente analisados
# ---------------------------------------------------------

artefatos_analisados_atual = {

    "pipeline":
        pipeline_nome
        if artefatos_analisaveis.get(
            "pipeline"
        ) is True
        else None,

    "csproj":
        csproj_nome
        if artefatos_analisaveis.get(
            "csproj"
        ) is True
        else None,

    "renovate_json":
        renovate_json_nome
        if artefatos_analisaveis.get(
            "renovate_json"
        ) is True
        else None,

    "renovate_setup":
        renovate_setup_nome
        if artefatos_analisaveis.get(
            "renovate_setup"
        ) is True
        else None,

    "dockerfile":
        dockerfile_nome
        if artefatos_analisaveis.get(
            "dockerfile"
        ) is True
        else None,

    "dockerfile_postgres":
        dockerfile_postgres_nome
        if artefatos_analisaveis.get(
            "dockerfile_postgres"
        ) is True
        else None,

    "docker_compose":
        docker_compose_nome
        if artefatos_analisaveis.get(
            "docker_compose"
        ) is True
        else None,

    "program_cs":
        program_cs_nome
        if artefatos_analisaveis.get(
            "program_cs"
        ) is True
        else None,

    "appsettings":
        appsettings_nome
        if artefatos_analisaveis.get(
            "appsettings"
        ) is True
        else None,

    "editorconfig":
        editorconfig_nome
        if artefatos_analisaveis.get(
            "editorconfig"
        ) is True
        else None,

    "env_example":
        env_example_nome
        if artefatos_analisaveis.get(
            "env_example"
        ) is True
        else None,

    "env_io_example":
        env_io_example_nome
        if artefatos_analisaveis.get(
            "env_io_example"
        ) is True
        else None,

    "scripts":
        scripts_analisados_atual
}


# ---------------------------------------------------------
# 12. Estado dos artefatos
# ---------------------------------------------------------

estado_artefatos_atual = copy.deepcopy(
    artefatos_analisaveis
)


# ---------------------------------------------------------
# 13. Caracterização tecnológica
# ---------------------------------------------------------

caracterizacao_tecnologica_atual = {

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline,

    "database_technology":
        tecnologia.get(
            "database_technology"
        ),

    "database_version":
        tecnologia.get(
            "database_version"
        ),

    "database_version_source":
        tecnologia.get(
            "database_version_source"
        ),

    "postgresql_evidenced":
        evidencias.get(
            "PostgreSQL evidenciado"
        ),

    "postgresql_dockerfile_present":
        evidencias.get(
            "Dockerfile PostgreSQL presente"
        ),

    "postgresql_dotnet_provider":
        evidencias.get(
            "Provider PostgreSQL (.NET)"
        ),

    "postgresql_version_identified":
        evidencias.get(
            "Versão PostgreSQL identificada"
        )
}


# ---------------------------------------------------------
# 14. Registro consolidado da versão atual
# ---------------------------------------------------------

registro_atual = {

    "versao":
        versao_atual,

    "snapshot":
        snapshot_atual,

    "artefatos_analisados":
        copy.deepcopy(
            artefatos_analisados_atual
        ),

    "estado_artefatos":
        copy.deepcopy(
            estado_artefatos_atual
        ),

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "caracterizacao_tecnologica":
        copy.deepcopy(
            caracterizacao_tecnologica_atual
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_atual,

    "metadados_interpretacao_ia":
        copy.deepcopy(
            metadados_ia_atual
        )
}


# ---------------------------------------------------------
# 15. Verifica se a versão já estava armazenada
# ---------------------------------------------------------

versao_ja_existia = (
    versao_atual
    in resultados_versoes
)


# ---------------------------------------------------------
# 16. Armazena a versão atual
# ---------------------------------------------------------

resultados_versoes[
    versao_atual
] = copy.deepcopy(
    registro_atual
)


# ---------------------------------------------------------
# 17. Resultado
# ---------------------------------------------------------

if versao_ja_existia:

    print(
        f"✓ Resultados da {versao_atual} atualizados "
        "para a análise longitudinal."
    )

else:

    print(
        f"✓ Resultados da {versao_atual} armazenados "
        "para a análise longitudinal."
    )


registro_salvo = resultados_versoes[
    versao_atual
]


print(
    "✓ Snapshot:",
    registro_salvo[
        "snapshot"
    ]
)


print(
    "✓ Nível:",
    registro_salvo[
        "classificacao"
    ].get(
        "nivel"
    )
)


print(
    "✓ Classificação:",
    registro_salvo[
        "classificacao"
    ].get(
        "classificacao"
    )
)


print(
    "✓ Banco de dados:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_technology"
    )
)


print(
    "✓ Versão configurada do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version"
    )
)


print(
    "✓ Fonte da versão do banco:",
    registro_salvo[
        "caracterizacao_tecnologica"
    ].get(
        "database_version_source"
    )
)


print(
    "✓ Dockerfile PostgreSQL:",
    (
        "analisado"
        if registro_salvo[
            "estado_artefatos"
        ].get(
            "dockerfile_postgres"
        ) is True
        else "não analisado"
    )
)


print(
    "✓ Interpretação assistida por IA:",
    (
        "disponível"
        if registro_salvo[
            "interpretacao_ia"
        ]
        else "não disponível"
    )
)


print(
    "✓ Versões atualmente armazenadas:",
    ", ".join(
        sorted(
            resultados_versoes.keys()
        )
    )
)

✓ Resultados da V4 armazenados para a análise longitudinal.
✓ Snapshot: web-1.26.8-beta.1
✓ Nível: 3
✓ Classificação: Parcial/Emergente
✓ Banco de dados: PostgreSQL
✓ Versão configurada do banco: 18
✓ Fonte da versão do banco: Dockerfile.postgres (imagem PostgreSQL literal)
✓ Dockerfile PostgreSQL: analisado
✓ Interpretação assistida por IA: disponível
✓ Versões atualmente armazenadas: V1, V2, V3, V4


## Longitudinal Pipeline Technical Analysis — V1–V4

A matriz abaixo sintetiza as evidências ao longo das quatro versões.

In [111]:
# ---------------------------------------------------------
# LONGITUDINAL PIPELINE TECHNICAL ANALYSIS — V1–V4
#
# Consolida os resultados determinísticos armazenados para
# V1, V2, V3 e V4 em uma matriz longitudinal comparável.
#
# Semântica:
#
# ✓ = evidência identificada
# — = ausência identificada em artefato válido analisado
# ? = evidência indeterminada ou não disponível
#
# A matriz não realiza interpretação assistida por IA.
#
# Dockerfile.postgres é tratado como evidência configuracional
# de containerização/tecnologia de banco. Sua presença não
# constitui evidência de deploy automatizado.
# ---------------------------------------------------------

import pandas as pd


# ---------------------------------------------------------
# 1. Versões esperadas
# ---------------------------------------------------------

versoes_esperadas = [
    "V1",
    "V2",
    "V3",
    "V4"
]


# ---------------------------------------------------------
# 2. Validação da estrutura longitudinal
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes "
        "não está disponível."
    )


# ---------------------------------------------------------
# 3. Verifica se todas as versões foram armazenadas
# ---------------------------------------------------------

versoes_ausentes = [
    versao
    for versao in versoes_esperadas
    if versao not in resultados_versoes
]


if versoes_ausentes:

    raise ValueError(
        "As seguintes versões ainda não possuem resultados "
        "armazenados para análise longitudinal: "
        + ", ".join(
            versoes_ausentes
        )
    )


# ---------------------------------------------------------
# 4. Valida a estrutura interna de cada versão
# ---------------------------------------------------------

for versao in versoes_esperadas:

    registro = resultados_versoes[
        versao
    ]

    if not isinstance(
        registro,
        dict
    ):

        raise TypeError(
            f"O registro da {versao} "
            "não possui estrutura válida."
        )

    if (
        "evidencias" not in registro
        or not isinstance(
            registro[
                "evidencias"
            ],
            dict
        )
    ):

        raise ValueError(
            f"As evidências da {versao} "
            "não estão disponíveis."
        )

    if (
        "classificacao" not in registro
        or not isinstance(
            registro[
                "classificacao"
            ],
            dict
        )
    ):

        raise ValueError(
            f"A classificação determinística da "
            f"{versao} não está disponível."
        )


# ---------------------------------------------------------
# 5. Evidências selecionadas para comparação longitudinal
#
# Chave:
# descrição apresentada na matriz
#
# Valor:
# chave utilizada no dicionário evidencias
# ---------------------------------------------------------

evidencias_longitudinais = {

    # -----------------------------------------------------
    # Integração contínua
    # -----------------------------------------------------

    "GitLab CI":
        "GitLab CI como código",

    "Restore no CI":
        "`dotnet restore` no CI",

    "Build Release":
        "Build Release no CI",

    "SonarQube":
        "SonarQube",

    "Espera pelo Quality Gate":
        "Espera pelo Quality Gate",

    "Quality Gate bloqueante":
        "Quality Gate bloqueante",

    "Cache Sonar":
        "Cache Sonar",

    "Cache NuGet":
        "Cache NuGet",

    "Regra para Merge Request":
        "Regra para Merge Request",

    "Regra para branch main":
        "Regra para branch main",


    # -----------------------------------------------------
    # Testes
    # -----------------------------------------------------

    "Testes automatizados":
        "Testes automatizados",


    # -----------------------------------------------------
    # Gerenciamento de dependências
    # -----------------------------------------------------

    "Renovate configurado":
        "Renovate configurado",

    "Renovate — NuGet":
        "Gerenciamento NuGet pelo Renovate",

    "Renovate — Dockerfile":
        "Gerenciamento Dockerfile pelo Renovate",

    "Vulnerability Alerts":
        "Vulnerability Alerts",

    "Lock File Maintenance":
        "Lock File Maintenance",

    "Job Renovate":
        "Job Renovate no pipeline",

    "Schedule Renovate":
        "Regra schedule para Renovate",

    "Execução manual Renovate":
        "Execução manual do Renovate",

    "Execução efetiva Renovate":
        "Execução efetiva do Renovate",


    # -----------------------------------------------------
    # Containerização
    # -----------------------------------------------------

    "Dockerfile":
        "Dockerfile presente",

    "Dockerfile PostgreSQL":
        "Dockerfile PostgreSQL presente",

    "Docker multi-stage":
        "Docker multi-stage build",

    "Docker Compose":
        "Docker Compose presente",


    # -----------------------------------------------------
    # Observabilidade
    # -----------------------------------------------------

    "Sentry em runtime":
        "Sentry integrado em runtime",

    "Health Checks":
        "Health Checks",

    "Matomo":
        "Matomo configurado",


    # -----------------------------------------------------
    # Qualidade estática
    # -----------------------------------------------------

    ".editorconfig":
        ".editorconfig presente",

    "Analyzer rules":
        "Regras de analyzer declaradas",

    "Security rules":
        "Regras de segurança declaradas",


    # -----------------------------------------------------
    # Configuração e ambiente
    # -----------------------------------------------------

    "Parametrização de ambientes":
        "Parametrização de ambientes",

    "Automação de ambiente local":
        "Automação de ambiente local",


    # -----------------------------------------------------
    # Banco de dados
    # -----------------------------------------------------

    "PostgreSQL":
        "PostgreSQL evidenciado",

    "Provider PostgreSQL (.NET)":
        "Provider PostgreSQL (.NET)",

    "Versão PostgreSQL identificada":
        "Versão PostgreSQL identificada",


    # -----------------------------------------------------
    # Entrega e recuperação
    # -----------------------------------------------------

    "Deploy automatizado":
        "Deploy automatizado",

    "Promoção automática":
        "Promoção automática",

    "Rollback automatizado":
        "Rollback automatizado"
}


# ---------------------------------------------------------
# 6. Conversão tri-state
# ---------------------------------------------------------

def simbolo_evidencia(
    valor
):

    if valor is True:
        return "✓"

    if valor is False:
        return "—"

    return "?"


# ---------------------------------------------------------
# 7. Criação da matriz longitudinal
# ---------------------------------------------------------

linhas = []


for descricao, chave in evidencias_longitudinais.items():

    linha = {
        "Evidência": descricao
    }


    for versao in versoes_esperadas:

        evidencias_versao = (
            resultados_versoes[
                versao
            ][
                "evidencias"
            ]
        )


        valor = evidencias_versao.get(
            chave,
            None
        )


        linha[
            versao
        ] = simbolo_evidencia(
            valor
        )


    linhas.append(
        linha
    )


df_longitudinal = pd.DataFrame(
    linhas
)


# ---------------------------------------------------------
# 8. Caracterização tecnológica longitudinal
# ---------------------------------------------------------

linhas_tecnologia = []


for versao in versoes_esperadas:

    registro = resultados_versoes[
        versao
    ]


    caracterizacao = registro.get(
        "caracterizacao_tecnologica",
        {}
    )


    linhas_tecnologia.append({

        "Versão":
            versao,

        "Snapshot":
            registro.get(
                "snapshot"
            ),

        "Target Framework":
            caracterizacao.get(
                "target_framework"
            ),

        "SDK Pipeline":
            caracterizacao.get(
                "sdk_pipeline"
            ),

        "Banco de dados":
            caracterizacao.get(
                "database_technology"
            ),

        "Dockerfile PostgreSQL":
            simbolo_evidencia(
                caracterizacao.get(
                    "postgresql_dockerfile_present"
                )
            ),

        "Versão configurada do banco":
            caracterizacao.get(
                "database_version"
            ),

        "Fonte da versão do banco":
            caracterizacao.get(
                "database_version_source"
            )
    })


df_tecnologia_longitudinal = pd.DataFrame(
    linhas_tecnologia
)


# ---------------------------------------------------------
# 9. Classificação longitudinal
# ---------------------------------------------------------

linhas_classificacao = []


for versao in versoes_esperadas:

    classificacao = (
        resultados_versoes[
            versao
        ].get(
            "classificacao",
            {}
        )
    )


    linhas_classificacao.append({

        "Versão":
            versao,

        "Nível":
            classificacao.get(
                "nivel"
            ),

        "Classificação":
            classificacao.get(
                "classificacao"
            ),

        "Motivo":
            classificacao.get(
                "motivo"
            )
    })


df_classificacao_longitudinal = pd.DataFrame(
    linhas_classificacao
)


# ---------------------------------------------------------
# 10. Apresentação dos resultados
#
# Observação:
# a versão do PostgreSQL apresentada abaixo representa a
# configuração identificada nos artefatos analisados e não
# comprova a versão efetivamente executada em produção.
# ---------------------------------------------------------

print(
    "MATRIZ LONGITUDINAL DE EVIDÊNCIAS — V1–V4\n"
)

display(
    df_longitudinal
)


print(
    "\nCARACTERIZAÇÃO TECNOLÓGICA — V1–V4\n"
)

display(
    df_tecnologia_longitudinal
)


print(
    "\nCLASSIFICAÇÃO DA AUTOMAÇÃO DO PIPELINE — V1–V4\n"
)

display(
    df_classificacao_longitudinal
)


# ---------------------------------------------------------
# 11. Legenda
# ---------------------------------------------------------

print(
    "\nLegenda:"
)

print(
    "✓ = evidência identificada"
)

print(
    "— = ausência identificada em artefato válido analisado"
)

print(
    "? = evidência indeterminada ou não disponível"
)

MATRIZ LONGITUDINAL DE EVIDÊNCIAS — V1–V4

                         Evidência V1 V2 V3 V4
0                        GitLab CI  ✓  ✓  ✓  ✓
1                    Restore no CI  —  ✓  ✓  ✓
2                    Build Release  —  ✓  ✓  ✓
3                        SonarQube  ✓  ✓  ✓  ✓
4         Espera pelo Quality Gate  ✓  ✓  ✓  ✓
5          Quality Gate bloqueante  —  —  —  —
6                      Cache Sonar  ✓  ✓  ✓  ✓
7                      Cache NuGet  —  ✓  ✓  ✓
8         Regra para Merge Request  ✓  —  —  —
9           Regra para branch main  ✓  ✓  ✓  ✓
10            Testes automatizados  —  —  —  —
11            Renovate configurado  ?  ✓  ✓  ✓
12                Renovate — NuGet  ?  ✓  ✓  ✓
13           Renovate — Dockerfile  ?  ✓  ✓  ✓
14            Vulnerability Alerts  ?  ✓  ✓  ✓
15           Lock File Maintenance  ?  ✓  ✓  ✓
16                    Job Renovate  —  ✓  —  —
17               Schedule Renovate  —  ✓  —  —
18        Execução manual Renovate  —  ✓  —  —
19       Execução efetiva Renovate  ?  ?  ?  ?
20                      Dockerfile  ✓  ✓  ✓  ✓
21           Dockerfile PostgreSQL  ✓  ✓  ✓  ✓
22              Docker multi-stage  ✓  ✓  ✓  ✓
23                  Docker Compose  ✓  ✓  ✓  ✓
24               Sentry em runtime  ✓  ✓  ✓  ✓
25                   Health Checks  ✓  ✓  ✓  ✓
26                          Matomo  ✓  ✓  ✓  ✓
27                   .editorconfig  ✓  ✓  ✓  ✓
28                  Analyzer rules  ✓  ✓  ✓  ✓
29                  Security rules  ✓  ✓  ✓  ✓
30     Parametrização de ambientes  ✓  ✓  ✓  ✓
31     Automação de ambiente local  ✓  ✓  ✓  ✓
32                      PostgreSQL  ✓  ✓  ✓  ✓
33      Provider PostgreSQL (.NET)  ✓  ✓  ✓  ✓
34  Versão PostgreSQL identificada  ✓  ✓  ✓  ✓
35             Deploy automatizado  —  —  —  —
36             Promoção automática  —  —  —  —
37           Rollback automatizado  —  —  —  —

CARACTERIZAÇÃO TECNOLÓGICA — V1–V4

,Versão,Snapshot,Target Framework,SDK Pipeline,Banco de dados,Dockerfile PostgreSQL,Versão configurada do banco,Fonte da versão do banco
0,V1,web-1.25.10-1,net9.0,None,PostgreSQL,✓,17,Dockerfile.postgres (imagem PostgreSQL literal)
1,V2,web-1.26.4-1,net10.0,10.0,PostgreSQL,✓,18,Dockerfile.postgres (imagem PostgreSQL literal)
2,V3,web-1.26.6-1,net10.0,10.0,PostgreSQL,✓,18,Dockerfile.postgres (imagem PostgreSQL literal)
3,V4,web-1.26.8-beta.1,net10.0,10.0,PostgreSQL,✓,18,Dockerfile.postgres (imagem PostgreSQL literal)

CLASSIFICAÇÃO DA AUTOMAÇÃO DO PIPELINE — V1–V4

,Versão,Nível,Classificação,Motivo
0,V1,2,Inicial / Adhoc,Existe pipeline versionado com automações bási...
1,V2,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
2,V3,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
3,V4,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...

Legenda:
✓ = evidência identificada
— = ausência identificada em artefato válido analisado
? = evidência indeterminada ou não disponível

In [112]:
# ---------------------------------------------------------
# LONGITUDINAL PIPELINE MATURITY CLASSIFICATION
#
# Consolida a classificação determinística da automação do
# pipeline para V1, V2, V3 e V4.
#
# A classificação representa exclusivamente a maturidade
# da automação observável no pipeline segundo a rubrica
# específica definida neste estudo.
# ---------------------------------------------------------


# ---------------------------------------------------------
# 1. Inicialização
# ---------------------------------------------------------

linhas_maturidade = []


# ---------------------------------------------------------
# 2. Consolidação por versão
# ---------------------------------------------------------

for versao in versoes_esperadas:

    resultado = resultados_versoes[
        versao
    ]

    classificacao = resultado.get(
        "classificacao",
        {}
    )


    linhas_maturidade.append(
        {

            "Versão":
                versao,

            "Snapshot":
                resultado.get(
                    "snapshot"
                ),

            "Nível":
                classificacao.get(
                    "nivel"
                ),

            "Classificação":
                classificacao.get(
                    "classificacao"
                ),

            "Motivo":
                classificacao.get(
                    "motivo"
                )
        }
    )


# ---------------------------------------------------------
# 3. DataFrame longitudinal
# ---------------------------------------------------------

df_maturidade_longitudinal = pd.DataFrame(
    linhas_maturidade
)


# ---------------------------------------------------------
# 4. Apresentação
# ---------------------------------------------------------

print(
    "EVOLUÇÃO DA CLASSIFICAÇÃO DA AUTOMAÇÃO "
    "DO PIPELINE — V1–V4\n"
)


display(
    df_maturidade_longitudinal
)

EVOLUÇÃO DA CLASSIFICAÇÃO DA AUTOMAÇÃO DO PIPELINE — V1–V4

,Versão,Snapshot,Nível,Classificação,Motivo
0,V1,web-1.25.10-1,2,Inicial / Adhoc,Existe pipeline versionado com automações bási...
1,V2,web-1.26.4-1,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
2,V3,web-1.26.6-1,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
3,V4,web-1.26.8-beta.1,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...

In [113]:
# ---------------------------------------------------------
# PREPARE LONGITUDINAL EVIDENCE FOR AI INTERPRETATION
#
# Estrutura os resultados determinísticos de V1–V4 para
# posterior interpretação longitudinal assistida por IA.
#
# As interpretações individuais da IA não são incluídas.
# A análise longitudinal recebe apenas:
#
# - identificação da versão;
# - snapshot;
# - caracterização tecnológica;
# - evidências determinísticas;
# - classificação determinística.
# ---------------------------------------------------------


# ---------------------------------------------------------
# 1. Validação
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
):

    raise ValueError(
        "A estrutura resultados_versoes "
        "não está disponível."
    )


if (
    "versoes_esperadas" not in globals()
    or not versoes_esperadas
):

    raise ValueError(
        "A lista versoes_esperadas "
        "não está disponível."
    )


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

evidencias_longitudinais_para_ia = {}


# ---------------------------------------------------------
# 3. Estruturação por versão
# ---------------------------------------------------------

for versao in versoes_esperadas:

    if versao not in resultados_versoes:

        raise ValueError(
            f"A {versao} ainda não possui resultados "
            "armazenados."
        )


    resultado = resultados_versoes[
        versao
    ]


    caracterizacao = resultado.get(
        "caracterizacao_tecnologica",
        {}
    )


    evidencias = resultado.get(
        "evidencias",
        {}
    )


    classificacao = resultado.get(
        "classificacao",
        {}
    )


    evidencias_longitudinais_para_ia[
        versao
    ] = {

        "versao":
            versao,

        "snapshot":
            resultado.get(
                "snapshot"
            ),

        "caracterizacao_tecnologica": {

            "target_framework":
                caracterizacao.get(
                    "target_framework"
                ),

            "sdk_pipeline":
                caracterizacao.get(
                    "sdk_pipeline"
                ),

            "database_technology":
                caracterizacao.get(
                    "database_technology"
                ),

            "postgresql_evidenced":
                caracterizacao.get(
                    "postgresql_evidenced"
                ),

            "postgresql_dockerfile_present":
                caracterizacao.get(
                    "postgresql_dockerfile_present"
                ),

            "postgresql_dotnet_provider":
                caracterizacao.get(
                    "postgresql_dotnet_provider"
                ),

            "database_version":
                caracterizacao.get(
                    "database_version"
                ),

            "database_version_source":
                caracterizacao.get(
                    "database_version_source"
                ),

            "postgresql_version_identified":
                caracterizacao.get(
                    "postgresql_version_identified"
                )
        },

        "evidencias":
            evidencias,

        "classificacao":
            classificacao
    }


# ---------------------------------------------------------
# 4. Metadados da análise longitudinal
# ---------------------------------------------------------

pacote_longitudinal_para_ia = {

    "escopo":
        "V1–V4",

    "tipo_analise":
        "interpretação longitudinal assistida por IA",

    "fonte":
        (
            "resultados determinísticos previamente "
            "extraídos e classificados pelo notebook"
        ),

    "restricoes": [

        (
            "A IA não deve alterar as evidências "
            "determinísticas."
        ),

        (
            "A IA não deve recalcular os níveis "
            "de classificação."
        ),

        (
            "A evolução temporal não deve ser "
            "considerada necessariamente monotônica."
        ),

        (
            "Configuração não deve ser interpretada "
            "automaticamente como execução efetiva."
        ),

        (
            "Ausência de evidência não deve ser "
            "interpretada como evidência de ausência "
            "quando o valor for indeterminado."
        ),

        (
            "A classificação refere-se à automação "
            "do pipeline e não à maturidade DevOps "
            "global da organização."
        ),

        (
            "A presença de Dockerfile.postgres representa "
            "evidência configuracional relacionada à "
            "containerização do PostgreSQL e não comprova "
            "deploy automatizado."
        ),

        (
            "A versão PostgreSQL identificada representa "
            "a versão configurada nos artefatos analisados "
            "e não comprova a versão efetivamente executada "
            "em produção."
        ),

        (
            "A presença de PostgreSQL nos artefatos modernos "
            "não comprova, isoladamente, a execução da "
            "migração do banco legado para PostgreSQL."
        )
    ],

    "versoes":
        evidencias_longitudinais_para_ia
}


# ---------------------------------------------------------
# 5. Resultado
# ---------------------------------------------------------

print(
    "✓ Evidências longitudinais de V1–V4 "
    "estruturadas para interpretação assistida por IA."
)


print(
    "✓ Versões incluídas:",
    ", ".join(
        evidencias_longitudinais_para_ia.keys()
    )
)

✓ Evidências longitudinais de V1–V4 estruturadas para interpretação assistida por IA.
✓ Versões incluídas: V1, V2, V3, V4

In [114]:
# ---------------------------------------------------------
# LONGITUDINAL AI INTERPRETATION PROMPT
#
# Prepara o prompt para interpretação longitudinal assistida
# por IA com base exclusivamente nos resultados determinísticos
# consolidados de V1, V2, V3 e V4.
# ---------------------------------------------------------

import json


# ---------------------------------------------------------
# 1. Validação
# ---------------------------------------------------------

if (
    "pacote_longitudinal_para_ia" not in globals()
    or not isinstance(
        pacote_longitudinal_para_ia,
        dict
    )
):

    raise ValueError(
        "O pacote longitudinal de evidências "
        "ainda não foi preparado."
    )


if (
    "versoes_esperadas" not in globals()
    or not versoes_esperadas
):

    raise ValueError(
        "A lista versoes_esperadas "
        "não está disponível."
    )


# ---------------------------------------------------------
# 2. Prompt longitudinal
# ---------------------------------------------------------

prompt_longitudinal = f"""
Realize uma interpretação técnica longitudinal das práticas de
automação do pipeline nas versões V1, V2, V3 e V4.

A análise integra um estudo acadêmico longitudinal sobre
modernização de software legado.

Utilize EXCLUSIVAMENTE os resultados determinísticos fornecidos
neste prompt.

Não reanalise os arquivos originais.

Não invente, complete ou presuma evidências que não estejam
explicitamente presentes nos dados fornecidos.

Não recalcule os níveis de maturidade.

Não altere as classificações determinísticas atribuídas pelo
notebook.

A classificação utilizada neste estudo refere-se exclusivamente
à maturidade da automação observável no pipeline e não à
maturidade DevOps global da organização.


SEMÂNTICA DAS EVIDÊNCIAS

Considere:

true
= evidência positiva identificada em artefato válido analisado;

false
= característica não identificada no artefato válido analisado,
dentro do escopo da análise;

null
= condição indeterminada, artefato ausente, inválido ou evidência
insuficiente para classificação.

Null não deve ser interpretado como ausência.

Não transforme uma condição indeterminada em evidência negativa.


OBJETIVO DA ANÁLISE LONGITUDINAL

Compare V1 → V2 → V3 → V4 considerando:

- permanência de práticas;
- capacidades introduzidas;
- capacidades retiradas;
- continuidade de configurações;
- alterações de orquestração;
- diferenças entre configuração, orquestração e execução efetiva;
- evolução ou estabilidade da classificação determinística;
- lacunas persistentes;
- evidências indeterminadas;
- mudanças tecnológicas relevantes ao pipeline;
- presença ou ausência de Dockerfile.postgres;
- alterações da versão configurada do PostgreSQL;
- mudanças na fonte utilizada para identificar a versão configurada.


REGRAS DE INTERPRETAÇÃO

1. A evolução temporal não deve ser considerada necessariamente
   monotônica.

2. A introdução de uma ferramenta ou configuração não significa,
   por si só, aumento do nível de maturidade.

3. A permanência de uma configuração entre versões não comprova
   que sua execução tenha permanecido equivalente.

4. A retirada de um job do pipeline não significa necessariamente
   abandono da prática fora do escopo analisado.

5. A configuração do Renovate não comprova sua execução efetiva.

6. A presença de um job Renovate evidencia orquestração no
   pipeline, mas não comprova execução bem-sucedida.

7. Evidência de execução efetiva do Renovate exige elementos
   adicionais, como logs, histórico de pipeline, branches ou
   merge requests produzidos pela ferramenta.

8. Dockerfile da aplicação evidencia configuração de build e
   empacotamento da aplicação, não deploy automatizado.

9. Dockerfile.postgres deve ser tratado separadamente do
   Dockerfile da aplicação.

10. Dockerfile.postgres evidencia configuração relacionada à
    imagem ou container PostgreSQL quando essa característica
    tiver sido identificada deterministicamente.

11. A presença de Dockerfile.postgres não comprova:

    - deploy automatizado;
    - execução efetiva do PostgreSQL;
    - versão efetivamente executada em produção;
    - Continuous Delivery;
    - Continuous Deployment;
    - migração efetiva do banco legado.

12. A introdução, permanência ou retirada de Dockerfile.postgres
    entre versões deve ser descrita como mudança configuracional
    ou tecnológica, salvo quando outras evidências sustentarem
    interpretação mais ampla.

13. Docker Compose evidencia configuração de serviços e ambiente,
    não deploy automatizado.

14. Scripts locais ou scripts de preparação de ambiente não devem
    ser classificados como deploy automatizado da aplicação.

15. SonarQube evidencia análise automatizada de qualidade estática,
    não testes automatizados.

16. Espera pelo Quality Gate não significa automaticamente que
    ele seja bloqueante.

17. Quality Gate configurado com comportamento não bloqueante não
    deve ser descrito como mecanismo obrigatório de impedimento
    do pipeline.

18. A ausência de comandos de testes nos pipelines analisados deve
    ser descrita apenas no escopo desses artefatos.

19. A ausência de comandos de deploy, promoção entre ambientes ou
    rollback nos pipelines analisados deve ser descrita apenas no
    escopo desses artefatos.

20. Não inferir Continuous Delivery apenas pela existência de
    integração contínua, Docker, Dockerfile.postgres ou scripts.

21. Não inferir Continuous Deployment sem evidência explícita de
    implantação automatizada.

22. Observabilidade não deve ser interpretada como automação de
    entrega.

23. Sentry, logging, health checks e Matomo devem ser tratados
    como capacidades de observabilidade quando evidenciados.

24. A presença de PostgreSQL caracteriza a tecnologia de banco de
    dados, não a maturidade do pipeline.

25. A identificação de Npgsql, UseNpgsql ou AddNpgsql pode
    sustentar a caracterização da integração do provider
    PostgreSQL com a aplicação .NET.

26. Uma versão do PostgreSQL identificada nos artefatos representa
    uma versão configurada, não necessariamente a versão
    efetivamente executada em produção.

27. Ao analisar uma versão configurada do PostgreSQL, considere
    também database_version_source.

28. Não atribua a mesma força de evidência a fontes diferentes
    sem observar a origem registrada em database_version_source.

29. Uma versão identificada em Dockerfile.postgres representa
    configuração da imagem/container PostgreSQL no artefato.

30. Uma versão identificada em Docker Compose representa
    configuração declarada do serviço ou imagem correspondente.

31. Uma versão obtida pela combinação de configuração e variável
    de ambiente deve ser descrita como versão configurada inferida
    da relação entre os artefatos, quando isso estiver indicado
    pela fonte armazenada.

32. A presença de PostgreSQL não comprova, isoladamente, a
    execução da migração do banco legado para PostgreSQL.

33. Mudanças da versão configurada do PostgreSQL entre V1–V4
    devem ser descritas como evolução ou alteração tecnológica,
    e não automaticamente como aumento da maturidade do pipeline.

34. Mudanças de Target Framework ou SDK devem ser tratadas como
    evolução tecnológica, e não automaticamente como evolução da
    maturidade da automação.

35. Capacidades adicionais podem mudar entre versões sem alterar
    o nível determinístico de maturidade.

36. A ausência posterior de uma capacidade anteriormente
    evidenciada não deve ser automaticamente interpretada como
    regressão global de maturidade.

37. Diferencie claramente:
    - presença de configuração;
    - orquestração no pipeline;
    - execução efetiva;
    - resultado operacional.

38. Caso V1, V2, V3 e V4 permaneçam no mesmo nível, explique a
    estabilidade da classificação sem forçar uma narrativa de
    crescimento de maturidade.

39. Caso haja progressão ou regressão de nível entre versões,
    descreva somente o que os níveis determinísticos armazenados
    indicarem.

40. Não recalcule um nível diferente mesmo que identifique uma
    possível inconsistência.

41. Caso existam diferenças entre a classificação armazenada e as
    evidências apresentadas, relate a inconsistência como limitação
    ou ponto de verificação, sem substituir a classificação.

42. Ao comparar V1 → V2, V2 → V3 e V3 → V4, diferencie:

    - capacidade introduzida;
    - capacidade preservada;
    - capacidade que deixou de ser evidenciada;
    - evidência que passou de null para true ou false;
    - mudança puramente tecnológica;
    - mudança na automação do pipeline.

43. Não atribua causalidade a partir da simples coexistência
    temporal entre uma mudança tecnológica e uma mudança no
    pipeline.

44. Utilize linguagem técnica, conservadora, rastreável e adequada
    a um trabalho acadêmico.

45. Evite expressões amplas ou promocionais como:

    - "pipeline DevOps completo";
    - "DevOps maduro";
    - "automação total";
    - "CI/CD plenamente implementado";

    quando essas afirmações não forem diretamente sustentadas
    pelas evidências determinísticas.


PACOTE LONGITUDINAL DE EVIDÊNCIAS

{json.dumps(
    pacote_longitudinal_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}


ESTRUTURA OBRIGATÓRIA DA RESPOSTA

### Síntese longitudinal

Apresente os principais padrões observados entre V1 e V4.

Diferencie evolução tecnológica de evolução da automação do
pipeline.


### Evolução entre as versões

Analise explicitamente:

V1 → V2

V2 → V3

V3 → V4

Destaque:

- o que permaneceu;
- o que foi introduzido;
- o que deixou de ser evidenciado;
- mudanças de configuração;
- mudanças de orquestração;
- mudanças tecnológicas.


### Práticas persistentes

Identifique práticas presentes ao longo de múltiplas versões.

Não confunda presença configuracional com execução efetiva.


### Capacidades introduzidas durante a evolução

Identifique capacidades que aparecem somente a partir de
determinada versão.

Informe quando a capacidade representar apenas configuração.


### Mudanças ou descontinuidades de orquestração

Diferencie claramente:

- configuração persistente;
- orquestração no pipeline;
- execução efetiva.

Considere especialmente o comportamento longitudinal do Renovate.


### Lacunas persistentes

Descreva apenas lacunas sustentadas pelas evidências
determinísticas.

Não transforme null em ausência.


### Evidências indeterminadas

Identifique condições que permaneçam sem comprovação suficiente.

Explique quando a ausência do artefato ou de evidência de runtime
impedir uma conclusão.


### Evolução da classificação da automação do pipeline

Compare os níveis determinísticos já calculados pelo notebook.

Não recalcule os níveis.

Explique estabilidade, progressão ou regressão somente quando os
dados determinísticos sustentarem essa interpretação.

Caso haja aparente inconsistência entre nível e evidências,
registre-a como ponto de verificação.


### Evolução tecnológica

Analise, quando disponíveis:

- Target Framework;
- SDK do pipeline;
- tecnologia de banco;
- provider PostgreSQL no .NET;
- presença de Dockerfile.postgres;
- versão configurada do PostgreSQL;
- fonte da versão configurada.

Ao descrever uma versão do PostgreSQL, preserve a distinção entre:

- versão configurada;
- fonte da configuração;
- versão efetivamente executada em produção.

Não confunda evolução tecnológica com aumento de maturidade do
pipeline.


### Limitações da análise longitudinal

Explique os limites decorrentes:

- do conjunto de artefatos analisados;
- da semântica tri-state;
- da distinção entre configuração e execução efetiva;
- da ausência de evidências de runtime quando aplicável;
- da impossibilidade de comprovar a versão efetivamente executada
  do PostgreSQL apenas pelos arquivos configuracionais.


### Conclusão longitudinal

Produza uma síntese técnica, conservadora e adequada a um trabalho
acadêmico.

Evite linguagem promocional, causalidade não demonstrada ou
afirmações que extrapolem os artefatos analisados.
"""


# ---------------------------------------------------------
# 3. Resultado
# ---------------------------------------------------------

print(
    "✓ Prompt longitudinal preparado."
)

print(
    "✓ Fonte: resultados determinísticos V1–V4."
)

✓ Prompt longitudinal preparado.
✓ Fonte: resultados determinísticos V1–V4.

In [115]:
# ---------------------------------------------------------
# AI-ASSISTED LONGITUDINAL INTERPRETATION
#
# Executa a interpretação longitudinal assistida por IA
# utilizando exclusivamente o pacote determinístico V1–V4.
#
# A IA não altera:
# - evidências determinísticas;
# - classificações individuais;
# - níveis de maturidade;
# - resultados armazenados das versões.
# ---------------------------------------------------------


# ---------------------------------------------------------
# 1. Configuração
# ---------------------------------------------------------

MODELO_IA_LONGITUDINAL = "gpt-5.6-terra"
ESFORCO_RACIOCINIO_LONGITUDINAL = "medium"


# ---------------------------------------------------------
# 2. Inicialização
# ---------------------------------------------------------

interpretacao_longitudinal_ia = None

metadados_interpretacao_longitudinal_ia = {

    "executada":
        False,

    "modelo_solicitado":
        MODELO_IA_LONGITUDINAL,

    "modelo_retornado":
        None,

    "esforco_raciocinio":
        ESFORCO_RACIOCINIO_LONGITUDINAL,

    "classificacoes_deterministicas_preservadas":
        True,

    "response_id":
        None,

    "input_tokens":
        None,

    "output_tokens":
        None,

    "total_tokens":
        None,

    "erro":
        None
}


# ---------------------------------------------------------
# 3. Validação dos resultados armazenados
# ---------------------------------------------------------

if (
    "resultados_versoes" not in globals()
    or not isinstance(
        resultados_versoes,
        dict
    )
    or not resultados_versoes
):

    raise ValueError(
        "Os resultados individuais das versões "
        "não estão disponíveis."
    )


# ---------------------------------------------------------
# 4. Validação das versões esperadas
# ---------------------------------------------------------

if (
    "versoes_esperadas" not in globals()
    or not isinstance(
        versoes_esperadas,
        list
    )
    or not versoes_esperadas
):

    raise ValueError(
        "A lista versoes_esperadas "
        "não está disponível."
    )


versoes_ausentes = [
    versao
    for versao in versoes_esperadas
    if versao not in resultados_versoes
]


if versoes_ausentes:

    raise ValueError(
        "Ainda faltam resultados das versões: "
        + ", ".join(
            versoes_ausentes
        )
    )


# ---------------------------------------------------------
# 5. Validação do pacote longitudinal
# ---------------------------------------------------------

if (
    "pacote_longitudinal_para_ia" not in globals()
    or not isinstance(
        pacote_longitudinal_para_ia,
        dict
    )
):

    raise ValueError(
        "O pacote longitudinal de evidências "
        "não está disponível."
    )


# ---------------------------------------------------------
# 6. Validação do prompt longitudinal
# ---------------------------------------------------------

if (
    "prompt_longitudinal" not in globals()
    or not isinstance(
        prompt_longitudinal,
        str
    )
    or not prompt_longitudinal.strip()
):

    raise ValueError(
        "O prompt longitudinal não foi preparado "
        "ou está vazio."
    )


# ---------------------------------------------------------
# 7. Validação do cliente OpenAI
# ---------------------------------------------------------

if (
    "client" not in globals()
    or client is None
):

    raise ValueError(
        "O cliente OpenAI não está disponível. "
        "Execute primeiro a célula de configuração "
        "da interpretação assistida por IA."
    )


# ---------------------------------------------------------
# 8. Instruções de interpretação longitudinal
# ---------------------------------------------------------

instrucoes_longitudinais = """
Atue como avaliador técnico de evidências relacionadas à
automação de pipelines de software.

Realize uma interpretação longitudinal conservadora,
rastreável e adequada a um trabalho acadêmico.

Utilize exclusivamente os resultados determinísticos
fornecidos no prompt.

Não reanalise arquivos originais.

Não invente evidências adicionais.

Não recalcule os níveis de maturidade.

Não altere as classificações determinísticas das versões.

Não interprete evolução temporal como necessariamente
monotônica.

Diferencie claramente:

- configuração;
- orquestração;
- execução efetiva;
- evidência positiva;
- ausência evidenciada;
- condição indeterminada.

Não transforme null em false.

Não confunda evolução tecnológica com aumento de maturidade
da automação do pipeline.

Não avalie a maturidade DevOps global da organização.

A classificação utilizada refere-se exclusivamente à
automação observável nos pipelines analisados segundo a
rubrica específica definida neste estudo.

Dockerfile da aplicação e Dockerfile.postgres possuem papéis
distintos e não devem ser tratados como o mesmo tipo de
evidência.

Dockerfile.postgres deve ser interpretado como evidência
configuracional relacionada à containerização do PostgreSQL
quando essa característica tiver sido identificada nos
resultados determinísticos.

A presença de Dockerfile.postgres não comprova, por si só:

- deployment automatizado;
- execução efetiva do PostgreSQL em produção;
- versão efetivamente executada em produção;
- Continuous Delivery;
- Continuous Deployment;
- migração efetiva do banco legado.

Quando uma versão configurada do PostgreSQL estiver presente,
considere também database_version_source.

Uma alteração da versão configurada do PostgreSQL ou de sua
fonte de evidência deve ser tratada como mudança tecnológica
ou configuracional, não automaticamente como evolução da
maturidade da automação do pipeline.

Capacidades como PostgreSQL, Dockerfile.postgres,
containerização, Renovate e observabilidade não devem elevar
arbitrariamente o nível determinístico de maturidade.

Caso exista aparente inconsistência entre as evidências e uma
classificação armazenada, registre-a como ponto de verificação,
mas não substitua nem recalcule a classificação.
"""


# ---------------------------------------------------------
# 9. Interpretação longitudinal assistida por IA
# ---------------------------------------------------------

try:

    response_longitudinal = client.responses.create(

        model=MODELO_IA_LONGITUDINAL,

        reasoning={
            "effort":
                ESFORCO_RACIOCINIO_LONGITUDINAL
        },

        instructions=(
            instrucoes_longitudinais
        ),

        input=(
            prompt_longitudinal
        ),

        store=False
    )


    # -----------------------------------------------------
    # 10. Recuperação da interpretação
    # -----------------------------------------------------

    interpretacao_longitudinal_ia = (
        response_longitudinal.output_text.strip()
        if response_longitudinal.output_text
        else None
    )


    if not interpretacao_longitudinal_ia:

        raise ValueError(
            "A API respondeu, mas não retornou "
            "interpretação longitudinal textual."
        )


    # -----------------------------------------------------
    # 11. Metadados da execução
    #
    # Nenhuma credencial ou segredo é armazenado.
    # -----------------------------------------------------

    metadados_interpretacao_longitudinal_ia[
        "executada"
    ] = True


    metadados_interpretacao_longitudinal_ia[
        "modelo_retornado"
    ] = getattr(
        response_longitudinal,
        "model",
        None
    )


    metadados_interpretacao_longitudinal_ia[
        "response_id"
    ] = getattr(
        response_longitudinal,
        "id",
        None
    )


    # -----------------------------------------------------
    # 12. Uso de tokens, quando disponibilizado
    # -----------------------------------------------------

    usage = getattr(
        response_longitudinal,
        "usage",
        None
    )


    if usage is not None:

        metadados_interpretacao_longitudinal_ia[
            "input_tokens"
        ] = getattr(
            usage,
            "input_tokens",
            None
        )

        metadados_interpretacao_longitudinal_ia[
            "output_tokens"
        ] = getattr(
            usage,
            "output_tokens",
            None
        )

        metadados_interpretacao_longitudinal_ia[
            "total_tokens"
        ] = getattr(
            usage,
            "total_tokens",
            None
        )


    # -----------------------------------------------------
    # 13. Resultado
    # -----------------------------------------------------

    print(
        "INTERPRETAÇÃO LONGITUDINAL "
        "ASSISTIDA POR IA — V1–V4\n"
    )


    print(
        interpretacao_longitudinal_ia
    )


    print(
        "\n-----------------------------------------"
    )


    print(
        "Modelo solicitado:",
        metadados_interpretacao_longitudinal_ia[
            "modelo_solicitado"
        ]
    )


    print(
        "Modelo retornado:",
        metadados_interpretacao_longitudinal_ia[
            "modelo_retornado"
        ]
    )


    print(
        "Esforço de raciocínio:",
        metadados_interpretacao_longitudinal_ia[
            "esforco_raciocinio"
        ]
    )


    print(
        "Classificações determinísticas preservadas:",
        metadados_interpretacao_longitudinal_ia[
            "classificacoes_deterministicas_preservadas"
        ]
    )


    print(
        "Execução:",
        "concluída"
    )


# ---------------------------------------------------------
# 14. Tratamento de erro
# ---------------------------------------------------------

except Exception as erro:

    interpretacao_longitudinal_ia = None


    metadados_interpretacao_longitudinal_ia[
        "executada"
    ] = False


    metadados_interpretacao_longitudinal_ia[
        "erro"
    ] = str(
        erro
    )


    print(
        "⚠ Não foi possível executar a "
        "interpretação longitudinal assistida por IA."
    )


    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO LONGITUDINAL ASSISTIDA POR IA — V1–V4

### Síntese longitudinal

Entre V1 e V4, observa-se a permanência de um pipeline GitLab CI versionado, com análise estática via SonarQube, espera pelo Quality Gate, regras associadas à branch `main` e configurações de containerização e ambiente. Em todas as versões, porém, o Quality Gate foi classificado como não bloqueante, e não foram identificados testes automatizados, deploy automatizado, promoção automática entre ambientes ou rollback automatizado nos pipelines analisados.

A mudança mais relevante na automação observável do pipeline ocorreu entre V1 e V2: V2 passou a evidenciar `dotnet restore`, build Release e cache NuGet no CI, além de configuração do Renovate e de sua orquestração por job, agendamento e execução manual. Essa alteração coincide com a progressão da classificação determinística de nível 2 para nível 3.

Entre V2 e V3, as configurações do Renovate permaneceram evidenciadas, mas deixaram de ser identificados o job Renovate no pipeline, a regra de agendamento e a execução manual. Portanto, há uma descontinuidade de orquestração no pipeline, sem evidência de remoção da configuração da ferramenta. V4 preserva o padrão de V3.

Em paralelo, houve evolução tecnológica entre V1 e V2: o Target Framework mudou de `net9.0` para `net10.0`, o SDK do pipeline passou a ser identificado como `10.0`, e a versão configurada do PostgreSQL passou de 17 para 18. Essas mudanças devem ser interpretadas como alterações tecnológicas e configuracionais; não comprovam, por si, aumento de maturidade da automação do pipeline.

---

### Evolução entre as versões

#### V1 → V2

**Capacidades preservadas**

Permaneceram evidenciados:

- GitLab CI como código;
- SonarQube;
- espera pelo Quality Gate;
- Quality Gate não bloqueante;
- cache Sonar;
- regra para a branch `main`;
- Dockerfile da aplicação, com build multi-stage, restore, build e publish;
- Dockerfile específico do PostgreSQL;
- Docker Compose, incluindo definição de build, política de restart, rede externa e reverse proxy;
- capacidades de observabilidade e configuração, como Sentry em runtime, health checks de banco e API, console logging, Matomo, `appsettings`, configuração externalizada e parametrização de ambientes;
- automação de ambiente local e script de inicialização de banco;
- PostgreSQL e provider PostgreSQL no .NET.

Essas permanências representam, predominantemente, continuidade de configuração e de automação parcial de integração e qualidade. Elas não demonstram continuidade de execução efetiva em runtime ou em produção.

**Capacidades introduzidas ou que passaram a ser evidenciadas**

Em V2, passaram a ser identificados no pipeline:

- `dotnet restore` no CI: de `false` para `true`;
- build Release no CI: de `false` para `true`;
- cache NuGet: de `false` para `true`.

Também passaram a ser identificados:

- Renovate configurado: de `null` para `true`;
- gerenciamento de dependências NuGet pelo Renovate: de `null` para `true`;
- gerenciamento de Dockerfiles pelo Renovate: de `null` para `true`;
- Vulnerability Alerts: de `null` para `true`;
- Lock File Maintenance: de `null` para `true`;
- job Renovate no pipeline: de `false` para `true`;
- regra de agendamento para Renovate: de `false` para `true`;
- execução manual do Renovate: de `false` para `true`;
- script de seed: de `false` para `true`.

A transição de `null` para `true` nas evidências de configuração do Renovate indica que V1 era indeterminada quanto a essas características, enquanto V2 contém evidência positiva. Isso não permite afirmar, apenas com base nesses dados, que a configuração foi necessariamente criada entre as versões; permite afirmar que ela passou a ser identificada deterministicamente em V2.

A presença de job, agendamento e execução manual do Renovate em V2 evidencia **orquestração prevista no pipeline**. Não há, entretanto, evidência de execução efetiva ou bem-sucedida do Renovate, pois essa característica permanece `null`.

**Capacidades que deixaram de ser evidenciadas**

A regra para Merge Request mudou de `true` em V1 para `false` em V2. No escopo dos artefatos válidos analisados, essa regra não foi identificada em V2. Isso constitui alteração na orquestração ou nas condições de acionamento observadas, mas não permite concluir que a prática tenha sido abandonada em outros mecanismos ou fora do escopo analisado.

**Mudanças tecnológicas**

- Target Framework: `net9.0` em V1 para `net10.0` em V2.
- SDK do pipeline: `null` em V1 para `10.0` em V2. O valor `null` em V1 é indeterminado; não comprova ausência de SDK configurado.
- PostgreSQL configurado: versão 17 em V1 para versão 18 em V2.
- Fonte da versão PostgreSQL: permaneceu `Dockerfile.postgres (imagem PostgreSQL literal)`.

A alteração da versão configurada do PostgreSQL representa mudança tecnológica/configuracional da imagem ou container PostgreSQL. Não comprova a versão efetivamente executada em produção, a execução de uma migração de banco ou aumento de maturidade do pipeline.

---

#### V2 → V3

**Capacidades preservadas**

V3 preserva as evidências de V2 relativas a:

- `dotnet restore` e build Release no CI;
- SonarQube, espera pelo Quality Gate e cache Sonar;
- cache NuGet;
- regra para a branch `main`;
- Quality Gate não bloqueante;
- configurações do Renovate, incluindo gerenciamento de NuGet e Dockerfiles, Vulnerability Alerts e Lock File Maintenance;
- Dockerfile da aplicação e suas etapas de restore, build e publish;
- Dockerfile.postgres;
- Docker Compose e seus elementos configuracionais;
- observabilidade, health checks e configuração externalizada;
- script de inicialização de banco e script de seed;
- PostgreSQL, provider .NET e versão configurada 18.

**Mudanças de orquestração**

Em V3, deixaram de ser evidenciados:

- job Renovate no pipeline: de `true` para `false`;
- regra de agendamento para Renovate: de `true` para `false`;
- execução manual do Renovate: de `true` para `false`.

A configuração do Renovate permaneceu `true`, mas a orquestração anteriormente identificada no pipeline não foi identificada em V3. Assim, os dados sustentam a distinção entre:

- **configuração persistente:** Renovate configurado e seus recursos declarados;
- **orquestração descontinuada nos artefatos analisados:** job, schedule e acionamento manual não identificados;
- **execução efetiva:** permanece indeterminada (`null`).

A mudança não permite concluir que o Renovate deixou de operar por completo, que tenha sido executado externamente ou que tenha sido substituído por outro mecanismo; apenas delimita o que deixou de ser evidenciado no pipeline analisado.

**Mudanças tecnológicas**

Não há mudança tecnológica determinística entre V2 e V3:

- Target Framework permanece `net10.0`;
- SDK do pipeline permanece `10.0`;
- PostgreSQL permanece evidenciado;
- provider PostgreSQL .NET permanece identificado;
- Dockerfile.postgres permanece presente;
- versão configurada do PostgreSQL permanece 18;
- fonte da versão permanece o Dockerfile.postgres com imagem PostgreSQL literal.

---

#### V3 → V4

**Capacidades preservadas**

V4 preserva integralmente o padrão determinístico de V3, incluindo:

- integração via GitLab CI como código;
- `dotnet restore` e build Release no CI;
- SonarQube, espera pelo Quality Gate não bloqueante, cache Sonar e cache NuGet;
- regra para `main`, sem regra para Merge Request identificada;
- configuração do Renovate, sem job, schedule ou execução manual identificados;
- Dockerfile da aplicação e Dockerfile.postgres;
- Docker Compose e configurações de ambiente;
- mecanismos de observabilidade e health checks;
- script de inicialização de banco e script de seed;
- tecnologia PostgreSQL, provider .NET e versão configurada 18.

**Mudanças introduzidas, retiradas ou tecnológicas**

Não foram identificadas mudanças determinísticas entre V3 e V4 nas evidências fornecidas. A ausência de alteração observável não permite inferir equivalência de execução efetiva dos pipelines ou dos serviços em runtime; indica apenas estabilidade das características classificadas nos artefatos analisados.

---

### Práticas persistentes

Ao longo das quatro versões, permanecem evidenciadas as seguintes práticas ou configurações:

| Categoria | Práticas persistentes | Interpretação conservadora |
|---|---|---|
| Pipeline | GitLab CI como código | Evidência de pipeline versionado. |
| Qualidade | SonarQube, espera pelo Quality Gate e cache Sonar | Evidenciam análise estática automatizada e espera configurada; não evidenciam testes automatizados. |
| Controle de qualidade | Quality Gate não bloqueante | A espera pelo gate não deve ser interpretada como bloqueio obrigatório do pipeline. |
| Regras de execução | Regra para branch `main` | Evidência configuracional/orquestracional para essa branch. |
| Containerização da aplicação | Dockerfile, build multi-stage, restore, build e publish | Evidenciam configuração de build e empacotamento da aplicação; não deployment automatizado. |
| Containerização de banco | Dockerfile.postgres | Evidência configuracional específica relacionada à imagem/container PostgreSQL. |
| Ambiente | Docker Compose, build definido, restart, rede externa e reverse proxy | Evidenciam configuração declarativa de serviços e ambiente; não deploy automatizado. |
| Observabilidade | Sentry, health checks, logging e Matomo | Evidenciam capacidades de observabilidade/configuração, não automação de entrega. |
| Banco de dados | PostgreSQL evidenciado e provider PostgreSQL .NET | Caracterizam a tecnologia e a integração do provider com a aplicação. |
| Configuração | `appsettings`, configuração externalizada, `.env.example`, `.env.io.example` e parametrização de ambientes | Evidenciam práticas de configuração; não comprovam aplicação dessas configurações em produção. |
| Ambiente local | Scripts e automação de ambiente local; script de inicialização de banco | Evidenciam suporte ao preparo de ambiente; não deploy automatizado da aplicação. |

Essas práticas persistentes mostram continuidade de configuração, de análise estática e de etapas de integração parcial. Elas não constituem evidência suficiente de execução efetiva contínua, promoção entre ambientes, entrega contínua ou implantação contínua.

---

### Capacidades introduzidas durante a evolução

A partir de V2, foram identificadas as seguintes capacidades:

1. **Etapas adicionais de integração no CI**
   - `dotnet restore` no CI;
   - build Release no CI;
   - cache NuGet.

   Essas evidências caracterizam maior estruturação observável das etapas de integração no pipeline.

2. **Configuração do Renovate**
   - configuração geral;
   - gerenciamento de dependências NuGet;
   - gerenciamento de Dockerfiles;
   - Vulnerability Alerts;
   - Lock File Maintenance.

   Essas capacidades são evidências de **configuração de gerenciamento automatizado de dependências**, não de execução efetiva da ferramenta.

3. **Orquestração do Renovate em V2**
   - job no pipeline;
   - regra de schedule;
   - execução manual.

   Essa combinação evidencia que V2 continha meios de orquestrar o Renovate no pipeline. Contudo, não comprova que execuções tenham ocorrido, concluído com sucesso ou produzido branches, merge requests ou atualizações aceitas.

4. **Script de seed**
   - passou de `false` em V1 para `true` a partir de V2.

   Trata-se de uma capacidade configuracional ou de preparação de ambiente/banco. Não comprova execução efetiva em ambiente de produção nem migração efetiva do banco legado.

---

### Mudanças ou descontinuidades de orquestração

O Renovate apresenta a principal variação longitudinal entre configuração e orquestração:

| Versão | Configuração Renovate | Job no pipeline | Schedule | Execução manual | Execução efetiva |
|---|---:|---:|---:|---:|---:|
| V1 | `null` | `false` | `false` | `false` | `null` |
| V2 | `true` | `true` | `true` | `true` | `null` |
| V3 | `true` | `false` | `false` | `false` | `null` |
| V4 | `true` | `false` | `false` | `false` | `null` |

A interpretação longitudinal é:

- **V1:** a configuração do Renovate é indeterminada; não foram identificados job, agendamento ou acionamento manual.
- **V2:** há configuração positiva e evidência de orquestração do Renovate no pipeline.
- **V3 e V4:** a configuração permanece, mas os mecanismos de orquestração identificados em V2 deixam de ser evidenciados.
- **Todas as versões:** a execução efetiva do Renovate é indeterminada. Não existem, no pacote fornecido, logs, histórico de pipelines, branches, merge requests ou outros resultados operacionais que comprovem execução bem-sucedida.

Também houve mudança na regra para Merge Request: identificada em V1 e não identificada de V2 a V4. Em contrapartida, a regra associada à branch `main` permaneceu evidenciada em todas as versões.

---

### Lacunas persistentes

Nos limites dos pipelines e artefatos válidos analisados, persistem em V1, V2, V3 e V4 as seguintes lacunas identificadas deterministicamente:

- testes automatizados: `false`;
- deploy automatizado: `false`;
- promoção automática entre ambientes: `false`;
- rollback automatizado: `false`;
- Quality Gate bloqueante: `false`;
- dump de banco presente: `false`.

A ausência de testes automatizados deve ser limitada aos pipelines analisados; SonarQube não substitui evidência de testes automatizados.

A ausência de deploy, promoção e rollback nos pipelines analisados não permite concluir que tais práticas inexista em todo o ambiente organizacional ou em mecanismos externos. Tampouco há base para caracterizar Continuous Delivery ou Continuous Deployment.

Além disso, o Quality Gate foi identificado como não bloqueante em todas as versões. Portanto, embora haja espera pelo gate, não é adequado descrevê-lo como impedimento obrigatório para progressão do pipeline.

---

### Evidências indeterminadas

As seguintes condições permanecem sem comprovação suficiente:

1. **Execução efetiva do Renovate**
   - `null` em V1, V2, V3 e V4.
   - Em V2, job, schedule e execução manual evidenciam orquestração possível, mas não resultado operacional.
   - Em V3 e V4, a ausência de job, schedule e execução manual identificados não transforma a execução efetiva em `false`; ela continua indeterminada.

2. **Configuração do Renovate em V1**
   - Renovate configurado e suas subcapacidades são `null`.
   - Esse estado não equivale a ausência de configuração; indica insuficiência de evidência para classificação.

3. **SDK do pipeline em V1**
   - O SDK do pipeline é `null`.
   - Não se deve interpretar esse resultado como ausência de SDK ou como incompatibilidade com o Target Framework `net9.0`; apenas não há identificação determinística suficiente no conjunto fornecido.

4. **Versão efetivamente executada do PostgreSQL em produção**
   - A versão foi identificada apenas como configuração em `Dockerfile.postgres`.
   - Não há evidência de runtime, inventário de produção, logs, execução de containers ou outro registro operacional que comprove a versão efetivamente em uso.

5. **Execução efetiva de Docker Compose, Dockerfiles, scripts de banco e mecanismos de observabilidade**
   - A presença desses artefatos e configurações não confirma que tenham sido executados em cada versão, em produção ou com resultado operacional específico.

---

### Evolução da classificação da automação do pipeline

As classificações determinísticas armazenadas pelo notebook são:

| Versão | Nível | Classificação |
|---|---:|---|
| V1 | 2 | Inicial / Adhoc |
| V2 | 3 | Parcial/Emergente |
| V3 | 3 | Parcial/Emergente |
| V4 | 3 | Parcial/Emergente |

A progressão de V1 para V2, de nível 2 para nível 3, é acompanhada por evidências adicionais de estruturação do CI: `dotnet restore`, build Release e cache NuGet no pipeline, além de configuração e orquestração do Renovate em V2. Conforme o motivo determinístico armazenado, V2 apresenta integração contínua estruturada e controles de qualidade, mas ainda sem automação de ponta a ponta.

A estabilidade em nível 3 entre V2, V3 e V4 deve ser interpretada sem pressupor evolução monotônica. Embora V3 tenha deixado de evidenciar o job, o schedule e a execução manual do Renovate, permaneceu classificada no nível 3 pelo notebook. Isso pode ser registrado como **ponto de verificação longitudinal**: houve redução da orquestração explicitamente identificada para o Renovate entre V2 e V3, mas a classificação armazenada não se alterou. Os dados fornecidos não autorizam recalcular ou substituir o nível, nem concluir que a classificação seja inconsistente; apenas indicam que a classificação não variou apesar dessa descontinuidade específica.

Em todas as versões, persistem lacunas compatíveis com a descrição de automação de ponta a ponta incompleta: testes automatizados, Quality Gate bloqueante, deploy automatizado, promoção automática e rollback automatizado não foram identificados.

---

### Evolução tecnológica

**Target Framework e SDK**

- **V1:** Target Framework `net9.0`; SDK do pipeline `null`.
- **V2, V3 e V4:** Target Framework `net10.0`; SDK do pipeline `10.0`.

A alteração de `net9.0` para `net10.0` e a posterior estabilidade em `net10.0` descrevem evolução tecnológica da aplicação e da configuração identificada no pipeline. Não constituem, isoladamente, evidência de maturidade superior da automação do pipeline.

**Tecnologia de banco e provider .NET**

Em todas as versões:

- a tecnologia de banco é PostgreSQL;
- PostgreSQL foi evidenciado;
- o Dockerfile.postgres está presente;
- o provider PostgreSQL no .NET foi identificado.

Esses elementos sustentam a caracterização da integração da aplicação .NET com PostgreSQL e da existência de configuração de containerização específica do banco. Eles não comprovam execução efetiva do banco, deploy automatizado, migração efetiva do banco legado ou uso produtivo da configuração identificada.

**Dockerfile.postgres**

O Dockerfile.postgres está presente de V1 a V4 e deve ser distinguido do Dockerfile da aplicação:

- o Dockerfile da aplicação evidencia configuração de build, publicação e empacotamento da aplicação;
- o Dockerfile.postgres evidencia configuração relacionada à imagem ou container PostgreSQL.

A permanência de ambos não demonstra deployment automatizado nem execução efetiva dos containers em qualquer ambiente.

**Versão configurada do PostgreSQL**

| Versão | Versão PostgreSQL configurada | Fonte registrada |
|---|---:|---|
| V1 | 17 | Dockerfile.postgres, imagem PostgreSQL literal |
| V2 | 18 | Dockerfile.postgres, imagem PostgreSQL literal |
| V3 | 18 | Dockerfile.postgres, imagem PostgreSQL literal |
| V4 | 18 | Dockerfile.postgres, imagem PostgreSQL literal |

A mudança de PostgreSQL 17 para 18 ocorre entre V1 e V2. A fonte de identificação é a mesma em todas as versões: uma imagem PostgreSQL literal no Dockerfile.postgres. Logo, trata-se de uma alteração configuracional/tecnológica observada no artefato de containerização do banco.

Essa evidência não permite afirmar:

- que PostgreSQL 17 ou 18 tenha sido efetivamente executado em produção;
- que a atualização tenha sido aplicada operacionalmente;
- que tenha ocorrido migração efetiva do banco legado;
- que a alteração tenha aumentado a maturidade do pipeline;
- que exista Continuous Delivery ou Continuous Deployment.

---

### Limitações da análise longitudinal

A análise é limitada aos resultados determinísticos fornecidos e aos artefatos previamente analisados pelo notebook. Portanto:

1. **Escopo dos artefatos**
   - As conclusões sobre testes, deploy, promoção e rollback referem-se aos pipelines e artefatos analisados.
   - Não é possível inferir a inexistência dessas práticas em processos externos, infraestrutura não analisada ou outros repositórios.

2. **Semântica tri-state**
   - Valores `true` representam evidência positiva identificada.
   - Valores `false` representam característica não identificada no artefato válido, dentro do escopo definido.