
# Longitudinal Technical Analysis of the CI Pipeline — V1 (MVP)–V4

Este notebook consolida os relatórios técnicos do pipeline das versões V1, V2, V3 e V4 do sistema analisado.
- **V1** - Módulos Contracheque (Empregados) e Cédula C
- **V2** - Módulo SIRH (Cadastro, Pós-Graduação)
- **V3** - Módulos SIRH (Ficha Financeira) e Contracheque (Pensionistas)
- **V4** - Módulo SIRH (Acadêmico)

As versões **V1**, **V2**, e **V3** estão em produção e **V4** encontra-se em fase de homologação.

O objetivo é preservar a **rastreabilidade temporal das evidências**, distinguindo:

1. **configuração** — capacidade declarada em artefato versionado;
2. **orquestração no pipeline** — capacidade explicitamente invocada pelo GitLab CI;
3. **execução efetiva** — capacidade comprovada por histórico de jobs, logs, branches ou Merge Requests.

> **Importante:** a ausência de evidência de execução não deve ser interpretada automaticamente como ausência da prática. Quando necessário, a situação é representada por `?`.


## 1. Scope

Versões analisadas:

- **V1** — `web-1.25.10-1`
- **V2** — `web-1.26.4-1`
- **V3** — `web-1.26.6-1`
- **V4** — `web-1.26.8-beta.1`

Artefatos principais considerados:
- `.gitlab-ci.yml`;
- `Boilerplate4Dev.csproj`;
- `renovate.json`;
- `RENOVATE_SETUP.md`;
- `Dockerfile`;
- `docker-compose.yaml`;
- `Program.cs`;
- `appsettings.json`;
- `.editorconfig`;
- `.env.example`;
- `.env.io.example`;
- `init.sql`;
- `seed.sql`;
- `start-db.ps1`.

A análise apresentada neste notebook corresponde ao recorte técnico já consolidado nos relatórios individuais e longitudinal.

## 2. Analysis Criteria

A análise foi conduzida a partir dos artefatos técnicos versionados associados às entregas V1, V2, V3 e V4, considerando tanto a presença das práticas quanto o nível de evidência disponível para sustentá-las. Para preservar a rastreabilidade entre os artefatos observados e as conclusões apresentadas, foram estabelecidos critérios para a classificação das evidências e para a avaliação da maturidade das práticas de automação do pipeline.

###2.1 Evidence Classification

As evidências foram analisadas considerando três níveis distintos:

Configuração: a capacidade está declarada em um artefato técnico versionado, indicando que foi configurada no projeto;

Orquestração no pipeline: a capacidade é explicitamente invocada ou incorporada à definição do pipeline de CI;

Execução efetiva: além da configuração ou orquestração, existem evidências de runtime que comprovam sua execução, como histórico de jobs, logs, branches ou Merge Requests gerados pela ferramenta.

Essa distinção evita inferir a execução de uma prática exclusivamente a partir da existência de sua configuração. Dessa forma, quando os artefatos analisados demonstram a configuração de uma capacidade, mas não fornecem evidências suficientes de sua execução efetiva, essa condição é explicitamente indicada na análise. Essa abordagem é particularmente relevante para a análise do Renovate, cuja configuração e orquestração podem ser verificadas nos artefatos versionados, enquanto sua execução efetiva depende de evidências adicionais do ambiente de CI.

Para representação das evidências nas matrizes, são utilizados os seguintes símbolos:

- **✓** para capacidade evidenciada ou configurada no artefato analisado;
- **—** para capacidade ausente ou não evidenciada no artefato analisado;
- **?** quando a confirmação depende de evidência adicional de execução.

A ausência de evidência de execução não é interpretada automaticamente como ausência da prática, preservando a distinção entre o que pode ser diretamente observado nos artefatos e aquilo que depende de evidências complementares.

###2.2 Pipeline Maturity Classification

Além da classificação das evidências individuais, foi adotada uma escala ordinal de quatro níveis para sintetizar o estágio de maturidade das práticas de automação do pipeline no recorte analisado.

Nível	Classificação	Critério:

1	`Ausente/Tradicional`	Práticas inexistentes ou totalmente manuais.

Ausência de pipeline versionado ou pipeline sem etapas relevantes de automação; build, testes, análise de qualidade e entrega predominantemente manuais.

2	`Inicial/Ad hoc`	Adoção pontual e não sistematizada.

Pipeline existente, mas com automações pontuais, por exemplo apenas build, análise estática ou alguma tarefa isolada; baixa integração entre etapas.

3	`Parcial/Emergente`	Práticas estruturadas, porém incompletas.

Pipeline versionado com práticas estruturadas de CI, como restore, build, análise de qualidade, gerenciamento automatizado de dependências ou outras etapas recorrentes, mas ainda com lacunas relevantes, como ausência de testes automatizados, deploy, promoção ou rollback.

4	`Avançado/Consolidado`	Práticas institucionalizadas e integradas.

Pipeline integrado cobrindo build, testes automatizados, controles de qualidade efetivamente bloqueantes e mecanismos estruturados de entrega/implantação, promoção e recuperação. A simples presença dos arquivos não basta: são necessárias também evidências de execução e continuidade dessas práticas.

A classificação é realizada a partir do conjunto das evidências observadas nas versões analisadas, considerando a existência e a continuidade das práticas de Integração Contínua, automação de build, análise de qualidade, gerenciamento de dependências, testes automatizados e mecanismos relacionados à entrega e implantação do software.

A escala é aplicada especificamente às práticas de automação do pipeline observadas no recorte temporal analisado. Portanto, o nível resultante não deve ser interpretado isoladamente como uma classificação da maturidade DevOps global do projeto ou da organização. Uma avaliação global exigiria a aplicação de critérios equivalentes às demais dimensões envolvidas na adoção de DevOps.

A classificação final do pipeline é apresentada somente após a análise individual das versões e a análise longitudinal, permitindo que o nível atribuído seja derivado das evidências técnicas apresentadas ao longo do relatório, e não estabelecido previamente como resultado da avaliação.

3. AI-Assisted Interpretation

A Inteligência Artificial é utilizada neste notebook como mecanismo de apoio à interpretação das evidências técnicas extraídas dos artefatos analisados.

A IA não realiza a identificação primária das práticas nem substitui os critérios objetivos definidos para a classificação da maturidade do pipeline. As evidências são previamente extraídas de forma automatizada a partir dos arquivos fornecidos, estruturadas e avaliadas segundo uma rubrica previamente estabelecida.

A partir dessas informações, a IA é utilizada para:

- interpretar o conjunto de evidências identificadas;
- verificar se as evidências sustentam a classificação obtida pelos critérios definidos;
- elaborar uma justificativa técnica e acadêmica para a classificação;
- identificar lacunas e limitações da análise;
- distinguir evidências de configuração, orquestração e execução efetiva;
- evitar inferências sobre práticas que não estejam diretamente sustentadas pelos artefatos analisados.

A interpretação assistida por IA deve ser conservadora e rastreável. A ausência de evidência não deve ser automaticamente interpretada como inexistência da prática, especialmente quando o artefato necessário para sua verificação não estiver disponível.

Assim, o fluxo analítico adotado neste notebook segue a sequência:

** `1`artefatos técnicos → `2`identificação e validação dos arquivos → `3`extração objetiva de evidências → `4`classificação determinística por critérios → `5`estruturação das evidências → `6`interpretação assistida por IA → `7`armazenamento dos resultados por versão → `8`consolidação das evidências → `9`análise longitudinal**

A classificação básica permanece reproduzível independentemente da IA, enquanto o modelo é utilizado como apoio à análise qualitativa e à elaboração da interpretação dos resultados.

In [25]:
# OpenAI API Setup
!pip install -q --upgrade openai

In [26]:
# OpenAI API Client Configuration
from google.colab import userdata
from openai import OpenAI

try:
    api_key = userdata.get("OPENAI_API_KEY")
except Exception:
    api_key = None

if not api_key:
    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada nos Secrets do Colab."
    )

client = OpenAI(api_key=api_key)

print("✓ Cliente de IA configurado com segurança.")

✓ Cliente de IA configurado com segurança.

In [27]:
# Bibliotecas
import re
import json
import os
import glob
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import pandas as pd
import yaml

In [28]:
# Common Utility Functions
def contem(texto, *padroes):
    if texto is None:
        return False

    texto = str(texto).lower()

    return any(
        str(padrao).lower() in texto
        for padrao in padroes
    )


def buscar_regex(texto, padrao):
    if texto is None:
        return None

    return re.search(
        padrao,
        str(texto),
        flags=re.IGNORECASE | re.MULTILINE
    )

In [29]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None

print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [30]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:
        root = ET.fromstring(csproj)

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar o arquivo .csproj:"
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # Pipeline versionado
    evidencias["GitLab CI como código"] = True


    # Restore
    evidencias["`dotnet restore` no CI"] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias["Build Release no CI"] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias["SonarQube"] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias["Espera pelo Quality Gate"] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias["Quality Gate bloqueante"] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias["Cache Sonar"] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias["Cache NuGet"] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias["Regra para Merge Request"] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias["Regra para branch main"] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias["Testes automatizados"] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias["Deploy automatizado"] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias["Promoção automática"] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias["Rollback automatizado"] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias["GitLab CI como código"] = None
    evidencias["`dotnet restore` no CI"] = None
    evidencias["Build Release no CI"] = None
    evidencias["SonarQube"] = None
    evidencias["Espera pelo Quality Gate"] = None
    evidencias["Quality Gate bloqueante"] = None
    evidencias["Cache Sonar"] = None
    evidencias["Cache NuGet"] = None
    evidencias["Regra para Merge Request"] = None
    evidencias["Regra para branch main"] = None
    evidencias["Testes automatizados"] = None
    evidencias["Deploy automatizado"] = None
    evidencias["Promoção automática"] = None
    evidencias["Rollback automatizado"] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias["Renovate configurado"] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )


    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias["Renovate configurado"] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=re.IGNORECASE | re.MULTILINE
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    # Se já havia evidência anterior, preserva True
    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:
        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline
}


# ---------------------------------------------------------
# 14. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()


# ---------------------------------------------------------
# 15. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? PostgreSQL configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local

## 3. V1 (MVP) — Pipeline Technical Analysis

### 3.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.25.10-1`**.

### 3.2 Análise dos Artefatos

In [31]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (2)
Saving .env.example to .env (2).example
Saving .env.io.example to .env.io (2).example
Saving appsettings.json to appsettings (2).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (2).csproj
Saving docker-compose.yaml to docker-compose (2).yaml
Saving Dockerfile to Dockerfile (2)
Saving gitlab-ci.yml to gitlab-ci (2).yml
Saving init.sql to init (2).sql
Saving Program.cs to Program (2).cs
Saving start-db.ps1 to start-db (2).ps1

✓ 11 arquivo(s) carregado(s):

  ✓ .editorconfig (2)
  ✓ .env (2).example
  ✓ .env.io (2).example
  ✓ Boilerplate4Dev (2).csproj
  ✓ Dockerfile (2)
  ✓ Program (2).cs
  ✓ appsettings (2).json
  ✓ docker-compose (2).yaml
  ✓ gitlab-ci (2).yml
  ✓ init (2).sql
  ✓ start-db (2).ps1

In [35]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:
    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None
dockerfile_valido = None
docker_compose_valido = None
program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):
    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):
    nome = nome_base(nome)

    # Remove sufixos adicionados pelo Colab:
    # arquivo (1).json -> arquivo.json
    # Dockerfile (2)   -> Dockerfile
    nome = re.sub(
        r"\s*\(\d+\)(?=\.|$)",
        "",
        nome
    )

    return nome.lower().strip()


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):
    if not candidatos:
        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _ in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(conteudo):
    if conteudo is None:
        return None

    if isinstance(
        conteudo,
        bytes
    ):
        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []
candidatos_dockerfile = []
candidatos_docker_compose = []
candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []

extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # GitLab CI
    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Projeto .NET
    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Renovate
    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Dockerfile
    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Docker Compose
    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Program.cs
    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # appsettings.json
    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .editorconfig
    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.io.example
    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.example
    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Scripts
    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile"
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):
    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):
    if conteudo is None:
        return None

    if not arquivo_nao_vazio(
        conteudo
    ):
        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):
            continue

        if "=" not in linha:
            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # O arquivo continua legível e utilizável
        # para extração de evidências.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile is not None:

    if not arquivo_nao_vazio(
        dockerfile
    ):

        dockerfile_valido = False

        validacao_artefatos.append(
            "✗ Dockerfile: arquivo vazio."
        )

    else:

        possui_from = bool(
            re.search(
                r"^\s*FROM\s+\S+",
                dockerfile,
                flags=(
                    re.IGNORECASE
                    | re.MULTILINE
                )
            )
        )

        if possui_from:

            dockerfile_valido = True

            validacao_artefatos.append(
                "✓ Dockerfile estruturalmente válido "
                "(instrução FROM identificada)."
            )

        else:

            dockerfile_valido = False

            validacao_artefatos.append(
                "✗ Dockerfile sem instrução FROM identificada."
            )


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 7. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 8. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):
    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):
        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {
    "Pipeline": pipeline_valido,
    ".csproj": csproj_valido,
    "renovate.json": renovate_json_valido,
    "RENOVATE_SETUP.md": renovate_setup_valido,
    "Dockerfile": dockerfile_valido,
    "Docker Compose": docker_compose_valido,
    "Program.cs": program_cs_valido,
    "appsettings.json": appsettings_valido,
    ".editorconfig": editorconfig_valido,
    ".env.example": env_example_valido,
    ".env.io.example": env_io_example_valido
}


for artefato, estado in estados_validacao.items():

    if estado is True:
        simbolo = "✓"

    elif estado is False:
        simbolo = "✗"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (2).yml
✓ .csproj: Boilerplate4Dev (2).csproj
? renovate.json: não fornecido
? RENOVATE_SETUP.md: não fornecido
✓ Dockerfile: Dockerfile (2)
✓ Docker Compose: docker-compose (2).yaml
✓ Program.cs: Program (2).cs
✓ appsettings.json: appsettings (2).json
✓ .editorconfig: .editorconfig (2)
✓ .env.example: .env (2).example
✓ .env.io.example: .env.io (2).example
✓ Scripts: 2 arquivo(s)
    - init (2).sql
    - start-db (2).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (2).sql: script SQL legível e não vazio.
✓ start-db (2).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
? renovate.json
? RENOVATE_SETUP.md
✓ Dockerfile
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

In [36]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

evidencias = {}


# ---------------------------------------------------------
# Recupera estados de validação de forma segura
# ---------------------------------------------------------

pipeline_valido = globals().get(
    "pipeline_valido",
    None
)

csproj_valido = globals().get(
    "csproj_valido",
    None
)

renovate_json_valido = globals().get(
    "renovate_json_valido",
    None
)

docker_compose_valido = globals().get(
    "docker_compose_valido",
    None
)

appsettings_valido = globals().get(
    "appsettings_valido",
    None
)


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj and csproj_valido is True:

    try:
        root = ET.fromstring(
            csproj
        )

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag in (
                "TargetFramework",
                "TargetFrameworks"
            ):

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError:
        target_framework = None


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

pipeline_yaml = None

if pipeline and pipeline_valido is True:

    try:
        pipeline_yaml = yaml.safe_load(
            pipeline
        )
    except Exception:
        pipeline_yaml = None


    # -----------------------------------------------------
    # SDK
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    quality_gate_wait = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )

    evidencias[
        "Espera pelo Quality Gate"
    ] = quality_gate_wait


    # -----------------------------------------------------
    # Identifica job do Sonar estruturalmente
    # -----------------------------------------------------

    chaves_reservadas_gitlab = {
        "image",
        "services",
        "stages",
        "variables",
        "default",
        "include",
        "workflow",
        "cache",
        "before_script",
        "after_script"
    }

    sonar_jobs = []

    if isinstance(
        pipeline_yaml,
        dict
    ):

        for nome_job, config_job in pipeline_yaml.items():

            if nome_job in chaves_reservadas_gitlab:
                continue

            if not isinstance(
                config_job,
                dict
            ):
                continue

            partes_job = []

            for campo in (
                "before_script",
                "script",
                "after_script"
            ):

                valor = config_job.get(
                    campo
                )

                if isinstance(
                    valor,
                    list
                ):

                    partes_job.extend(
                        str(item)
                        for item in valor
                    )

                elif valor:

                    partes_job.append(
                        str(valor)
                    )

            texto_job = "\n".join(
                partes_job
            )

            if contem(
                texto_job,
                "sonar",
                "sonarscanner"
            ):

                sonar_jobs.append(
                    config_job
                )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    # -----------------------------------------------------

    if (
        quality_gate_wait
        and sonar_jobs
    ):

        allow_failure_sonar = False

        for job in sonar_jobs:

            allow_failure = job.get(
                "allow_failure"
            )

            if allow_failure is True:
                allow_failure_sonar = True
                break

            # Alguns pipelines podem representar
            # allow_failure por estrutura mais complexa.
            if isinstance(
                allow_failure,
                dict
            ):
                allow_failure_sonar = True
                break

        evidencias[
            "Quality Gate bloqueante"
        ] = not allow_failure_sonar

    elif quality_gate_wait:

        # Existe espera pelo Quality Gate,
        # mas não foi possível vinculá-la
        # com segurança a um job específico.
        evidencias[
            "Quality Gate bloqueante"
        ] = None

    else:

        evidencias[
            "Quality Gate bloqueante"
        ] = False


    # -----------------------------------------------------
    # Caches
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Regras
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )

    evidencias[
        "Regra para branch main"
    ] = (
        contem(
            pipeline,
            "ci_commit_branch"
        )
        and buscar_regex(
            pipeline,
            r"ci_commit_branch.*main"
        ) is not None
    )


    # -----------------------------------------------------
    # Testes
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )


else:

    for chave in (
        "GitLab CI como código",
        "`dotnet restore` no CI",
        "Build Release no CI",
        "SonarQube",
        "Espera pelo Quality Gate",
        "Quality Gate bloqueante",
        "Cache Sonar",
        "Cache NuGet",
        "Regra para Merge Request",
        "Regra para branch main",
        "Testes automatizados",
        "Deploy automatizado",
        "Promoção automática",
        "Rollback automatizado"
    ):
        evidencias[chave] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if (
    renovate_json
    and renovate_json_valido is True
):

    try:
        renovate_data = json.loads(
            renovate_json
        )

        evidencias[
            "Renovate configurado"
        ] = True

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget"
            in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile"
            in enabled_managers
        )

        evidencias[
            "Vulnerability Alerts"
        ] = (
            renovate_data.get(
                "vulnerabilityAlerts"
            ) is not None
            or contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )
        )

        evidencias[
            "Lock File Maintenance"
        ] = (
            renovate_data.get(
                "lockFileMaintenance"
            ) is not None
        )

    except Exception:

        evidencias[
            "Renovate configurado"
        ] = None

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = None

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = None

        evidencias[
            "Vulnerability Alerts"
        ] = None

        evidencias[
            "Lock File Maintenance"
        ] = None


elif renovate_json:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate no pipeline
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    job_renovate = (
        contem(
            pipeline,
            "renovate/renovate"
        )
        or contem(
            pipeline,
            "renovate $ci_project_path",
            "renovate ${ci_project_path}"
        )
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = job_renovate

    evidencias[
        "Regra schedule para Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "schedule"
        )
    )

    evidencias[
        "Execução manual do Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e orquestração não comprovam
# execução efetiva da ferramenta.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = quantidade_from >= 2

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if (
    docker_compose
    and docker_compose_valido is True
):

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = buscar_regex(
        docker_compose,
        r"external\s*:\s*true"
    ) is not None

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )


elif docker_compose:

    # Arquivo fornecido, mas não validado
    # estruturalmente.
    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql"
    )

    evidencias[
        "Health Check de API"
    ] = contem(
        program_cs,
        "addurlgroup"
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings.json
# ---------------------------------------------------------

if (
    appsettings
    and appsettings_valido is True
):

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "connectionstrings",
        "environment"
    )


elif appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

else:

    evidencias[
        ".env.example presente"
    ] = None


if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

else:

    evidencias[
        ".env.io.example presente"
    ] = None


if env_example or env_io_example:

    texto_env = "\n".join(
        texto
        for texto in (
            env_example,
            env_io_example
        )
        if texto
    )

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        texto_env,
        "environment",
        "stage",
        "server",
        "host",
        "version",
        "project"
    )

else:

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    texto_scripts = "\n".join(
        list(
            scripts.keys()
        )
        + list(
            scripts.values()
        )
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        texto_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        texto_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        texto_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        texto_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 12. Resultado
# ---------------------------------------------------------

print(
    "EVIDÊNCIAS EXTRAÍDAS\n"
)

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net9.0
SDK Pipeline: None

✓ GitLab CI como código
— `dotnet restore` no CI
— Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
— Cache NuGet
✓ Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
— Health Check de banco
— Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
— PostgreSQL configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ .env.io.example presente
✓ Parametrização de ambientes
✓ Scripts presentes
✓ Script de inicialização de banco
— Script de seed
— Dump de banco presente
✓ Automação de ambiente local

In [37]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 2
Classificação: Inicial/Ad hoc
Motivo: Existe pipeline versionado com automações pontuais, mas sem CI estruturada completa.

In [38]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
# ---------------------------------------------------------

if not evidencias:
    raise ValueError(
        "Nenhuma evidência foi extraída."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    "artefatos_analisados": {

        "pipeline": pipeline_nome,
        "csproj": csproj_nome,
        "renovate_json": renovate_json_nome,
        "renovate_setup": renovate_setup_nome,
        "dockerfile": dockerfile_nome,
        "docker_compose": docker_compose_nome,
        "program_cs": program_cs_nome,
        "appsettings": appsettings_nome,
        "editorconfig": editorconfig_nome,
        "env_example": env_example_nome,
        "env_io_example": env_io_example_nome,
        "scripts": scripts_nomes
    },

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline
    },

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "postgresql_configured":
            evidencias.get(
                "PostgreSQL configurado"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            )
    },

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },

    "classificacao_deterministica":
        resultado_maturidade
}


print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)

print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (2).yml",
    "csproj": "Boilerplate4Dev (2).csproj",
    "renovate_json": null,
    "renovate_setup": null,
    "dockerfile": "Dockerfile (2)",
    "docker_compose": "docker-compose (2).yaml",
    "program_cs": "Program (2).cs",
    "appsettings": "appsettings (2).json",
    "editorconfig": ".editorconfig (2)",
    "env_example": ".env (2).example",
    "env_io_example": ".env.io (2).example",
    "scripts": [
      "init (2).sql",
      "start-db (2).ps1"
    ]
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net9.0",
    "sdk_pipeline": null
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": false,
    "build_release": false,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": false,
    "merge_request_rule": true,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": null,
    "nuget_manager": null,
    "dockerfile_manager": null,
    "vulnerability_alerts": null,
    "lock_file_maintenance": null,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": false,
    "api_health_check": false,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "postgresql_configured": false,
    "environment_parameterization": true
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": false,
    "database_dump_present": false,
    "local_environment_automation": true
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "nivel": 2,
    "classificacao": "Inicial/Ad hoc",
    "motivo": "Existe pipeline versionado com automações pontuais, mas sem CI estruturada completa."
  }
}

In [39]:
# ---------------------------------------------------------
# MATURITY CRITERIA
# ---------------------------------------------------------

criterios_maturidade = """
Escala de maturidade das práticas de automação do pipeline:

Nível 1 — Ausente/Tradicional
Não há automação relevante das atividades de build, qualidade, testes ou entrega.

Nível 2 — Inicial/Ad hoc
Existe pipeline versionado, porém as automações são pontuais ou isoladas.

Nível 3 — Parcial/Emergente
Existe pipeline versionado com práticas estruturadas de integração contínua, como restore, build e controles de qualidade, mas ainda existem lacunas relevantes.

Nível 4 — Avançado/Consolidado
Existem práticas integradas e consolidadas envolvendo build, testes automatizados, controles de qualidade bloqueantes, entrega, promoção e recuperação.

A atribuição do nível 4 exige evidências suficientes de integração e execução das práticas. A simples presença de arquivos de configuração não é suficiente.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:
    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica das evidências relacionadas à automação de pipeline apresentadas abaixo.

A classificação foi previamente calculada por critérios determinísticos implementados no notebook.

Sua função NÃO é realizar uma nova classificação independente.

Sua função é interpretar as evidências e avaliar se elas sustentam a classificação determinística.

{criterios_maturidade}

EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}

REGRAS DA ANÁLISE:

1. Utilize exclusivamente as evidências fornecidas.
2. Não presuma práticas não evidenciadas.
3. Não avalie a maturidade DevOps global do projeto.
4. Avalie somente a automação do pipeline e as evidências técnicas relacionadas.
5. Considere:
   true = evidência positiva;
   false = evidência negativa no artefato analisado;
   null = evidência indeterminada.
6. Null não significa ausência da prática.
7. Quality Gate configurado não significa necessariamente Quality Gate bloqueante.
8. allow_failure:true no job de qualidade impede interpretar o Quality Gate como bloqueante.
9. renovate.json demonstra configuração, mas não execução.
10. Um job Renovate demonstra orquestração, mas não comprova execução bem-sucedida.
11. Execução efetiva do Renovate exige evidências de runtime, como histórico de pipeline, logs, branches renovate/* ou merge requests criadas pela ferramenta.
12. Dockerfile e Docker Compose demonstram configuração e automação de construção/execução de contêineres, mas não comprovam deploy automatizado.
13. Scripts locais ou de inicialização de banco não devem ser tratados como deploy automatizado.
14. Sentry, Matomo, logging e health checks caracterizam observabilidade e não constituem, isoladamente, automação de entrega.
15. Ausência de comandos de deploy no pipeline não prova que nenhum deploy seja realizado fora dele.
16. O mesmo princípio se aplica à promoção entre ambientes e ao rollback.
17. Compare explicitamente as evidências com a classificação determinística.
18. Se a classificação for sustentada, declare isso.
19. Se houver inconsistência, descreva-a explicitamente, sem substituir arbitrariamente a classificação.
20. Utilize linguagem técnica, conservadora, rastreável e adequada a um trabalho acadêmico.
Produza a resposta em português nesta estrutura:

### Avaliação da classificação
Classificação determinística:
Avaliação: Sustentada / Parcialmente sustentada / Não sustentada

### Evidências que sustentam a avaliação
...

### Lacunas identificadas
...

### Limitações da interpretação
...

### Síntese
...
"""

print(
    "✓ Prompt de interpretação preparado."
)

✓ Prompt de interpretação preparado.

In [40]:
# ---------------------------------------------------------
# VERSION ANALYSIS STORAGE
# ---------------------------------------------------------

resultados_versoes = {}

print(
    "✓ Estrutura para armazenamento das análises "
    "longitudinais inicializada."
)

✓ Estrutura para armazenamento das análises longitudinais inicializada.

In [41]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Recupera a chave da API
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception:

    api_key = None


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 2. Validação
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not prompt:

    raise ValueError(
        "O prompt de interpretação ainda não foi criado."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


# ---------------------------------------------------------
# 3. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 4. Interpretação assistida
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model="gpt-5.6-terra",

        instructions=(
            "Atue como avaliador técnico de práticas DevOps. "
            "Sua interpretação deve ser conservadora, "
            "rastreável e limitada às evidências fornecidas. "
            "Não realize uma nova classificação independente. "
            "Avalie se as evidências sustentam a classificação "
            "determinística calculada pelo notebook."
        ),

        input=prompt
    )


    interpretacao_ia = response.output_text


    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


except Exception as erro:

    interpretacao_ia = None

    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação
Classificação determinística: **Nível 2 — Inicial/Ad hoc**
Avaliação: **Sustentada**

### Evidências que sustentam a avaliação
- Há evidência de pipeline versionado em GitLab CI, indicada por `gitlab_ci: true` e pelo artefato `gitlab-ci (2).yml`. Isso é compatível com o requisito mínimo do nível 2: existência de pipeline versionado.
- O pipeline contém automação de análise de qualidade com SonarQube (`sonarqube: true`) e espera pelo resultado do Quality Gate (`quality_gate_wait: true`).
- Há regras de execução associadas a merge requests e à branch principal (`merge_request_rule: true` e `main_branch_rule: true`), indicando que parte da automação está vinculada a eventos relevantes do fluxo de integração.
- A existência de Dockerfile com build multiestágio, restore, build e publish (`multi_stage_build`, `docker_restore`, `docker_build` e `docker_publish` como `true`) demonstra automação de construção de imagem de contêiner.
- O Docker Compose apresenta automação para construção e execução local ou em ambiente composto (`docker_compose_build: true`), além de elementos operacionais como política de reinício, rede externa e proxy reverso.
- Existem scripts de automação local, incluindo inicialização de banco de dados e automação de ambiente local (`database_initialization_script: true` e `local_environment_automation: true`).

Essas evidências demonstram automações pontuais e artefatos estruturados de construção, qualidade e execução em contêineres. Contudo, elas não demonstram uma cadeia completa e integrada de CI/CD. Portanto, sustentam a caracterização de pipeline versionado com automações isoladas ou incompletas, compatível com o nível 2.

### Lacunas identificadas
- Não há evidência de `dotnet restore` no pipeline (`dotnet_restore: false`) nem de build em configuração Release (`build_release: false`). Embora o Dockerfile contenha etapas de restore e build, isso não comprova que tais atividades estejam integradas e executadas no pipeline GitLab CI.
- Não há testes automatizados evidenciados no pipeline (`automated_tests: false`). Esta é uma lacuna relevante para caracterizar integração contínua estruturada.
- O Quality Gate não pode ser considerado bloqueante (`quality_gate_blocking: false`). Assim, apesar da análise SonarQube e da espera pelo Quality Gate, não há evidência de que uma condição de qualidade reprovada interrompa o fluxo.
- Não há cache de dependências NuGet no pipeline (`nuget_cache: false`), embora exista cache específico do Sonar (`sonar_cache: true`). Isso não impede a automação, mas limita a evidência de otimização e consolidação da CI.
- Não há evidências de deploy automatizado, promoção entre ambientes ou rollback automatizado (`automated_deploy`, `automated_promotion` e `automated_rollback` iguais a `false`).
- Não há evidências fornecidas de gestão automatizada de dependências. Os indicadores relativos a Renovate e alertas de vulnerabilidades estão como `null` ou `false`, o que deve ser interpretado como indeterminação ou ausência de job identificado, sem inferir ausência absoluta da prática fora dos artefatos analisados.
- Recursos de observabilidade, como Sentry, Matomo, logging e health checks, estão configurados, mas não comprovam automação de entrega, promoção ou recuperação.

Em conjunto, essas lacunas impedem que as evidências sustentem o nível 3, que exigiria práticas de CI mais estruturadas envolvendo restore, build e controles de qualidade, ou o nível 4, que exigiria integração comprovada entre build, testes, controles bloqueantes, entrega, promoção e recuperação.

### Limitações da interpretação
- A análise está limitada aos indicadores e artefatos explicitamente fornecidos. Não foram apresentados logs de execução, histórico de pipelines, resultados de jobs, artefatos publicados ou registros de deploy.
- A presença de Dockerfile e Docker Compose comprova configuração e automação de build/execução de contêineres, mas não permite concluir que imagens sejam publicadas, implantadas ou promovidas automaticamente pelo pipeline.
- A ausência de deploy, promoção ou rollback no pipeline analisado não prova que essas práticas não ocorram por mecanismos externos, manuais ou em outros repositórios.
- O valor `null` para itens de gerenciamento de dependências representa evidência indeterminada, e não ausência definitiva da prática.
- A configuração do SonarQube e a espera pelo Quality Gate não permitem interpretá-lo como bloqueante, pois `quality_gate_blocking` está explicitamente marcado como `false`.

### Síntese
A classificação determinística **Nível 2 — Inicial/Ad hoc** está sustentada pelas evidências disponíveis. Há pipeline GitLab CI versionado, análise de qualidade, regras de acionamento por merge request e branch principal, construção de contêineres e automações locais. Entretanto, não há evidência de uma CI completa e integrada com restore e build explicitamente executados no pipeline, testes automatizados e Quality Gate bloqueante. Também não há comprovação de deploy, promoção ou rollback automatizados. Assim, as evidências não sustentam elevação para os níveis 3 ou 4.

In [42]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS — V1
# ---------------------------------------------------------

import copy

if not evidencias:
    raise ValueError(
        "As evidências da V1 não estão disponíveis."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação de maturidade da V1 "
        "não está disponível."
    )

if evidencias_para_ia is None:
    raise ValueError(
        "O pacote estruturado de evidências da V1 "
        "não está disponível."
    )


resultados_versoes["V1"] = {

    "versao": "V1",

    "snapshot":
        "web-1.25.10-1",

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_ia
        if "interpretacao_ia" in globals()
        else None,

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline
}


print(
    "✓ Resultados da V1 armazenados para a análise longitudinal."
)

✓ Resultados da V1 armazenados para a análise longitudinal.

## 4. V2 — Pipeline Technical Analysis

### 4.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.4-1`**.

### 4.2 Análise dos Artefatos

In [43]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None

print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [44]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:
        root = ET.fromstring(csproj)

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar o arquivo .csproj:"
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # Pipeline versionado
    evidencias["GitLab CI como código"] = True


    # Restore
    evidencias["`dotnet restore` no CI"] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias["Build Release no CI"] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias["SonarQube"] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias["Espera pelo Quality Gate"] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias["Quality Gate bloqueante"] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias["Cache Sonar"] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias["Cache NuGet"] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias["Regra para Merge Request"] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias["Regra para branch main"] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias["Testes automatizados"] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias["Deploy automatizado"] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias["Promoção automática"] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias["Rollback automatizado"] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias["GitLab CI como código"] = None
    evidencias["`dotnet restore` no CI"] = None
    evidencias["Build Release no CI"] = None
    evidencias["SonarQube"] = None
    evidencias["Espera pelo Quality Gate"] = None
    evidencias["Quality Gate bloqueante"] = None
    evidencias["Cache Sonar"] = None
    evidencias["Cache NuGet"] = None
    evidencias["Regra para Merge Request"] = None
    evidencias["Regra para branch main"] = None
    evidencias["Testes automatizados"] = None
    evidencias["Deploy automatizado"] = None
    evidencias["Promoção automática"] = None
    evidencias["Rollback automatizado"] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias["Renovate configurado"] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )


    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias["Renovate configurado"] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=re.IGNORECASE | re.MULTILINE
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    # Se já havia evidência anterior, preserva True
    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:
        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline
}


# ---------------------------------------------------------
# 14. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()


# ---------------------------------------------------------
# 15. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? PostgreSQL configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local

In [45]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (3)
Saving .env.example to .env (3).example
Saving appsettings.json to appsettings (3).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (3).csproj
Saving docker-compose.yaml to docker-compose (3).yaml
Saving Dockerfile to Dockerfile (3)
Saving env.io.example to env.io.example
Saving gitlab-ci.yml to gitlab-ci (3).yml
Saving init.sql to init (3).sql
Saving Program.cs to Program (3).cs
Saving renovate.json to renovate.json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP.md
Saving seed.sql to seed.sql
Saving start-db.ps1 to start-db (3).ps1

✓ 14 arquivo(s) carregado(s):

  ✓ .editorconfig (3)
  ✓ .env (3).example
  ✓ Boilerplate4Dev (3).csproj
  ✓ Dockerfile (3)
  ✓ Program (3).cs
  ✓ RENOVATE_SETUP.md
  ✓ appsettings (3).json
  ✓ docker-compose (3).yaml
  ✓ env.io.example
  ✓ gitlab-ci (3).yml
  ✓ init (3).sql
  ✓ renovate.json
  ✓ seed.sql
  ✓ start-db (3).ps1

In [46]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:
    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None
dockerfile_valido = None
docker_compose_valido = None
program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):
    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):
    nome = nome_base(nome)

    # Remove sufixos adicionados pelo Colab:
    # arquivo (1).json -> arquivo.json
    # Dockerfile (2)   -> Dockerfile
    nome = re.sub(
        r"\s*\(\d+\)(?=\.|$)",
        "",
        nome
    )

    return nome.lower().strip()


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):
    if not candidatos:
        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _ in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(conteudo):
    if conteudo is None:
        return None

    if isinstance(
        conteudo,
        bytes
    ):
        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []
candidatos_dockerfile = []
candidatos_docker_compose = []
candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []

extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # GitLab CI
    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Projeto .NET
    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Renovate
    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Dockerfile
    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Docker Compose
    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Program.cs
    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # appsettings.json
    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .editorconfig
    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.io.example
    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.example
    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Scripts
    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile"
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):
    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):
    if conteudo is None:
        return None

    if not arquivo_nao_vazio(
        conteudo
    ):
        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):
            continue

        if "=" not in linha:
            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # O arquivo continua legível e utilizável
        # para extração de evidências.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile is not None:

    if not arquivo_nao_vazio(
        dockerfile
    ):

        dockerfile_valido = False

        validacao_artefatos.append(
            "✗ Dockerfile: arquivo vazio."
        )

    else:

        possui_from = bool(
            re.search(
                r"^\s*FROM\s+\S+",
                dockerfile,
                flags=(
                    re.IGNORECASE
                    | re.MULTILINE
                )
            )
        )

        if possui_from:

            dockerfile_valido = True

            validacao_artefatos.append(
                "✓ Dockerfile estruturalmente válido "
                "(instrução FROM identificada)."
            )

        else:

            dockerfile_valido = False

            validacao_artefatos.append(
                "✗ Dockerfile sem instrução FROM identificada."
            )


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 7. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 8. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):
    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):
        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {
    "Pipeline": pipeline_valido,
    ".csproj": csproj_valido,
    "renovate.json": renovate_json_valido,
    "RENOVATE_SETUP.md": renovate_setup_valido,
    "Dockerfile": dockerfile_valido,
    "Docker Compose": docker_compose_valido,
    "Program.cs": program_cs_valido,
    "appsettings.json": appsettings_valido,
    ".editorconfig": editorconfig_valido,
    ".env.example": env_example_valido,
    ".env.io.example": env_io_example_valido
}


for artefato, estado in estados_validacao.items():

    if estado is True:
        simbolo = "✓"

    elif estado is False:
        simbolo = "✗"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (3).yml
✓ .csproj: Boilerplate4Dev (3).csproj
✓ renovate.json: renovate.json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP.md
✓ Dockerfile: Dockerfile (3)
✓ Docker Compose: docker-compose (3).yaml
✓ Program.cs: Program (3).cs
✓ appsettings.json: appsettings (3).json
✓ .editorconfig: .editorconfig (3)
✓ .env.example: .env (3).example
✓ .env.io.example: env.io.example
✓ Scripts: 3 arquivo(s)
    - init (3).sql
    - seed.sql
    - start-db (3).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (3).sql: script SQL legível e não vazio.
✓ seed.sql: script SQL legível e não vazio.
✓ start-db (3).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

In [47]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj and csproj_valido is True:

    root = ET.fromstring(csproj)

    for elemento in root.iter():

        tag = elemento.tag.split("}")[-1]

        if tag in (
            "TargetFramework",
            "TargetFrameworks"
        ):

            target_framework = (
                elemento.text.strip()
                if elemento.text
                else None
            )

            break


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    # -----------------------------------------------------
    # SDK
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    quality_gate_wait = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )

    evidencias[
        "Espera pelo Quality Gate"
    ] = quality_gate_wait


    # -----------------------------------------------------
    # Identifica job do Sonar estruturalmente
    # -----------------------------------------------------

    chaves_reservadas_gitlab = {
        "image",
        "services",
        "stages",
        "variables",
        "default",
        "include",
        "workflow",
        "cache",
        "before_script",
        "after_script"
    }

    sonar_jobs = []

    if isinstance(pipeline_yaml, dict):

        for nome_job, config_job in pipeline_yaml.items():

            if nome_job in chaves_reservadas_gitlab:
                continue

            if not isinstance(config_job, dict):
                continue

            partes_job = []

            for campo in (
                "before_script",
                "script",
                "after_script"
            ):

                valor = config_job.get(campo)

                if isinstance(valor, list):
                    partes_job.extend(
                        str(item)
                        for item in valor
                    )

                elif valor:
                    partes_job.append(
                        str(valor)
                    )

            texto_job = "\n".join(partes_job)

            if contem(
                texto_job,
                "sonar",
                "sonarscanner"
            ):
                sonar_jobs.append(
                    config_job
                )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    # -----------------------------------------------------

    if quality_gate_wait and sonar_jobs:

        allow_failure_sonar = any(
            job.get("allow_failure") is True
            for job in sonar_jobs
        )

        evidencias[
            "Quality Gate bloqueante"
        ] = not allow_failure_sonar

    elif quality_gate_wait:

        # Quality Gate existe, mas não foi possível
        # vincular com segurança a um job específico.
        evidencias[
            "Quality Gate bloqueante"
        ] = None

    else:

        evidencias[
            "Quality Gate bloqueante"
        ] = False


    # -----------------------------------------------------
    # Caches
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Regras
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )

    evidencias[
        "Regra para branch main"
    ] = (
        contem(
            pipeline,
            "ci_commit_branch"
        )
        and buscar_regex(
            pipeline,
            r"ci_commit_branch.*main"
        ) is not None
    )


    # -----------------------------------------------------
    # Testes
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )


else:

    for chave in (
        "GitLab CI como código",
        "`dotnet restore` no CI",
        "Build Release no CI",
        "SonarQube",
        "Espera pelo Quality Gate",
        "Quality Gate bloqueante",
        "Cache Sonar",
        "Cache NuGet",
        "Regra para Merge Request",
        "Regra para branch main",
        "Testes automatizados",
        "Deploy automatizado",
        "Promoção automática",
        "Rollback automatizado"
    ):
        evidencias[chave] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if (
    renovate_json
    and renovate_json_valido is True
):

    renovate_data = json.loads(
        renovate_json
    )

    evidencias[
        "Renovate configurado"
    ] = True

    enabled_managers = renovate_data.get(
        "enabledManagers",
        []
    )

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = (
        "nuget" in enabled_managers
    )

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = (
        "dockerfile" in enabled_managers
    )

    evidencias[
        "Vulnerability Alerts"
    ] = (
        renovate_data.get(
            "vulnerabilityAlerts"
        ) is not None
        or contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )
    )

    evidencias[
        "Lock File Maintenance"
    ] = (
        renovate_data.get(
            "lockFileMaintenance"
        ) is not None
    )

elif renovate_json:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate no pipeline
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    job_renovate = (
        contem(
            pipeline,
            "renovate/renovate"
        )
        or contem(
            pipeline,
            "renovate $ci_project_path",
            "renovate ${ci_project_path}"
        )
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = job_renovate

    evidencias[
        "Regra schedule para Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "schedule"
        )
    )

    evidencias[
        "Execução manual do Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração/orquestração não prova execução.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = quantidade_from >= 2

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias["Dockerfile presente"] = None
    evidencias["Docker multi-stage build"] = None
    evidencias["Restore no Dockerfile"] = None
    evidencias["Build no Dockerfile"] = None
    evidencias["Publish no Dockerfile"] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = buscar_regex(
        docker_compose,
        r"external\s*:\s*true"
    ) is not None

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias["Docker Compose presente"] = None
    evidencias["Build definido no Docker Compose"] = None
    evidencias["Política de restart"] = None
    evidencias["Rede externa no Docker Compose"] = None
    evidencias["Reverse proxy configurado"] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql"
    )

    evidencias[
        "Health Check de API"
    ] = contem(
        program_cs,
        "addurlgroup"
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole"
    )

else:

    evidencias["Sentry integrado em runtime"] = None
    evidencias["Health Checks"] = None
    evidencias["Health Check de banco"] = None
    evidencias["Health Check de API"] = None
    evidencias["Console Logging"] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "connectionstrings",
        "environment"
    )

else:

    evidencias["appsettings presente"] = None
    evidencias["Sentry configurado"] = None
    evidencias["Matomo configurado"] = None
    evidencias["PostgreSQL configurado"] = None
    evidencias["Configuração externalizada"] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security"
    )

else:

    evidencias[".editorconfig presente"] = None
    evidencias["Regras de analyzer declaradas"] = None
    evidencias["Regras de segurança declaradas"] = None


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

else:

    evidencias[
        ".env.example presente"
    ] = None


if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

else:

    evidencias[
        ".env.io.example presente"
    ] = None


if env_example or env_io_example:

    texto_env = "\n".join(
        texto
        for texto in (
            env_example,
            env_io_example
        )
        if texto
    )

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        texto_env,
        "environment",
        "stage",
        "server",
        "host",
        "version",
        "project"
    )

else:

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    texto_scripts = "\n".join(
        list(scripts.keys())
        + list(scripts.values())
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        texto_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        texto_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        texto_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        texto_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "localhost"
    )

else:

    evidencias["Scripts presentes"] = None
    evidencias["Script de inicialização de banco"] = None
    evidencias["Script de seed"] = None
    evidencias["Dump de banco presente"] = None
    evidencias["Automação de ambiente local"] = None


# ---------------------------------------------------------
# 12. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
✓ Job Renovate no pipeline
✓ Regra schedule para Renovate
✓ Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
— Health Check de banco
— Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
— PostgreSQL configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ .env.io.example presente
✓ Parametrização de ambientes
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local

In [48]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [49]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
# ---------------------------------------------------------

if not evidencias:
    raise ValueError(
        "Nenhuma evidência foi extraída."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    "artefatos_analisados": {

        "pipeline": pipeline_nome,
        "csproj": csproj_nome,
        "renovate_json": renovate_json_nome,
        "renovate_setup": renovate_setup_nome,
        "dockerfile": dockerfile_nome,
        "docker_compose": docker_compose_nome,
        "program_cs": program_cs_nome,
        "appsettings": appsettings_nome,
        "editorconfig": editorconfig_nome,
        "env_example": env_example_nome,
        "env_io_example": env_io_example_nome,
        "scripts": scripts_nomes
    },

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline
    },

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "postgresql_configured":
            evidencias.get(
                "PostgreSQL configurado"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            )
    },

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },

    "classificacao_deterministica":
        resultado_maturidade
}


print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)

print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (3).yml",
    "csproj": "Boilerplate4Dev (3).csproj",
    "renovate_json": "renovate.json",
    "renovate_setup": "RENOVATE_SETUP.md",
    "dockerfile": "Dockerfile (3)",
    "docker_compose": "docker-compose (3).yaml",
    "program_cs": "Program (3).cs",
    "appsettings": "appsettings (3).json",
    "editorconfig": ".editorconfig (3)",
    "env_example": ".env (3).example",
    "env_io_example": "env.io.example",
    "scripts": [
      "init (3).sql",
      "seed.sql",
      "start-db (3).ps1"
    ]
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0"
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": true,
    "renovate_schedule": true,
    "renovate_manual": true,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": false,
    "api_health_check": false,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "postgresql_configured": false,
    "environment_parameterization": true
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta."
  }
}

In [50]:
# ---------------------------------------------------------
# MATURITY CRITERIA
# ---------------------------------------------------------

criterios_maturidade = """
Escala de maturidade das práticas de automação do pipeline:

Nível 1 — Ausente/Tradicional
Não há automação relevante das atividades de build, qualidade, testes ou entrega.

Nível 2 — Inicial/Ad hoc
Existe pipeline versionado, porém as automações são pontuais ou isoladas.

Nível 3 — Parcial/Emergente
Existe pipeline versionado com práticas estruturadas de integração contínua, como restore, build e controles de qualidade, mas ainda existem lacunas relevantes.

Nível 4 — Avançado/Consolidado
Existem práticas integradas e consolidadas envolvendo build, testes automatizados, controles de qualidade bloqueantes, entrega, promoção e recuperação.

A atribuição do nível 4 exige evidências suficientes de integração e execução das práticas. A simples presença de arquivos de configuração não é suficiente.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:
    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica das evidências relacionadas à automação de pipeline apresentadas abaixo.

A classificação foi previamente calculada por critérios determinísticos implementados no notebook.

Sua função NÃO é realizar uma nova classificação independente.

Sua função é interpretar as evidências e avaliar se elas sustentam a classificação determinística.

{criterios_maturidade}

EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}

REGRAS DA ANÁLISE:

1. Utilize exclusivamente as evidências fornecidas.
2. Não presuma práticas não evidenciadas.
3. Não avalie a maturidade DevOps global do projeto.
4. Avalie somente a automação do pipeline e as evidências técnicas relacionadas.
5. Considere:
   true = evidência positiva;
   false = evidência negativa no artefato analisado;
   null = evidência indeterminada.
6. Null não significa ausência da prática.
7. Quality Gate configurado não significa necessariamente Quality Gate bloqueante.
8. allow_failure:true no job de qualidade impede interpretar o Quality Gate como bloqueante.
9. renovate.json demonstra configuração, mas não execução.
10. Um job Renovate demonstra orquestração, mas não comprova execução bem-sucedida.
11. Execução efetiva do Renovate exige evidências de runtime, como histórico de pipeline, logs, branches renovate/* ou merge requests criadas pela ferramenta.
12. Dockerfile e Docker Compose demonstram configuração e automação de construção/execução de contêineres, mas não comprovam deploy automatizado.
13. Scripts locais ou de inicialização de banco não devem ser tratados como deploy automatizado.
14. Sentry, Matomo, logging e health checks caracterizam observabilidade e não constituem, isoladamente, automação de entrega.
15. Ausência de comandos de deploy no pipeline não prova que nenhum deploy seja realizado fora dele.
16. O mesmo princípio se aplica à promoção entre ambientes e ao rollback.
17. Compare explicitamente as evidências com a classificação determinística.
18. Se a classificação for sustentada, declare isso.
19. Se houver inconsistência, descreva-a explicitamente, sem substituir arbitrariamente a classificação.
20. Utilize linguagem técnica, conservadora, rastreável e adequada a um trabalho acadêmico.
Produza a resposta em português nesta estrutura:

### Avaliação da classificação
Classificação determinística:
Avaliação: Sustentada / Parcialmente sustentada / Não sustentada

### Evidências que sustentam a avaliação
...

### Lacunas identificadas
...

### Limitações da interpretação
...

### Síntese
...
"""

print(
    "✓ Prompt de interpretação preparado."
)

✓ Prompt de interpretação preparado.

In [51]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Recupera a chave da API
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception:

    api_key = None


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 2. Validação
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not prompt:

    raise ValueError(
        "O prompt de interpretação ainda não foi criado."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


# ---------------------------------------------------------
# 3. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 4. Interpretação assistida
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model="gpt-5.6-terra",

        instructions=(
            "Atue como avaliador técnico de práticas DevOps. "
            "Sua interpretação deve ser conservadora, "
            "rastreável e limitada às evidências fornecidas. "
            "Não realize uma nova classificação independente. "
            "Avalie se as evidências sustentam a classificação "
            "determinística calculada pelo notebook."
        ),

        input=prompt
    )


    interpretacao_ia = response.output_text


    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


except Exception as erro:

    interpretacao_ia = None

    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação
**Classificação determinística:** Nível 3 — **Parcial/Emergente**
**Avaliação:** **Sustentada**

### Evidências que sustentam a avaliação
A classificação como nível 3 é sustentada pelas evidências de integração contínua estruturada presentes nos artefatos analisados:

- Há pipeline GitLab CI versionado (`gitlab_ci: true`), atendendo ao requisito básico de automação declarada e rastreável no repositório.
- O pipeline contempla restauração de dependências .NET (`dotnet_restore: true`) e compilação em modo Release (`build_release: true`), caracterizando automação de build compatível com práticas de integração contínua.
- Há integração com SonarQube (`sonarqube: true`) e espera pelo resultado do Quality Gate (`quality_gate_wait: true`). Isso evidencia execução ou orquestração de análise estática no fluxo de CI.
- Os caches de Sonar (`sonar_cache: true`) e NuGet (`nuget_cache: true`) reforçam que o pipeline possui estrutura operacional além de comandos isolados, contribuindo para eficiência e repetibilidade das execuções.
- A regra associada à branch principal (`main_branch_rule: true`) indica que parte do pipeline possui direcionamento condicionado ao fluxo principal do repositório.
- A presença de `.editorconfig`, regras de analisadores e regras de segurança declaradas (`editorconfig_present`, `analyzer_rules_declared` e `security_rules_declared`) complementa a existência de controles de qualidade estática.
- A automação de dependências está configurada por meio do Renovate, incluindo gerenciadores para NuGet e Dockerfile, alertas de vulnerabilidade, manutenção de lock files, job de Renovate, agendamento e acionamento manual. Essas evidências demonstram configuração e orquestração planejada para atualização de dependências.
- O Dockerfile possui build multiestágio, restauração, build e publicação da aplicação. O Docker Compose também evidencia automação de construção e execução local ou em ambiente baseado em contêineres.
- Scripts para inicialização e seed de banco, além de automação de ambiente local, fornecem suporte à reprodutibilidade do ambiente de desenvolvimento, embora não caracterizem entrega automatizada.

Em conjunto, essas evidências são compatíveis com a caracterização determinística de que existe integração contínua estruturada, incluindo restore, build e controles de qualidade, sem comprovação de automação completa do ciclo de entrega.

### Lacunas identificadas
As lacunas registradas nas evidências impedem que o conjunto seja interpretado como automação consolidada de nível 4:

- Não há testes automatizados evidenciados (`automated_tests: false`). Portanto, não há suporte para afirmar que o pipeline execute testes unitários, de integração, end-to-end ou outro tipo de teste automatizado como controle de qualidade.
- Embora o Quality Gate seja aguardado (`quality_gate_wait: true`), ele não é bloqueante (`quality_gate_blocking: false`). Conforme as regras fornecidas, essa condição não permite interpretar o controle de qualidade como impeditivo para continuidade do pipeline.
- Não há regra específica para merge requests (`merge_request_rule: false`), o que limita a evidência de aplicação sistemática das validações antes da integração de alterações propostas.
- Não há evidência de deploy automatizado (`automated_deploy: false`), promoção automatizada entre ambientes (`automated_promotion: false`) ou rollback automatizado (`automated_rollback: false`).
- Dockerfile e Docker Compose comprovam automação de construção e execução de contêineres, mas não comprovam publicação de imagem, implantação em infraestrutura, promoção de versão ou recuperação automatizada.
- A configuração do Renovate e a presença de job agendado demonstram capacidade de orquestração, mas a execução efetiva é indeterminada (`renovate_effective_execution: null`). Não foram fornecidos logs, histórico de pipelines, branches `renovate/*` ou merge requests criadas pela ferramenta.
- Os health checks existentes não incluem verificação de banco de dados nem de API (`database_health_check: false` e `api_health_check: false`), reduzindo a evidência de validações operacionais mais abrangentes. Ainda assim, essa observação é complementar, pois health checks não constituem, isoladamente, automação de entrega.

### Limitações da interpretação
- A análise está limitada exclusivamente aos indicadores apresentados. Não foram avaliados arquivos completos de pipeline, logs, histórico de execuções, configurações de infraestrutura, registros de deploy ou políticas externas ao repositório.
- A ausência de automação de deploy, promoção ou rollback nos artefatos analisados não demonstra que tais práticas não existam em ferramentas, pipelines ou processos externos. Apenas não há evidência suficiente para afirmá-las neste escopo.
- A configuração do Renovate não comprova atualizações executadas com sucesso, pois a evidência de execução efetiva foi informada como `null`.
- A existência de SonarQube e de espera pelo Quality Gate não comprova bloqueio de qualidade, porque `quality_gate_blocking` está explicitamente marcado como `false`.
- Elementos de observabilidade, como Sentry, Matomo, logging e health checks, foram considerados apenas como contexto técnico operacional. Eles não foram interpretados como evidência de automação de entrega.
- A análise não reclassifica o projeto nem avalia sua maturidade DevOps global; ela verifica a aderência das evidências à classificação determinística fornecida.

### Síntese
A classificação determinística de **Nível 3 — Parcial/Emergente** está **sustentada** pelas evidências. O conjunto demonstra um pipeline GitLab CI versionado com restauração de dependências, build em Release, análise estática com SonarQube, espera por Quality Gate, caches e automações complementares de dependências e contêineres.

Contudo, permanecem lacunas relevantes para uma caracterização de automação avançada e consolidada: não há testes automatizados evidenciados, o Quality Gate não é bloqueante, e não há evidências de deploy, promoção ou rollback automatizados. Assim, as evidências suportam a conclusão de integração contínua estruturada, mas incompleta quanto à automação ponta a ponta exigida para o nível 4.

In [52]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS — V2
# ---------------------------------------------------------

import copy

if not evidencias:
    raise ValueError(
        "As evidências da V2 não estão disponíveis."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação de maturidade da V2 "
        "não está disponível."
    )

if evidencias_para_ia is None:
    raise ValueError(
        "O pacote estruturado de evidências da V2 "
        "não está disponível."
    )


resultados_versoes["V2"] = {

    "versao": "V2",
    "snapshot": "web-1.26.4-1",

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_ia
        if "interpretacao_ia" in globals()
        else None,

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline
}


print(
    "✓ Resultados da V2 armazenados para a análise longitudinal."
)

✓ Resultados da V2 armazenados para a análise longitudinal.

## 5. V3 — Pipeline Technical Analysis

### 5.1 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.6-1`**.

### 5.2 Análise dos Artefatos

In [53]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None

print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [54]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:
        root = ET.fromstring(csproj)

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar o arquivo .csproj:"
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # Pipeline versionado
    evidencias["GitLab CI como código"] = True


    # Restore
    evidencias["`dotnet restore` no CI"] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias["Build Release no CI"] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias["SonarQube"] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias["Espera pelo Quality Gate"] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias["Quality Gate bloqueante"] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias["Cache Sonar"] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias["Cache NuGet"] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias["Regra para Merge Request"] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias["Regra para branch main"] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias["Testes automatizados"] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias["Deploy automatizado"] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias["Promoção automática"] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias["Rollback automatizado"] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias["GitLab CI como código"] = None
    evidencias["`dotnet restore` no CI"] = None
    evidencias["Build Release no CI"] = None
    evidencias["SonarQube"] = None
    evidencias["Espera pelo Quality Gate"] = None
    evidencias["Quality Gate bloqueante"] = None
    evidencias["Cache Sonar"] = None
    evidencias["Cache NuGet"] = None
    evidencias["Regra para Merge Request"] = None
    evidencias["Regra para branch main"] = None
    evidencias["Testes automatizados"] = None
    evidencias["Deploy automatizado"] = None
    evidencias["Promoção automática"] = None
    evidencias["Rollback automatizado"] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias["Renovate configurado"] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )


    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias["Renovate configurado"] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=re.IGNORECASE | re.MULTILINE
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    # Se já havia evidência anterior, preserva True
    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:
        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline
}


# ---------------------------------------------------------
# 14. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()


# ---------------------------------------------------------
# 15. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? PostgreSQL configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local

In [55]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (4)
Saving .env.example to .env (4).example
Saving .env.io.example to .env.io (3).example
Saving appsettings.json to appsettings (4).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (4).csproj
Saving docker-compose.yaml to docker-compose (4).yaml
Saving Dockerfile to Dockerfile (4)
Saving gitlab-ci.yml to gitlab-ci (4).yml
Saving init.sql to init (4).sql
Saving Program.cs to Program (4).cs
Saving renovate.json to renovate (1).json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP (1).md
Saving seed.sql to seed (1).sql
Saving start-db.ps1 to start-db (4).ps1

✓ 14 arquivo(s) carregado(s):

  ✓ .editorconfig (4)
  ✓ .env (4).example
  ✓ .env.io (3).example
  ✓ Boilerplate4Dev (4).csproj
  ✓ Dockerfile (4)
  ✓ Program (4).cs
  ✓ RENOVATE_SETUP (1).md
  ✓ appsettings (4).json
  ✓ docker-compose (4).yaml
  ✓ gitlab-ci (4).yml
  ✓ init (4).sql
  ✓ renovate (1).json
  ✓ seed (1).sql
  ✓ start-db (4).ps1

In [56]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:
    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None
dockerfile_valido = None
docker_compose_valido = None
program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):
    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):
    nome = nome_base(nome)

    # Remove sufixos adicionados pelo Colab:
    # arquivo (1).json -> arquivo.json
    # Dockerfile (2)   -> Dockerfile
    nome = re.sub(
        r"\s*\(\d+\)(?=\.|$)",
        "",
        nome
    )

    return nome.lower().strip()


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):
    if not candidatos:
        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _ in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(conteudo):
    if conteudo is None:
        return None

    if isinstance(
        conteudo,
        bytes
    ):
        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []
candidatos_dockerfile = []
candidatos_docker_compose = []
candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []

extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # GitLab CI
    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Projeto .NET
    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Renovate
    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Dockerfile
    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Docker Compose
    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Program.cs
    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # appsettings.json
    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .editorconfig
    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.io.example
    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.example
    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Scripts
    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile"
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):
    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):
    if conteudo is None:
        return None

    if not arquivo_nao_vazio(
        conteudo
    ):
        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):
            continue

        if "=" not in linha:
            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # O arquivo continua legível e utilizável
        # para extração de evidências.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile is not None:

    if not arquivo_nao_vazio(
        dockerfile
    ):

        dockerfile_valido = False

        validacao_artefatos.append(
            "✗ Dockerfile: arquivo vazio."
        )

    else:

        possui_from = bool(
            re.search(
                r"^\s*FROM\s+\S+",
                dockerfile,
                flags=(
                    re.IGNORECASE
                    | re.MULTILINE
                )
            )
        )

        if possui_from:

            dockerfile_valido = True

            validacao_artefatos.append(
                "✓ Dockerfile estruturalmente válido "
                "(instrução FROM identificada)."
            )

        else:

            dockerfile_valido = False

            validacao_artefatos.append(
                "✗ Dockerfile sem instrução FROM identificada."
            )


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 7. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 8. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):
    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):
        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {
    "Pipeline": pipeline_valido,
    ".csproj": csproj_valido,
    "renovate.json": renovate_json_valido,
    "RENOVATE_SETUP.md": renovate_setup_valido,
    "Dockerfile": dockerfile_valido,
    "Docker Compose": docker_compose_valido,
    "Program.cs": program_cs_valido,
    "appsettings.json": appsettings_valido,
    ".editorconfig": editorconfig_valido,
    ".env.example": env_example_valido,
    ".env.io.example": env_io_example_valido
}


for artefato, estado in estados_validacao.items():

    if estado is True:
        simbolo = "✓"

    elif estado is False:
        simbolo = "✗"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (4).yml
✓ .csproj: Boilerplate4Dev (4).csproj
✓ renovate.json: renovate (1).json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP (1).md
✓ Dockerfile: Dockerfile (4)
✓ Docker Compose: docker-compose (4).yaml
✓ Program.cs: Program (4).cs
✓ appsettings.json: appsettings (4).json
✓ .editorconfig: .editorconfig (4)
✓ .env.example: .env (4).example
✓ .env.io.example: .env.io (3).example
✓ Scripts: 3 arquivo(s)
    - init (4).sql
    - seed (1).sql
    - start-db (4).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (4).sql: script SQL legível e não vazio.
✓ seed (1).sql: script SQL legível e não vazio.
✓ start-db (4).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

In [57]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj and csproj_valido is True:

    root = ET.fromstring(csproj)

    for elemento in root.iter():

        tag = elemento.tag.split("}")[-1]

        if tag in (
            "TargetFramework",
            "TargetFrameworks"
        ):

            target_framework = (
                elemento.text.strip()
                if elemento.text
                else None
            )

            break


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    # -----------------------------------------------------
    # SDK
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    quality_gate_wait = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )

    evidencias[
        "Espera pelo Quality Gate"
    ] = quality_gate_wait


    # -----------------------------------------------------
    # Identifica job do Sonar estruturalmente
    # -----------------------------------------------------

    chaves_reservadas_gitlab = {
        "image",
        "services",
        "stages",
        "variables",
        "default",
        "include",
        "workflow",
        "cache",
        "before_script",
        "after_script"
    }

    sonar_jobs = []

    if isinstance(pipeline_yaml, dict):

        for nome_job, config_job in pipeline_yaml.items():

            if nome_job in chaves_reservadas_gitlab:
                continue

            if not isinstance(config_job, dict):
                continue

            partes_job = []

            for campo in (
                "before_script",
                "script",
                "after_script"
            ):

                valor = config_job.get(campo)

                if isinstance(valor, list):
                    partes_job.extend(
                        str(item)
                        for item in valor
                    )

                elif valor:
                    partes_job.append(
                        str(valor)
                    )

            texto_job = "\n".join(partes_job)

            if contem(
                texto_job,
                "sonar",
                "sonarscanner"
            ):
                sonar_jobs.append(
                    config_job
                )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    # -----------------------------------------------------

    if quality_gate_wait and sonar_jobs:

        allow_failure_sonar = any(
            job.get("allow_failure") is True
            for job in sonar_jobs
        )

        evidencias[
            "Quality Gate bloqueante"
        ] = not allow_failure_sonar

    elif quality_gate_wait:

        # Quality Gate existe, mas não foi possível
        # vincular com segurança a um job específico.
        evidencias[
            "Quality Gate bloqueante"
        ] = None

    else:

        evidencias[
            "Quality Gate bloqueante"
        ] = False


    # -----------------------------------------------------
    # Caches
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Regras
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )

    evidencias[
        "Regra para branch main"
    ] = (
        contem(
            pipeline,
            "ci_commit_branch"
        )
        and buscar_regex(
            pipeline,
            r"ci_commit_branch.*main"
        ) is not None
    )


    # -----------------------------------------------------
    # Testes
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )


else:

    for chave in (
        "GitLab CI como código",
        "`dotnet restore` no CI",
        "Build Release no CI",
        "SonarQube",
        "Espera pelo Quality Gate",
        "Quality Gate bloqueante",
        "Cache Sonar",
        "Cache NuGet",
        "Regra para Merge Request",
        "Regra para branch main",
        "Testes automatizados",
        "Deploy automatizado",
        "Promoção automática",
        "Rollback automatizado"
    ):
        evidencias[chave] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if (
    renovate_json
    and renovate_json_valido is True
):

    renovate_data = json.loads(
        renovate_json
    )

    evidencias[
        "Renovate configurado"
    ] = True

    enabled_managers = renovate_data.get(
        "enabledManagers",
        []
    )

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = (
        "nuget" in enabled_managers
    )

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = (
        "dockerfile" in enabled_managers
    )

    evidencias[
        "Vulnerability Alerts"
    ] = (
        renovate_data.get(
            "vulnerabilityAlerts"
        ) is not None
        or contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )
    )

    evidencias[
        "Lock File Maintenance"
    ] = (
        renovate_data.get(
            "lockFileMaintenance"
        ) is not None
    )

elif renovate_json:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate no pipeline
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    job_renovate = (
        contem(
            pipeline,
            "renovate/renovate"
        )
        or contem(
            pipeline,
            "renovate $ci_project_path",
            "renovate ${ci_project_path}"
        )
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = job_renovate

    evidencias[
        "Regra schedule para Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "schedule"
        )
    )

    evidencias[
        "Execução manual do Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração/orquestração não prova execução.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = quantidade_from >= 2

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias["Dockerfile presente"] = None
    evidencias["Docker multi-stage build"] = None
    evidencias["Restore no Dockerfile"] = None
    evidencias["Build no Dockerfile"] = None
    evidencias["Publish no Dockerfile"] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = buscar_regex(
        docker_compose,
        r"external\s*:\s*true"
    ) is not None

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias["Docker Compose presente"] = None
    evidencias["Build definido no Docker Compose"] = None
    evidencias["Política de restart"] = None
    evidencias["Rede externa no Docker Compose"] = None
    evidencias["Reverse proxy configurado"] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql"
    )

    evidencias[
        "Health Check de API"
    ] = contem(
        program_cs,
        "addurlgroup"
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole"
    )

else:

    evidencias["Sentry integrado em runtime"] = None
    evidencias["Health Checks"] = None
    evidencias["Health Check de banco"] = None
    evidencias["Health Check de API"] = None
    evidencias["Console Logging"] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "connectionstrings",
        "environment"
    )

else:

    evidencias["appsettings presente"] = None
    evidencias["Sentry configurado"] = None
    evidencias["Matomo configurado"] = None
    evidencias["PostgreSQL configurado"] = None
    evidencias["Configuração externalizada"] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security"
    )

else:

    evidencias[".editorconfig presente"] = None
    evidencias["Regras de analyzer declaradas"] = None
    evidencias["Regras de segurança declaradas"] = None


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

else:

    evidencias[
        ".env.example presente"
    ] = None


if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

else:

    evidencias[
        ".env.io.example presente"
    ] = None


if env_example or env_io_example:

    texto_env = "\n".join(
        texto
        for texto in (
            env_example,
            env_io_example
        )
        if texto
    )

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        texto_env,
        "environment",
        "stage",
        "server",
        "host",
        "version",
        "project"
    )

else:

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    texto_scripts = "\n".join(
        list(scripts.keys())
        + list(scripts.values())
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        texto_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        texto_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        texto_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        texto_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "localhost"
    )

else:

    evidencias["Scripts presentes"] = None
    evidencias["Script de inicialização de banco"] = None
    evidencias["Script de seed"] = None
    evidencias["Dump de banco presente"] = None
    evidencias["Automação de ambiente local"] = None


# ---------------------------------------------------------
# 12. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
— Health Check de banco
— Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
— PostgreSQL configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ .env.io.example presente
✓ Parametrização de ambientes
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local

In [58]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [59]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
# ---------------------------------------------------------

if not evidencias:
    raise ValueError(
        "Nenhuma evidência foi extraída."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    "artefatos_analisados": {

        "pipeline": pipeline_nome,
        "csproj": csproj_nome,
        "renovate_json": renovate_json_nome,
        "renovate_setup": renovate_setup_nome,
        "dockerfile": dockerfile_nome,
        "docker_compose": docker_compose_nome,
        "program_cs": program_cs_nome,
        "appsettings": appsettings_nome,
        "editorconfig": editorconfig_nome,
        "env_example": env_example_nome,
        "env_io_example": env_io_example_nome,
        "scripts": scripts_nomes
    },

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline
    },

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "postgresql_configured":
            evidencias.get(
                "PostgreSQL configurado"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            )
    },

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },

    "classificacao_deterministica":
        resultado_maturidade
}


print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)

print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (4).yml",
    "csproj": "Boilerplate4Dev (4).csproj",
    "renovate_json": "renovate (1).json",
    "renovate_setup": "RENOVATE_SETUP (1).md",
    "dockerfile": "Dockerfile (4)",
    "docker_compose": "docker-compose (4).yaml",
    "program_cs": "Program (4).cs",
    "appsettings": "appsettings (4).json",
    "editorconfig": ".editorconfig (4)",
    "env_example": ".env (4).example",
    "env_io_example": ".env.io (3).example",
    "scripts": [
      "init (4).sql",
      "seed (1).sql",
      "start-db (4).ps1"
    ]
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0"
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": false,
    "api_health_check": false,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "postgresql_configured": false,
    "environment_parameterization": true
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta."
  }
}

In [60]:
# ---------------------------------------------------------
# MATURITY CRITERIA
# ---------------------------------------------------------

criterios_maturidade = """
Escala de maturidade das práticas de automação do pipeline:

Nível 1 — Ausente/Tradicional
Não há automação relevante das atividades de build, qualidade, testes ou entrega.

Nível 2 — Inicial/Ad hoc
Existe pipeline versionado, porém as automações são pontuais ou isoladas.

Nível 3 — Parcial/Emergente
Existe pipeline versionado com práticas estruturadas de integração contínua, como restore, build e controles de qualidade, mas ainda existem lacunas relevantes.

Nível 4 — Avançado/Consolidado
Existem práticas integradas e consolidadas envolvendo build, testes automatizados, controles de qualidade bloqueantes, entrega, promoção e recuperação.

A atribuição do nível 4 exige evidências suficientes de integração e execução das práticas. A simples presença de arquivos de configuração não é suficiente.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:
    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica das evidências relacionadas à automação de pipeline apresentadas abaixo.

A classificação foi previamente calculada por critérios determinísticos implementados no notebook.

Sua função NÃO é realizar uma nova classificação independente.

Sua função é interpretar as evidências e avaliar se elas sustentam a classificação determinística.

{criterios_maturidade}

EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}

REGRAS DA ANÁLISE:

1. Utilize exclusivamente as evidências fornecidas.
2. Não presuma práticas não evidenciadas.
3. Não avalie a maturidade DevOps global do projeto.
4. Avalie somente a automação do pipeline e as evidências técnicas relacionadas.
5. Considere:
   true = evidência positiva;
   false = evidência negativa no artefato analisado;
   null = evidência indeterminada.
6. Null não significa ausência da prática.
7. Quality Gate configurado não significa necessariamente Quality Gate bloqueante.
8. allow_failure:true no job de qualidade impede interpretar o Quality Gate como bloqueante.
9. renovate.json demonstra configuração, mas não execução.
10. Um job Renovate demonstra orquestração, mas não comprova execução bem-sucedida.
11. Execução efetiva do Renovate exige evidências de runtime, como histórico de pipeline, logs, branches renovate/* ou merge requests criadas pela ferramenta.
12. Dockerfile e Docker Compose demonstram configuração e automação de construção/execução de contêineres, mas não comprovam deploy automatizado.
13. Scripts locais ou de inicialização de banco não devem ser tratados como deploy automatizado.
14. Sentry, Matomo, logging e health checks caracterizam observabilidade e não constituem, isoladamente, automação de entrega.
15. Ausência de comandos de deploy no pipeline não prova que nenhum deploy seja realizado fora dele.
16. O mesmo princípio se aplica à promoção entre ambientes e ao rollback.
17. Compare explicitamente as evidências com a classificação determinística.
18. Se a classificação for sustentada, declare isso.
19. Se houver inconsistência, descreva-a explicitamente, sem substituir arbitrariamente a classificação.
20. Utilize linguagem técnica, conservadora, rastreável e adequada a um trabalho acadêmico.
Produza a resposta em português nesta estrutura:

### Avaliação da classificação
Classificação determinística:
Avaliação: Sustentada / Parcialmente sustentada / Não sustentada

### Evidências que sustentam a avaliação
...

### Lacunas identificadas
...

### Limitações da interpretação
...

### Síntese
...
"""

print(
    "✓ Prompt de interpretação preparado."
)

✓ Prompt de interpretação preparado.

In [61]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Recupera a chave da API
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception:

    api_key = None


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 2. Validação
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not prompt:

    raise ValueError(
        "O prompt de interpretação ainda não foi criado."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


# ---------------------------------------------------------
# 3. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 4. Interpretação assistida
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model="gpt-5.6-terra",

        instructions=(
            "Atue como avaliador técnico de práticas DevOps. "
            "Sua interpretação deve ser conservadora, "
            "rastreável e limitada às evidências fornecidas. "
            "Não realize uma nova classificação independente. "
            "Avalie se as evidências sustentam a classificação "
            "determinística calculada pelo notebook."
        ),

        input=prompt
    )


    interpretacao_ia = response.output_text


    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


except Exception as erro:

    interpretacao_ia = None

    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação
Classificação determinística: **Nível 3 — Parcial/Emergente**

Avaliação: **Sustentada**

### Evidências que sustentam a avaliação
A classificação no nível 3 é compatível com as evidências de uma integração contínua estruturada, sem demonstração de automação completa de entrega e recuperação.

- Há evidência de pipeline versionado em GitLab CI (`gitlab_ci: true`), atendendo ao requisito básico de automação estruturada no repositório.
- O pipeline contempla etapas fundamentais de integração contínua:
  - restauração de dependências .NET (`dotnet_restore: true`);
  - compilação em configuração Release (`build_release: true`);
  - uso de cache de dependências NuGet (`nuget_cache: true`);
  - uso de cache para análise Sonar (`sonar_cache: true`).
- Há controles de qualidade estática configurados:
  - SonarQube (`sonarqube: true`);
  - espera pelo resultado do Quality Gate (`quality_gate_wait: true`);
  - regras de analisadores e de segurança declaradas (`analyzer_rules_declared: true` e `security_rules_declared: true`);
  - presença de `.editorconfig`.
- Há uma regra associada à branch principal (`main_branch_rule: true`), o que indica algum direcionamento de execução ou controle do pipeline para o fluxo principal do repositório.
- A automação de contêineres está documentada por artefatos técnicos:
  - Dockerfile presente com build multiestágio;
  - etapas de restore, build e publish no Dockerfile;
  - Docker Compose com build, política de reinicialização, rede externa e proxy reverso.

  Esses elementos sustentam automação de construção e execução local ou em ambiente de contêineres, embora não comprovem entrega automatizada.
- A configuração do Renovate demonstra preocupação estruturada com manutenção de dependências, incluindo gerenciadores NuGet e Dockerfile, alertas de vulnerabilidade e manutenção de lock files. Contudo, a própria evidência distingue corretamente configuração de execução efetiva.
- Existem scripts de automação local para inicialização e população de banco de dados, além de automação de ambiente local. Tais elementos contribuem para a reprodutibilidade operacional, mas não são interpretados como automação de deploy.
- Há integração de observabilidade em tempo de execução, incluindo Sentry, logging em console, health checks e Matomo. Essas evidências são complementares ao processo operacional, mas não foram indevidamente usadas como prova de entrega automatizada.

Em conjunto, os itens acima caracterizam práticas de CI além de automações isoladas, o que é coerente com o nível 3.

### Lacunas identificadas
As seguintes lacunas impedem que as evidências sustentem o nível 4:

- Não há testes automatizados no pipeline (`automated_tests: false`). Portanto, não há evidência de execução automatizada de testes como parte do fluxo de integração contínua.
- O Quality Gate não pode ser considerado bloqueante (`quality_gate_blocking: false`). Embora haja espera pelo resultado do gate, a evidência disponível não permite concluir que uma falha de qualidade interrompa obrigatoriamente o pipeline. Conforme a regra fornecida, isso é compatível com cenário como `allow_failure: true`.
- Não há regra evidenciada para merge requests (`merge_request_rule: false`), reduzindo a demonstração de controles consistentes no fluxo de integração de mudanças.
- Não há evidência de job Renovate, agendamento, execução manual ou execução efetiva:
  - `renovate_job: false`;
  - `renovate_schedule: false`;
  - `renovate_manual: false`;
  - `renovate_effective_execution: null`.

  Assim, o `renovate.json` comprova configuração, mas não orquestração nem atualização efetiva de dependências.
- Não há deploy automatizado, promoção automatizada entre ambientes ou rollback automatizado (`automated_deploy`, `automated_promotion` e `automated_rollback` são todos `false`).
- Embora existam Dockerfile e Docker Compose, esses artefatos demonstram automação de build e composição de contêineres, não execução automatizada de deploy em ambientes de destino.
- Os health checks existentes não incluem verificação específica de banco de dados nem de API (`database_health_check: false` e `api_health_check: false`). Essa lacuna não determina, isoladamente, o nível do pipeline, mas limita a evidência de validações operacionais mais completas.
- A configuração de PostgreSQL não está evidenciada (`postgresql_configured: false`), apesar da existência de scripts relacionados ao banco. Não é possível inferir integração automatizada desse banco ao pipeline.

### Limitações da interpretação
A interpretação está restrita aos indicadores apresentados e não substitui a classificação determinística calculada pelo notebook.

Em particular:

- A ausência de comandos de deploy, promoção ou rollback no pipeline analisado não demonstra que tais atividades nunca ocorram por mecanismos externos, manuais ou em outros repositórios; demonstra apenas que não foram evidenciadas nos artefatos fornecidos.
- A configuração do Renovate não permite concluir que a ferramenta tenha sido executada com sucesso, pois não foram apresentados logs, histórico de pipelines, branches `renovate/*` ou merge requests geradas pela ferramenta.
- A presença de SonarQube e de espera pelo Quality Gate não permite concluir que o gate seja bloqueante, pois a evidência informa explicitamente `quality_gate_blocking: false`.
- Dockerfile, Docker Compose, scripts locais e arquivos de ambiente indicam configuração e automação técnica de construção ou execução, mas não comprovam entrega contínua.
- As integrações de Sentry, Matomo, logging e health checks são evidências de observabilidade; isoladamente, não demonstram automação de deploy, promoção ou recuperação.

### Síntese
A classificação determinística como **Nível 3 — Parcial/Emergente** está **sustentada** pelas evidências. O conjunto analisado demonstra um pipeline versionado com práticas estruturadas de integração contínua — restore, build em Release, caches e análise estática com SonarQube — além de automação de construção de contêineres.

Contudo, permanecem lacunas relevantes para um nível 4: ausência de testes automatizados, Quality Gate não bloqueante, inexistência de evidências de deploy, promoção e rollback automatizados, e ausência de execução comprovada do Renovate. Portanto, as evidências sustentam a conclusão de automação de pipeline parcial e estruturada, mas não de uma cadeia de entrega integrada e consolidada de ponta a ponta.

In [62]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS — V3
# ---------------------------------------------------------

import copy

if not evidencias:
    raise ValueError(
        "As evidências da V3 não estão disponíveis."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação de maturidade da V3 "
        "não está disponível."
    )

if evidencias_para_ia is None:
    raise ValueError(
        "O pacote estruturado de evidências da V1 "
        "não está disponível."
    )


resultados_versoes["V3"] = {

    "versao": "V3",
    "snapshot": "web-1.26.6-1",

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_ia
        if "interpretacao_ia" in globals()
        else None,

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline
}


print(
    "✓ Resultados da V3 armazenados para a análise longitudinal."
)

✓ Resultados da V3 armazenados para a análise longitudinal.

## 6. V4 — Pipeline Technical Analysis

### 6.2 Scope

Este relatório analisa o pipeline e os artefatos relacionados presentes no snapshot **`web-1.26.8-beta.1`**.

### 6.2 Análise dos Artefatos

In [63]:
# ---------------------------------------------------------
# RESET DA ANÁLISE
# ---------------------------------------------------------

# Arquivos carregados
arquivos = {}


# ---------------------------------------------------------
# Artefatos principais
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None


# ---------------------------------------------------------
# Containerização
# ---------------------------------------------------------

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None


# ---------------------------------------------------------
# Aplicação e observabilidade
# ---------------------------------------------------------

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None


# ---------------------------------------------------------
# Qualidade estática
# ---------------------------------------------------------

editorconfig = None
editorconfig_nome = None


# ---------------------------------------------------------
# Configuração de ambiente
# ---------------------------------------------------------

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None


# ---------------------------------------------------------
# Scripts
# ---------------------------------------------------------

scripts = {}
scripts_nomes = []


# ---------------------------------------------------------
# Informações tecnológicas extraídas
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None


# ---------------------------------------------------------
# Resultados da análise
# ---------------------------------------------------------

evidencias = {}

resultado_maturidade = None

evidencias_para_ia = None

print("✓ Estado da análise limpo.")

✓ Estado da análise limpo.

In [64]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

# Reinicia as evidências a cada execução
evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj:

    try:
        root = ET.fromstring(csproj)

        for elemento in root.iter():

            tag = elemento.tag.split("}")[-1]

            if tag == "TargetFramework":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

            elif tag == "TargetFrameworks":

                target_framework = (
                    elemento.text.strip()
                    if elemento.text
                    else None
                )

                break

    except ET.ParseError as erro:

        print(
            "⚠ Não foi possível interpretar o arquivo .csproj:"
        )

        print(erro)


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline:

    # SDK .NET utilizado no pipeline
    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # Pipeline versionado
    evidencias["GitLab CI como código"] = True


    # Restore
    evidencias["`dotnet restore` no CI"] = contem(
        pipeline,
        "dotnet restore"
    )


    # Build Release
    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias["Build Release no CI"] = (
        possui_build
        and possui_release
    )


    # SonarQube
    evidencias["SonarQube"] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # Quality Gate
    evidencias["Espera pelo Quality Gate"] = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )


    # Quality Gate bloqueante
    quality_gate_wait = evidencias[
        "Espera pelo Quality Gate"
    ]

    allow_failure_match = buscar_regex(
        pipeline,
        r"allow_failure\s*:\s*true"
    )

    allow_failure_true = (
        allow_failure_match is not None
    )

    evidencias["Quality Gate bloqueante"] = (
        quality_gate_wait
        and not allow_failure_true
    )


    # Cache Sonar
    evidencias["Cache Sonar"] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )


    # Cache NuGet
    evidencias["Cache NuGet"] = contem(
        pipeline,
        ".nuget/packages"
    )


    # Merge Request
    evidencias["Regra para Merge Request"] = contem(
        pipeline,
        "merge_request_event"
    )


    # Branch main
    possui_variavel_branch = contem(
        pipeline,
        "ci_commit_branch"
    )

    possui_main_match = buscar_regex(
        pipeline,
        r"ci_commit_branch.*main"
    )

    possui_main = (
        possui_main_match is not None
    )

    evidencias["Regra para branch main"] = (
        possui_variavel_branch
        and possui_main
    )


    # Testes automatizados
    evidencias["Testes automatizados"] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # Deploy automatizado
    evidencias["Deploy automatizado"] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # Promoção automática
    evidencias["Promoção automática"] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # Rollback automatizado
    evidencias["Rollback automatizado"] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )

else:

    evidencias["GitLab CI como código"] = None
    evidencias["`dotnet restore` no CI"] = None
    evidencias["Build Release no CI"] = None
    evidencias["SonarQube"] = None
    evidencias["Espera pelo Quality Gate"] = None
    evidencias["Quality Gate bloqueante"] = None
    evidencias["Cache Sonar"] = None
    evidencias["Cache NuGet"] = None
    evidencias["Regra para Merge Request"] = None
    evidencias["Regra para branch main"] = None
    evidencias["Testes automatizados"] = None
    evidencias["Deploy automatizado"] = None
    evidencias["Promoção automática"] = None
    evidencias["Rollback automatizado"] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if renovate_json:

    evidencias["Renovate configurado"] = True

    try:

        renovate_data = json.loads(
            renovate_json
        )

        enabled_managers = renovate_data.get(
            "enabledManagers",
            []
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = (
            "nuget" in enabled_managers
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = (
            "dockerfile" in enabled_managers
        )


        # Vulnerability Alerts
        vulnerability_alerts = renovate_data.get(
            "vulnerabilityAlerts"
        )

        if vulnerability_alerts is not None:

            evidencias[
                "Vulnerability Alerts"
            ] = True

        else:

            evidencias[
                "Vulnerability Alerts"
            ] = contem(
                renovate_json,
                "vulnerabilityalerts",
                "osv"
            )


        # Lock File Maintenance
        lock_file_maintenance = renovate_data.get(
            "lockFileMaintenance"
        )

        if lock_file_maintenance is not None:

            evidencias[
                "Lock File Maintenance"
            ] = True

        else:

            evidencias[
                "Lock File Maintenance"
            ] = contem(
                renovate_json,
                "lockfilemaintenance"
            )


    except json.JSONDecodeError:

        print(
            "⚠ renovate.json inválido. "
            "A análise será feita por busca textual."
        )

        evidencias[
            "Gerenciamento NuGet pelo Renovate"
        ] = contem(
            renovate_json,
            '"nuget"'
        )

        evidencias[
            "Gerenciamento Dockerfile pelo Renovate"
        ] = contem(
            renovate_json,
            '"dockerfile"'
        )

        evidencias[
            "Vulnerability Alerts"
        ] = contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )

        evidencias[
            "Lock File Maintenance"
        ] = contem(
            renovate_json,
            "lockfilemaintenance"
        )

else:

    evidencias["Renovate configurado"] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate orquestrado no pipeline
# ---------------------------------------------------------

if pipeline:

    possui_imagem_renovate = contem(
        pipeline,
        "renovate/renovate"
    )

    possui_comando_renovate = contem(
        pipeline,
        "renovate $ci_project_path",
        "renovate ${ci_project_path}"
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = (
        possui_imagem_renovate
        or possui_comando_renovate
    )


    evidencias[
        "Regra schedule para Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "schedule"
        )
    )


    evidencias[
        "Execução manual do Renovate"
    ] = (
        evidencias[
            "Job Renovate no pipeline"
        ]
        and contem(
            pipeline,
            "when: manual",
            "ci_pipeline_source == \"web\"",
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração e job não comprovam execução efetiva
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    # Detecta múltiplos FROM
    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=re.IGNORECASE | re.MULTILINE
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = (
        quantidade_from >= 2
    )

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias[
        "Dockerfile presente"
    ] = None

    evidencias[
        "Docker multi-stage build"
    ] = None

    evidencias[
        "Restore no Dockerfile"
    ] = None

    evidencias[
        "Build no Dockerfile"
    ] = None

    evidencias[
        "Publish no Dockerfile"
    ] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = (
        contem(
            docker_compose,
            "external:"
        )
        and contem(
            docker_compose,
            "true"
        )
    )

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias[
        "Docker Compose presente"
    ] = None

    evidencias[
        "Build definido no Docker Compose"
    ] = None

    evidencias[
        "Política de restart"
    ] = None

    evidencias[
        "Rede externa no Docker Compose"
    ] = None

    evidencias[
        "Reverse proxy configurado"
    ] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql",
        "npgsql",
        "healthcheck"
    )

    evidencias[
        "Health Check de API"
    ] = (
        contem(
            program_cs,
            "addurlgroup",
            "httpclient",
            "healthcheck"
        )
        and contem(
            program_cs,
            "health"
        )
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole",
        "console"
    )

else:

    evidencias[
        "Sentry integrado em runtime"
    ] = None

    evidencias[
        "Health Checks"
    ] = None

    evidencias[
        "Health Check de banco"
    ] = None

    evidencias[
        "Health Check de API"
    ] = None

    evidencias[
        "Console Logging"
    ] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry",
        "dsn"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "environment",
        "connectionstrings",
        "configuration"
    )

else:

    evidencias[
        "appsettings presente"
    ] = None

    evidencias[
        "Sentry configurado"
    ] = None

    evidencias[
        "Matomo configurado"
    ] = None

    evidencias[
        "PostgreSQL configurado"
    ] = None

    evidencias[
        "Configuração externalizada"
    ] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security",
        "ca2",
        "s"
    )

else:

    evidencias[
        ".editorconfig presente"
    ] = None

    evidencias[
        "Regras de analyzer declaradas"
    ] = None

    evidencias[
        "Regras de segurança declaradas"
    ] = None


# ---------------------------------------------------------
# 10. .env.example
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        env_example,
        "environment",
        "env",
        "stage",
        "server",
        "host"
    )

else:

    evidencias[
        ".env.example presente"
    ] = None

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. .env.io.example
# ---------------------------------------------------------

if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

    # Se já havia evidência anterior, preserva True
    evidencia_parametrizacao = contem(
        env_io_example,
        "environment",
        "stage",
        "server",
        "version",
        "deployer",
        "project"
    )

    valor_atual = evidencias.get(
        "Parametrização de ambientes"
    )

    if valor_atual is True:
        evidencias[
            "Parametrização de ambientes"
        ] = True

    elif valor_atual is False:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

    else:
        evidencias[
            "Parametrização de ambientes"
        ] = evidencia_parametrizacao

else:

    evidencias[
        ".env.io.example presente"
    ] = None


# ---------------------------------------------------------
# 12. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    conteudo_scripts = "\n".join(
        str(conteudo)
        for conteudo in scripts.values()
    )

    nomes_scripts = "\n".join(
        str(nome)
        for nome in scripts.keys()
    )

    conteudo_total_scripts = (
        nomes_scripts
        + "\n"
        + conteudo_scripts
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        conteudo_total_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        conteudo_total_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        conteudo_total_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        conteudo_total_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "init.sql",
        "localhost"
    )

else:

    evidencias[
        "Scripts presentes"
    ] = None

    evidencias[
        "Script de inicialização de banco"
    ] = None

    evidencias[
        "Script de seed"
    ] = None

    evidencias[
        "Dump de banco presente"
    ] = None

    evidencias[
        "Automação de ambiente local"
    ] = None


# ---------------------------------------------------------
# 13. Resumo tecnológico
# ---------------------------------------------------------

tecnologia = {
    "target_framework": target_framework,
    "sdk_pipeline": sdk_pipeline
}


# ---------------------------------------------------------
# 14. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()


# ---------------------------------------------------------
# 15. Exibição tri-state
# ---------------------------------------------------------

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: None
SDK Pipeline: None

? GitLab CI como código
? `dotnet restore` no CI
? Build Release no CI
? SonarQube
? Espera pelo Quality Gate
? Quality Gate bloqueante
? Cache Sonar
? Cache NuGet
? Regra para Merge Request
? Regra para branch main
? Testes automatizados
? Deploy automatizado
? Promoção automática
? Rollback automatizado
? Renovate configurado
? Gerenciamento NuGet pelo Renovate
? Gerenciamento Dockerfile pelo Renovate
? Vulnerability Alerts
? Lock File Maintenance
? Job Renovate no pipeline
? Regra schedule para Renovate
? Execução manual do Renovate
? Execução efetiva do Renovate
? Dockerfile presente
? Docker multi-stage build
? Restore no Dockerfile
? Build no Dockerfile
? Publish no Dockerfile
? Docker Compose presente
? Build definido no Docker Compose
? Política de restart
? Rede externa no Docker Compose
? Reverse proxy configurado
? Sentry integrado em runtime
? Health Checks
? Health Check de banco
? Health Check de API
? Console Logging
? appsettings presente
? Sentry configurado
? Matomo configurado
? PostgreSQL configurado
? Configuração externalizada
? .editorconfig presente
? Regras de analyzer declaradas
? Regras de segurança declaradas
? .env.example presente
? Parametrização de ambientes
? .env.io.example presente
? Scripts presentes
? Script de inicialização de banco
? Script de seed
? Dump de banco presente
? Automação de ambiente local

In [65]:
# ---------------------------------------------------------
# ARTIFACT UPLOAD
# ---------------------------------------------------------

from google.colab import files

uploaded = files.upload()

arquivos = {}

for nome, conteudo in uploaded.items():
    arquivos[nome] = conteudo.decode(
        "utf-8",
        errors="ignore"
    )


# ---------------------------------------------------------
# Resultado do upload
# ---------------------------------------------------------

if arquivos:

    print(
        f"\n✓ {len(arquivos)} arquivo(s) carregado(s):\n"
    )

    for nome in sorted(arquivos):
        print(f"  ✓ {nome}")

else:

    print(
        "\n⚠ Nenhum arquivo foi carregado."
    )

Saving .editorconfig to .editorconfig (5)
Saving .env.example to .env (5).example
Saving .env.io.example to .env.io (4).example
Saving appsettings.json to appsettings (5).json
Saving Boilerplate4Dev.csproj to Boilerplate4Dev (5).csproj
Saving docker-compose.yaml to docker-compose (5).yaml
Saving Dockerfile to Dockerfile (5)
Saving gitlab-ci.yml to gitlab-ci (5).yml
Saving init.sql to init (5).sql
Saving Program.cs to Program (5).cs
Saving renovate.json to renovate (2).json
Saving RENOVATE_SETUP.md to RENOVATE_SETUP (2).md
Saving seed.sql to seed (2).sql
Saving start-db.ps1 to start-db (5).ps1

✓ 14 arquivo(s) carregado(s):

  ✓ .editorconfig (5)
  ✓ .env (5).example
  ✓ .env.io (4).example
  ✓ Boilerplate4Dev (5).csproj
  ✓ Dockerfile (5)
  ✓ Program (5).cs
  ✓ RENOVATE_SETUP (2).md
  ✓ appsettings (5).json
  ✓ docker-compose (5).yaml
  ✓ gitlab-ci (5).yml
  ✓ init (5).sql
  ✓ renovate (2).json
  ✓ seed (2).sql
  ✓ start-db (5).ps1

In [67]:
# ---------------------------------------------------------
# ARTIFACT IDENTIFICATION AND VALIDATION
# ---------------------------------------------------------

if not arquivos:
    raise ValueError(
        "Nenhum arquivo foi carregado. "
        "Execute primeiro a etapa Artifact Upload."
    )


# ---------------------------------------------------------
# Reinicia variáveis de identificação
# ---------------------------------------------------------

pipeline = None
pipeline_nome = None

csproj = None
csproj_nome = None

renovate_json = None
renovate_json_nome = None

renovate_setup = None
renovate_setup_nome = None

dockerfile = None
dockerfile_nome = None

docker_compose = None
docker_compose_nome = None

program_cs = None
program_cs_nome = None

appsettings = None
appsettings_nome = None

editorconfig = None
editorconfig_nome = None

env_example = None
env_example_nome = None

env_io_example = None
env_io_example_nome = None

scripts = {}
scripts_nomes = []

validacao_artefatos = []


# ---------------------------------------------------------
# Estados formais de validação
#
# None  = artefato não fornecido / não validável
# True  = artefato fornecido e validado
# False = artefato fornecido, porém inválido
# ---------------------------------------------------------

pipeline_valido = None
csproj_valido = None
renovate_json_valido = None
renovate_setup_valido = None
dockerfile_valido = None
docker_compose_valido = None
program_cs_valido = None
appsettings_valido = None
editorconfig_valido = None
env_example_valido = None
env_io_example_valido = None

scripts_validos = {}


# ---------------------------------------------------------
# Normalização de nomes
# ---------------------------------------------------------

def nome_base(nome):
    return (
        nome
        .replace("\\", "/")
        .split("/")[-1]
        .strip()
    )


def normalizar_nome(nome):
    nome = nome_base(nome)

    # Remove sufixos adicionados pelo Colab:
    # arquivo (1).json -> arquivo.json
    # Dockerfile (2)   -> Dockerfile
    nome = re.sub(
        r"\s*\(\d+\)(?=\.|$)",
        "",
        nome
    )

    return nome.lower().strip()


# ---------------------------------------------------------
# Seleção de artefato único
# ---------------------------------------------------------

def selecionar_unico(
    candidatos,
    descricao
):
    if not candidatos:
        return None, None

    if len(candidatos) > 1:

        nomes = ", ".join(
            sorted(
                nome
                for nome, _ in candidatos
            )
        )

        raise ValueError(
            f"Mais de um arquivo foi identificado como "
            f"{descricao}: {nomes}. "
            "Forneça apenas um artefato desse tipo por versão."
        )

    return (
        candidatos[0][1],
        candidatos[0][0]
    )


# ---------------------------------------------------------
# Conversão segura para texto
# ---------------------------------------------------------

def como_texto(conteudo):
    if conteudo is None:
        return None

    if isinstance(
        conteudo,
        bytes
    ):
        return conteudo.decode(
            "utf-8-sig",
            errors="replace"
        )

    texto = str(
        conteudo
    )

    # Remove BOM caso o conteúdo já seja string.
    return texto.lstrip(
        "\ufeff"
    )


# ---------------------------------------------------------
# Candidatos
# ---------------------------------------------------------

candidatos_pipeline = []
candidatos_csproj = []
candidatos_renovate = []
candidatos_renovate_setup = []
candidatos_dockerfile = []
candidatos_docker_compose = []
candidatos_program = []
candidatos_appsettings = []
candidatos_editorconfig = []
candidatos_env_example = []
candidatos_env_io_example = []

extensoes_script = {
    ".sql",
    ".ps1",
    ".sh",
    ".bat",
    ".cmd"
}


# ---------------------------------------------------------
# Identificação dos arquivos
# ---------------------------------------------------------

for nome, conteudo in arquivos.items():

    base = nome_base(
        nome
    )

    normalizado = normalizar_nome(
        nome
    )


    # GitLab CI
    if normalizado in {
        ".gitlab-ci.yml",
        ".gitlab-ci.yaml",
        "gitlab-ci.yml",
        "gitlab-ci.yaml"
    }:

        candidatos_pipeline.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Projeto .NET
    if normalizado.endswith(
        ".csproj"
    ):

        candidatos_csproj.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Renovate
    if normalizado == "renovate.json":

        candidatos_renovate.append(
            (
                base,
                conteudo
            )
        )

        continue


    if normalizado == "renovate_setup.md":

        candidatos_renovate_setup.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Dockerfile
    if normalizado == "dockerfile":

        candidatos_dockerfile.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Docker Compose
    if normalizado in {
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml"
    }:

        candidatos_docker_compose.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Program.cs
    if normalizado == "program.cs":

        candidatos_program.append(
            (
                base,
                conteudo
            )
        )

        continue


    # appsettings.json
    if normalizado == "appsettings.json":

        candidatos_appsettings.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .editorconfig
    if normalizado == ".editorconfig":

        candidatos_editorconfig.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.io.example
    if normalizado in {
        ".env.io.example",
        "env.io.example"
    }:

        candidatos_env_io_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # .env.example
    if normalizado in {
        ".env.example",
        "env.example"
    }:

        candidatos_env_example.append(
            (
                base,
                conteudo
            )
        )

        continue


    # Scripts
    extensao = Path(
        normalizado
    ).suffix

    if extensao in extensoes_script:

        scripts[
            base
        ] = como_texto(
            conteudo
        )

        scripts_nomes.append(
            base
        )


# ---------------------------------------------------------
# Seleção dos artefatos
# ---------------------------------------------------------

pipeline, pipeline_nome = selecionar_unico(
    candidatos_pipeline,
    "pipeline GitLab CI"
)

csproj, csproj_nome = selecionar_unico(
    candidatos_csproj,
    "arquivo .csproj"
)

renovate_json, renovate_json_nome = selecionar_unico(
    candidatos_renovate,
    "renovate.json"
)

renovate_setup, renovate_setup_nome = selecionar_unico(
    candidatos_renovate_setup,
    "RENOVATE_SETUP.md"
)

dockerfile, dockerfile_nome = selecionar_unico(
    candidatos_dockerfile,
    "Dockerfile"
)

docker_compose, docker_compose_nome = selecionar_unico(
    candidatos_docker_compose,
    "Docker Compose"
)

program_cs, program_cs_nome = selecionar_unico(
    candidatos_program,
    "Program.cs"
)

appsettings, appsettings_nome = selecionar_unico(
    candidatos_appsettings,
    "appsettings.json"
)

editorconfig, editorconfig_nome = selecionar_unico(
    candidatos_editorconfig,
    ".editorconfig"
)

env_example, env_example_nome = selecionar_unico(
    candidatos_env_example,
    ".env.example"
)

env_io_example, env_io_example_nome = selecionar_unico(
    candidatos_env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# Conversão para texto
# ---------------------------------------------------------

pipeline = como_texto(
    pipeline
)

csproj = como_texto(
    csproj
)

renovate_json = como_texto(
    renovate_json
)

renovate_setup = como_texto(
    renovate_setup
)

dockerfile = como_texto(
    dockerfile
)

docker_compose = como_texto(
    docker_compose
)

program_cs = como_texto(
    program_cs
)

appsettings = como_texto(
    appsettings
)

editorconfig = como_texto(
    editorconfig
)

env_example = como_texto(
    env_example
)

env_io_example = como_texto(
    env_io_example
)


# ---------------------------------------------------------
# Funções auxiliares de validação
# ---------------------------------------------------------

def arquivo_nao_vazio(
    conteudo
):
    return (
        conteudo is not None
        and bool(
            conteudo.strip()
        )
    )


def validar_env(
    conteudo,
    descricao
):
    if conteudo is None:
        return None

    if not arquivo_nao_vazio(
        conteudo
    ):
        validacao_artefatos.append(
            f"✗ {descricao}: arquivo vazio."
        )

        return False

    linhas_invalidas = []

    for numero, linha in enumerate(
        conteudo.splitlines(),
        start=1
    ):

        linha = linha.strip()

        if (
            not linha
            or linha.startswith("#")
        ):
            continue

        if "=" not in linha:
            linhas_invalidas.append(
                numero
            )

    if linhas_invalidas:

        validacao_artefatos.append(
            f"⚠ {descricao}: "
            f"{len(linhas_invalidas)} linha(s) "
            "sem formato CHAVE=VALOR."
        )

        # O arquivo continua legível e utilizável
        # para extração de evidências.
        return True

    validacao_artefatos.append(
        f"✓ {descricao} estruturalmente válido."
    )

    return True


# ---------------------------------------------------------
# 1. Pipeline YAML
# ---------------------------------------------------------

if pipeline is not None:

    if not arquivo_nao_vazio(
        pipeline
    ):

        pipeline_valido = False

        validacao_artefatos.append(
            "✗ Pipeline: arquivo vazio."
        )

    else:

        try:

            pipeline_yaml = yaml.safe_load(
                pipeline
            )

            if not isinstance(
                pipeline_yaml,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            pipeline_valido = True

            validacao_artefatos.append(
                "✓ Pipeline YAML válido."
            )

        except Exception as erro:

            pipeline_valido = False

            validacao_artefatos.append(
                f"✗ Pipeline YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 2. .csproj XML
# ---------------------------------------------------------

if csproj is not None:

    if not arquivo_nao_vazio(
        csproj
    ):

        csproj_valido = False

        validacao_artefatos.append(
            "✗ .csproj: arquivo vazio."
        )

    else:

        try:

            ET.fromstring(
                csproj
            )

            csproj_valido = True

            validacao_artefatos.append(
                "✓ .csproj XML válido."
            )

        except ET.ParseError as erro:

            csproj_valido = False

            validacao_artefatos.append(
                f"✗ .csproj XML inválido: {erro}"
            )


# ---------------------------------------------------------
# 3. renovate.json
# ---------------------------------------------------------

if renovate_json is not None:

    if not arquivo_nao_vazio(
        renovate_json
    ):

        renovate_json_valido = False

        validacao_artefatos.append(
            "✗ renovate.json: arquivo vazio."
        )

    else:

        try:

            renovate_data_validacao = json.loads(
                renovate_json
            )

            if not isinstance(
                renovate_data_validacao,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            renovate_json_valido = True

            validacao_artefatos.append(
                "✓ renovate.json válido."
            )

        except Exception as erro:

            renovate_json_valido = False

            validacao_artefatos.append(
                f"✗ renovate.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 4. RENOVATE_SETUP.md
# ---------------------------------------------------------

if renovate_setup is not None:

    if arquivo_nao_vazio(
        renovate_setup
    ):

        renovate_setup_valido = True

        validacao_artefatos.append(
            "✓ RENOVATE_SETUP.md legível e não vazio."
        )

    else:

        renovate_setup_valido = False

        validacao_artefatos.append(
            "✗ RENOVATE_SETUP.md: arquivo vazio."
        )


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile is not None:

    if not arquivo_nao_vazio(
        dockerfile
    ):

        dockerfile_valido = False

        validacao_artefatos.append(
            "✗ Dockerfile: arquivo vazio."
        )

    else:

        possui_from = bool(
            re.search(
                r"^\s*FROM\s+\S+",
                dockerfile,
                flags=(
                    re.IGNORECASE
                    | re.MULTILINE
                )
            )
        )

        if possui_from:

            dockerfile_valido = True

            validacao_artefatos.append(
                "✓ Dockerfile estruturalmente válido "
                "(instrução FROM identificada)."
            )

        else:

            dockerfile_valido = False

            validacao_artefatos.append(
                "✗ Dockerfile sem instrução FROM identificada."
            )


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose is not None:

    if not arquivo_nao_vazio(
        docker_compose
    ):

        docker_compose_valido = False

        validacao_artefatos.append(
            "✗ Docker Compose: arquivo vazio."
        )

    else:

        try:

            docker_compose_obj = yaml.safe_load(
                docker_compose
            )

            if not isinstance(
                docker_compose_obj,
                dict
            ):
                raise ValueError(
                    "estrutura YAML raiz não é um mapeamento"
                )

            if "services" not in docker_compose_obj:

                docker_compose_valido = False

                validacao_artefatos.append(
                    "✗ Docker Compose YAML válido, "
                    "mas sem seção 'services'."
                )

            else:

                docker_compose_valido = True

                validacao_artefatos.append(
                    "✓ Docker Compose YAML válido "
                    "e seção 'services' identificada."
                )

        except Exception as erro:

            docker_compose_valido = False

            validacao_artefatos.append(
                f"✗ Docker Compose YAML inválido: {erro}"
            )


# ---------------------------------------------------------
# 7. Program.cs
# ---------------------------------------------------------

if program_cs is not None:

    if not arquivo_nao_vazio(
        program_cs
    ):

        program_cs_valido = False

        validacao_artefatos.append(
            "✗ Program.cs: arquivo vazio."
        )

    else:

        indicadores_cs = (
            "WebApplication",
            "CreateBuilder",
            "builder.",
            "Build("
        )

        program_cs_valido = any(
            indicador.lower()
            in program_cs.lower()
            for indicador in indicadores_cs
        )

        if program_cs_valido:

            validacao_artefatos.append(
                "✓ Program.cs legível e com estrutura "
                "compatível com inicialização de aplicação .NET."
            )

        else:

            validacao_artefatos.append(
                "⚠ Program.cs legível, mas a estrutura "
                "esperada de inicialização .NET "
                "não foi identificada."
            )


# ---------------------------------------------------------
# 8. appsettings.json
# ---------------------------------------------------------

if appsettings is not None:

    if not arquivo_nao_vazio(
        appsettings
    ):

        appsettings_valido = False

        validacao_artefatos.append(
            "✗ appsettings.json: arquivo vazio."
        )

    else:

        try:

            appsettings_obj = json.loads(
                appsettings
            )

            if not isinstance(
                appsettings_obj,
                dict
            ):
                raise ValueError(
                    "raiz JSON não é um objeto"
                )

            appsettings_valido = True

            validacao_artefatos.append(
                "✓ appsettings.json válido."
            )

        except Exception as erro:

            appsettings_valido = False

            validacao_artefatos.append(
                f"✗ appsettings.json inválido: {erro}"
            )


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig is not None:

    if not arquivo_nao_vazio(
        editorconfig
    ):

        editorconfig_valido = False

        validacao_artefatos.append(
            "✗ .editorconfig: arquivo vazio."
        )

    else:

        possui_secao = bool(
            re.search(
                r"^\s*\[[^\]]+\]\s*$",
                editorconfig,
                flags=re.MULTILINE
            )
        )

        editorconfig_valido = possui_secao

        if possui_secao:

            validacao_artefatos.append(
                "✓ .editorconfig estruturalmente válido "
                "(seção de configuração identificada)."
            )

        else:

            validacao_artefatos.append(
                "⚠ .editorconfig legível, "
                "mas nenhuma seção foi identificada."
            )


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

env_example_valido = validar_env(
    env_example,
    ".env.example"
)

env_io_example_valido = validar_env(
    env_io_example,
    ".env.io.example"
)


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

for script_nome in sorted(
    scripts_nomes
):

    conteudo_script = scripts.get(
        script_nome
    )

    if arquivo_nao_vazio(
        conteudo_script
    ):

        scripts_validos[
            script_nome
        ] = True

        extensao = Path(
            normalizar_nome(
                script_nome
            )
        ).suffix

        tipo_script = {
            ".sql": "SQL",
            ".ps1": "PowerShell",
            ".sh": "Shell",
            ".bat": "Batch",
            ".cmd": "Command"
        }.get(
            extensao,
            "script"
        )

        validacao_artefatos.append(
            f"✓ {script_nome}: "
            f"script {tipo_script} legível e não vazio."
        )

    else:

        scripts_validos[
            script_nome
        ] = False

        validacao_artefatos.append(
            f"✗ {script_nome}: arquivo vazio."
        )


# ---------------------------------------------------------
# Resultado da identificação
# ---------------------------------------------------------

print(
    "ARTEFATOS IDENTIFICADOS\n"
)


def imprimir_artefato(
    descricao,
    nome
):
    if nome:

        print(
            f"✓ {descricao}: {nome}"
        )

    else:

        print(
            f"? {descricao}: não fornecido"
        )


imprimir_artefato(
    "Pipeline",
    pipeline_nome
)

imprimir_artefato(
    ".csproj",
    csproj_nome
)

imprimir_artefato(
    "renovate.json",
    renovate_json_nome
)

imprimir_artefato(
    "RENOVATE_SETUP.md",
    renovate_setup_nome
)

imprimir_artefato(
    "Dockerfile",
    dockerfile_nome
)

imprimir_artefato(
    "Docker Compose",
    docker_compose_nome
)

imprimir_artefato(
    "Program.cs",
    program_cs_nome
)

imprimir_artefato(
    "appsettings.json",
    appsettings_nome
)

imprimir_artefato(
    ".editorconfig",
    editorconfig_nome
)

imprimir_artefato(
    ".env.example",
    env_example_nome
)

imprimir_artefato(
    ".env.io.example",
    env_io_example_nome
)


if scripts_nomes:

    print(
        f"✓ Scripts: "
        f"{len(scripts_nomes)} arquivo(s)"
    )

    for nome in sorted(
        scripts_nomes
    ):
        print(
            f"    - {nome}"
        )

else:

    print(
        "? Scripts: não fornecidos"
    )


# ---------------------------------------------------------
# Resultado da validação
# ---------------------------------------------------------

print(
    "\nVALIDAÇÃO\n"
)

if validacao_artefatos:

    for mensagem in validacao_artefatos:

        print(
            mensagem
        )

else:

    print(
        "Nenhum artefato sujeito a validação "
        "foi fornecido."
    )


# ---------------------------------------------------------
# Estado técnico da validação
# ---------------------------------------------------------

print(
    "\nESTADO DA VALIDAÇÃO\n"
)

estados_validacao = {
    "Pipeline": pipeline_valido,
    ".csproj": csproj_valido,
    "renovate.json": renovate_json_valido,
    "RENOVATE_SETUP.md": renovate_setup_valido,
    "Dockerfile": dockerfile_valido,
    "Docker Compose": docker_compose_valido,
    "Program.cs": program_cs_valido,
    "appsettings.json": appsettings_valido,
    ".editorconfig": editorconfig_valido,
    ".env.example": env_example_valido,
    ".env.io.example": env_io_example_valido
}


for artefato, estado in estados_validacao.items():

    if estado is True:
        simbolo = "✓"

    elif estado is False:
        simbolo = "✗"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {artefato}"
    )

ARTEFATOS IDENTIFICADOS

✓ Pipeline: gitlab-ci (5).yml
✓ .csproj: Boilerplate4Dev (5).csproj
✓ renovate.json: renovate (2).json
✓ RENOVATE_SETUP.md: RENOVATE_SETUP (2).md
✓ Dockerfile: Dockerfile (5)
✓ Docker Compose: docker-compose (5).yaml
✓ Program.cs: Program (5).cs
✓ appsettings.json: appsettings (5).json
✓ .editorconfig: .editorconfig (5)
✓ .env.example: .env (5).example
✓ .env.io.example: .env.io (4).example
✓ Scripts: 3 arquivo(s)
    - init (5).sql
    - seed (2).sql
    - start-db (5).ps1

VALIDAÇÃO

✓ Pipeline YAML válido.
✓ .csproj XML válido.
✓ renovate.json válido.
✓ RENOVATE_SETUP.md legível e não vazio.
✓ Dockerfile estruturalmente válido (instrução FROM identificada).
✓ Docker Compose YAML válido e seção 'services' identificada.
✓ Program.cs legível e com estrutura compatível com inicialização de aplicação .NET.
✓ appsettings.json válido.
✓ .editorconfig estruturalmente válido (seção de configuração identificada).
✓ .env.example estruturalmente válido.
✓ .env.io.example estruturalmente válido.
✓ init (5).sql: script SQL legível e não vazio.
✓ seed (2).sql: script SQL legível e não vazio.
✓ start-db (5).ps1: script PowerShell legível e não vazio.

ESTADO DA VALIDAÇÃO

✓ Pipeline
✓ .csproj
✓ renovate.json
✓ RENOVATE_SETUP.md
✓ Dockerfile
✓ Docker Compose
✓ Program.cs
✓ appsettings.json
✓ .editorconfig
✓ .env.example
✓ .env.io.example

In [68]:
# ---------------------------------------------------------
# AUTOMATED EVIDENCE EXTRACTION
# ---------------------------------------------------------

target_framework = None
sdk_pipeline = None

evidencias = {}


# ---------------------------------------------------------
# 1. .csproj
# ---------------------------------------------------------

if csproj and csproj_valido is True:

    root = ET.fromstring(csproj)

    for elemento in root.iter():

        tag = elemento.tag.split("}")[-1]

        if tag in (
            "TargetFramework",
            "TargetFrameworks"
        ):

            target_framework = (
                elemento.text.strip()
                if elemento.text
                else None
            )

            break


# ---------------------------------------------------------
# 2. GitLab CI
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    # -----------------------------------------------------
    # SDK
    # -----------------------------------------------------

    match_sdk = buscar_regex(
        pipeline,
        r"mcr\.microsoft\.com/dotnet/sdk:([0-9.]+)"
    )

    if match_sdk:
        sdk_pipeline = match_sdk.group(1)


    # -----------------------------------------------------
    # Pipeline versionado
    # -----------------------------------------------------

    evidencias[
        "GitLab CI como código"
    ] = True


    # -----------------------------------------------------
    # Restore
    # -----------------------------------------------------

    evidencias[
        "`dotnet restore` no CI"
    ] = contem(
        pipeline,
        "dotnet restore"
    )


    # -----------------------------------------------------
    # Build Release
    # -----------------------------------------------------

    possui_build = contem(
        pipeline,
        "dotnet build"
    )

    possui_release = contem(
        pipeline,
        "--configuration release",
        "-c release"
    )

    evidencias[
        "Build Release no CI"
    ] = (
        possui_build
        and possui_release
    )


    # -----------------------------------------------------
    # SonarQube
    # -----------------------------------------------------

    evidencias[
        "SonarQube"
    ] = contem(
        pipeline,
        "dotnet-sonarscanner",
        "sonarscanner",
        "sonar.host.url",
        "sonar_token"
    )


    # -----------------------------------------------------
    # Quality Gate
    # -----------------------------------------------------

    quality_gate_wait = contem(
        pipeline,
        "sonar.qualitygate.wait=true"
    )

    evidencias[
        "Espera pelo Quality Gate"
    ] = quality_gate_wait


    # -----------------------------------------------------
    # Identifica job do Sonar estruturalmente
    # -----------------------------------------------------

    chaves_reservadas_gitlab = {
        "image",
        "services",
        "stages",
        "variables",
        "default",
        "include",
        "workflow",
        "cache",
        "before_script",
        "after_script"
    }

    sonar_jobs = []

    if isinstance(pipeline_yaml, dict):

        for nome_job, config_job in pipeline_yaml.items():

            if nome_job in chaves_reservadas_gitlab:
                continue

            if not isinstance(config_job, dict):
                continue

            partes_job = []

            for campo in (
                "before_script",
                "script",
                "after_script"
            ):

                valor = config_job.get(campo)

                if isinstance(valor, list):
                    partes_job.extend(
                        str(item)
                        for item in valor
                    )

                elif valor:
                    partes_job.append(
                        str(valor)
                    )

            texto_job = "\n".join(partes_job)

            if contem(
                texto_job,
                "sonar",
                "sonarscanner"
            ):
                sonar_jobs.append(
                    config_job
                )


    # -----------------------------------------------------
    # Quality Gate bloqueante
    # -----------------------------------------------------

    if quality_gate_wait and sonar_jobs:

        allow_failure_sonar = any(
            job.get("allow_failure") is True
            for job in sonar_jobs
        )

        evidencias[
            "Quality Gate bloqueante"
        ] = not allow_failure_sonar

    elif quality_gate_wait:

        # Quality Gate existe, mas não foi possível
        # vincular com segurança a um job específico.
        evidencias[
            "Quality Gate bloqueante"
        ] = None

    else:

        evidencias[
            "Quality Gate bloqueante"
        ] = False


    # -----------------------------------------------------
    # Caches
    # -----------------------------------------------------

    evidencias[
        "Cache Sonar"
    ] = contem(
        pipeline,
        "${sonar_user_home}/cache",
        ".sonar"
    )

    evidencias[
        "Cache NuGet"
    ] = contem(
        pipeline,
        ".nuget/packages"
    )


    # -----------------------------------------------------
    # Regras
    # -----------------------------------------------------

    evidencias[
        "Regra para Merge Request"
    ] = contem(
        pipeline,
        "merge_request_event"
    )

    evidencias[
        "Regra para branch main"
    ] = (
        contem(
            pipeline,
            "ci_commit_branch"
        )
        and buscar_regex(
            pipeline,
            r"ci_commit_branch.*main"
        ) is not None
    )


    # -----------------------------------------------------
    # Testes
    # -----------------------------------------------------

    evidencias[
        "Testes automatizados"
    ] = contem(
        pipeline,
        "dotnet test",
        "pytest",
        "npm test",
        "npm run test",
        "mvn test",
        "gradle test"
    )


    # -----------------------------------------------------
    # Deploy
    # -----------------------------------------------------

    evidencias[
        "Deploy automatizado"
    ] = contem(
        pipeline,
        "kubectl apply",
        "helm upgrade",
        "docker stack deploy",
        "docker compose up",
        "docker-compose up",
        "oc apply"
    )


    # -----------------------------------------------------
    # Promoção
    # -----------------------------------------------------

    evidencias[
        "Promoção automática"
    ] = contem(
        pipeline,
        "promote",
        "promotion",
        "promote-to-production",
        "promote_to_production"
    )


    # -----------------------------------------------------
    # Rollback
    # -----------------------------------------------------

    evidencias[
        "Rollback automatizado"
    ] = contem(
        pipeline,
        "helm rollback",
        "kubectl rollout undo",
        "docker service rollback"
    )


else:

    for chave in (
        "GitLab CI como código",
        "`dotnet restore` no CI",
        "Build Release no CI",
        "SonarQube",
        "Espera pelo Quality Gate",
        "Quality Gate bloqueante",
        "Cache Sonar",
        "Cache NuGet",
        "Regra para Merge Request",
        "Regra para branch main",
        "Testes automatizados",
        "Deploy automatizado",
        "Promoção automática",
        "Rollback automatizado"
    ):
        evidencias[chave] = None


# ---------------------------------------------------------
# 3. Renovate
# ---------------------------------------------------------

if (
    renovate_json
    and renovate_json_valido is True
):

    renovate_data = json.loads(
        renovate_json
    )

    evidencias[
        "Renovate configurado"
    ] = True

    enabled_managers = renovate_data.get(
        "enabledManagers",
        []
    )

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = (
        "nuget" in enabled_managers
    )

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = (
        "dockerfile" in enabled_managers
    )

    evidencias[
        "Vulnerability Alerts"
    ] = (
        renovate_data.get(
            "vulnerabilityAlerts"
        ) is not None
        or contem(
            renovate_json,
            "vulnerabilityalerts",
            "osv"
        )
    )

    evidencias[
        "Lock File Maintenance"
    ] = (
        renovate_data.get(
            "lockFileMaintenance"
        ) is not None
    )

elif renovate_json:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None

else:

    evidencias[
        "Renovate configurado"
    ] = None

    evidencias[
        "Gerenciamento NuGet pelo Renovate"
    ] = None

    evidencias[
        "Gerenciamento Dockerfile pelo Renovate"
    ] = None

    evidencias[
        "Vulnerability Alerts"
    ] = None

    evidencias[
        "Lock File Maintenance"
    ] = None


# ---------------------------------------------------------
# 4. Renovate no pipeline
# ---------------------------------------------------------

if pipeline and pipeline_valido is True:

    job_renovate = (
        contem(
            pipeline,
            "renovate/renovate"
        )
        or contem(
            pipeline,
            "renovate $ci_project_path",
            "renovate ${ci_project_path}"
        )
    )

    evidencias[
        "Job Renovate no pipeline"
    ] = job_renovate

    evidencias[
        "Regra schedule para Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "schedule"
        )
    )

    evidencias[
        "Execução manual do Renovate"
    ] = (
        job_renovate
        and contem(
            pipeline,
            "when: manual",
            'ci_pipeline_source == "web"',
            "ci_pipeline_source == 'web'"
        )
    )

else:

    evidencias[
        "Job Renovate no pipeline"
    ] = None

    evidencias[
        "Regra schedule para Renovate"
    ] = None

    evidencias[
        "Execução manual do Renovate"
    ] = None


# Configuração/orquestração não prova execução.
evidencias[
    "Execução efetiva do Renovate"
] = None


# ---------------------------------------------------------
# 5. Dockerfile
# ---------------------------------------------------------

if dockerfile:

    evidencias[
        "Dockerfile presente"
    ] = True

    quantidade_from = len(
        re.findall(
            r"^\s*FROM\s+",
            dockerfile,
            flags=(
                re.IGNORECASE
                | re.MULTILINE
            )
        )
    )

    evidencias[
        "Docker multi-stage build"
    ] = quantidade_from >= 2

    evidencias[
        "Restore no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet restore"
    )

    evidencias[
        "Build no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet build"
    )

    evidencias[
        "Publish no Dockerfile"
    ] = contem(
        dockerfile,
        "dotnet publish"
    )

else:

    evidencias["Dockerfile presente"] = None
    evidencias["Docker multi-stage build"] = None
    evidencias["Restore no Dockerfile"] = None
    evidencias["Build no Dockerfile"] = None
    evidencias["Publish no Dockerfile"] = None


# ---------------------------------------------------------
# 6. Docker Compose
# ---------------------------------------------------------

if docker_compose:

    evidencias[
        "Docker Compose presente"
    ] = True

    evidencias[
        "Build definido no Docker Compose"
    ] = contem(
        docker_compose,
        "build:"
    )

    evidencias[
        "Política de restart"
    ] = contem(
        docker_compose,
        "restart:"
    )

    evidencias[
        "Rede externa no Docker Compose"
    ] = buscar_regex(
        docker_compose,
        r"external\s*:\s*true"
    ) is not None

    evidencias[
        "Reverse proxy configurado"
    ] = contem(
        docker_compose,
        "traefik",
        "nginx",
        "reverse proxy"
    )

else:

    evidencias["Docker Compose presente"] = None
    evidencias["Build definido no Docker Compose"] = None
    evidencias["Política de restart"] = None
    evidencias["Rede externa no Docker Compose"] = None
    evidencias["Reverse proxy configurado"] = None


# ---------------------------------------------------------
# 7. Program.cs / Observabilidade
# ---------------------------------------------------------

if program_cs:

    evidencias[
        "Sentry integrado em runtime"
    ] = contem(
        program_cs,
        "usesentry",
        "sentry"
    )

    evidencias[
        "Health Checks"
    ] = contem(
        program_cs,
        "addhealthchecks",
        "maphealthchecks"
    )

    evidencias[
        "Health Check de banco"
    ] = contem(
        program_cs,
        "addnpgsql"
    )

    evidencias[
        "Health Check de API"
    ] = contem(
        program_cs,
        "addurlgroup"
    )

    evidencias[
        "Console Logging"
    ] = contem(
        program_cs,
        "addconsole"
    )

else:

    evidencias["Sentry integrado em runtime"] = None
    evidencias["Health Checks"] = None
    evidencias["Health Check de banco"] = None
    evidencias["Health Check de API"] = None
    evidencias["Console Logging"] = None


# ---------------------------------------------------------
# 8. appsettings
# ---------------------------------------------------------

if appsettings:

    evidencias[
        "appsettings presente"
    ] = True

    evidencias[
        "Sentry configurado"
    ] = contem(
        appsettings,
        "sentry"
    )

    evidencias[
        "Matomo configurado"
    ] = contem(
        appsettings,
        "matomo"
    )

    evidencias[
        "PostgreSQL configurado"
    ] = contem(
        appsettings,
        "postgres",
        "npgsql"
    )

    evidencias[
        "Configuração externalizada"
    ] = contem(
        appsettings,
        "connectionstrings",
        "environment"
    )

else:

    evidencias["appsettings presente"] = None
    evidencias["Sentry configurado"] = None
    evidencias["Matomo configurado"] = None
    evidencias["PostgreSQL configurado"] = None
    evidencias["Configuração externalizada"] = None


# ---------------------------------------------------------
# 9. .editorconfig
# ---------------------------------------------------------

if editorconfig:

    evidencias[
        ".editorconfig presente"
    ] = True

    evidencias[
        "Regras de analyzer declaradas"
    ] = contem(
        editorconfig,
        "dotnet_diagnostic",
        "severity"
    )

    evidencias[
        "Regras de segurança declaradas"
    ] = contem(
        editorconfig,
        "security"
    )

else:

    evidencias[".editorconfig presente"] = None
    evidencias["Regras de analyzer declaradas"] = None
    evidencias["Regras de segurança declaradas"] = None


# ---------------------------------------------------------
# 10. Arquivos de ambiente
# ---------------------------------------------------------

if env_example:

    evidencias[
        ".env.example presente"
    ] = True

else:

    evidencias[
        ".env.example presente"
    ] = None


if env_io_example:

    evidencias[
        ".env.io.example presente"
    ] = True

else:

    evidencias[
        ".env.io.example presente"
    ] = None


if env_example or env_io_example:

    texto_env = "\n".join(
        texto
        for texto in (
            env_example,
            env_io_example
        )
        if texto
    )

    evidencias[
        "Parametrização de ambientes"
    ] = contem(
        texto_env,
        "environment",
        "stage",
        "server",
        "host",
        "version",
        "project"
    )

else:

    evidencias[
        "Parametrização de ambientes"
    ] = None


# ---------------------------------------------------------
# 11. Scripts
# ---------------------------------------------------------

if scripts:

    evidencias[
        "Scripts presentes"
    ] = True

    texto_scripts = "\n".join(
        list(scripts.keys())
        + list(scripts.values())
    )

    evidencias[
        "Script de inicialização de banco"
    ] = contem(
        texto_scripts,
        "init.sql",
        "create table",
        "create schema"
    )

    evidencias[
        "Script de seed"
    ] = contem(
        texto_scripts,
        "seed.sql",
        "insert into"
    )

    evidencias[
        "Dump de banco presente"
    ] = contem(
        texto_scripts,
        "pg_dump",
        ".dump",
        "postgresql database dump"
    )

    evidencias[
        "Automação de ambiente local"
    ] = contem(
        texto_scripts,
        "docker compose",
        "docker-compose",
        "start-db",
        "localhost"
    )

else:

    evidencias["Scripts presentes"] = None
    evidencias["Script de inicialização de banco"] = None
    evidencias["Script de seed"] = None
    evidencias["Dump de banco presente"] = None
    evidencias["Automação de ambiente local"] = None


# ---------------------------------------------------------
# 12. Resultado
# ---------------------------------------------------------

print("EVIDÊNCIAS EXTRAÍDAS\n")

print(
    "Target Framework:",
    target_framework
)

print(
    "SDK Pipeline:",
    sdk_pipeline
)

print()

for nome, valor in evidencias.items():

    if valor is True:
        simbolo = "✓"

    elif valor is False:
        simbolo = "—"

    else:
        simbolo = "?"

    print(
        f"{simbolo} {nome}"
    )

EVIDÊNCIAS EXTRAÍDAS

Target Framework: net10.0
SDK Pipeline: 10.0

✓ GitLab CI como código
✓ `dotnet restore` no CI
✓ Build Release no CI
✓ SonarQube
✓ Espera pelo Quality Gate
— Quality Gate bloqueante
✓ Cache Sonar
✓ Cache NuGet
— Regra para Merge Request
✓ Regra para branch main
— Testes automatizados
— Deploy automatizado
— Promoção automática
— Rollback automatizado
✓ Renovate configurado
✓ Gerenciamento NuGet pelo Renovate
✓ Gerenciamento Dockerfile pelo Renovate
✓ Vulnerability Alerts
✓ Lock File Maintenance
— Job Renovate no pipeline
— Regra schedule para Renovate
— Execução manual do Renovate
? Execução efetiva do Renovate
✓ Dockerfile presente
✓ Docker multi-stage build
✓ Restore no Dockerfile
✓ Build no Dockerfile
✓ Publish no Dockerfile
✓ Docker Compose presente
✓ Build definido no Docker Compose
✓ Política de restart
✓ Rede externa no Docker Compose
✓ Reverse proxy configurado
✓ Sentry integrado em runtime
✓ Health Checks
— Health Check de banco
— Health Check de API
✓ Console Logging
✓ appsettings presente
✓ Sentry configurado
✓ Matomo configurado
— PostgreSQL configurado
✓ Configuração externalizada
✓ .editorconfig presente
✓ Regras de analyzer declaradas
✓ Regras de segurança declaradas
✓ .env.example presente
✓ .env.io.example presente
✓ Parametrização de ambientes
✓ Scripts presentes
✓ Script de inicialização de banco
✓ Script de seed
— Dump de banco presente
✓ Automação de ambiente local

In [69]:
# ---------------------------------------------------------
# PIPELINE MATURITY CLASSIFICATION
# ---------------------------------------------------------

def classificar_maturidade(e):

    if not e:

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "Nenhuma evidência foi extraída."
            )
        }


    gitlab_ci = e.get(
        "GitLab CI como código"
    )

    restore = e.get(
        "`dotnet restore` no CI"
    )

    build = e.get(
        "Build Release no CI"
    )

    sonar = e.get(
        "SonarQube"
    )

    quality_gate_wait = e.get(
        "Espera pelo Quality Gate"
    )

    quality_gate_blocking = e.get(
        "Quality Gate bloqueante"
    )

    testes = e.get(
        "Testes automatizados"
    )

    deploy = e.get(
        "Deploy automatizado"
    )

    promocao = e.get(
        "Promoção automática"
    )

    rollback = e.get(
        "Rollback automatizado"
    )


    # -----------------------------------------------------
    # Evidência insuficiente
    # -----------------------------------------------------

    if all(
        valor is None
        for valor in (
            gitlab_ci,
            restore,
            build,
            sonar
        )
    ):

        return {
            "nivel": None,
            "classificacao": "Indeterminado",
            "motivo": (
                "O pipeline não está disponível ou não pôde "
                "ser validado."
            )
        }


    # -----------------------------------------------------
    # CI estruturada
    # -----------------------------------------------------

    ci_estruturada = (
        gitlab_ci is True
        and restore is True
        and build is True
    )

    qualidade = (
        sonar is True
        or quality_gate_wait is True
    )


    # -----------------------------------------------------
    # Nível 4
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
        and testes is True
        and quality_gate_blocking is True
        and deploy is True
        and promocao is True
        and rollback is True
    ):

        return {
            "nivel": 4,
            "classificacao": "Avançado/Consolidado",
            "motivo": (
                "O pipeline apresenta CI estruturada, testes "
                "automatizados, controle de qualidade bloqueante, "
                "deploy, promoção e rollback automatizados."
            )
        }


    # -----------------------------------------------------
    # Nível 3
    # -----------------------------------------------------

    if (
        ci_estruturada
        and qualidade
    ):

        return {
            "nivel": 3,
            "classificacao": "Parcial/Emergente",
            "motivo": (
                "O pipeline apresenta integração contínua "
                "estruturada e controles de qualidade, mas "
                "a automação de ponta a ponta permanece incompleta."
            )
        }


    # -----------------------------------------------------
    # Nível 2
    # -----------------------------------------------------

    if (
        gitlab_ci is True
        and (
            restore is True
            or build is True
            or sonar is True
        )
    ):

        return {
            "nivel": 2,
            "classificacao": "Inicial/Ad hoc",
            "motivo": (
                "Existe pipeline versionado com automações "
                "pontuais, mas sem CI estruturada completa."
            )
        }


    # -----------------------------------------------------
    # Nível 1
    # -----------------------------------------------------

    if gitlab_ci is True:

        return {
            "nivel": 1,
            "classificacao": "Ausente/Tradicional",
            "motivo": (
                "O pipeline existe, mas não foram identificadas "
                "automações relevantes segundo os critérios definidos."
            )
        }


    return {
        "nivel": None,
        "classificacao": "Indeterminado",
        "motivo": (
            "As evidências disponíveis são insuficientes."
        )
    }


# ---------------------------------------------------------
# Executa a classificação
# ---------------------------------------------------------

resultado_maturidade = classificar_maturidade(
    evidencias
)


# ---------------------------------------------------------
# Resultado
# ---------------------------------------------------------

print("CLASSIFICAÇÃO DE MATURIDADE\n")

print(
    "Nível:",
    resultado_maturidade["nivel"]
)

print(
    "Classificação:",
    resultado_maturidade["classificacao"]
)

print(
    "Motivo:",
    resultado_maturidade["motivo"]
)

CLASSIFICAÇÃO DE MATURIDADE

Nível: 3
Classificação: Parcial/Emergente
Motivo: O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta.

In [70]:
# ---------------------------------------------------------
# EVIDENCE PREPARATION FOR AI INTERPRETATION
# ---------------------------------------------------------

if not evidencias:
    raise ValueError(
        "Nenhuma evidência foi extraída."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação determinística ainda não foi executada."
    )


# ---------------------------------------------------------
# Pacote estruturado
# ---------------------------------------------------------

evidencias_para_ia = {

    "artefatos_analisados": {

        "pipeline": pipeline_nome,
        "csproj": csproj_nome,
        "renovate_json": renovate_json_nome,
        "renovate_setup": renovate_setup_nome,
        "dockerfile": dockerfile_nome,
        "docker_compose": docker_compose_nome,
        "program_cs": program_cs_nome,
        "appsettings": appsettings_nome,
        "editorconfig": editorconfig_nome,
        "env_example": env_example_nome,
        "env_io_example": env_io_example_nome,
        "scripts": scripts_nomes
    },

    "caracterizacao_tecnologica": {

        "target_framework":
            target_framework,

        "sdk_pipeline":
            sdk_pipeline
    },

    "integracao_continua": {

        "gitlab_ci":
            evidencias.get(
                "GitLab CI como código"
            ),

        "dotnet_restore":
            evidencias.get(
                "`dotnet restore` no CI"
            ),

        "build_release":
            evidencias.get(
                "Build Release no CI"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            ),

        "sonar_cache":
            evidencias.get(
                "Cache Sonar"
            ),

        "nuget_cache":
            evidencias.get(
                "Cache NuGet"
            ),

        "merge_request_rule":
            evidencias.get(
                "Regra para Merge Request"
            ),

        "main_branch_rule":
            evidencias.get(
                "Regra para branch main"
            ),

        "automated_tests":
            evidencias.get(
                "Testes automatizados"
            )
    },

    "gerenciamento_dependencias": {

        "renovate_configured":
            evidencias.get(
                "Renovate configurado"
            ),

        "nuget_manager":
            evidencias.get(
                "Gerenciamento NuGet pelo Renovate"
            ),

        "dockerfile_manager":
            evidencias.get(
                "Gerenciamento Dockerfile pelo Renovate"
            ),

        "vulnerability_alerts":
            evidencias.get(
                "Vulnerability Alerts"
            ),

        "lock_file_maintenance":
            evidencias.get(
                "Lock File Maintenance"
            ),

        "renovate_job":
            evidencias.get(
                "Job Renovate no pipeline"
            ),

        "renovate_schedule":
            evidencias.get(
                "Regra schedule para Renovate"
            ),

        "renovate_manual":
            evidencias.get(
                "Execução manual do Renovate"
            ),

        "renovate_effective_execution":
            evidencias.get(
                "Execução efetiva do Renovate"
            )
    },

    "containerizacao": {

        "dockerfile_present":
            evidencias.get(
                "Dockerfile presente"
            ),

        "multi_stage_build":
            evidencias.get(
                "Docker multi-stage build"
            ),

        "docker_restore":
            evidencias.get(
                "Restore no Dockerfile"
            ),

        "docker_build":
            evidencias.get(
                "Build no Dockerfile"
            ),

        "docker_publish":
            evidencias.get(
                "Publish no Dockerfile"
            ),

        "docker_compose_present":
            evidencias.get(
                "Docker Compose presente"
            ),

        "docker_compose_build":
            evidencias.get(
                "Build definido no Docker Compose"
            ),

        "restart_policy":
            evidencias.get(
                "Política de restart"
            ),

        "external_network":
            evidencias.get(
                "Rede externa no Docker Compose"
            ),

        "reverse_proxy":
            evidencias.get(
                "Reverse proxy configurado"
            )
    },

    "observabilidade": {

        "sentry_configured":
            evidencias.get(
                "Sentry configurado"
            ),

        "sentry_runtime_integration":
            evidencias.get(
                "Sentry integrado em runtime"
            ),

        "health_checks":
            evidencias.get(
                "Health Checks"
            ),

        "database_health_check":
            evidencias.get(
                "Health Check de banco"
            ),

        "api_health_check":
            evidencias.get(
                "Health Check de API"
            ),

        "console_logging":
            evidencias.get(
                "Console Logging"
            ),

        "matomo_configured":
            evidencias.get(
                "Matomo configurado"
            )
    },

    "configuracao_e_ambiente": {

        "appsettings_present":
            evidencias.get(
                "appsettings presente"
            ),

        "externalized_configuration":
            evidencias.get(
                "Configuração externalizada"
            ),

        "env_example_present":
            evidencias.get(
                ".env.example presente"
            ),

        "env_io_example_present":
            evidencias.get(
                ".env.io.example presente"
            ),

        "postgresql_configured":
            evidencias.get(
                "PostgreSQL configurado"
            ),

        "environment_parameterization":
            evidencias.get(
                "Parametrização de ambientes"
            )
    },

    "qualidade_estatica": {

        "editorconfig_present":
            evidencias.get(
                ".editorconfig presente"
            ),

        "analyzer_rules_declared":
            evidencias.get(
                "Regras de analyzer declaradas"
            ),

        "security_rules_declared":
            evidencias.get(
                "Regras de segurança declaradas"
            ),

        "sonarqube":
            evidencias.get(
                "SonarQube"
            ),

        "quality_gate_wait":
            evidencias.get(
                "Espera pelo Quality Gate"
            ),

        "quality_gate_blocking":
            evidencias.get(
                "Quality Gate bloqueante"
            )
    },

    "automacao_local": {

        "scripts_present":
            evidencias.get(
                "Scripts presentes"
            ),

        "database_initialization_script":
            evidencias.get(
                "Script de inicialização de banco"
            ),

        "database_seed_script":
            evidencias.get(
                "Script de seed"
            ),

        "database_dump_present":
            evidencias.get(
                "Dump de banco presente"
            ),

        "local_environment_automation":
            evidencias.get(
                "Automação de ambiente local"
            )
    },

    "entrega_e_recuperacao": {

        "automated_deploy":
            evidencias.get(
                "Deploy automatizado"
            ),

        "automated_promotion":
            evidencias.get(
                "Promoção automática"
            ),

        "automated_rollback":
            evidencias.get(
                "Rollback automatizado"
            )
    },

    "classificacao_deterministica":
        resultado_maturidade
}


print(
    "EVIDÊNCIAS PREPARADAS PARA A IA\n"
)

print(
    json.dumps(
        evidencias_para_ia,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

EVIDÊNCIAS PREPARADAS PARA A IA

{
  "artefatos_analisados": {
    "pipeline": "gitlab-ci (5).yml",
    "csproj": "Boilerplate4Dev (5).csproj",
    "renovate_json": "renovate (2).json",
    "renovate_setup": "RENOVATE_SETUP (2).md",
    "dockerfile": "Dockerfile (5)",
    "docker_compose": "docker-compose (5).yaml",
    "program_cs": "Program (5).cs",
    "appsettings": "appsettings (5).json",
    "editorconfig": ".editorconfig (5)",
    "env_example": ".env (5).example",
    "env_io_example": ".env.io (4).example",
    "scripts": [
      "init (5).sql",
      "seed (2).sql",
      "start-db (5).ps1"
    ]
  },
  "caracterizacao_tecnologica": {
    "target_framework": "net10.0",
    "sdk_pipeline": "10.0"
  },
  "integracao_continua": {
    "gitlab_ci": true,
    "dotnet_restore": true,
    "build_release": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false,
    "sonar_cache": true,
    "nuget_cache": true,
    "merge_request_rule": false,
    "main_branch_rule": true,
    "automated_tests": false
  },
  "gerenciamento_dependencias": {
    "renovate_configured": true,
    "nuget_manager": true,
    "dockerfile_manager": true,
    "vulnerability_alerts": true,
    "lock_file_maintenance": true,
    "renovate_job": false,
    "renovate_schedule": false,
    "renovate_manual": false,
    "renovate_effective_execution": null
  },
  "containerizacao": {
    "dockerfile_present": true,
    "multi_stage_build": true,
    "docker_restore": true,
    "docker_build": true,
    "docker_publish": true,
    "docker_compose_present": true,
    "docker_compose_build": true,
    "restart_policy": true,
    "external_network": true,
    "reverse_proxy": true
  },
  "observabilidade": {
    "sentry_configured": true,
    "sentry_runtime_integration": true,
    "health_checks": true,
    "database_health_check": false,
    "api_health_check": false,
    "console_logging": true,
    "matomo_configured": true
  },
  "configuracao_e_ambiente": {
    "appsettings_present": true,
    "externalized_configuration": true,
    "env_example_present": true,
    "env_io_example_present": true,
    "postgresql_configured": false,
    "environment_parameterization": true
  },
  "qualidade_estatica": {
    "editorconfig_present": true,
    "analyzer_rules_declared": true,
    "security_rules_declared": true,
    "sonarqube": true,
    "quality_gate_wait": true,
    "quality_gate_blocking": false
  },
  "automacao_local": {
    "scripts_present": true,
    "database_initialization_script": true,
    "database_seed_script": true,
    "database_dump_present": false,
    "local_environment_automation": true
  },
  "entrega_e_recuperacao": {
    "automated_deploy": false,
    "automated_promotion": false,
    "automated_rollback": false
  },
  "classificacao_deterministica": {
    "nivel": 3,
    "classificacao": "Parcial/Emergente",
    "motivo": "O pipeline apresenta integração contínua estruturada e controles de qualidade, mas a automação de ponta a ponta permanece incompleta."
  }
}

In [71]:
# ---------------------------------------------------------
# MATURITY CRITERIA
# ---------------------------------------------------------

criterios_maturidade = """
Escala de maturidade das práticas de automação do pipeline:

Nível 1 — Ausente/Tradicional
Não há automação relevante das atividades de build, qualidade, testes ou entrega.

Nível 2 — Inicial/Ad hoc
Existe pipeline versionado, porém as automações são pontuais ou isoladas.

Nível 3 — Parcial/Emergente
Existe pipeline versionado com práticas estruturadas de integração contínua, como restore, build e controles de qualidade, mas ainda existem lacunas relevantes.

Nível 4 — Avançado/Consolidado
Existem práticas integradas e consolidadas envolvendo build, testes automatizados, controles de qualidade bloqueantes, entrega, promoção e recuperação.

A atribuição do nível 4 exige evidências suficientes de integração e execução das práticas. A simples presença de arquivos de configuração não é suficiente.
"""


# ---------------------------------------------------------
# AI INTERPRETATION PROMPT
# ---------------------------------------------------------

if evidencias_para_ia is None:
    raise ValueError(
        "As evidências ainda não foram preparadas."
    )


prompt = f"""
Você deve realizar uma interpretação técnica das evidências relacionadas à automação de pipeline apresentadas abaixo.

A classificação foi previamente calculada por critérios determinísticos implementados no notebook.

Sua função NÃO é realizar uma nova classificação independente.

Sua função é interpretar as evidências e avaliar se elas sustentam a classificação determinística.

{criterios_maturidade}

EVIDÊNCIAS E CLASSIFICAÇÃO DETERMINÍSTICA:

{json.dumps(
    evidencias_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}

REGRAS DA ANÁLISE:

1. Utilize exclusivamente as evidências fornecidas.
2. Não presuma práticas não evidenciadas.
3. Não avalie a maturidade DevOps global do projeto.
4. Avalie somente a automação do pipeline e as evidências técnicas relacionadas.
5. Considere:
   true = evidência positiva;
   false = evidência negativa no artefato analisado;
   null = evidência indeterminada.
6. Null não significa ausência da prática.
7. Quality Gate configurado não significa necessariamente Quality Gate bloqueante.
8. allow_failure:true no job de qualidade impede interpretar o Quality Gate como bloqueante.
9. renovate.json demonstra configuração, mas não execução.
10. Um job Renovate demonstra orquestração, mas não comprova execução bem-sucedida.
11. Execução efetiva do Renovate exige evidências de runtime, como histórico de pipeline, logs, branches renovate/* ou merge requests criadas pela ferramenta.
12. Dockerfile e Docker Compose demonstram configuração e automação de construção/execução de contêineres, mas não comprovam deploy automatizado.
13. Scripts locais ou de inicialização de banco não devem ser tratados como deploy automatizado.
14. Sentry, Matomo, logging e health checks caracterizam observabilidade e não constituem, isoladamente, automação de entrega.
15. Ausência de comandos de deploy no pipeline não prova que nenhum deploy seja realizado fora dele.
16. O mesmo princípio se aplica à promoção entre ambientes e ao rollback.
17. Compare explicitamente as evidências com a classificação determinística.
18. Se a classificação for sustentada, declare isso.
19. Se houver inconsistência, descreva-a explicitamente, sem substituir arbitrariamente a classificação.
20. Utilize linguagem técnica, conservadora, rastreável e adequada a um trabalho acadêmico.
Produza a resposta em português nesta estrutura:

### Avaliação da classificação
Classificação determinística:
Avaliação: Sustentada / Parcialmente sustentada / Não sustentada

### Evidências que sustentam a avaliação
...

### Lacunas identificadas
...

### Limitações da interpretação
...

### Síntese
...
"""

print(
    "✓ Prompt de interpretação preparado."
)

✓ Prompt de interpretação preparado.

In [72]:
# ---------------------------------------------------------
# AI-ASSISTED TECHNICAL INTERPRETATION
# ---------------------------------------------------------

from google.colab import userdata
from openai import OpenAI


# ---------------------------------------------------------
# 1. Recupera a chave da API
# ---------------------------------------------------------

try:

    api_key = userdata.get(
        "OPENAI_API_KEY"
    )

except Exception:

    api_key = None


if not api_key:

    raise ValueError(
        "A chave OPENAI_API_KEY não foi encontrada. "
        "Configure-a nos Secrets do Google Colab."
    )


# ---------------------------------------------------------
# 2. Validação
# ---------------------------------------------------------

if evidencias_para_ia is None:

    raise ValueError(
        "As evidências para a IA ainda não foram preparadas."
    )


if not prompt:

    raise ValueError(
        "O prompt de interpretação ainda não foi criado."
    )


if resultado_maturidade is None:

    raise ValueError(
        "A classificação determinística ainda não foi calculada."
    )


# ---------------------------------------------------------
# 3. Cliente OpenAI
# ---------------------------------------------------------

client = OpenAI(
    api_key=api_key
)


# ---------------------------------------------------------
# 4. Interpretação assistida
# ---------------------------------------------------------

try:

    response = client.responses.create(

        model="gpt-5.6-terra",

        instructions=(
            "Atue como avaliador técnico de práticas DevOps. "
            "Sua interpretação deve ser conservadora, "
            "rastreável e limitada às evidências fornecidas. "
            "Não realize uma nova classificação independente. "
            "Avalie se as evidências sustentam a classificação "
            "determinística calculada pelo notebook."
        ),

        input=prompt
    )


    interpretacao_ia = response.output_text


    print(
        "INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA\n"
    )

    print(
        interpretacao_ia
    )


except Exception as erro:

    interpretacao_ia = None

    print(
        "⚠ Não foi possível executar a interpretação "
        "assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO TÉCNICA ASSISTIDA POR IA

### Avaliação da classificação
Classificação determinística: **Nível 3 — Parcial/Emergente**

Avaliação: **Sustentada**

### Evidências que sustentam a avaliação
A classificação em nível 3 é sustentada pela presença de uma estrutura de integração contínua versionada em GitLab CI, com etapas relevantes de automação de construção e qualidade:

- Há evidência de pipeline versionado em GitLab CI (`gitlab_ci: true`).
- O pipeline executa restauração de dependências .NET (`dotnet_restore: true`) e build em configuração Release (`build_release: true`), caracterizando práticas básicas e estruturadas de integração contínua.
- Há integração com SonarQube (`sonarqube: true`) e espera pelo resultado do Quality Gate (`quality_gate_wait: true`).
- Existem configurações de qualidade estática, incluindo `.editorconfig`, regras de analisadores e regras de segurança declaradas (`editorconfig_present`, `analyzer_rules_declared` e `security_rules_declared` iguais a `true`).
- Há uso de cache para NuGet e SonarQube, indicando preocupação com reprodutibilidade e eficiência operacional da execução do pipeline (`nuget_cache: true` e `sonar_cache: true`).
- A regra associada à branch principal está evidenciada (`main_branch_rule: true`), o que indica algum direcionamento de execução do pipeline conforme o fluxo de branches.
- A containerização possui automação de build tecnicamente estruturada: Dockerfile presente, build multiestágio, restore, build e publish no contexto da imagem (`multi_stage_build`, `docker_restore`, `docker_build` e `docker_publish` iguais a `true`).
- O Docker Compose complementa a automação de execução em ambiente conteinerizado, com build, política de reinicialização, rede externa e proxy reverso configurados. Essas evidências sustentam automação de construção e execução local/operacional, embora não caracterizem entrega automatizada.
- Existem scripts de inicialização e seed de banco de dados, além de automação de ambiente local (`local_environment_automation: true`). Tais elementos são coerentes com uma maturidade parcial de automação do ciclo de desenvolvimento.

Em conjunto, essas evidências demonstram que o projeto ultrapassa automações isoladas ou estritamente ad hoc. Há uma base estruturada de CI envolvendo restauração, compilação e análise de qualidade, compatível com o nível 3.

### Lacunas identificadas
Persistem lacunas relevantes que impedem interpretar as evidências como suficientes para o nível 4:

- Não há evidência de testes automatizados no pipeline (`automated_tests: false`). Portanto, embora exista build e análise estática, não está evidenciada uma validação automatizada funcional ou de integração.
- O Quality Gate não pode ser considerado bloqueante (`quality_gate_blocking: false`). A presença de SonarQube e de espera pelo Quality Gate não compensa essa limitação, pois o controle de qualidade não está evidenciado como impedimento efetivo para a progressão do pipeline.
- Não há regra de pipeline para merge requests (`merge_request_rule: false`), reduzindo a evidência de controles integrados ao fluxo de revisão e integração de código.
- Não há evidência de deploy automatizado, promoção entre ambientes ou rollback automatizado (`automated_deploy`, `automated_promotion` e `automated_rollback` iguais a `false`).
- A configuração do Renovate demonstra gerenciamento declarado de dependências, vulnerabilidades e lock files, mas não comprova sua execução. Não há job, agenda ou acionamento manual evidenciado (`renovate_job`, `renovate_schedule` e `renovate_manual` iguais a `false`), e a execução efetiva permanece indeterminada (`renovate_effective_execution: null`).
- Os health checks existentes não incluem evidência de verificação específica de banco de dados ou API (`database_health_check: false` e `api_health_check: false`). Embora essa lacuna esteja mais relacionada à observabilidade e à prontidão operacional, ela não adiciona evidência de recuperação automatizada.

Assim, não há evidência suficiente de integração ponta a ponta entre validação, entrega, promoção e recuperação, que seria necessária para sustentar o nível 4.

### Limitações da interpretação
A interpretação está limitada aos campos e artefatos sumarizados nas evidências fornecidas.

Em particular:

- A ausência de deploy, promoção ou rollback automatizados no conjunto analisado não prova que essas práticas não ocorram por mecanismos externos ao pipeline, como plataformas de infraestrutura, processos de operação ou ferramentas não incluídas nos artefatos.
- A ausência de testes automatizados refere-se às evidências analisadas e não permite concluir que não existam testes em outros repositórios, pipelines ou etapas não inspecionadas.
- A configuração de Renovate não permite inferir execução real, criação de merge requests ou atualização bem-sucedida de dependências. O valor `null` para execução efetiva é indeterminação, e não evidência negativa.
- Dockerfile, Docker Compose, scripts de banco e configurações de observabilidade demonstram capacidades de construção, execução e instrumentação, mas não comprovam deploy automatizado nem promoção controlada entre ambientes.
- Sentry, Matomo, logging e health checks contribuem para observabilidade, porém não constituem, isoladamente, evidência de automação de entrega ou recuperação.

### Síntese
A classificação determinística de **Nível 3 — Parcial/Emergente** está sustentada pelas evidências. O projeto apresenta uma base estruturada de integração contínua, incluindo pipeline versionado, restore, build em Release, análise estática com SonarQube, caches e automação de construção de contêineres.

Contudo, as lacunas em testes automatizados, bloqueio efetivo do Quality Gate, deploy, promoção e rollback impedem caracterizar uma automação integrada e consolidada de ponta a ponta. As evidências de containerização, scripts locais, gerenciamento configurado de dependências e observabilidade reforçam a infraestrutura técnica disponível, mas não substituem evidências de execução de entrega e recuperação automatizadas.

In [73]:
# ---------------------------------------------------------
# STORE VERSION ANALYSIS RESULTS — V4
# ---------------------------------------------------------

import copy

if not evidencias:
    raise ValueError(
        "As evidências da V4 não estão disponíveis."
    )

if resultado_maturidade is None:
    raise ValueError(
        "A classificação de maturidade da V4 "
        "não está disponível."
    )

if evidencias_para_ia is None:
    raise ValueError(
        "O pacote estruturado de evidências da V4 "
        "não está disponível."
    )


resultados_versoes["V4"] = {

    "versao": "V4",
    "snapshot": "web-1.26.8-beta.1",

    "evidencias":
        copy.deepcopy(
            evidencias
        ),

    "classificacao":
        copy.deepcopy(
            resultado_maturidade
        ),

    "evidencias_para_ia":
        copy.deepcopy(
            evidencias_para_ia
        ),

    "interpretacao_ia":
        interpretacao_ia
        if "interpretacao_ia" in globals()
        else None,

    "target_framework":
        target_framework,

    "sdk_pipeline":
        sdk_pipeline
}


print(
    "✓ Resultados da V4 armazenados "
    "para a análise longitudinal."
)

✓ Resultados da V4 armazenados para a análise longitudinal.


## Longitudinal Pipeline Technical Analysis — V1–V4

A matriz abaixo sintetiza as evidências ao longo das quatro versões.

In [74]:
# ---------------------------------------------------------
# LONGITUDINAL PIPELINE TECHNICAL ANALYSIS — V1–V4
# ---------------------------------------------------------

versoes_esperadas = [
    "V1",
    "V2",
    "V3",
    "V4"
]


# ---------------------------------------------------------
# 1. Verifica se todas as análises foram armazenadas
# ---------------------------------------------------------

versoes_ausentes = [
    versao
    for versao in versoes_esperadas
    if versao not in resultados_versoes
]


if versoes_ausentes:

    raise ValueError(
        "As seguintes versões ainda não possuem resultados "
        "armazenados para análise longitudinal: "
        + ", ".join(versoes_ausentes)
    )


# ---------------------------------------------------------
# 2. Evidências selecionadas para comparação longitudinal
# ---------------------------------------------------------

evidencias_longitudinais = {

    "GitLab CI":
        "GitLab CI como código",

    "Restore no CI":
        "`dotnet restore` no CI",

    "Build Release":
        "Build Release no CI",

    "SonarQube":
        "SonarQube",

    "Espera pelo Quality Gate":
        "Espera pelo Quality Gate",

    "Quality Gate bloqueante":
        "Quality Gate bloqueante",

    "Cache Sonar":
        "Cache Sonar",

    "Cache NuGet":
        "Cache NuGet",

    "Regra para Merge Request":
        "Regra para Merge Request",

    "Regra para branch main":
        "Regra para branch main",

    "Testes automatizados":
        "Testes automatizados",

    "Renovate configurado":
        "Renovate configurado",

    "Renovate — NuGet":
        "Gerenciamento NuGet pelo Renovate",

    "Renovate — Dockerfile":
        "Gerenciamento Dockerfile pelo Renovate",

    "Vulnerability Alerts":
        "Vulnerability Alerts",

    "Lock File Maintenance":
        "Lock File Maintenance",

    "Job Renovate":
        "Job Renovate no pipeline",

    "Schedule Renovate":
        "Regra schedule para Renovate",

    "Execução manual Renovate":
        "Execução manual do Renovate",

    "Execução efetiva Renovate":
        "Execução efetiva do Renovate",

    "Dockerfile":
        "Dockerfile presente",

    "Docker multi-stage":
        "Docker multi-stage build",

    "Docker Compose":
        "Docker Compose presente",

    "Sentry em runtime":
        "Sentry integrado em runtime",

    "Health Checks":
        "Health Checks",

    "Matomo":
        "Matomo configurado",

    ".editorconfig":
        ".editorconfig presente",

    "Analyzer rules":
        "Regras de analyzer declaradas",

    "Security rules":
        "Regras de segurança declaradas",

    "Parametrização de ambientes":
        "Parametrização de ambientes",

    "Automação de ambiente local":
        "Automação de ambiente local",

    "Deploy automatizado":
        "Deploy automatizado",

    "Promoção automática":
        "Promoção automática",

    "Rollback automatizado":
        "Rollback automatizado"
}


# ---------------------------------------------------------
# 3. Conversão tri-state
# ---------------------------------------------------------

def simbolo_evidencia(valor):

    if valor is True:
        return "✓"

    if valor is False:
        return "—"

    return "?"


# ---------------------------------------------------------
# 4. Cria matriz longitudinal
# ---------------------------------------------------------

linhas = []

for descricao, chave in evidencias_longitudinais.items():

    linha = {
        "Evidência": descricao
    }

    for versao in versoes_esperadas:

        evidencias_versao = (
            resultados_versoes[
                versao
            ][
                "evidencias"
            ]
        )

        linha[versao] = simbolo_evidencia(
            evidencias_versao.get(
                chave
            )
        )

    linhas.append(
        linha
    )


df_longitudinal = pd.DataFrame(
    linhas
)


print(
    "MATRIZ LONGITUDINAL DE EVIDÊNCIAS — V1–V4\n"
)

display(
    df_longitudinal
)

MATRIZ LONGITUDINAL DE EVIDÊNCIAS — V1–V4

                      Evidência V1 V2 V3 V4
0                     GitLab CI  ✓  ✓  ✓  ✓
1                 Restore no CI  —  ✓  ✓  ✓
2                 Build Release  —  ✓  ✓  ✓
3                     SonarQube  ✓  ✓  ✓  ✓
4      Espera pelo Quality Gate  ✓  ✓  ✓  ✓
5       Quality Gate bloqueante  —  —  —  —
6                   Cache Sonar  ✓  ✓  ✓  ✓
7                   Cache NuGet  —  ✓  ✓  ✓
8      Regra para Merge Request  ✓  —  —  —
9        Regra para branch main  ✓  ✓  ✓  ✓
10         Testes automatizados  —  —  —  —
11         Renovate configurado  ?  ✓  ✓  ✓
12             Renovate — NuGet  ?  ✓  ✓  ✓
13        Renovate — Dockerfile  ?  ✓  ✓  ✓
14         Vulnerability Alerts  ?  ✓  ✓  ✓
15        Lock File Maintenance  ?  ✓  ✓  ✓
16                 Job Renovate  —  ✓  —  —
17            Schedule Renovate  —  ✓  —  —
18     Execução manual Renovate  —  ✓  —  —
19    Execução efetiva Renovate  ?  ?  ?  ?
20                   Dockerfile  ✓  ✓  ✓  ✓
21           Docker multi-stage  ✓  ✓  ✓  ✓
22               Docker Compose  ✓  ✓  ✓  ✓
23            Sentry em runtime  ✓  ✓  ✓  ✓
24                Health Checks  ✓  ✓  ✓  ✓
25                       Matomo  ✓  ✓  ✓  ✓
26                .editorconfig  ✓  ✓  ✓  ✓
27               Analyzer rules  ✓  ✓  ✓  ✓
28               Security rules  ✓  ✓  ✓  ✓
29  Parametrização de ambientes  ✓  ✓  ✓  ✓
30  Automação de ambiente local  ✓  ✓  ✓  ✓
31          Deploy automatizado  —  —  —  —
32          Promoção automática  —  —  —  —
33        Rollback automatizado  —  —  —  —

In [75]:
# ---------------------------------------------------------
# LONGITUDINAL MATURITY CLASSIFICATION
# ---------------------------------------------------------

linhas_maturidade = []


for versao in versoes_esperadas:

    resultado = resultados_versoes[
        versao
    ]

    classificacao = resultado[
        "classificacao"
    ]

    linhas_maturidade.append(
        {
            "Versão":
                versao,

            "Snapshot":
                resultado.get(
                    "snapshot"
                ),

            "Target Framework":
                resultado.get(
                    "target_framework"
                ),

            "SDK Pipeline":
                resultado.get(
                    "sdk_pipeline"
                ),

            "Nível":
                classificacao.get(
                    "nivel"
                ),

            "Classificação":
                classificacao.get(
                    "classificacao"
                ),

            "Motivo":
                classificacao.get(
                    "motivo"
                )
        }
    )


df_maturidade_longitudinal = pd.DataFrame(
    linhas_maturidade
)


print(
    "EVOLUÇÃO DA CLASSIFICAÇÃO DE MATURIDADE\n"
)

display(
    df_maturidade_longitudinal
)

EVOLUÇÃO DA CLASSIFICAÇÃO DE MATURIDADE

,Versão,Snapshot,Target Framework,SDK Pipeline,Nível,Classificação,Motivo
0,V1,web-1.25.10-1,net9.0,None,2,Inicial/Ad hoc,Existe pipeline versionado com automações pont...
1,V2,web-1.26.4-1,net10.0,10.0,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
2,V3,web-1.26.6-1,net10.0,10.0,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...
3,V4,web-1.26.8-beta.1,net10.0,10.0,3,Parcial/Emergente,O pipeline apresenta integração contínua estru...

In [76]:
# ---------------------------------------------------------
# PREPARE LONGITUDINAL EVIDENCE
# ---------------------------------------------------------

evidencias_longitudinais_para_ia = {}


for versao in versoes_esperadas:

    resultado = resultados_versoes[
        versao
    ]

    evidencias_longitudinais_para_ia[
        versao
    ] = {

        "snapshot":
            resultado.get(
                "snapshot"
            ),

        "target_framework":
            resultado.get(
                "target_framework"
            ),

        "sdk_pipeline":
            resultado.get(
                "sdk_pipeline"
            ),

        "evidencias":
            resultado.get(
                "evidencias"
            ),

        "classificacao":
            resultado.get(
                "classificacao"
            )
    }


print(
    "✓ Evidências longitudinais estruturadas."
)

✓ Evidências longitudinais estruturadas.

In [77]:
# ---------------------------------------------------------
# LONGITUDINAL AI INTERPRETATION PROMPT
# ---------------------------------------------------------

prompt_longitudinal = f"""
Realize uma análise técnica longitudinal das práticas de
automação do pipeline nas versões V1, V2, V3 e V4.

A análise deve utilizar EXCLUSIVAMENTE os resultados das
análises individuais produzidas anteriormente pelo notebook.

Não reanalise os arquivos originais.

Não invente evidências adicionais.

Compare as versões considerando:

- permanência de práticas;
- introdução de novas capacidades;
- retirada de capacidades do pipeline;
- continuidade de configurações;
- diferenças entre configuração, orquestração e execução;
- evolução da classificação determinística;
- lacunas persistentes ao longo das versões.

Considere:

true  = evidência positiva;
false = ausência ou não evidência no artefato analisado;
null  = condição indeterminada.

Null não deve ser interpretado como ausência.

A configuração do Renovate não comprova sua execução efetiva.

A presença de um job Renovate demonstra orquestração, mas
não comprova execução bem-sucedida.

Dockerfile e Docker Compose não comprovam deploy automatizado.

Observabilidade não deve ser interpretada como automação
de entrega.

A ausência de comandos de deploy, promoção ou rollback nos
artefatos analisados não permite concluir que essas práticas
não ocorram fora do escopo analisado.

RESULTADOS DAS ANÁLISES INDIVIDUAIS:

{json.dumps(
    evidencias_longitudinais_para_ia,
    indent=2,
    ensure_ascii=False,
    default=str
)}

Produza a resposta em português nesta estrutura:

### Síntese longitudinal

### Evolução entre as versões
Analise V1 → V2 → V3 → V4.

### Práticas persistentes

### Capacidades introduzidas durante a evolução

### Mudanças ou descontinuidades de orquestração

### Lacunas persistentes

### Evolução da maturidade do pipeline

### Limitações da análise longitudinal

### Conclusão longitudinal

Use linguagem técnica, conservadora e adequada a um
trabalho acadêmico.
"""

print(
    "✓ Prompt longitudinal preparado."
)

✓ Prompt longitudinal preparado.

In [78]:
# ---------------------------------------------------------
# AI-ASSISTED LONGITUDINAL INTERPRETATION
# ---------------------------------------------------------

if not resultados_versoes:

    raise ValueError(
        "Os resultados individuais das versões "
        "não estão disponíveis."
    )


if not prompt_longitudinal:

    raise ValueError(
        "O prompt longitudinal não foi preparado."
    )


try:

    response_longitudinal = client.responses.create(

        model="gpt-5.6-terra",

        instructions=(
            "Atue como avaliador técnico de práticas DevOps. "
            "Realize uma interpretação longitudinal conservadora "
            "e rastreável. Utilize exclusivamente os resultados "
            "das análises individuais fornecidos. Não reclassifique "
            "arbitrariamente as versões e não invente evidências."
        ),

        input=prompt_longitudinal
    )


    interpretacao_longitudinal_ia = (
        response_longitudinal.output_text
    )


    print(
        "INTERPRETAÇÃO LONGITUDINAL "
        "ASSISTIDA POR IA — V1–V4\n"
    )

    print(
        interpretacao_longitudinal_ia
    )


except Exception as erro:

    interpretacao_longitudinal_ia = None

    print(
        "⚠ Não foi possível executar a "
        "interpretação longitudinal assistida por IA."
    )

    print(
        f"Detalhes: {erro}"
    )

INTERPRETAÇÃO LONGITUDINAL ASSISTIDA POR IA — V1–V4

### Síntese longitudinal

A evolução entre V1 (`web-1.25.10-1`) e V4 (`web-1.26.8-beta.1`) evidencia a consolidação de uma integração contínua parcialmente estruturada. O principal avanço ocorre entre V1 e V2, quando passam a existir evidências positivas de restauração de dependências e build em modo Release no CI, cache NuGet e configuração de Renovate acompanhada de mecanismos de orquestração no pipeline.

De V2 em diante, o conjunto principal de práticas de CI, análise de qualidade, construção de contêineres, configuração de execução local e observabilidade permanece estável. Contudo, não há evidência positiva, em nenhuma versão, de testes automatizados, deploy automatizado, promoção entre ambientes ou rollback automatizado. Assim, a evolução observada é predominantemente de fortalecimento da integração contínua e da gestão configurada de dependências, sem evidência de evolução para entrega contínua ou implantação contínua.

A interpretação distingue três dimensões:

- **Configuração:** presença de arquivos, regras e definições declarativas, como Renovate, Dockerfile, Docker Compose, arquivos de ambiente e configurações de observabilidade.
- **Orquestração:** existência de jobs, regras de agendamento, regras de acionamento e comandos no pipeline.
- **Execução efetiva:** comprovação de que uma automação foi executada com sucesso. Essa dimensão permanece indeterminada para Renovate em todas as versões e não pode ser inferida apenas da configuração ou do job.

---

### Evolução entre as versões

#### V1 → V2

A transição de V1 para V2 concentra as principais mudanças positivas observadas.

Em V1, já há evidência de GitLab CI como código, SonarQube, espera pelo Quality Gate, cache Sonar, regras para Merge Request e branch `main`, além de Dockerfile multi-stage e Docker Compose. Entretanto, não há evidência de `dotnet restore` no CI, build Release no CI ou cache NuGet. A classificação é nível 2, **Inicial/Ad hoc**, compatível com a presença de automações pontuais sem uma CI completa evidenciada.

Em V2, surgem evidências positivas de:

- `dotnet restore` no CI;
- build Release no CI;
- cache NuGet;
- SDK do pipeline explicitamente identificado como `10.0`;
- configuração de Renovate;
- gerenciamento de dependências NuGet e Dockerfile pelo Renovate;
- Vulnerability Alerts e Lock File Maintenance;
- job Renovate no pipeline;
- regra de agendamento (`schedule`) para Renovate;
- possibilidade de execução manual do Renovate;
- script de seed de banco.

Esses elementos indicam uma ampliação da capacidade de integração contínua e da automação declarativa da manutenção de dependências. Contudo, a execução efetiva do Renovate permanece `null`; portanto, não há comprovação de que as execuções agendadas ou manuais tenham sido concluídas com sucesso.

Há também uma mudança na evidência das regras de acionamento: em V1 existe regra para Merge Request, enquanto em V2 essa evidência é `false`; a regra para a branch `main` permanece positiva. Com base apenas nos resultados fornecidos, pode-se afirmar que a regra de Merge Request deixa de estar evidenciada a partir de V2, mas não é possível determinar a causa dessa alteração nem afirmar que a prática deixou de ocorrer por outros mecanismos.

#### V2 → V3

Entre V2 e V3, a estrutura principal de CI permanece estável:

- GitLab CI como código;
- restore e build Release no CI;
- SonarQube com espera pelo Quality Gate;
- cache Sonar e NuGet;
- regra para branch `main`;
- Dockerfile multi-stage com restore, build e publish;
- Docker Compose com definição de build, política de restart, rede externa e reverse proxy;
- configurações de runtime, observabilidade e ambiente local.

A principal descontinuidade está relacionada ao Renovate. Em V2 havia configuração e também orquestração explícita no pipeline, por meio de job, schedule e execução manual. Em V3, a configuração do Renovate permanece positiva — inclusive para NuGet, Dockerfile, Vulnerability Alerts e Lock File Maintenance —, mas deixam de existir evidências de:

- job Renovate no pipeline;
- regra schedule para Renovate;
- execução manual do Renovate.

Portanto, V3 preserva a **configuração** de manutenção automatizada de dependências, mas não preserva a **orquestração explícita pelo pipeline** que estava evidenciada em V2. A execução efetiva continua `null`, logo não pode ser inferida nem em V2 nem em V3.

A classificação permanece no nível 3, **Parcial/Emergente**, sem alteração no motivo determinístico informado.

#### V3 → V4

De V3 para V4, os resultados são integralmente estáveis nas práticas analisadas. Permanecem evidenciados:

- CI como código;
- restore e build Release no CI;
- cache Sonar e NuGet;
- SonarQube e espera pelo Quality Gate;
- regra para branch `main`;
- configuração do Renovate e seus gerenciadores;
- Dockerfile e Docker Compose;
- configurações de observabilidade, ambiente e qualidade estática;
- automação de ambiente local.

Também permanecem sem evidência:

- regra para Merge Request;
- job, agendamento ou execução manual de Renovate;
- testes automatizados;
- deploy, promoção e rollback automatizados;
- health checks específicos de banco e API;
- configuração PostgreSQL;
- dump de banco.

A classificação permanece nível 3, **Parcial/Emergente**. Assim, V4 representa continuidade do patamar atingido em V2 e mantido em V3, sem novas capacidades de pipeline evidenciadas.

---

### Práticas persistentes

As seguintes práticas apresentam evidência positiva contínua de V1 a V4:

- GitLab CI como código;
- SonarQube;
- espera pelo Quality Gate;
- cache Sonar;
- regra para branch `main`;
- Dockerfile presente;
- Dockerfile multi-stage;
- restore, build e publish definidos no Dockerfile;
- Docker Compose presente;
- build definido no Docker Compose;
- política de restart;
- rede externa no Docker Compose;
- reverse proxy configurado;
- integração de Sentry em runtime;
- Health Checks em sentido geral;
- Console Logging;
- `appsettings` presente;
- configuração de Sentry e Matomo;
- configuração externalizada;
- `.editorconfig`;
- regras de analyzer e regras de segurança declaradas;
- `.env.example` e `.env.io.example`;
- parametrização de ambientes;
- scripts presentes;
- script de inicialização de banco;
- automação de ambiente local.

Essas práticas demonstram continuidade da infraestrutura declarativa, da padronização de configuração, de aspectos de qualidade estática e de suporte à execução local e conteinerizada.

Entretanto, essa permanência não deve ser interpretada como evidência de deploy automatizado. Dockerfile e Docker Compose demonstram capacidades de empacotamento e definição de execução, mas não comprovam a existência de uma etapa automatizada de implantação em ambiente de destino.

---

### Capacidades introduzidas durante a evolução

As capacidades introduzidas com evidência positiva aparecem predominantemente em V2 e persistem até V4, exceto a orquestração de Renovate no pipeline.

#### Integração contínua estruturada

A partir de V2, passam a estar evidenciados:

- `dotnet restore` no CI;
- build Release no CI;
- cache NuGet;
- SDK do pipeline identificado como `10.0`.

Essas evidências fortalecem a caracterização de uma CI estruturada, pois tornam explícitas etapas de restauração, compilação em configuração de produção e reutilização de dependências.

#### Configuração de gerenciamento de dependências

Em V2, e mantida em V3 e V4, há evidência positiva de:

- configuração de Renovate;
- gerenciamento de dependências NuGet;
- gerenciamento de dependências em Dockerfile;
- Vulnerability Alerts;
- Lock File Maintenance.

Esses resultados comprovam a existência de configuração declarativa para atualização e manutenção de dependências. Não comprovam, por si só, que o Renovate tenha sido executado, que tenha criado atualizações ou que tais atualizações tenham sido integradas com sucesso.

#### Suporte adicional ao ambiente local

O script de seed, ausente em V1 e presente de V2 a V4, amplia a automação de preparação de dados para ambientes locais ou controlados. Trata-se de uma capacidade de automação de ambiente, não de uma evidência de automação de entrega.

---

### Mudanças ou descontinuidades de orquestração

A principal mudança de orquestração ocorre no ciclo V2 → V3.

Em V2, a presença conjunta de job Renovate, regra schedule e execução manual demonstra que a ferramenta possuía mecanismos explícitos de acionamento no pipeline. Isso caracteriza **orquestração**, mas não execução efetiva bem-sucedida, que permanece indeterminada (`null`).

Em V3 e V4:

- a configuração do Renovate permanece presente;
- o job Renovate deixa de estar evidenciado;
- a regra de agendamento deixa de estar evidenciada;
- a execução manual deixa de estar evidenciada;
- a execução efetiva continua indeterminada.

Dessa forma, observa-se uma descontinuidade entre a configuração persistente do Renovate e sua orquestração explícita no GitLab CI. Os resultados não permitem concluir se o Renovate passou a ser executado externamente ao pipeline, se foi desabilitado ou se utiliza outro mecanismo não coberto pelos artefatos analisados.

Há também uma alteração na evidência de regra para Merge Request: positiva em V1 e `false` de V2 a V4. O resultado indica ausência de evidência dessa regra nas versões posteriores, mas não permite inferir a substituição por outro gatilho ou a retirada operacional da validação de Merge Requests fora do escopo analisado.

---

### Lacunas persistentes

As principais lacunas persistentes, considerando exclusivamente os resultados individuais, são:

- ausência de evidência de testes automatizados em todas as versões;
- ausência de evidência de Quality Gate bloqueante, embora exista espera pelo Quality Gate;
- ausência de evidência de deploy automatizado;
- ausência de evidência de promoção automática entre ambientes;
- ausência de evidência de rollback automatizado;
- ausência de evidência de health check específico de banco;
- ausência de evidência de health check específico de API;
- ausência de evidência de configuração PostgreSQL;
- ausência de dump de banco;
- execução efetiva do Renovate indeterminada em todas as versões.

As lacunas de deploy, promoção e rollback devem ser interpretadas com cautela. A ausência de comandos ou mecanismos correspondentes nos artefatos analisados não comprova que tais práticas não ocorram em sistemas externos, plataformas de infraestrutura, processos operacionais ou repositórios não incluídos na análise.

Da mesma forma, observabilidade — representada por Sentry, Matomo, Console Logging e Health Checks gerais — não caracteriza automação de entrega. Esses elementos podem apoiar a operação e o diagnóstico em runtime, mas não demonstram que exista um fluxo automatizado de entrega, promoção ou reversão.

---

### Evolução da maturidade do pipeline

A classificação determinística evolui de:

| Versão | Nível | Classificação |
|---|---:|---|
| V1 | 2 | Inicial/Ad hoc |
| V2 | 3 | Parcial/Emergente |
| V3 | 3 | Parcial/Emergente |
| V4 | 3 | Parcial/Emergente |

A mudança de V1 para V2 é sustentada pelas novas evidências de restore, build Release, cache NuGet e pela ampliação de controles configurados de dependências. Esse conjunto justifica a passagem de um pipeline com automações pontuais para uma CI parcialmente estruturada.

A manutenção do nível 3 em V3 e V4 é coerente com a estabilidade das práticas centrais de CI e qualidade. A retirada da evidência de orquestração de Renovate não altera a classificação fornecida, pois a CI principal permanece estruturada. Ao mesmo tempo, não há evidências que suportem uma progressão para um nível superior, especialmente devido à ausência de testes automatizados e de automação de entrega ponta a ponta.

Portanto, a trajetória de maturidade é de evolução inicial relevante entre V1 e V2, seguida de estabilização em um patamar intermediário e incompleto.

---

### Limitações da análise longitudinal

Esta análise é limitada estritamente aos resultados individuais fornecidos para V1, V2, V3 e V4. Não foram reanalisados arquivos originais nem inferidas práticas além das evidências apresentadas.

Em particular:

- valores `false` foram tratados como ausência ou não evidência no artefato analisado;
- valores `null` foram tratados como indeterminados e não como ausência;
- a configuração de Renovate não foi interpretada como prova de execução;
- a presença de job Renovate em V2 foi interpretada como evidência de orquestração, não de execução bem-sucedida;
- Dockerfile e Docker Compose foram interpretados como capacidades de build e execução conteinerizada, não como evidência de deploy automatizado;
- elementos de observabilidade não foram interpretados como automação de entrega;
- a ausência de deploy, promoção ou rollback nos artefatos analisados não permite afirmar que tais capacidades estejam ausentes de ambientes, ferramentas ou processos externos ao escopo.

Além disso, as transições de valores positivos para `false`, como a regra de Merge Request e a orquestração do Renovate, descrevem mudanças na evidência disponível entre snapshots. Elas não permitem determinar, sem evidência adicional, a motivação, o mecanismo substituto ou o comportamento operacional efetivo.

---

### Conclusão longitudinal

A evolução longitudinal indica que o pipeline progrediu de um estágio inicial, com automações isoladas em V1, para um estágio parcial e emergente a partir de V2. O avanço foi sustentado pela explicitação de etapas fundamentais de CI — restore, build Release e cache NuGet — e pela introdução de configuração abrangente para manutenção de dependências via Renovate.

A partir de V2, a estrutura central do pipeline permanece estável até V4. Contudo, a orquestração explícita do Renovate observada em V2 não permanece evidenciada em V3 e V4, embora sua configuração continue presente. Não há comprovação de execução efetiva do Renovate em nenhuma versão.

A principal limitação de maturidade permanece a ausência de evidências de testes automatizados, Quality Gate bloqueante, deploy automatizado, promoção e rollback. Assim, as versões V2, V3 e V4 demonstram integração contínua parcialmente estruturada e controles de qualidade configurados, mas não fornecem evidência suficiente para caracterizar uma cadeia de entrega contínua ou implantação contínua de ponta a ponta.